#!/usr/bin/env bash

source message_functions || exit 1

serve_jar=${HOME}/hmf/repos/hmftools/serve/target/serve-*-jar-with-dependencies.jar

if [ ! -f ${serve_jar} ]; then
    error "Could not locate serve jar!"
fi

info "Copying ${serve_jar} to serve-vm-prod-1"
gcloud compute scp ${serve_jar} serve-vm-prod-1:/data/tools/serve/pilot/serve.jar