#!/usr/bin/env bash

source message_functions || exit 1

version=1.8
serve_jar=${HOME}/hmf/repos/hmftools/serve/target/serve-${version}-jar-with-dependencies.jar

if [ ! -f ${serve_jar} ]; then
    error "Could not locate serve jar!"
fi

info "Copying ${serve_jar} to gs://common-tools/"
gsutil cp ${serve_jar} gs://common-tools/serve/${version}/serve.jar

info "Copying ${serve_jar} to serve-vm"
gcloud compute scp ${serve_jar} serve-vm:/data/tools/serve/${version}/serve.jar