#!/usr/bin/env bash

source message_functions || exit 1

vicc_importer_jar=${HOME}/hmf/repos/hmftools/vicc-importer/target/vicc-importer-*-jar-with-dependencies.jar

if [ ! -f ${vicc_importer_jar} ]; then
    error "Could not locate vicc importer jar!"
fi

info "Copying ${vicc_importer_jar} to gs://common-tools/"
gsutil cp ${vicc_importer_jar} gs://common-tools/vicc-importer/pilot/vicc-importer.jar

info "Copying ${vicc_importer_jar} to serve-vm-prod-1"
gcloud compute scp ${vicc_importer_jar} serve-vm-prod-1:/data/tools/vicc-importer/pilot/vicc-importer.jar