#!/usr/bin/env bash

source message_functions || exit 1

version=1.9
protect_jar=${HOME}/hmf/repos/hmftools/protect/target/protect-${version}-jar-with-dependencies.jar

if [ ! -f ${protect_jar} ]; then
    error "Could not locate protect jar!"
fi

info "Copying ${protect_jar} to gs://common-tools/"
gsutil cp ${protect_jar} gs://common-tools/protect/${version}/protect.jar

info "Copying ${protect_jar} to data-vm-prod-2"
gcloud compute scp ${protect_jar} data-vm-prod-2:/data/tools/protect/${version}/protect.jar