#!/usr/bin/env bash

source message_functions || exit 1

ecrf_files_cpct_xml=${HOME}/Downloads/*_cpct_ecrf.xml
ecrf_files_cpct_csv=${HOME}/Downloads/*_cpct_form_status.csv
ecrf_files_drup_xml=${HOME}/Downloads/*_drup_ecrf.xml

if [ ! -f ${ecrf_files_cpct_xml} ]; then
    error "Could not locate cpct xml file!"
fi

if [ ! -f ${ecrf_files_cpct_csv} ]; then
    error "Could not locate cpct scv file!"
fi

if [ ! -f ${ecrf_files_drup_xml} ]; then
    error "Could not locate drup xml file!"
fi

info "Uploading ${ecrf_files_cpct_xml} to gs://hmf-ops-data/ecrf/"
gsutil cp ${ecrf_files_cpct_xml} gs://hmf-ops-data/ecrf/

info "Uploading ${ecrf_files_cpct_csv} to gs://hmf-ops-data/ecrf/"
gsutil cp ${ecrf_files_cpct_csv} gs://hmf-ops-data/ecrf/

info "Uploading ${ecrf_files_drup_xml} to gs://hmf-ops-data/ecrf/"
gsutil cp ${ecrf_files_drup_xml} gs://hmf-ops-data/ecrf/

info "Clinical eCRF files are uploaded from CPCT and DRUP!"