#!/usr/bin/env bash

source message_functions || exit 1

ckb_zip_file=${HOME}/Downloads/json_file_format/*.zip

if [ ! -f ${ckb_zip_file} ]; then
    error "Could not locate ckb zip file!"
fi

info "Uploading ${ckb_zip_file} to gs://hmf-crunch-resources/ckb/"
gsutil cp ${ckb_zip_file} gs://hmf-crunch-resources/ckb/
info "CKB zip file has been uploaded!"