#!/usr/bin/env bash

source message_functions || exit 1

ckb_filters_download="${HOME}/Downloads/SERVE Curation - CKB Filter Configuration.tsv"
ckb_filters_final="${HOME}/Downloads/ckb_filters.tsv"
mv "${ckb_filters_download}" "${ckb_filters_final}"

if [[ ! -f ${ckb_filters_final} ]]; then
    error "Could not locate ckb filters file!"
fi

info "Uploading ${ckb_filters_final} to serve-vm-prod-1:/data/resources/custom/serve"
gcloud compute scp ${ckb_filters_final} "serve-vm-prod-1:/data/resources/custom/serve"
