#!/usr/bin/env bash

source locate_files || exit 1
source actin_config || exit 1

patient=$1

gcp_project="$(production_actin_emc_project)"
clinical_feed_input_questionnaire_file="$(locate_actin_clinical_feed_input_bucket ${gcp_project})/actin-1/ACTIN_Data_Consulten.tsv"

gsutil cat ${clinical_feed_input_questionnaire_file} | grep ${patient}