#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source actin_config || exit 1

gcp_project="$(production_actin_nki_project)"
trial_status_bucket="$(locate_actin_trial_status_bucket ${gcp_project})"

info "Showing trial status trial JSON for ${gcp_project}"
gsutil cat "${trial_status_bucket}"/"trial_status.json" | jq