#!/usr/bin/env bash

source message_functions || exit 1

actin_id=$1 && shift

if [[ -z "${actin_id}" ]]; then
    error "Parameter patient missing. Exiting.";
fi

hospital_id="$(lookup_nki_hospital_id_for_actin_id ${actin_id})"

do_extract_patient_tracking_details_nki ${hospital_id}