#!/usr/bin/env bash

source message_functions || exit 1

patient=$1 && shift
gcp_project=$1 && shift

if [[ -z "${patient}" || -z "${gcp_project}" ]]; then
    error "Parameters missing. Exiting.";
fi

forceUseHartwigSequencing="false"
while [[ $# -gt 0 ]]; do
    case $1 in
        --force_use_hartwig_sequencing)
            forceUseHartwigSequencing="true"
            ;;
        *)
            error "Unknown option, only --force_use_hartwig_sequencing is supported: $1."
            ;;
    esac
    shift
done

gcloud pubsub topics publish projects/${gcp_project}/topics/analysis-pipeline.pending \
    --message="{\"patientId\": \"${patient}\", \"trigger\": \"MANUAL\", \"forceUseHartwigSequencing\": \"${forceUseHartwigSequencing}\"}"