#!/usr/bin/env bash

source message_functions || exit 1

patient=$1 && shift
gcp_project=$1 && shift

if [[ -z "${patient}" || -z "${gcp_project}" ]]; then
    error "Parameters missing. Exiting.";
fi

if [[ "${gcp_project}" == "actin-emc" ]]; then
    if [[ $# -eq 0 || "$1" == --* ]]; then
        error "Namespace parameter required for 'actin-emc'."
        exit 1
    fi
    namespace=$1
    shift
fi

forceUseHartwigSequencing="false"
while [[ $# -gt 0 ]]; do
    case $1 in
        --force_use_hartwig_sequencing)
            forceUseHartwigSequencing="true"
            ;;
        *)
            error "Unknown option, only --force_use_hartwig_sequencing is supported: $1."
            ;;
    esac
    shift
done

if [[ -n "${namespace}" ]]; then
    topic_suffix=".${namespace}"
else
    topic_suffix=""
fi

gcloud pubsub topics publish projects/${gcp_project}/topics/analysis-pipeline${topic_suffix}.pending \
    --message="{\"patientId\": \"${patient}\", \"trigger\": \"MANUAL\", \"forceUseHartwigSequencing\": \"${forceUseHartwigSequencing}\"}"