#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

vm=$1 && shift
project=$1 && shift

if [[ -z "${vm}" || -z "${project}" ]]; then
    error "Missing parameters. Exiting."
fi

version="1.0"
actin_jar="${HOME}/hmf/repos/actin/system/target/system-${version}-jar-with-dependencies.jar"

info "Copying ${actin_jar} to ${vm}"
gcloud compute --project ${project} scp ${actin_jar} ${vm}:$(locate_pilot_actin)