#!/bin/bash
source locate_files
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift
input_dir=${run_dir}/sv_pilot/

linx_jar=$(locate_pilot_linx)

${prefix}/do_run_linx_visualiser ${run_dir} ${linx_jar} ${input_dir} $@
