#!/bin/bash
source locate_files
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=$(locate_pilot_database_credentials)
linx_jar=/data/common/tools/sv-linx_pilot/sv-linx.jar

${prefix}/do_run_linx ${run_dir} ${credentials} ${linx_jar} $@
