#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift
output_dir=${run_dir}/linx/

credentials=$(locate_reference_validation_sets_database_credentials)
linx_jar=$(locate_prod_linx)

do_run_linx ${run_dir} ${credentials} ${linx_jar} ${output_dir} "$@"
