#!/bin/bash
source load_metadata

run_dir=$1 && shift
linx_jar=$1 && shift
input_dir=$1 && shift

# Load metadata
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

links=${input_dir}/${tumor_sample}.linx.vis_sv_data.csv
exons=${input_dir}/${tumor_sample}.linx.vis_gene_exon.csv
segments=${input_dir}/${tumor_sample}.linx.vis_segments.csv
cna=${input_dir}/${tumor_sample}.linx.vis_copy_number.csv

circos=/data/common/tools/circos_v0.69.6/bin/circos

java -cp ${linx_jar} com.hartwig.hmftools.linx.SvVisualiser \
    -sample ${tumor_sample} \
    -plot_out ${input_dir}/plot/ \
    -data_out ${input_dir}/circos/ \
    -segment ${segments} \
    -link ${links} \
    -exon ${exons} \
    -cna ${cna} \
    -circos ${circos} \
    $@


#Example usage
#   do_run_linx_visualiser_prod /data/cpct/runs/180419_HMFregCPCT_FR15412337_FR16985125_CPCT02030466 -threads 8
#   do_run_linx_visualiser_pilot /data/cpct/runs/180419_HMFregCPCT_FR15412337_FR16985125_CPCT02030466 -chromosome 15 -debug
#
# Optional arguments
#
# -threads  sets number of threads
# -chromosome   will only produce plot for supplied chromosome
# -clusterId    will only produce plot for supplied clusterId
# -debug    replaces sv positions with sv id

