#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift
sv_data_dir=${run_dir}/linx/

credentials=$(locate_prod_database_credentials)
linx_jar=$(locate_prod_linx)

do_run_load_linx ${run_dir} ${credentials} ${linx_jar} ${sv_data_dir} "$@"
