#!/usr/bin/env bash

source locate_files

prefix=$(dirname $(readlink $0 || echo $0))
run_dir=$1 && shift
sv_data_dir=${run_dir}/sv/

credentials=$(locate_prod_database_credentials)
linx_jar=$(locate_prod_linx)

${prefix}/do_run_load_linx ${run_dir} ${credentials} ${linx_jar} ${sv_data_dir} "$@"
