#!/usr/bin/env bash


all_created_reports=$( hmf_api_get "reports/created" )
created_reports=$(echo "${all_created_reports}" | jq '[.[] | select(.create_time + "Z" | fromdateiso8601 > 1577833199 ) ]' | jq 'sort_by(.create_time)')

touch reported_samples_list.csv
while read -r report_info; do
    sample_name=$(echo "${report_info}" | cut -f1)
    report_type=$(echo "${report_info}" | cut -f2)
    #create_date=$(echo "${report_info}" | cut -f3)
    id=$(echo "${report_info}" | cut -f4)
    if [[ $( hmf_api_get reports/shared?report_created_id=${id} | jq -r .[] | wc -l ) -gt 0 ]]; then
         if [[ $( cat reported_samples_list.csv | grep ${sample_name} | wc -l ) -gt 0 ]]; then
            cat reported_samples_list.csv | grep -v ${sample_name} > tmp.csv && mv -f tmp.csv reported_samples_list.csv
         fi
         share_date=$( hmf_api_get reports/shared?report_created_id=${id} | jq -r .[].share_time | cut -c1-10 )
         tat=$( get_current_TAT.sh ${sample_name} | tail -1 )
         echo $sample_name','$share_date','$tat','$report_type  >> reported_samples_list.csv
    fi
done < <(echo "${created_reports}" | jq -cr '.[] | [.sample_name,.report_type,.create_time,.id] | @csv')

#gcloud compute scp --project="hmf-ops" --zone="europe-west4-a" --recurse "ops-vm-prod-2":~/reported_samples_list.csv ~/reported_samples_list.csv