#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

mcgi_patient=$1 && shift

if [[ -z "${mcgi_patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

base_mcgi_dir="/data/experiments/pw_mcgi_actin_experiment/actin_system"
patient_record_json="${base_mcgi_dir}/patients/${mcgi_patient}.patient_record.json"
treatment_match_json="${base_mcgi_dir}/treatment_matches/${mcgi_patient}.treatment_match.json"

output_directory="${base_mcgi_dir}/reports"

actin_jar="/data/experiments/pw_mcgi_actin_experiment/actin_jar/actin.jar"

java -cp ${actin_jar} com.hartwig.actin.report.ReporterApplicationKt \
    -patient_json ${patient_record_json} \
    -treatment_match_json ${treatment_match_json} \
    -profile "MCGI" \
    -output_directory ${output_directory} \
    "$@"
