#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting.";
fi

clinical_json="$(locate_actin_clinical_directory)/${sample}.clinical.json"

output_directory="$(locate_actin_reports_directory)"

actin_jar="$(locate_pilot_actin)"

java11 -cp ${actin_jar} com.hartwig.actin.report.ReportApplication \
    -clinical_json ${clinical_json} \
    -output_directory ${output_directory} \
    "$@"

