#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift
output_dir=${run_dir}/pgx_pilot

# START VIRTUAL ENV
source /data/common/dbs/pgx/venv/pgx/bin/activate

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

germline_vcf=$(locate_germline_variants ${run_dir} ${ref_sample})

# REFERENCES
pgx_tool=$(locate_pgx_main)
pgx_resource_dir=$(locate_pgx_resource_dir)
vcftools_tool=$(locate_vcftools)

# RUN
python ${pgx_tool} ${germline_vcf} ${tumor_sample} ${output_dir}  \
    --panel ${pgx_resource_dir}/panelfiles/DPYD.json \
    --sourcedir ${pgx_resource_dir} \
    --vcftools ${vcftools_tool}
