#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

# START VIRTUAL ENV
source /data/common/dbs/pgx/venv/pgx/bin/activate

output_dir=${run_dir}/pgx_pilot

version_pgx_tool=/data/common/tools/knowledgebase-importer_v1.0
version=$( echo $version_pgx_tool | tr "_" " " | tr "v" " "| awk '{print $1}' )
echo ${version}

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

if [ -d ${output_dir} ]; then
    rm -r ${output_dir}
        echo "[INFO] pgx pilot dir exist. Pgx dir is just removed and will be replaced"
fi

germline_vcf=$(locate_germline_variants ${run_dir} ${ref_sample})

# REFERENCES
pgx_tool=$(locate_pgx_main)
pgx_resource_dir=$(locate_pgx_resource_dir)
vcftools_tool=$(locate_vcftools)

# RUN
python ${pgx_tool} ${germline_vcf} ${tumor_sample} ${output_dir}  \
    --panel ${pgx_resource_dir}/panelfiles/DPYD.json \
    --sourcedir ${pgx_resource_dir} \
    --vcftools ${vcftools_tool}
