#!/usr/bin/env bash

source locate_files || exit 1

run_dir=$1 && shift
sample=$1 && shift
barcode=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

if [[ -z "${sample}" || -z "${barcode}" ]]; then
    error "No tumor information provided. Exiting"
fi

if [[   -z "${sample}" || -z "${barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  tumor_sample name: ${sample}"
    warn "  tum sample barcode: ${barcode}"
    exit 1;
fi

panel_vcf_name=$(locate_purple_somatic_variants_panel ${run_dir})
pipeline_version_file=${run_dir}/pipeline.version

do_run_base_panel_reporter  \
      -panel_vcf_name ${panel_vcf_name} \
      -pipeline_version_file ${pipeline_version_file} \
      -require_pipeline_version_file \
      -tumor_sample_id ${sample} \
      -tumor_sample_barcode ${barcode} \
      -ref_genome_version 38 "$@"