#!/usr/bin/env bash

source locate_files || exit 1

patient_reporter_jar=$(locate_pilot_patient_reporter) #TODO: Move to prod version when 7.25 is released

primary_tumor_tsv=/data/dbs/clinical_data/curated_primary_tumor.tsv
lims_dir=/data/ops/lims/prod
company_logo=$(locate_company_logo_prod)
signature=$(locate_signature_prod)

expected_pipeline_version=$(extract_expected_pipeline_version_research) #TODO: Move to prod version when 7.25 is released

java -cp ${patient_reporter_jar} com.hartwig.hmftools.patientreporter.PanelReporterApplication \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -expected_pipeline_version ${expected_pipeline_version} \
    -comments "This is a pilot patient report and is not meant for production purpose" \
    "$@"