#!/usr/bin/env bash

object=$1 && shift
api_credentials=$1 && shift

token=$(do_request_iclusion_token ${api_credentials} | jq -r '.access_token')

endpoint=$(awk '/^endpoint/ {print $2}' ${api_credentials})

curl --request GET \
  --url "${endpoint}/${object}" \
  --header 'Accept: application/json' \
  --header "Authorization: Bearer $token"
