#!/usr/bin/env bash

source iclusion_function || exit 1

object=$1 && shift
api_credentials=$1 && shift

token=$(do_request_iclusion_token "${api_credentials}" | jq -r '.access_token')

endpoint=$(extract_iclusion_endpoint "${api_credentials}")

curl --request GET \
  --url "${endpoint}/${object}" \
  --header 'Accept: application/json' \
  --header "Authorization: Bearer ${token}"
