#!/usr/bin/env bash

set -e

function do_curl() {
    curl --oauth2-bearer "$(gcloud auth print-access-token)" "$@"
}

AR_URL="https://europe-west4-maven.pkg.dev/actin-build/build-registry-maven/com/hartwig/actin"

[[ $# -ne 3 ]] && echo "USAGE: $0 [tool name] [tool version] [destination path]" && exit 1

tool=$1
version=$2
destination=$3

remote_dir="${AR_URL}/${tool}/system/${version}"

expected_md5="$(do_curl -o - -L "${remote_dir}/system-${version}.jar.md5")"
do_curl -o "${destination}" -L "${remote_dir}/system-${version}.jar"
actual_md5="$(md5sum "${destination}" | awk '{print $1}')"
[[ ${actual_md5} == "" ]] && echo "No local md5" && exit 1
if [[ ${actual_md5} != "${expected_md5}" ]]; then
    echo "Checksum not as expected for ${tool} version ${version}"
    rm "${destination}"
    exit 1
else
    echo "Fetched ${tool} version ${version} (md5=${actual_md5}) to ${destination}"
fi