#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1
source locate_files || exit 1

actin_credentials="$(cat $HOME/connection_secret.txt)"
actin_database_name="actin_personalization"

# NOTE: Make sure the below location contains the actual SQL you want to use!
actin_database_sql="$(locate_actin_personalization_database_sql_script)"

db_host=$(extract_database_host "${actin_credentials}")
db_port=$(extract_database_port "${actin_credentials}")
db_user=$(extract_database_user "${actin_credentials}")
db_pass=$(extract_database_password "${actin_credentials}")

info "Rebuilding ACTIN personalization db '${actin_database_name}' on '${db_host}' using ${actin_database_sql} "

mysql ${actin_database_name} --host="${db_host}" --port="${db_port}" --user="${db_user}" --password="${db_pass}" < ${actin_database_sql}

info "Done!"