#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

#  dd
age=$1 && shift # In years, eg "62"
who_status=$1 && shift # number between 0 and 5
has_ras_mutation=$1 && shift # true or false
metastasis_locations=$1 && shift # set of LocationGroup (see code, e.g. "LIVER_AND_INTRAHEPATIC_BILE_DUCTS;RETROPERITONEUM_AND_PERITONEUM"

if [[ -z "${age}" || -z "${who_status}" || -z "${has_ras_mutation}" || -z "${metastasis_locations}" ]]; then
    error "Missing parameters. Format should be 'age', 'who_status', 'has_ras_mutation', 'metastasis_locations'"
fi

ncr_dataset=$(locate_ncr_dataset)
personalization_jar=$(locate_actin_personalization_jar)
output_path="/data/patient_like_me/reports/personalized_demo.pdf"

java -cp ${personalization_jar} com.hartwig.actin.personalization.similarity.PersonalizationReportWriterApplicationKt \
    -ncr_file ${ncr_dataset} \
    -age ${age} \
    -who_status ${who_status} \
    -has_ras_mutation ${has_ras_mutation} \
    -metastasis_locations ${metastasis_locations} \
    -output_path ${output_path}