#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

ncr_file="$(locate_latest_ncr_crc_dataset_analysis_vm)"
personalization_jar="$(locate_actin_personalization_jar)"
output_directory="$(locate_personalization_reference_db_analysis_vm)"
treatment_db_directory="$(locate_actin_treatment_db_directory)"

info "Running NCR ingestion on ${ncr_file}"

java -cp ${personalization_jar} com.hartwig.actin.personalization.ncr.NcrIngestionApplicationKt \
    -ncr_file ${ncr_file} \
    -output_directory ${output_directory} \
    -treatment_db_path ${treatment_db_directory} \
    "$@"