#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

info "Replacing training output and resources with GCP bucket contents"
create_or_cleanup_dir "/data/reference_patient_data"
gsutil -m rsync -r gs://actin-personalization-reference-patient-data /data/reference_patient_data/

info "Replacing patient-like-me data with GCP bucket contents"
create_or_cleanup_dir "/data/patient_like_me/sources/cairo"
gsutil -m rsync -r gs://hmf-crunch-actin-dccg-dataset/cairo /data/patient_like_me/sources/cairo/

create_or_cleanup_dir "/data/patient_like_me/sources/ncr"
gsutil -m rsync -r gs://hmf-crunch-actin-ncr-dataset /data/patient_like_me/sources/ncr/

create_or_cleanup_dir "/data/patient_like_me/sources/orchestra"
gsutil -m rsync -r gs://hmf-crunch-actin-orchestra-dataset /data/patient_like_me/sources/orchestra/

create_or_cleanup_dir "/data/patient_like_me/sources/palga"
gsutil -m rsync -r gs://hmf-crunch-actin-palga-dataset /data/patient_like_me/sources/palga/

treatment_db_dir="$(locate_actin_treatment_db_directory)"
treatment_db_bucket="$(locate_actin_treatment_db_bucket)"
create_or_cleanup_dir ${treatment_db_dir}
gsutil -m rsync -r ${treatment_db_bucket} ${treatment_db_dir}