#!/usr/bin/env bash

source message_functions || exit 1

nas_user="rsyncuser"
creds_name="nas-credentials-rsyncuser"
password=$(gcloud secrets versions access "latest" --secret="${creds_name}" --project=hmf-secrets) || die "Unable to retrieve password"

if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") \${local-file-path} \${nas-dir-path}"
    echo " Exmpl: $(basename "$0") /path/to/file /volume1/web/playground"
    echo "---"
    exit 1
fi

source_file_path=$1 && shift
nas_dir_path=$1 && shift

# explicitly pass on original file permissions (--perms)
info "Copying local file '${source_file_path}' to 'nas:${nas_dir_path}/'"
sshpass -f <(cat <<< "${password}") rsync --perms --protect-args "${source_file_path}" "${nas_user}@nas:${nas_dir_path}/"