#!/usr/bin/env bash

nas_path="/volume1/bfx/upload"

if [[ -z "$1" || $1 == "-h" || $1 == "--help" ]]; then
    echo " Descr: Copies file to NAS ${nas_path}"
    echo " Usage: $(basename "$0") \${path-to-file}"
    exit 1
fi

copy_file_to_nas "$1" "${nas_path}"
