#!/usr/bin/env bash

source message_functions || exit 1
source secrets_functions || exit 1

if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") \${nas-source-path} \${local-target-path}"
    echo " Exmpl: $(basename "$0") '/volume1/web/playground/test/test-file.txt' /local/dir/"
    echo "        $(basename "$0") '/volume1/web/playground/test/test-file.txt' /local/dir/new-file-name.txt"
    echo "---"
    exit 1
fi

password=$(get_nas_rsyncuser_credentials)
[[ -n "${password}" ]] || die "Was somehow unable to retrieve password"

source=$1 && shift
target=$1 && shift
ssh_port=2210

if [[ -d "$target" && ! "$target" =~ \/$ ]]; then
    target="${target}/"
fi

info "  Syncing 'nas.prod-1:${source}' to '${target}'"
sshpass -p "${password}" rsync -e "ssh -p ${ssh_port}" --chmod=ugo=rw --protect-args "rsyncuser@nas.prod-1:${source}" "${target}"