#!/usr/bin/env bash

source message_functions || exit 1
source secrets_functions || exit 1

password=$(get_nas_rsyncuser_credentials)
[[ -n "${password}" ]] || die "Was somehow unable to retrieve password"

if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") \${nas-source-dir-path} \${local-target-dir-path}"
    echo "        $(basename "$0") '/volume1/web/playground/test/' /local/dir/"
    echo "---"
    exit 1
fi

source_dir=$1 && shift
target_dir=$1 && shift
extra_rsync_params=$1 && shift

[[ "${source_dir}" =~ \/$ ]] || source_dir="${source_dir}/"
[[ "${target_dir}" =~ \/$ ]] || target_dir="${target_dir}/"
[[ -d "${target_dir}" ]] || die "Target dir is not a directory (${target_dir})"

info "  Syncing 'nas:${source_dir}' to '${target_dir}'"
sshpass -f <(cat <<< "${password}") rsync -a --protect-args "$extra_rsync_params" "rsyncuser@nas:${source_dir}" "${target_dir}"