#!/usr/bin/env bash

source message_functions || exit 1
source secrets_functions || exit 1

if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") \${local-source-dir-path} \${nas-target-dir-path}"
    echo "        $(basename "$0") '/local/dir/' '/volume1/web/playground/test/'"
    echo "---"
    exit 1
fi

password=$(get_nas_rsyncuser_credentials)
[[ -n "${password}" ]] || die "Was somehow unable to retrieve password"

source_dir=$1 && shift
target_dir=$1 && shift
ssh_port=2210

[[ "${source_dir}" =~ \/$ ]] || source_dir="${source_dir}/"
[[ "${target_dir}" =~ \/$ ]] || target_dir="${target_dir}/"
[[ -d "${source_dir}" ]] || die "Source dir is not a directory (${source_dir})"

sshpass -p "${password}" rsync -e "ssh -p ${ssh_port}" -ah --omit-dir-times --protect-args "${source_dir}" "rsyncuser@nas.prod-1:${target_dir}"