#!/usr/bin/env bash

source message_functions || exit 1

bucket="hmf-share-services"
input="${1-/data/ops/recurrent/submission_cleanup/jobs/input_submission.list}"

[[ -f "${input}" ]] || die "Input file does not exist [$input]"

info "Gathering all files from bucket [${bucket}]"
all_files_in_bucket=$(gsutil ls "gs://${bucket}/")
printf "%s\n" "${all_files_in_bucket}"
info "Checking bucket content for submissions from input file [${input}]"
cut -d" " -f1 < "${input}" | while read -r submission; do
    if [[ "${submission}" != "" ]]; then
        info "Grepping files for submission [${submission}]"
        grep -i "${submission}" <<< "${all_files_in_bucket}"
    fi
done
info "Finished"