#!/usr/bin/env python

import sys
import os


def printAllKLength(set, k):
    n = len(set)
    printAllKLengthRec(set, "", n, k)


def printAllKLengthRec(set, prefix, n, k):
    if k == 0:
        print(prefix)
        return
    for i in range(n):
        new_prefix = prefix + set[i]
        printAllKLengthRec(set, new_prefix, n, k - 1)


if __name__ == "__main__":
    script = os.path.basename(__file__)
    if len(sys.argv) == 2:
        k = int(sys.argv[1])
    else:
        sys.exit("Usage: %s <length-of-index-sequences>" % script)

    set = ['A', 'C', 'T', 'G']
    printAllKLength(set, k)
 
