#!/usr/bin/env bash

script_dir="/data/common/repos/scripts/gcp"
script_name="sync_shallow_rport_from_gcp"
script_path="${script_dir}/${script_name}"

timestamp="$(date +%y%m%d_%H%M%S)"
log_dir="/data/ops/cron/logs/"
log="${log_dir}/${timestamp}_cron_${script_name}.log"

${script_path} > "${log}" 2>&1
