#!/usr/bin/env bash

script_dir="/data/common/repos/scripts/gcp"
script_name="sync_snpcheck_to_gcp"
script_path="$script_dir/$script_name"

timestamp="$(date +%y%m%d_%H%M)"
log_dir="/data/ops/cron/logs/"
log="$log_dir/cron_$script_name.log"

echo "Running $0 ($timestamp)"
${script_path} > "$log" 2>&1