#!/usr/bin/env bash

metadataFile=$1
rnaOverview="/data/data_archive/rna_seq/overview/overview.tsv"
rnaDir=./rnaseq

cat ${metadataFile} | grep -v "^#" | cut -f3 | while read sampleId; do
    echo "[INFO] Checking $sampleId"
    fastqPath=$( cat ${rnaOverview} | awk -v sampleId="${sampleId}" '$1 == sampleId' | cut -f4)
    if [[ "${fastqPath}" ]]; then
        echo "[INFO]   found $fastqPath"
        ln -s ${fastqPath} ${rnaDir}/
    fi
done
