#!/usr/bin/env bash

metadataFile=$1
entityName=$2

entitySbpId=$( query_sbp_api -type entities | grep ${entityName} | cut -f3 )
cat ${metadataFile} | grep -v "^#" | cut -f1 | while read setName; do
  setId=$( query_sbp_api -type sets | grep ${setName} | cut -f5)

  tumorBamJson="./logs/json/${setName}_tumor_bam.json"
  echo "[INFO] Creating ${tumorBamJson}"

  create_share_json_for_tumor_bam ${setId} ${entitySbpId} > "${tumorBamJson}"
done