#!/usr/bin/env bash

patientIdsTsv=$1
datareqInputTsv=$2

unfiltered="metadata_unfiltered.tsv"
filtered="metadata_filtered.tsv"
final="metadata_final.tsv"

if [[ ! -f ${patientIdsTsv} ]]; then 
  echo "[EXIT] Cannot find ${patientIdsTsv}" && exit 1;
fi
if [[ ! -f ${datareqInputTsv} ]]; then 
  echo "[EXIT] Cannot find ${datareqInputTsv}" && exit 1;
fi

## select metadata info of all biopsies for each patient
head -1 ${datareqInputTsv} | sed 's/sbpSetName/setName/' > ${unfiltered}
cat ${patientIdsTsv} | grep -v "^#" | while read patientId; do 
  grep ${patientId} ${datareqInputTsv}
done | sort | uniq >> ${unfiltered}

## select metadata info for each biopsy
#head -1 ${datareqInputTsv} | sed 's/sbpSetName/setName/' > ${unfiltered}
#cat ${patientIdsTsv} | grep -v "^#" | while read patientId; do 
#  cat ${datareqInputTsv} | awk -v pid=${patientId} '$11 ~ pid'
#done | sort | uniq >> ${unfiltered}

## Example columns
#  1                    #sbpSetName : 170812_HMFregCPCT_FR13999384_FR15410900_CPCT02010615
#  2                       sbpSetId : 7942
#  3                      sbpBucket : hmf-output-2018-50
#  4                      sbpStatus : Failed
#  5                      hmfStatus : Done
#  6                       hmfLabel : CPCT
#  7                 puritySampleId : CPCT02010615T
#  8                       purityQC : FAIL_DELETED_GENES
#  9                   purityStatus : NORMAL
# 10                    tumorPurity : 0.13
# 11                       sampleId : CPCT02010615T
# 12                      patientId : CPCT02010615
# 13           primaryTumorLocation : Lung
# 14                  cancerSubtype : Non-Small cell
# 15                     biopsyDate : 2017-07-19
# 16                     biopsySite : Kidney
# 17                 biopsyLocation : left
# 18                         gender : male
# 19                      birthYear : 1940
# 20                      deathDate : NA
# 21        hasSystemicPreTreatment : Yes
# 22    hasRadiotherapyPreTreatment : Yes
# 23                 treatmentGiven : Yes
# 24             treatmentStartDate : 2017-08-03
# 25               treatmentEndDate : NA
# 26                      treatment : Nivolumab
# 27                  treatmentType : Immunotherapy
# 28                   responseDate : 2017-09-04
# 29               responseMeasured : Yes
# 30                  firstResponse : PD
# 31                  preTreatments : Carboplatin/Cisplatin/Oxaliplatin
# 32              allPostTreatments : Nivolumab
# 33          allPostTreatmentTypes : Immunotherapy

## =======================
## FILTER
## =======================

## HEADER
cat ${unfiltered} | grep "^#" > ${filtered}
## SETS
cat ${unfiltered} | grep -v "^#" | awk '$8 ~ /^PASS$/' | awk '$9 !~ /NO_TUMOR/' | awk '$10 > 0.195' >> ${filtered}
#cat ${unfiltered} | grep -v "^#" | awk '$8 ~ /^PASS$/' | awk '$9 !~ /NO_TUMOR/' >> ${filtered}
#cat ${unfiltered} | grep -v "^#" | grep -v DRUP01 >> ${filtered}
#cat ${unfiltered} | grep -v "^#" >> ${filtered}

## =======================
## SELECT COLUMNS
## =======================

## select all (tumor + patient + treatment)
cat ${filtered} | cut -f 1,10-30 > ${final}
## OR select columns of tumor + patient (no treatment)
#cat ${filtered} | cut -f 1,10-20 > ${final}
## OR select only tumor + treatment
#cat ${filtered} | cut -f 1,10-17,21-30 > ${final}

## report
countBefore=$( cat ${unfiltered} | grep -v "^#" | wc -l )
countAfter=$( cat ${filtered} | grep -v "^#" | wc -l )
echo "[INFO] Output in ${final} (from $countBefore to $countAfter)"

## tmp
wc -l metadata*