#!/usr/bin/env bash

dr_name=$1 && shift
request_name=$1 && shift

if [ -z "${dr_name}" ] || [ -z "${request_name}" ]; then
    echo "Usage: create_base_directory_structure_for_data_request dr request_name"
    echo "   eg create_base_directory_structure_for_data_request DR-028 DR-028-update2"
    exit 1
fi

final_dr_path=/data/data_archive/datarequests/${dr_name}/${request_name}

echo "[INFO] Creating base directory structure for request ${request_name} on DR ${dr_name}"
if [ -d ${final_dr_path} ]; then
    echo "[WARN] Directory already exists: ${final_dr_path}. Exiting"
    exit 1
fi

# Create directories which always exist for every DR
mkdir -p ${final_dr_path}
mkdir ${final_dr_path}/logs
mkdir ${final_dr_path}/metadata

echo "[INFO] Finished creating structure at ${final_dr_path}"