#!/usr/bin/env bash

dr_name=$1 && shift
request_name=$1 && shift

if [ -z "${dr_name}" ] || [ -z "${request_name}" ]; then
    echo "Usage: create_complete_data_request dr_name request_name"
    echo "   eg create_complete_data_request DR-028 DR-028-update2"
    exit 1
fi

dr_path=/data/data_archive/datarequests/${dr_name}/${request_name}

create_base_directory_structure_for_data_request ${dr_path}
if [ $? = 0 ]; then
    echo "success"
else
    echo "fail"
fi

