#!/usr/bin/env bash

prefix=`dirname $(readlink $0 || echo $0)`

metadataFile=$1

do_generate_extra_clinical_data ${metadataFile} "post_biopsy_drugs_by_biopsy" ${prefix}/sql_postBiopsyDrugsByBiopsy.sql