#!/usr/bin/env bash

source message_functions || exit 1
source lama || exit 1

tumor_barcode=$1 && shift

if [[ -z "${tumor_barcode}" ]]; then
    error "No tumor barcode ID passed to function. Exiting"
fi

lama_endpoint=$(curl http://lama.prod-1/api/queries/patient-reporter/isolation-barcode/${barcode} -L | jq .)

hospitalName=$(echo $lama_endpoint | jq .hospitalName)
contractCode=$(echo $lama_endpoint | jq .contractCode)

lama "contact-group/contract-code/${contractCode}/hospital/${hospitalName}"

