#!/usr/bin/env bash

source message_functions || exit 1

tumor_barcode=$1 && shift

if [[ -z "${tumor_barcode}" ]]; then
    error "No tumor barcode ID passed to function. Exiting"
fi

lama_endpoint=$(curl "http://lama.prod-1/api/queries/patient-reporter/isolation-barcode/${tumor_barcode}" -L | jq .)

hospitalName=$(echo $lama_endpoint | jq .hospitalName | tr -d '"')
contractCode=$(echo $lama_endpoint | jq .contractCode | tr -d '"')

echo "Contact details on sample ${tumor_barcode}"
lama "contact-group/contract-code/${contractCode}/hospital/${hospitalName}"