#!/usr/bin/env bash

set -o pipefail

source message_functions || exit 1

NA="N/A"

get_script="lama_api_get"

declare -A classes_with_table_support=(["contact-groups"]=1 ["contract"]=1 ["hospitals"]=1 ["isolates"]=1 ["patient"]=1 ["report"]=1
["status"]=1 ["statuses"]=1 ["tumor-sample"]=1 ["reference-sample"]=1 ["queries/consent"]=1 ["queries/database-loader"]=1
["queries/patient-reporter"]=1 ["queries/registration"]=1 ["TUMOR_INFO"]=1)

print_usage(){
    script=$(basename "$0")
    echo "---"
    echo "Usage: $script [-jtd] <class> [<filter>]"
    echo "Examples:"
    echo " $script hospitals"
    echo " $script contracts"
    echo " $script contact-groups"
    echo " $script tumor-sample ACTN01020001T"
    echo " $script statuses ACTN01020001T"
    echo " $script status isolation-barcode/FR30539000"
    echo " $script queries/consents ACTN01020001T"
    echo " $script queries/consent isolation-barcode/FR30539000"
    echo " $script reports ACTN01020001T"
    echo " $script -j queries/registration isolation-barcode/FR30539000 | jq"
    echo " $script -j queries/patient-reporter isolation-barcode/FR30539000 | jq"
    echo " $script -j queries/database-loader isolation-barcode/FR30539000 | jq"
    echo " $script TUMOR_INFO"
    echo "Options:"
    echo "  -j  Output raw api json content instead of TSV table"
    echo "  -t  Use testing/pilot environment as source instead of production"
    echo "  -d  Debug mode (print final class/filter before execution)"
    echo "Notes:"
    echo "  - Options need to be provided before the query request"
    echo "  - Always use JSON output format for all non-interactive use"
    echo "  - For all available endpoints in PROD see http://lama.prod-1/api/ui"
    echo "  - For all available endpoints in DEV see http://lama.pilot-1/api/ui"
    echo "---"
    exit 1
}

output_json='FALSE'
print_debug='FALSE'
additional_get_params=""

while getopts ':jtd' flag; do
    case "${flag}" in
        j) output_json='TRUE' ;;
        d) print_debug='TRUE' ;;
        t) additional_get_params="-t";;
        *) print_usage >&2
    esac
done
class=${*:$OPTIND:1} && shift # obligatory
filter=${*:$OPTIND:1} && shift # optional

if [[ -z "$class" || $1 == "-h"  || $1 == "--help" ]]; then
    print_usage >&2
fi

main(){
    api_class="${class}"
    api_filter="${filter}"

    # Early check on table support
    if [[ "${output_json}" == "FALSE" && "${classes_with_table_support["${class}"]}" -ne 1 ]]; then
        die "Class has no table output support [${class}]"
    fi

    # Reset class if needed
    if [[ "${class}" == "TUMOR_INFO" ]]; then
        api_class="tumor-samples"
    fi

    # Construct filter
    if [[ -n "${filter}" && "${filter}" =~ \/ ]]; then
        api_filter="/${filter}"
    elif [[ -n "${filter}" && "${class}" == "contract" ]]; then
        api_filter="/code/${filter}"
    elif [[ -n "${filter}" && "${class}" == "patient" ]]; then
            api_filter="/patient-id/${filter}"
    elif [[ -n "${filter}" ]]; then
        api_filter="/sample-id/${filter}"
    fi

    # Construct query path
    api_query="${api_class}${api_filter}"

    if [[ "${print_debug}" == "TRUE" ]]; then
        debug "Script path: $0"
        debug "Input class: ${class}"
        debug "Input filter: ${filter}"
        debug "Api query: ${get_script} ${api_query}"
    fi

    # Perform the GET
    json_result=$($get_script $additional_get_params "${api_query}") || die "Unable to get result for path [${api_query}]"

    # in case LAMA fails it sometimes returns HTML and no fail exit code so need to check content
    if [[ $( head -1 <<< "${json_result}") == "<!doctype html>" ]]; then
        die "Query failed (response body is HTML instead of JSON)"
        exit 1
    elif [[ "${output_json}" == "TRUE" ]]; then
        echo "${json_result}"
        exit 0
    fi

    # make sure json is an array from now on regardless of count
    firstCharacter=${json_result:0:1}
    if [[ ! "${firstCharacter}" == '[' ]]; then
        json_result="[${json_result}]"
    fi

    # print result as table
    if [[ "${class}" =~ ^queries/consent ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\n" sampleId barcode storeData internalUse externalUse externalUseWithCheck isCup
        jq -r '.[] | [.sampleId,
            .barcode,
            .storeDataForReuse,
            .allowInternalUse,
            .allowExternalUseWithoutCheck,
            .allowExternalUseWithCheck,
            .isCup
        ] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^contact-group ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" contractCode hospitalName mainContactName mainContactEmail recipientsContactName recipientsContactEmail
        jq -r '.[] | [.contractCode, .hospitalName, .mainContact.name, .mainContact.email, ([.recipients[].name]|join(";")),
        ([.recipients[].email]|join(";"))] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^contract ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" code displayName sampleIdStart type startDate endDate
        jq -r '.[] | [.code, .displayName, .sampleIdStart, .type, .startDate//"N/A", .endDate//"N/A"] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^hospital ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\n" code name officialName postalCode  city
         jq -r '.[] | [.code, .name, .officialName, .postalCode, .city] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^isolate ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" sampleId sampleBarcode coupeBarcode isolationBarcode inputType resultType experimentNr status
        jq -r '.[] | [.sampleId,
            .isolationBarcode,
            .coupeBarcode,
            .sampleBarcode,
            .inputType,
            .resultType,
            .experimentNr,
            .status
        ] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^status ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
        sampleId sampleType sampleBarcode isolationBarcodes registrationDate isolationStatus libraryPrepStatus snpCheckStatus
        jq -r '.[] | [.sampleId,
            .type,
            .sampleBarcode,
            (.isolationBarcodes|join(",")),
            .registrationDate,
            .isolationStatus,
            .libraryPrepStatus,
            .snpCheckStatus
        ] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^tumor-sample ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" sampleId patientId submissionNr samplingDate arrivalHmf ptumInfo biopsyInfo contractCode sampleBarcodes
        jq -r '.[] | [.sampleId,
            .patientId,
            .submissionNr,
            .samplingDate,
            .arrivalHmf,
            if .tumorType then .tumorType.location|split(" ")[0]|split("/")[0] else "NA" end,
            if .biopsy then .biopsy.location|split(" ")[0]|split("/")[0] else "NA" end,
            .contractCode,
            (.sampleBarcodes|join(","))
        ] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^reference-sample ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" sampleId patientId submissionNr samplingDate arrivalHmf sampleBarcode
        jq --arg na "$NA" -r '.[] | [
            .sampleId//$na,
            .patientId//$na,
            .submissionNr//$na,
            .samplingDate//$na,
            .arrivalHmf//$na,
            .sampleBarcode//$na
        ] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^patient ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" patientId reportingId tumSampleIds tumBarcodes refSampleIds refBarcodes
        jq -r '.[] | [.patientId,
            .reportingId//"N/A",
            ([.tumorSamples[].sampleId//"N/A"]|join(",")),
            ([.tumorSamples[].sampleBarcodes[]//"N/A"]|join(",")),
            ([.referenceSamples[].sampleId//"N/A"]|join(",")),
            ([.referenceSamples[].sampleBarcode//"N/A"]|join(","))
        ] | @tsv' <<< "${json_result}"
    elif [[ "${class}" =~ ^report ]]; then
        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" isolationBarcode type purity hasReliablePurity hasReliableQuality createTime
        jq -r '.[] | [.isolationBarcode, .type, .purity, .hasReliablePurity, .hasReliableQuality, .createTime] | @tsv' <<< "${json_result}"
    elif [[ "${class}" == "TUMOR_INFO" ]]; then
            printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" sampleId tumLocation tumType tumExtra tumDoids biospyLocation biospySubLocation biospyPalgaCode
            jq -r --arg na "$NA" '.[] | select(.tumorType != null) | [
                .sampleId//$na,
                .tumorType.location//$na,
                .tumorType.type//$na,
                .tumorType.extra//$na,
                (.tumorType.doids|join(";"))//$na,
                .biopsy.location//$na,
                .biopsy.subLocation//$na,
                .biopsy.locationPalgaCode//$na
            ] | @tsv' <<< "${json_result}"
    else
        die "Table format for class ${class} is not supported (add -j before other params to get result in JSON format)"
    fi
}

main