#!/usr/bin/env bash

source message_functions || exit 1

LAMA_API_URL="http://lama-preview.prod-1/api"
OUTPUT_TSV=${1-"/data/dbs/clinical_data/curated_primary_tumor_from_lama_preview.tsv"}

function main (){
    info "Retrieving tumor samples from LAMA [$LAMA_API_URL]"
    samples=$(curl --silent "${LAMA_API_URL}/tumor-samples")
    sample_count=$(jq 'length' <<< "$samples")

    info "Extracting tumorType info for ${sample_count} samples"

    # Exact columns are for backwards compatibility with pre-lama curated_primary_tumor.tsv file
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
      "patientIdentifier" \
      "location" \
      "subLocation" \
      "type" \
      "subType" \
      "extraDetails" \
      "doids" \
      "snomedConceptIds" \
      "overridden" > "$OUTPUT_TSV"

    jq -r 'sort_by(.patientId) | .[] | [
      (.patientId | split("-") | join("")),
      (if .tumorType then .tumorType.location else "" end),
      "", # sublocation
      (if .tumorType then
        .tumorType.type + (if .tumorType.extra and .tumorType.extra != "" then "["+.tumorType.extra+"]" else "" end)
      else "" end),
      "", # subtype
      "", # extraDetails
      (if .tumorType then .tumorType.doids|join(";") else "" end),
      "0", # snomedConceptIds
      "false" # overridden
    ] | @tsv' <<< "${samples}" >> "$OUTPUT_TSV"

    info "Written output to ${OUTPUT_TSV}"

    info "Finished with $0"
}

main