#!/usr/bin/env bash

source message_functions || exit 1

cloud_sql_proxy_tool=$1 && shift

if [[ -z ${cloud_sql_proxy_tool} ]]; then
    error "No cloud sql proxy provided"
fi

info "Starting cloud sql proxy towards hmf-actin"

${cloud_sql_proxy_tool} -instances=hmf-actin:europe-west4:actin-emc-prod-1=tcp:127.0.0.1:3307