#!/usr/bin/env bash

source lims_functions || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

tumor_sample=$1 && shift
tumor_sample_barcode=$1 && shift


if [[ -z "${tumor_sample}" || -z "${tumor_sample_barcode}" ]]; then
    error "No tumor information provided. Exiting"
fi

if [[ -z "${tumor_sample_barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  tumor_sample name: ${tumor_sample}"
    warn "  tum sample barcode: ${tumor_sample_barcode}"
    exit 1;
fi

do_run_base_panel_reporter \
    -tumor_sample_id ${tumor_sample} \
    -tumor_sample_barcode ${tumor_sample_barcode} \
    -ref_genome_version 38 \
    "$@"
