#!/usr/bin/env bash

prod_writer_sql_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=mysql-patients-sql-prod-1-writer --project=hmf-secrets)
}

prod_reader_sql_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=mysql-patients-sql-prod-1-reader --project=hmf-secrets)
}

diagnostic_writer_sql_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=mysql-diagnostic-patients-sql-prod-1-writer --project=hmf-secrets)
}

extract_database_host() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" host)
}

extract_database_port() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" port)
}

extract_database_user() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" user)
}

extract_database_dependencies() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" database_dependencies)
}

extract_database_password() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" password)
}

extract_credentials_value() {
    local credentials=$1 && shift
    local value=$1 && shift

    echo "$(echo ${credentials} | sed 's/ /\n/g' | grep ${value}= | cut -d"=" -f2 | sed 's/"//g')"
}

pull_iclusion_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=iclusion-api-credentials --project=hmf-secrets)
}

extract_credentials_value_iclusion() {
    credentials=$1 && shift
    value=$1 && shift

    echo "$(echo ${credentials} | sed 's/: /=/g' | sed 's/ /\n/g' | grep ${value}= | cut -d"=" -f2 | sed 's/"//g')"
}

