#!/usr/bin/env bash

pull_prod_writer_sql_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=mysql-patients-sql-prod-1-writer --project=hmf-secrets)
}

pull_diagnostic_writer_sql_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=mysql-diagnostic-patients-sql-prod-1-writer --project=hmf-secrets)
}

extract_credentials_value() {
    credentials=$1 && shift
    value=$1 && shift

    echo "$(echo ${credentials} | sed 's/ /\n/g' | grep ${value}= | cut -d"=" -f2 | sed 's/"//g')"
}
