#!/usr/bin/env bash

iclusion_credentials() {
    echo $(gcloud secrets versions access "latest" --secret=iclusion-api-credentials --project=hmf-secrets)
}

extract_iclusion_endpoint() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" endpoint)
}

extract_iclusion_client_id() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" client_id)
}

extract_iclusion_client_secret() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" client_secret)
}

extract_iclusion_username() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" username)
}

extract_iclusion_password() {
    local credentials=$1 && shift
    echo $(extract_credentials_value "${credentials}" password)
}

extract_credentials_value_iclusion() {
    credentials=$1 && shift
    value=$1 && shift

    echo "$(echo ${credentials} | sed 's/: /=/g' | sed 's/ /\n/g' | grep ${value}= | cut -d"=" -f 2- | sed 's/"//g')"
}