#!/usr/bin/env bash

source message_functions || exit 1

##################################### JARS #####################################

locate_pilot_actin() {
    echo "/data/actin/system/actin.jar"
}

locate_pilot_isofox() {
    echo "/data/experiments/pilot_tools/isofox/isofox.jar"
}

locate_actin_isofox() {
    echo "/data/actin/tools/isofox/1.6.1/isofox.jar"
}

locate_prod_sage() {
    echo "/data/tools/sage/3.2.3/sage.jar"
}

locate_research_sage() {
    echo "/data/tools/sage/3.2.5/sage.jar"
}

locate_pilot_sage() {
    echo "/data/experiments/pilot_tools/sage/sage.jar"
}

locate_prod_purple() {
    echo "/data/tools/purple/3.5.1/purple.jar"
}

locate_pilot_purple() {
    echo "/data/experiments/pilot_tools/purple/purple.jar"
}

locate_prod_virus_interpreter() {
    echo "/data/tools/virus-interpreter/1.2/virus-interpreter.jar"
}

locate_pilot_virus_interpreter() {
    echo "/data/experiments/pilot_tools/virus-interpreter/virus-interpreter.jar"
}

locate_prod_lilac() {
    echo "/data/tools/lilac/1.1/lilac.jar"
}

locate_research_lilac() {
    echo "/data/tools/lilac/1.5.2/lilac.jar"
}

locate_pilot_lilac() {
    echo "/data/experiments/pilot_tools/lilac/lilac.jar"
}

locate_prod_cuppa_chart() {
    echo "/data/tools/cuppa/1.8.1.rc1/cuppa-chart"
}

locate_prod_cuppa_dna() {
    echo "/data/tools/cuppa/1.8.1.rc1/cuppa.jar"
}

locate_prod_cuppa_dna_rna() {
    echo "/data/tools/cuppa/1.8.1.rc1/cuppa.jar"
}

locate_pilot_cuppa() {
    echo " /data/tools/cuppa/1.8.1.rc1/cuppa.jar"
}

locate_prod_paddle() {
    echo "/data/tools/paddle/1.0/paddle.jar"
}

locate_prod_linx() {
    echo "/data/tools/linx/1.20.1/linx.jar"
}

locate_pilot_linx() {
    echo "/data/experiments/tools/linx.jar"
}

locate_prod_sigs() {
    echo "/data/tools/sigs/1.1/sigs.jar"
}

locate_pilot_sigs() {
    echo "/data/experiments/pilot_tools/sigs/sigs.jar"
}

locate_prod_orange() {
    echo "/data/tools/orange/1.6/orange.jar"
}

locate_research_orange() {
    echo "/data/tools/orange/3.0.2/orange.jar"
}

locate_pilot_orange() {
    echo "/data/experiments/pilot_tools/orange/orange.jar"
}

locate_prod_patient_db() {
    echo "/data/tools/patient-db/3.72/patient-db.jar"
}

locate_research_patient_db() {
    echo "/data/tools/patient-db/5.33/patient-db.jar"
}

locate_prod_clinical_patient_db() {
    echo "/data/tools/patient-db/5.33.2/patient-db.jar"
}

locate_diagnostic_patient_db() {
    echo "/data/tools/patient-db/3.69/patient-db.jar"
}

locate_pilot_patient_db() {
    echo "/data/experiments/pilot_tools/patient-db/patient-db.jar"
}

locate_prod_patient_reporter() {
    echo "/data/tools/patient-reporter/7.26.2/patient-reporter.jar"
}

locate_panel_patient_reporter() {
    echo "/data/experiments/panel_report/patient-reporter.jar"
}

locate_pilot_patient_reporter() {
    echo "/data/experiments/pilot_tools/patient-reporter/patient-reporter.jar"
}

locate_pilot_oncoact_db() {
    echo "/data/experiments/pilot_tools/oncoact-db/oncoact-db.jar"
}

locate_prod_vicc_importer() {
    echo "/data/tools/vicc-importer/1.2/vicc-importer.jar"
}

locate_pilot_vicc_importer() {
    echo "/data/experiments/pilot_tools/vicc-importer/vicc-importer.jar"
}

locate_prod_iclusion_importer() {
    echo "/data/tools/iclusion-importer/1.6/iclusion-importer.jar"
}

locate_pilot_iclusion_importer() {
    echo "/data/experiments/pilot_tools/iclusion-importer/iclusion-importer.jar"
}

locate_prod_ckb_importer() {
    echo "/data/tools/ckb-importer/1.4/ckb-importer.jar"
}

locate_latest_ckb_importer() {
    echo "/data/tools/ckb-importer/2.2.0/ckb-importer.jar"
}

locate_pilot_ckb_importer() {
    echo "/data/experiments/pilot_tools/ckb-importer/ckb-importer.jar"
}

locate_prod_serve() {
    echo "/data/tools/serve/1.12/serve.jar"
}

locate_research_serve() {
    echo "/data/tools/serve/2.5.0/serve.jar"
}

locate_pilot_serve() {
    echo "/data/experiments/pilot_tools/serve/serve.jar"
}

locate_prod_protect() {
    echo "/data/tools/protect/2.3/protect.jar"
}

locate_research_protect() {
    echo "/data/tools/protect/2.3/protect.jar"
}

locate_pilot_protect() {
    echo "/data/experiments/pilot_tools/protect/protect.jar"
}

locate_prod_rose() {
    echo "/data/tools/rose/1.3/rose.jar"
}

locate_pilot_rose() {
    echo "/data/experiments/pilot_tools/rose/rose.jar"
}

locate_prod_pave() {
    echo "/data/tools/pave/1.3.1/pave.jar"
}

locate_prod_hmf_id_generator() {
    echo "/data/tools/hmf-id-generator/2.8/hmf-id-generator.jar"
}

locate_pilot_hmf_id_generator() {
    echo "/data/tools/hmf-id-generator/pilot/hmf-id-generator.jar"
}

locate_prod_datarequest() {
    echo "/data/tools/datarequest/datarequest_prod.jar"
}

locate_pilot_datarequest() {
    echo "/data/tools/datarequest/datarequest_pilot.jar"
}

locate_dsync() {
    echo "/data/tools/dsync/1.8.0/dsync.jar"
}

locate_run_contexts_writer() {
    echo "/data/tools/clinical-db-loader/1.1.0/clinical-db-loader.jar"
}

############################# Clinical patient data ############################

locate_tumor_location_mapping_pilot() {
    echo "/data/resources/ops/clinical_curation/pilot_tumor_location_mapping.tsv"
}

locate_tumor_location_mapping_prod() {
    echo "/data/resources/ops/clinical_curation/tumor_location_mapping.tsv"
}

locate_tumor_location_overrides_pilot() {
    echo "/data/resources/ops/clinical_curation/pilot_tumor_location_overrides.tsv"
}

locate_tumor_location_overrides_prod() {
    echo "/data/resources/ops/clinical_curation/tumor_location_overrides.tsv"
}

locate_treatment_mapping_pilot() {
    echo "/data/resources/ops/clinical_curation/pilot_treatment_mapping.tsv"
}

locate_treatment_mapping_prod() {
    echo "/data/resources/ops/clinical_curation/treatment_mapping.tsv"
}

locate_biopsy_site_mapping_prod() {
    echo "/data/resources/ops/clinical_curation/biopsy_site_mapping.tsv"
}

############################# Patient report data ############################

locate_germline_reporting_prod() {
    echo "/data/resources/ops/germline_reporting/germline_reporting.tsv"
}

locate_clinical_transcripts_prod() {
    echo "/data/resources/ops/clinical_transcripts/clinical_transcripts.tsv"
}

locate_summary_patient_report_prod() {
    echo "/data/resources/ops/summary_patient_report/summary_samples.tsv"
}

locate_special_remark_patient_report_pilot() {
    echo "/data/resources/ops/special_remark_patient_report/special_remark_samples_pilot.tsv"
}

locate_special_remark_patient_report_prod() {
    echo "/data/resources/ops/special_remark_patient_report/special_remark_samples.tsv"
}

locate_rva_logo_prod() {
    echo "/data/resources/ops/patient_report_images/L633_l_testlaboratoria_rva_en_color.jpeg"
}

locate_company_logo_prod() {
    echo "/data/resources/ops/patient_report_images/hartwig_logo.jpg"
}

locate_company_logo_oncoact_prod() {
    echo "/data/resources/ops/patient_report_images/hartwig_oncoact_logo.jpg"
}

locate_signature_prod() {
    echo "/data/resources/ops/patient_report_images/signature_edwin_transparant.png"
}

############################### NON JAVA TOOLS #################################

locate_peach_main() {
    echo "$(locate_repo_dir "peach")/peach"
}

############################# PIPELINE VERSION #################################

extract_expected_pipeline_version() {
    echo "5.31"
}

extract_expected_pipeline_version_data_vm() {
    echo "5.31"
}

extract_expected_pipeline_version_research() {
    echo "5.31"
}

extract_expected_pipeline_version_panel() {
    echo "5.32.9cd1b4b"
}

############################## ACTIN Resources #################################

locate_actin_local_resource_repo() {
    echo "$HOME/hmf/repos/actin-resources-private"
}

locate_actin_database_sql_script() {
    echo "/data/resources/actin/sql_database/generate_database.sql"
}

locate_actin_database_views_sql_script() {
    echo "/data/resources/actin/sql_database/generate_views.sql"
}

locate_actin_clinical_curation_directory() {
    echo "/data/resources/actin/clinical_curation"
}

locate_actin_treatment_db_directory() {
    echo "/data/resources/actin/treatment_db"
}

locate_actin_trial_config_directory() {
    echo "/data/resources/actin/trial_config"
}

locate_actin_ctc_config_directory() {
    echo "/data/resources/actin/ctc_config"
}

locate_actin_minimal_molecular_json() {
    echo "/data/resources/actin/minimal_molecular_json/minimal.json"
}

locate_actin_serve_db() {
    echo "/data/resources/actin/serve_db"
}

locate_actin_external_trial_mapping_tsv() {
    echo "/data/resources/actin/evidence_curation/external_trial_mapping.tsv"
}

locate_actin_known_genes_tsv() {
    echo "/data/resources/actin/serve_db/KnownGenes.SERVE.37.tsv"
}

locate_actin_rna_sample_metadata_file() {
    echo "/data/resources/actin/rna_cohort/actin_sample_cohort_mapping.csv"
}

############################### ACTIN Cohort ###################################

locate_cohort_actin() {
    echo "/data/experiments/charlotte_emc_actionability/system/actin.jar"
}

locate_actin_cohort_pipeline_directory() {
    sample=$1

    echo "/data/experiments/charlotte_emc_actionability/pipelines/${sample}"
}

locate_actin_cohort_molecular_directory() {
    sample=$1

    echo "/data/experiments/charlotte_emc_actionability/molecular/${sample}"
}

locate_actin_cohort_clinical_directory() {
    echo "/data/experiments/charlotte_emc_actionability/clinical"
}

locate_actin_cohort_trial_config_directory() {
    echo "/data/resources/actin/cohort_analysis/trial_config"
}

locate_actin_cohort_trial_database_directory() {
    echo "/data/experiments/charlotte_emc_actionability/trial_database"
}

locate_actin_cohort_treatment_match_directory() {
    echo "/data/experiments/actin_cohort/treatment_matches"
}

############################### ACTIN Buckets ##################################

locate_actin_clinical_data_feed_bucket() {
    echo "gs://actin-prod-clinical-data-feed"
}

locate_actin_clinical_output_bucket() {
    echo "gs://actin-prod-clinical-pipeline-output"
}

locate_actin_evaluation_bucket() {
    echo "gs://actin-prod-evaluation"
}

locate_actin_shared_reports_bucket() {
    echo "gs://actin-prod-shared-reports"
}

locate_actin_wgs_pipeline_bucket() {
    echo "gs://actin-prod-wgs-pipeline-output"
}

locate_actin_prod_data_bucket() {
    echo "gs://actin-prod-patient-data"
}

locate_actin_analysis_bucket() {
  echo "gs://actin-prod-actin-analysis-output"
}

################################# ACTIN Data Bucket Based ###################################

locate_actin_blob(){
  local gsutilUri=$1 && shift
  local name=$1 && shift
  if gsutil ls "${reportGsutilUri}" >/dev/null 2>&1; then
    echo "${reportGsutilUri}"
  else
    error "Could not locate ${name} for patient '${patient}'"
  fi
}

locate_actin_clinical_json() {
  local patient=$1 && shift
  local reportGsutilUri="$(locate_actin_clinical_output_bucket)/${patient}.clinical.json"
  echo $(locate_actin_blob reportGsutilUri "clinical json")
}

locate_actin_clinical_json_for_sample() {
  local sample=$1 && shift
  patient=$(echo ${sample} | head -c 12)
  locate_actin_clinical_json patient
}

locate_actin_molecular_json() {
  local sample=$1 && shift
  local reportGsutilUri="$(locate_actin_analysis_bucket)}/molecular/${sample}.molecular.json"
  echo $(locate_actin_blob reportGsutilUri "molecular json")
}

locate_actin_orange_no_germline_json() {
  local sample=$1 && shift
  local reportGsutilUri = "$(locate_actin_analysis_bucket)/orange/${sample}.orange.json"
  echo $(locate_actin_blob reportGsutilUri "orange json")
}

locate_actin_orange_no_germline_pdf() {
  local sample=$1 && shift
  local reportGsutilUri="$(locate_actin_analysis_bucket)/orange/${sample}.orange.pdf"
  echo $(locate_actin_blob reportGsutilUri "orange pdf")
}

locate_actin_treatment_match_json() {
  local patient=$1 && shift
  local reportGsutilUri="$(locate_actin_analysis_bucket)/algo/${patient}.treatment_match.json"
  echo $(locate_actin_blob reportGsutilUri "treatment match json")
}

locate_actin_report_pdf() {
  local patient=$1 && shift
  local reportGsutilUri="$(locate_actin_analysis_bucket)/report/${patient}.actin.pdf"
  echo $(locate_actin_blob reportGsutilUri "ACTIN report PDF")
}

locate_actin_evaluation_details() {
  local patient=$1 && shift
  local reportGsutilUri="$(locate_actin_analysis_bucket)/evaluation/${patient}.evaluation.details.tsv"
  echo $(locate_actin_blob reportGsutilUri "ACTIN evaluation details")
}

locate_actin_evaluation_summary() {
  local patient=$1 && shift
  local reportGsutilUri="$(locate_actin_analysis_bucket)/evaluation/${patient}.evaluation.summary.tsv"
  echo $(locate_actin_blob reportGsutilUri "ACTIN evaluation summary")
}

################################# ACTIN Data VM Based ###################################

locate_actin_curated_clinical_directory() {
    echo "/data/actin/clinical/curated"
}

locate_actin_clinical_input_feed_directory() {
    echo "/data/actin/clinical/input_feed/latest"
}

locate_actin_wgs_pipeline_output_directory() {
    echo "/data/actin/wgs_pipeline_output"
}

locate_actin_wts_pipeline_output_directory() {
    echo "/data/actin/wts_pipeline_output"
}

locate_actin_molecular_directory() {
    echo "/data/actin/molecular"
}

locate_actin_molecular_directory_for_sample() {
    local sample=$1 && shift

    if [[ -z "${sample}" ]]; then
        error "No sample provided. Exiting"
    fi

    echo "$(locate_actin_molecular_directory)/${sample}"
}

locate_most_recent_actin_molecular_sample() {
    local patient=$1
    local sample=""
    local molecular_dir=""
    for i in {9..1}; do
        sample="${patient}T${i}"
        molecular_dir=$(locate_actin_molecular_directory_for_sample ${sample})
        if [[ -d "${molecular_dir}" ]]; then
            break
        fi
    done

    if [[ ! -d "${molecular_dir}" ]]; then
        sample="${patient}T"
    fi

    echo ${sample}
}

locate_most_recent_actin_molecular_json() {
    local patient=$1
    local sample=$(locate_most_recent_actin_molecular_sample ${patient})

    echo $(locate_actin_molecular_json ${sample})
}

locate_actin_trial_database_directory() {
    echo "/data/actin/trial_database"
}

locate_actin_treatment_match_directory() {
    echo "/data/actin/treatment_matches"
}

##################################### RNA ######################################

locate_rna_bam_directory() {
    local run_dir=$1 && shift

    echo "${run_dir}/rna_bam"
}

locate_rna_bam() {
    local run_dir=$1 && shift

    local bam_directory=$(locate_rna_bam_directory ${run_dir})
    local bam=$(find -L "${bam_directory}/" -type f -name "*.sorted.dups.bam")

    echo "${bam}"
}

locate_rna_hla_bam() {
    local run_dir=$1 && shift

    local bam_directory=$(locate_rna_bam_directory ${run_dir})
    local bam=$(find -L "${bam_directory}/" -type f -name "*.hla.bam")

    echo "${bam}"
}

locate_rna_sage_somatic_directory() {
    local run_dir=$1 && shift

    echo "${run_dir}/sage_rna_somatic"
}

locate_rna_sage_germline_directory() {
    local run_dir=$1 && shift

    echo "${run_dir}/sage_rna_germline"
}

locate_rna_annotated_somatic_variants() {
    local run_dir=$1 && shift

    local rna_sage_somatic_directory=$(locate_rna_sage_somatic_directory ${run_dir})
    local rna_annotated_vcf=$(find -L "${rna_sage_somatic_directory}/" -type f -name "*.purple.somatic.with_rna.vcf.gz")

    echo "${rna_annotated_vcf}"
}

locate_rna_annotated_germline_variants() {
    local run_dir=$1 && shift

    local rna_sage_germline_directory=$(locate_rna_sage_germline_directory ${run_dir})
    local rna_annotated_vcf=$(find -L "${rna_sage_germline_directory}/" -type f -name "*.purple.germline.with_rna.vcf.gz")

    echo "${rna_annotated_vcf}"
}

locate_rna_analysis_bucket() {
    local sample=$1 && shift
    local rna_analysis_bucket=""

    # Check if there is a Log.out for this sample in the bucket
    gsutil -q stat "gs://hmf-rna-analysis/samples/${sample}/Log.out"
    if [[ $? == 0 ]]; then
        rna_analysis_bucket="gs://hmf-rna-analysis/samples/${sample}"
    fi

    # If it does not exist, try again with another file (run.log):
    if [[ -z ${rna_analysis_bucket} ]]; then
        gsutil -q stat "gs://hmf-rna-analysis/samples/${sample}/run.log"
        if [[ $? == 0 ]]; then
            rna_analysis_bucket="gs://hmf-rna-analysis/samples/${sample}"
        fi
    fi

    echo "${rna_analysis_bucket}"
}

############################# Pipeline Resources ###############################

locate_ensembl_data_dir_37() {
    echo "/data/resources/public/ensembl_data_cache/37"
}

locate_ensembl_data_dir_38() {
    echo "/data/resources/public/ensembl_data_cache/38"
}

locate_amber_snpcheck_37_vcf() {
    echo "/data/resources/public/amber/37/Amber.snpcheck.37.vcf"
}

locate_amber_snpcheck_38_vcf() {
    echo "/data/resources/public/amber/38/Amber.snpcheck.38.vcf"
}

locate_cuppa_ref_dir_dna() {
    echo "/data/resources/public/cuppa"
}

locate_cuppa_ref_dir_dna_rna() {
    echo "/data/resources/actin/cuppa_ref_dna_rna_1_8"
}

locate_cohort_mapping_tsv() {
    echo "/data/resources/public/orange/cohort_mapping.tsv"
}

locate_cohort_percentiles_tsv() {
    echo "/data/resources/public/orange/cohort_percentiles.tsv"
}

locate_isofox_gene_distribution_csv() {
    echo "/data/resources/actin/rna_reference_database/isofox.hmf_3444.gene_distribution.37.csv"
}

locate_isofox_alt_sj_cohort_csv() {
    echo "/data/resources/actin/rna_reference_database/isofox.hmf_3444.alt_sj_cohort.37.csv"
}

locate_doid_json() {
    echo "/data/resources/public/disease_ontology/doid.json"
}

locate_atc_tsv() {
    echo "/data/resources/actin/atc_config/atc_tree.tsv"
}

locate_driver_gene_panel_37_tsv() {
    echo "/data/resources/public/gene_panel/37/DriverGenePanel.37.tsv"
}

locate_driver_gene_panel_38_tsv() {
    echo "/data/resources/public/gene_panel/38/DriverGenePanel.38.tsv"
}

locate_known_fusion_data_37_csv() {
    echo "/data/resources/public/fusions/37/known_fusion_data.37.csv"
}

locate_known_fusion_data_38_csv() {
    echo "/data/resources/public/fusions/38/known_fusion_data.38.csv"
}

locate_peach_resource_dir() {
    echo "/data/dbs/peach"
}

############################### Ops Resources #################################

locate_samplesheets_dir() {
    echo "/data/samplesheets"
}

locate_sample_registration_unregistered_jsons_dir() {
    echo "/data/ops/api/prod/jsons"
}

locate_sample_registration_registered_jsons_dir() {
    echo "/data/ops/api/prod/jsons/registered"
}

locate_sample_registration_logs_dir() {
    echo "/data/ops/api/prod/logs"
}

locate_snpcheck_dir() {
    echo "/data/snpcheck"
}

locate_snpcheck_vcf_upload_dir() {
    echo "/data/snpcheck/gcp-sync"
}

############################### SERVE Resources ################################

locate_pilot_iclusion_trial_tsv() {
    echo "/data/resources/crunch/serve/iclusion/iclusion_trials_pilot.tsv"
}

locate_prod_iclusion_trial_tsv() {
    echo "/data/resources/crunch/serve/iclusion/iclusion_trials_prod.tsv"
}

locate_latest_iclusion_trial_tsv() {
    echo "/data/resources/crunch/serve/iclusion/iclusion_trials_latest.tsv"
}

locate_prod_iclusion_trial_tsv_pilot() {
    echo "/data/resources/crunch/serve/iclusion/iclusion_trials_pilot.tsv"
}

locate_iclusion_filter_tsv() {
    echo "/data/resources/crunch/serve/curation/iclusion_filters.tsv"
}

locate_iclusion_filter_pilot_tsv() {
  echo "/data/resources/crunch/serve/curation/iclusion_filters_pilot.tsv"
}

locate_vicc_json() {
    echo "/data/resources/crunch/serve/vicc/all.json"
}

locate_docm_tsv() {
    echo "/data/resources/crunch/serve/docm/docm_v3.2.tsv"
}

locate_hartwig_cohort_hotspots_tsv() {
    echo "/data/resources/crunch/serve/hartwig/hotspot/hartwig_cohort_hotspots.tsv"
}

locate_hartwig_curated_hotspots_tsv() {
    echo "/data/resources/crunch/serve/hartwig/hotspot/hartwig_curated_hotspots.tsv"
}

locate_hartwig_curated_genes_tsv() {
    echo "/data/resources/crunch/serve/hartwig/gene/hartwig_curated_genes.tsv"
}

locate_ckb_flex_data_production_dir() {
    echo "/data/resources/custom/ckb/production/ckb_flex_dump"
}

locate_ckb_flex_data_latest_dir() {
    echo "/data/resources/custom/ckb/latest/ckb_flex_dump"
}

locate_ckb_filter_tsv() {
    echo "/data/resources/crunch/serve/curation/ckb_filters.tsv"
}

locate_ckb_filter_pilot_tsv() {
    echo "/data/resources/crunch/serve/curation/ckb_filters_pilot.tsv"
}

locate_ckb_drug_class_curation_pilot_tsv() {
    echo "/data/resources/crunch/serve/curation/ckb_treatment_approach_curation_pilot.tsv"
}

locate_ckb_drug_curation_tsv() {
    echo "/data/resources/crunch/serve/curation/ckb_treatment_approach_curation.tsv"
}

locate_public_missing_doids_mapping_tsv() {
    echo "/data/resources/crunch/serve/curation/public_doids_mapping.tsv"
}

locate_private_missing_doids_mapping_tsv() {
    echo "/data/resources/crunch/serve/curation/private_doids_mapping.tsv"
}

############################### ROSE Resources ################################

locate_actionability_database_tsv() {
    echo "/data/resources/ops/rose/actionability.tsv"
}

locate_actionability_database_tsv_pilot() {
    echo "/data/resources/crunch/rose/actionability.tsv"
}

#################################### Repos #####################################

locate_repo_dir() {
    local repo_name=$1 && shift
    echo "/data/repos/${repo_name}"
}

locate_resources_repo_dir() {
    local repo_name=$1 && shift
    echo "/data/resources/${repo_name}"
}

################################# REF GENOME ###################################

locate_ref_genome_37_fasta_file() {
    echo "/data/resources/bucket/reference_genome/37/Homo_sapiens.GRCh37.GATK.illumina.fasta"
}

locate_ref_genome_38_fasta_file() {
    echo "/data/resources/bucket/reference_genome/38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
}

locate_ref_genome_37_to_38_chain() {
    echo "/data/resources/crunch/reference_genome_liftover/hg19ToHg38.over.chain"
}

locate_ref_genome_38_to_37_chain() {
    echo "/data/resources/crunch/reference_genome_liftover/hg38ToHg19.over.chain"
}

##################################  METRICS ####################################

locate_wgs_metrics() {
    local run_dir=$1 && shift
    local sample=$1 && shift

    local metrics_file=""
    local metrics_dir_pre_v5=${run_dir}/QCStats
    local metrics_dir_v5=${run_dir}/${sample}/bam_metrics

    if [[ -d "${metrics_dir_pre_v5}" ]]; then
        metrics_file=$(find -L ${metrics_dir_pre_v5}/ -type f -name "${sample}*_WGSMetrics.txt")
    elif [[ -d "${metrics_dir_v5}" ]]; then
        metrics_file=$(find -L ${metrics_dir_v5}/ -type f -name "${sample}.wgsmetrics")
        # Some runs have new structure but still old file names.
        if [[ -z ${metrics_file} ]]; then
            metrics_file=$(find -L ${metrics_dir_v5}/ -type f -name "${sample}*_WGSMetrics.txt")
        fi
    fi

    if [[ -z "${metrics_file}" ]]; then
        error "Unable to locate metrics file for ${sample} in run ${run_dir}."
    fi

    echo ${metrics_file}
}

locate_flagstats() {
    local run_dir=$1 && shift
    local sample=$1 && shift

    local flagstats_file=""
    local flagstats_dir_pre_v5=${run_dir}/${sample}/mapping
    local flagstats_dir_v5=${run_dir}/${sample}/flagstat

    if [[ -d "${flagstats_dir_pre_v5}" ]]; then
        flagstats_file=$(find -L ${flagstats_dir_pre_v5}/ -type f -name "${sample}*.realigned.flagstat")
    elif [[ -d "${flagstats_dir_v5}" ]]; then
        flagstats_file=$(find -L ${flagstats_dir_v5}/ -type f -name "${sample}.flagstat")
        # Some runs have new structure but still old file names.
        if [[ -z ${flagstats_file} ]]; then
            flagstats_file=$(find -L ${flagstats_dir_v5}/ -type f -name "${sample}*.realigned.flagstat")
        fi
    fi

    if [[ -z "${flagstats_file}" ]]; then
        error "Unable to locate flagstats file for ${sample} in run ${run_dir}."
    fi

    echo ${flagstats_file}
}

##################################### AMBER ####################################

locate_amber_directory() {
    local run_dir=$1
    local amber_dir=${run_dir}/amber

    if [[ ! -d "${amber_dir}" ]]; then
        error "Unable to locate AMBER directory in ${run_dir}."
    fi

    echo ${amber_dir}
}

###################################### SAGE ####################################

locate_sage_somatic_data_directory() {
    local run_dir=$1
    local sage_somatic_dir=""

    if [[ -d "${run_dir}/sage_somatic" ]]; then
        sage_somatic_dir="${run_dir}/sage_somatic"
    elif [[ -d "${run_dir}/sage" ]]; then
        sage_somatic_dir="${run_dir}/sage"
    fi

    echo "${sage_somatic_dir}"
}

locate_sage_filtered_somatic_variants() {
    local run_dir=$1
    local sage_dir_old=${run_dir}/sage
    local sage_dir=${run_dir}/sage_somatic

    local somatic_vcf=""

    if [[ -d "${sage_dir}" ]]; then
        somatic_vcf=$(find -L ${sage_dir}/ -type f -name "*.sage.somatic.filtered.vcf.gz")
    elif [[ -d "${sage_dir_old}" ]]; then
        somatic_vcf=$(find -L ${sage_dir_old}/ -type f -name "*.sage.somatic.filtered.vcf.gz")
    fi

    if [[ -z "${somatic_vcf}" ]]; then
        error "Unable to locate sage filtered somatic variants in ${run_dir}."
    fi
    echo ${somatic_vcf}
}

locate_sage_full_somatic_variants() {
    local run_dir=$1
    local sage_dir_old=${run_dir}/sage
    local sage_dir=${run_dir}/sage_somatic

    local somatic_vcf=""

    if [[ -d "${sage_dir}" ]]; then
        somatic_vcf=$(find -L ${sage_dir}/ -type f -name "*.sage.somatic.vcf.gz")
    elif [[ -d "${sage_dir_old}" ]]; then
        somatic_vcf=$(find -L ${sage_dir_old}/ -type f -name "*.sage.somatic.vcf.gz")
    fi

    if [[ -z "${somatic_vcf}" ]]; then
        error "Unable to locate sage full somatic variants in ${run_dir}."
    fi
    echo ${somatic_vcf}
}

locate_sage_bqr_tsv() {
    local run_dir=$1 && shift
    local sample=$1 && shift

    local sage_dir="${run_dir}/sage_somatic"

    local bqr_tsv=""

    if [[ -d "${sage_dir}" ]]; then
        bqr_tsv=$(find -L ${sage_dir}/ -type f -name "${sample}.sage.bqr.tsv")
    fi

    if [[ -z "${bqr_tsv}" ]]; then
        error "Unable to locate BQR TSV for ${sample} in ${run_dir}."
    fi

    echo ${bqr_tsv}
}

locate_sage_bqr_plot() {
    local run_dir=$1 && shift
    local sample=$1 && shift

    local sage_dir_old=${run_dir}/sage
    local sage_dir=${run_dir}/sage_somatic

    local bqr_plot=""

    if [[ -d "${sage_dir}" ]]; then
        bqr_plot=$(find -L ${sage_dir}/ -type f -name "${sample}.sage.bqr.png")
    elif [[ -d "${sage_dir_old}" ]]; then
        bqr_plot=$(find -L ${sage_dir_old}/ -type f -name "${sample}.sage.bqr.png")
    fi

    if [[ -z "${bqr_plot}" ]]; then
        error "Unable to locate BQR plot for ${sample} in ${run_dir}."
    fi
    echo ${bqr_plot}
}

locate_sage_germline_data_directory() {
    local run_dir=$1

    echo "${run_dir}/sage_germline"
}

locate_sage_germline_gene_coverage() {
    local run_dir=$1 && shift

    local sage_dir=${run_dir}/sage_germline

    local gene_coverage_tsv=""

    if [[ -d "${sage_dir}" ]]; then
        gene_coverage_tsv=$(find -L ${sage_dir}/ -type f -name "*.sage.gene.coverage.tsv")
    fi

    if [[ -z "${gene_coverage_tsv}" ]]; then
        error "Unable to locate SAGE germline gene coverage in ${run_dir}."
    fi
    echo ${gene_coverage_tsv}
}

##################################### PURPLE ###################################

locate_purple_data_directory() {
    local run_dir=$1

    local purple_data_dir="${run_dir}/purple"
    if [[ ! -d "${purple_data_dir}" ]]; then
        error "Unable to locate purple data directory in ${run_dir}."
    fi

    echo "${purple_data_dir}"
}

locate_purple_plot_directory() {
    local run_dir=$1

    local purple_plot_dir="${run_dir}/purple/plot"
    if [[ ! -d "${purple_plot_dir}" ]]; then
        error "Unable to locate purple plot directory in ${run_dir}."
    fi

    echo "${purple_plot_dir}"
}

locate_purple_purity() {
    local run_dir=$1
    local purple_purity_tsv=$(find -L ${run_dir}/purple/ -type f -name "*.purple.purity.tsv")
    if [[ -z "${purple_purity_tsv}" ]]; then
        error "Unable to locate purple purity in ${run_dir}."
    fi
    echo ${purple_purity_tsv}
}

locate_purple_pilot_purity() {
    local run_dir=$1
    local purple_pilot_dir=${run_dir}/purple_pilot
    local purple_purity_tsv=""

    if [[ -d "${purple_pilot_dir}" ]]; then
        purple_purity_tsv=$(find -L ${purple_pilot_dir}/ -type f -name "*.purple.purity.tsv")
    fi

    if [[ -z "${purple_purity_tsv}" ]]; then
        error "Unable to locate purple pilot purity in ${run_dir}."
    fi
    echo ${purple_purity_tsv}
}

locate_purple_qc() {
    local run_dir=$1
    local purple_qc_file=$(find -L ${run_dir}/purple/ -type f -name "*.purple.qc")
    if [[ -z "${purple_qc_file}" ]]; then
        error "Unable to locate purple qc in ${run_dir}."
    fi
    echo ${purple_qc_file}
}

locate_purple_somatic_driver_catalog() {
    local run_dir=$1
    local purple_somatic_driver_tsv=$(find -L ${run_dir}/purple/ -type f -name "*.driver.catalog.somatic.tsv")
    if [[ -z "${purple_somatic_driver_tsv}" ]]; then
        error "Unable to locate purple somatic driver catalog in ${run_dir}."
    fi
    echo ${purple_somatic_driver_tsv}
}

locate_purple_somatic_copynumber_tsv() {
    local run_dir=$1
    local purple_somatic_copynumber_tsv=$(find -L ${run_dir}/purple/ -type f -name "*.purple.cnv.somatic.tsv")
    if [[ -z "${purple_somatic_copynumber_tsv}" ]]; then
        error "Unable to locate purple somatic copynumbers in ${run_dir}."
    fi
    echo ${purple_somatic_copynumber_tsv}
}

locate_purple_gene_copynumbers() {
    local run_dir=$1
    local purple_gene_copynumbers=$(find -L ${run_dir}/purple/ -type f -name "*.purple.cnv.gene.tsv")
    if [[ -z "${purple_gene_copynumbers}" ]]; then
        error "Unable to locate purple gene copynumbers in ${run_dir}."
    fi
    echo ${purple_gene_copynumbers}
}

locate_purple_pilot_gene_copynumbers() {
    local run_dir=$1
    local purple_pilot_dir=${run_dir}/purple_pilot
    local purple_gene_copynumbers=""

    if [[ -d "${purple_pilot_dir}" ]]; then
        purple_gene_copynumbers=$(find -L ${purple_pilot_dir}/ -type f -name "*.purple.cnv.gene.tsv")
    fi

    if [[ -z "${purple_gene_copynumbers}" ]]; then
        error "Unable to locate purple pilot gene copynumbers in ${run_dir}."
    fi
    echo ${purple_gene_copynumbers}
}

locate_purple_somatic_variants() {
    local run_dir=$1
    local somatic_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.somatic.vcf.gz")
    if [[ -z "${somatic_vcf}" ]]; then
        error "Unable to locate purple somatic variants in ${run_dir}."
    fi
    echo ${somatic_vcf}
}

locate_purple_somatic_variants_panel() {
    local run_dir=$1
    local somatic_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.somatic.vcf.gz")
    if [[ -z "${somatic_vcf}" ]]; then
        error "Unable to locate purple somatic variants in ${run_dir}."
    fi
    echo ${somatic_vcf} | tr "/" " " | awk '{print $NF}'
}

locate_purple_pilot_somatic_variants() {
    local run_dir=$1
    local purple_pilot_dir=${run_dir}/purple_pilot
    local somatic_vcf=""

    if [[ -d "${purple_pilot_dir}" ]]; then
        somatic_vcf=$(find -L ${purple_pilot_dir}/ -type f -name "*.purple.somatic.vcf.gz")
    fi

    if [[ -z "${somatic_vcf}" ]]; then
        error "Unable to locate purple pilot somatic variants in ${run_dir}."
    fi

    echo ${somatic_vcf}
}

locate_purple_circos_plot() {
    local run_dir=$1
    local circos_plot=$(find -L ${run_dir}/purple/plot/ -type f -name "*.circos.png")
    if [[ -z "${circos_plot}" ]]; then
        error "Unable to locate purple circos plot in ${run_dir}."
    fi
    echo ${circos_plot}
}

locate_purple_pilot_circos_plot() {
    local run_dir=$1
    local purple_pilot_dir=${run_dir}/purple_pilot
    local circos_plot=""

    if [[ -d "${purple_pilot_dir}" ]]; then
        circos_plot=$(find -L ${purple_pilot_dir}/plot/ -type f -name "*.circos.png")
    fi

    if [[ -z "${circos_plot}" ]]; then
        error "Unable to locate purple pilot circos plot in ${run_dir}."
    fi
    echo ${circos_plot}
}

################################ PURPLE Germline ###############################

locate_purple_germline_variants() {
    local run_dir=$1
    local germline_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.germline.vcf.gz")
    if [[ -z "${germline_vcf}" ]]; then
        error "Unable to locate purple germline variants in ${run_dir}."
    fi
    echo ${germline_vcf}
}

locate_purple_pilot_germline_variants() {
    local run_dir=$1
    local purple_dir=${run_dir}/purple_pilot

    local germline_vcf=""

    if [[ -d "${purple_dir}" ]]; then
        germline_vcf=$(find -L ${purple_dir} -type f -name "*.purple.germline.vcf.gz")
    fi

    if [[ -z "${germline_vcf}" ]]; then
        error "Unable to locate purple pilot germline variants in ${run_dir}."
    fi
    echo ${germline_vcf}
}

locate_purple_germline_deletions() {
    local run_dir=$1
    local purple_germline_deletion_tsv=$(find -L ${run_dir}/purple/ -type f -name "*.purple.germline.deletion.tsv")
    if [[ -z "${purple_germline_deletion_tsv}" ]]; then
        error "Unable to locate purple germline deletions in ${run_dir}."
    fi
    echo ${purple_germline_deletion_tsv}
}

locate_purple_germline_driver_catalog() {
    local run_dir=$1
    local purple_germline_driver_tsv=$(find -L ${run_dir}/purple/ -type f -name "*.driver.catalog.germline.tsv")
    if [[ -z "${purple_germline_driver_tsv}" ]]; then
        error "Unable to locate purple germline driver catalog in ${run_dir}."
    fi
    echo ${purple_germline_driver_tsv}
}

############################ Structural Variants ###############################

locate_purple_structural_variants() {
    local run_dir=$1
    local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
    if [[ -z "${structural_vcf}" ]]; then
        error "Unable to locate purple structural variants in ${run_dir}."
    fi
    echo ${structural_vcf}
}

locate_purple_pilot_structural_variants() {
    local run_dir=$1
    local purple_pilot_dir=${run_dir}/purple_pilot
    local structural_vcf=""

    if [[ -d "${purple_pilot_dir}" ]]; then
        structural_vcf=$(find -L ${purple_pilot_dir}/ -type f -name "*.purple.sv.vcf.gz")
    fi

    if [[ -z "${structural_vcf}" ]]; then
        error "Unable to locate purple pilot structural variants in ${run_dir}."
    fi
    echo ${structural_vcf}
}

locate_gripss_structural_variants() {
    local run_dir=$1
    local gripss_dir="${run_dir}/gripss_somatic"
    [[ -d "${gripss_dir}" ]] || gripss_dir="${run_dir}/gripss"

    local structural_vcf=""
    if [[ -d "${gripss_dir}" ]]; then
        structural_vcf=$(find -L ${gripss_dir}/ -type f -name "*.gripss.somatic.filtered.vcf.gz")
        # With GRIPSS 2.0 the name has changed from "somatic filtered" to "filtered somatic"
        if [[ -z ${structural_vcf} ]]; then
            structural_vcf=$(find -L ${gripss_dir}/ -type f -name "*.gripss.filtered.somatic.vcf.gz")
        fi
    fi

    if [[ -z "${structural_vcf}" ]]; then
        error "Unable to locate GRIPSS structural variants in ${run_dir}."
    fi
    echo ${structural_vcf}
}

locate_gripss_recovery_candidates() {
    local run_dir=$1
    local gripss_dir="${run_dir}/gripss_somatic"
    [[ -d "${gripss_dir}" ]] || gripss_dir="${run_dir}/gripss"

    local structural_vcf=""
    if [[ -d "${gripss_dir}" ]]; then
        structural_vcf=$(find -L ${gripss_dir}/ -type f -name "*.gripss.somatic.vcf.gz")
    fi

    if [[ -z "${structural_vcf}" ]]; then
        error "Unable to locate GRIPSS recovery variants in ${run_dir}."
    fi
    echo ${structural_vcf}
}

##################################### LINX #####################################

locate_linx_somatic_data_directory() {
    local run_dir=$1

    local linx_somatic_data_directory="${run_dir}/linx"
    if [[ ! -d "${linx_somatic_data_directory}" ]]; then
        error "Unable to locate linx somatic data directory in ${run_dir}."
    fi
    echo "${linx_somatic_data_directory}"
}

locate_linx_plot_directory() {
    local run_dir=$1

    local linx_plot_dir="${run_dir}/linx/plot"
    echo "${linx_plot_dir}"
}

locate_linx_fusions() {
    local run_dir=$1
    local fusion_tsv=$(find -L ${run_dir}/linx/ -type f -name "*.linx.fusion.tsv")
    if [[ -z "${fusion_tsv}" ]]; then
        error "Unable to locate linx fusions tsv in ${run_dir}."
    fi
    echo ${fusion_tsv}
}

locate_linx_breakends() {
    local run_dir=$1
    local disruption_tsv=$(find -L ${run_dir}/linx/ -type f -name "*.linx.breakend.tsv")
    if [[ -z "${disruption_tsv}" ]]; then
        error "Unable to locate linx disruptions tsv in ${run_dir}."
    fi
    echo ${disruption_tsv}
}

locate_linx_driver_catalog() {
    local run_dir=$1
    local driver_catalog_tsv=$(find -L ${run_dir}/linx/ -type f -name "*.driver.catalog.tsv")
    if [[ -z "${driver_catalog_tsv}" ]]; then
        error "Unable to locate linx drivers catalog in ${run_dir}."
    fi
    echo ${driver_catalog_tsv}
}

locate_linx_drivers() {
    local run_dir=$1
    local driver_tsv=$(find -L ${run_dir}/linx/ -type f -name "*.drivers.tsv")
    if [[ -z "${driver_tsv}" ]]; then
        error "Unable to locate linx drivers in ${run_dir}."
    fi
    echo ${driver_tsv}
}

locate_linx_structural_variants() {
    local run_dir=$1
    local structural_variant_tsv=$(find -L ${run_dir}/linx/ -type f -name "*.linx.svs.tsv")
    if [[ -z "${structural_variant_tsv}" ]]; then
        error "Unable to locate linx structural variant tsv in ${run_dir}."
    fi
    echo ${structural_variant_tsv}
}

################################# LINX GERMLINE ################################

locate_linx_germline_data_directory() {
    local run_dir=$1
    local linx_germline_data_directory="${run_dir}/linx_germline"
    if [[ ! -d "${linx_germline_data_directory}" ]]; then
        error "Unable to locate linx germline data directory in ${run_dir}."
    fi
    echo ${linx_germline_data_directory}
}

locate_linx_germline_disruptions() {
    local run_dir=$1
    local germline_disruption_tsv=$(find -L ${run_dir}/linx_germline/ -type f -name "*.linx.germline.disruption.tsv")
    if [[ -z "${germline_disruption_tsv}" ]]; then
        error "Unable to locate linx germline disruptions in ${run_dir}."
    fi
    echo ${germline_disruption_tsv}
}

##################################### LILAC ####################################

locate_lilac_data_directory() {
    local run_dir=$1

    echo "${run_dir}/lilac"
}

locate_lilac_results() {
    local run_dir=$1
    local results_file=""
    results_file=$(find -L "${run_dir}/lilac/" -type f -name "*.lilac.csv" -or -name "*.lilac.tsv")
    if [[ -z "${results_file}" ]]; then
        error "Unable to locate lilac result csv/tsv in ${run_dir}."
    fi
    echo "${results_file}"
}

locate_lilac_qc() {
    local run_dir=$1
    local qc_file=""
    qc_file=$(find -L "${run_dir}/lilac/" -type f -name "*.lilac.qc.csv" -or -name "*.lilac.qc.tsv")
    if [[ -z "${qc_file}" ]]; then
        error "Unable to locate lilac qc csv/tsv in ${run_dir}."
    fi
    echo "${qc_file}"
}

locate_lilac_hla_bam_for_sample() {
    local run_dir=$1 && shift
    local sample=$1 && shift

    local hla_bam=$(find -L ${run_dir}/lilac_slicer -type f -name "${sample}.hla.bam")
    if [[ -z "${hla_bam}" ]]; then
        error "Unable to locate lilac HLA BAM for ${sample} in ${run_dir}."
    fi
    echo ${hla_bam}
}


##################################### ROSE #####################################

locate_rose_pilot() {
    local run_dir=$1
    local rose_tsv=$(find -L ${run_dir}/rose_pilot/ -type f -name "*.rose.tsv")
    echo $rose_tsv
    if [[ -z "${rose_tsv}" ]]; then
        error "Unable to locate rose pilot tsv in ${run_dir}."
    fi
    echo ${rose_tsv}
}

locate_rose() {
    local run_dir=$1
    local rose_tsv=$(find -L ${run_dir}/rose/ -type f -name "*.rose.tsv")
    if [[ -z "${rose_tsv}" ]]; then
        error "Unable to locate rose tsv in ${run_dir}."
    fi
    echo ${rose_tsv}
}

#################################### ISOFOX ####################################

locate_isofox_data_directory() {
    local run_dir=$1

    echo "${run_dir}/isofox"
}

locate_isofox_summary() {
    local run_dir=$1
    local summary_csv=$(find -L ${run_dir}/isofox/ -type f -name "*.isf.summary.csv")
    if [[ -z "${summary_csv}" ]]; then
        error "Unable to locate isofox summary csv in ${run_dir}."
    fi
    echo ${summary_csv}
}

locate_isofox_gene_data() {
    local run_dir=$1
    local gene_data_csv=$(find -L ${run_dir}/isofox/ -type f -name "*.isf.gene_data.csv")
    if [[ -z "${gene_data_csv}" ]]; then
        error "Unable to locate isofox gene data csv in ${run_dir}."
    fi
    echo ${gene_data_csv}
}

locate_isofox_pass_fusions() {
    local run_dir=$1
    local pass_fusions_csv=$(find -L ${run_dir}/isofox/ -type f -name "*.isf.pass_fusions.csv")
    if [[ -z "${pass_fusions_csv}" ]]; then
        error "Unable to locate isofox pass fusions csv in ${run_dir}."
    fi
    echo ${pass_fusions_csv}
}

locate_isofox_alt_splice_junctions() {
    local run_dir=$1
    local alt_splice_junc_csv=$(find -L ${run_dir}/isofox/ -type f -name "*.isf.alt_splice_junc.csv")
    if [[ -z "${alt_splice_junc_csv}" ]]; then
        error "Unable to locate isofox alt splice junction csv in ${run_dir}."
    fi
    echo ${alt_splice_junc_csv}
}

##################################### Sigs #####################################

locate_sigs_data_directory() {
    local run_dir=$1
    if [[ ! -d ${run_dir} ]]; then
        error "Run dir is not a directory: ${run_dir}"
    fi
    echo "${run_dir}/sigs"
}

locate_sigs_allocation_tsv() {
    local run_dir=$1
    local sigs_allocation_tsv=$(find -L ${run_dir}/sigs/ -type f -name "*.sig.allocation.tsv")
    if [[ -z "${sigs_allocation_tsv}" ]]; then
        error "Unable to locate sigs allocation tsv in ${run_dir}."
    fi
    echo ${sigs_allocation_tsv}
}

locate_sigs_pilot_dir() {
    local run_dir=$1
    if [[ ! -d ${run_dir} ]]; then
        error "Run dir is not a directory: ${run_dir}"
    fi
    echo "${run_dir}/sigs_pilot"
}

##################################### GATK #####################################

locate_gatk_germline_variants() {
    local run_dir=$1 && shift

    local germline_vcf=""
    local gatk_dir="${run_dir}/gatk_germline"

    if [[ -d "${gatk_dir}" ]]; then
        germline_vcf=$(find -L ${gatk_dir}/ -type f -name "*.germline.vcf.gz")
        # Some runs have GATK calls in a new place but with old file name.
        if [[ -z "${germline_vcf}" ]]; then
            germline_vcf=$(find -L ${gatk_dir}/ -type f -name "*.annotated.vcf.gz")
        fi
    fi

    if [[ -z "${germline_vcf}" ]]; then
        error "Unable to locate GATK germline VCF in ${run_dir}."
    fi

    echo ${germline_vcf}
}

#################################### PEACH #####################################

locate_peach_venv_dir() {
    echo "$(locate_peach_resource_dir)/venv/peach"
}

locate_peach_requirements() {
    echo "$(locate_repo_dir "peach")/requirements.txt"
}

locate_peach_pilot_output_dir() {
    local run_dir=$1

    echo "${run_dir}/peach_pilot"
}

locate_peach_pilot_calls() {
    local run_dir=$1
    local peach_pilot_output_dir=$(locate_peach_pilot_output_dir "${run_dir}")

    local peach_pilot_calls_tsv=""

    if [[ -d "${peach_pilot_output_dir}" ]]; then
        peach_pilot_calls_tsv=$(find -L "${peach_pilot_output_dir}" -type f -name "*.peach.calls.tsv")
    fi

    if [[ -z "${peach_pilot_calls_tsv}" ]]; then
        error "Unable to locate pilot PEACH calls tsv in ${run_dir}."
    fi

    echo "${peach_pilot_calls_tsv}"
}

locate_peach_pilot_genotype() {
    local run_dir=$1
    local peach_pilot_output_dir=$(locate_peach_pilot_output_dir "${run_dir}")

    local peach_pilot_genotype_tsv=""

    if [[ -d "${peach_pilot_output_dir}" ]]; then
        peach_pilot_genotype_tsv=$(find -L "${peach_pilot_output_dir}" -type f -name "*.peach.genotype.tsv")
    fi

    if [[ -z "${peach_pilot_genotype_tsv}" ]]; then
        error "Unable to locate pilot PEACH genotype tsv in ${run_dir}."
    fi

    echo "${peach_pilot_genotype_tsv}"
}

locate_peach_prod_output_dir() {
    local run_dir=$1

    echo "${run_dir}/peach"
}

locate_peach_prod_calls() {
    local run_dir=$1
    local peach_prod_output_dir=$(locate_peach_prod_output_dir "${run_dir}")

    local peach_prod_calls_tsv=""

    if [[ -d "${peach_prod_output_dir}" ]]; then
        peach_prod_calls_tsv=$(find -L "${peach_prod_output_dir}" -type f -name "*.peach.calls.tsv")
    fi

    if [[ -z "${peach_prod_calls_tsv}" ]]; then
        error "Unable to locate prod PEACH calls tsv in ${run_dir}."
    fi

    echo "${peach_prod_calls_tsv}"
}

locate_peach_prod_genotype() {
    local run_dir=$1
    local peach_prod_output_dir=$(locate_peach_prod_output_dir "${run_dir}")

    local peach_prod_genotype_tsv=""

    if [[ -d "${peach_prod_output_dir}" ]]; then
        peach_prod_genotype_tsv=$(find -L "${peach_prod_output_dir}" -type f -name "*.peach.genotype.tsv")
    fi

    if [[ -z "${peach_prod_genotype_tsv}" ]]; then
        error "Unable to locate prod PEACH genotype tsv in ${run_dir}."
    fi

    echo "${peach_prod_genotype_tsv}"
}

#################################### CHORD #####################################

locate_chord_data_directory() {
    local run_dir=$1

    echo "${run_dir}/chord"
}

locate_chord_prediction() {
    local run_dir=$1
    local chord_prediction_file=$(find -L ${run_dir}/chord/ -type f -name "*_chord_prediction.txt")
    if [[ -z "${chord_prediction_file}" ]]; then
        error "Unable to locate CHORD prediction file in ${run_dir}."
    fi
    echo ${chord_prediction_file}
}

locate_chord_pilot_prediction() {
    local run_dir=$1
    local chord_prediction_file=$(find -L ${run_dir}/chord_pilot/ -type f -name "*_chord_prediction.txt")
    if [[ -z "${chord_prediction_file}" ]]; then
        error "Unable to locate pilot CHORD prediction file in ${run_dir}."
    fi
    echo ${chord_prediction_file}
}

################################ VIRUSBreakend #################################

locate_virus_breakend_tsv() {
    local run_dir=$1
    local virus_breakend_tsv=$(find -L ${run_dir}/virusbreakend/ -type f -name "*.virusbreakend.vcf.summary.tsv")
    if [[ -z "${virus_breakend_tsv}" ]]; then
        error "Unable to locate virus breakend conclusion tsv in ${run_dir}."
    fi
    echo ${virus_breakend_tsv}
}

################################ VIRUS Interpreter #################################

locate_virus_interpreter_data_directory() {
    local run_dir=$1

    virus_dir="${run_dir}/virus_interpreter"
    if [[ ! -d ${virus_dir} ]]; then
        virus_dir="${run_dir}/virusintrprtr"
    fi

    echo ${virus_dir}
}

locate_virus_annotation_tsv_pilot() {
    local run_dir=$1

    if [[ -d ${run_dir}/virusintrprtr_pilot/ ]]; then
        local virus_annotation_tsv=$(find -L ${run_dir}/virusintrprtr_pilot/ -type f -name "*.virus.annotated.tsv")
    fi

    if [[ -z "${virus_annotation_tsv}" ]]; then
        error "Unable to locate pilot virus annotation TSV in ${run_dir}."
    fi

    echo ${virus_annotation_tsv}
}

locate_virus_annotation_tsv() {
    local run_dir=$1

    if [[ -d "${run_dir}/virus_interpreter/" ]]; then
        local virus_annotation_tsv=$(find -L ${run_dir}/virus_interpreter/ -type f -name "*.virus.annotated.tsv")
    elif [[ -d "${run_dir}/virusintrprtr/" ]]; then
        local virus_annotation_tsv=$(find -L ${run_dir}/virusintrprtr/ -type f -name "*.virus.annotated.tsv")
    fi

    if [[ -z "${virus_annotation_tsv}" ]]; then
        error "Unable to locate virus annotation TSV in ${run_dir}."
    fi
    echo ${virus_annotation_tsv}
}

################################ iClusion importer #################################

locate_pilot_iclusion_importer_trial_tsv() {
    echo "/data/resources/custom/iclusion/iclusion_trials_pilot.tsv"
}

locate_prod_iclusion_importer_trial_tsv() {
    echo "/data/resources/custom/iclusion/iclusion_trials_prod.tsv"
}

locate_latest_iclusion_importer_trial_tsv() {
    echo "/data/resources/custom/iclusion/iclusion_trials_latest.tsv"
}
################################## CUPPA #######################################

locate_cuppa_data_directory() {
    local run_dir=$1

    echo "${run_dir}/cuppa"
}

locate_cuppa_dna_rna_data_directory() {
    local run_dir=$1

    echo "${run_dir}/cuppa_dna_rna"
}

locate_cuppa_result_csv() {
    local run_dir=$1
    local result_csv=$(find -L ${run_dir}/cuppa/ -type f -name "*.cup.data.csv")
    if [[ -z "${result_csv}" ]]; then
        error "Unable to locate cuppa result csv in ${run_dir}."
    fi
    echo ${result_csv}
}

locate_cuppa_dna_rna_result_csv() {
    local run_dir=$1
    local result_csv=$(find -L ${run_dir}/cuppa_dna_rna/ -type f -name "*.cup.data.csv")
    if [[ -z "${result_csv}" ]]; then
        error "Unable to locate cuppa dna-rna result csv in ${run_dir}."
    fi
    echo ${result_csv}
}

locate_cuppa_summary_plot() {
    local run_dir=$1
    local plot=$(find -L ${run_dir}/cuppa/ -type f -name "*.cup.report.summary.png")
    if [[ -z "${plot}" ]]; then
        error "Unable to locate cuppa summary plot in ${run_dir}."
    fi
    echo ${plot}
}

locate_cuppa_dna_rna_summary_plot() {
    local run_dir=$1
    local plot=$(find -L ${run_dir}/cuppa_dna_rna/ -type f -name "*.cup.report.summary.png")
    if [[ -z "${plot}" ]]; then
        error "Unable to locate cuppa dna-rna summary plot in ${run_dir}."
    fi
    echo ${plot}
}

locate_cuppa_feature_plot() {
    # Feature plot is optional so no warn if it cannot be found.
    local run_dir=$1
    local plot=$(find -L ${run_dir}/cuppa/ -type f -name "*.cup.report.features.png")
    echo ${plot}
}

locate_cuppa_dna_rna_feature_plot() {
    # Feature plot is optional so no warn if it cannot be found.
    local run_dir=$1
    local plot=$(find -L ${run_dir}/cuppa_dna_rna/ -type f -name "*.cup.report.features.png")
    echo ${plot}
}

locate_cuppa_chart_plot() {
    local run_dir=$1
    local plot=$(find -L ${run_dir}/cuppa/ -type f -name "*.cuppa.chart.png")
    if [[ -z "${plot}" ]]; then
        error "Unable to locate cuppa chart in ${run_dir}."
    fi
    echo ${plot}
}

locate_cuppa_dna_rna_chart_plot() {
    local run_dir=$1
    local plot=$(find -L ${run_dir}/cuppa_dna_rna/ -type f -name "*.cuppa.chart.png")
    if [[ -z "${plot}" ]]; then
        error "Unable to locate cuppa dna-rna chart in ${run_dir}."
    fi
    echo ${plot}
}

locate_cuppa_conclusion_txt() {
    local run_dir=$1
    local conclusion_txt=$(find -L ${run_dir}/cuppa/ -type f -name "*.cuppa.conclusion.txt")
    if [[ -z "${conclusion_txt}" ]]; then
        error "Unable to locate cuppa conclusion in ${run_dir}."
    fi
    echo ${conclusion_txt}
}

################################### PROTECT ####################################

locate_protect_evidence() {
    local run_dir=$1
    local protect_evidence_tsv=$(find -L ${run_dir}/protect/ -type f -name "*.protect.tsv")
    if [[ -z "${protect_evidence_tsv}" ]]; then
        error "Unable to locate PROTECT evidence tsv in ${run_dir}."
    fi
    echo ${protect_evidence_tsv}
}

locate_protect_evidence_old() {
    local run_dir=$1
    local protect_evidence_tsv=$(find -L ${run_dir}/protect_old/ -type f -name "*.protect.tsv")
    if [[ -z "${protect_evidence_tsv}" ]]; then
        error "Unable to locate PROTECT evidence tsv in ${run_dir}."
    fi
    echo ${protect_evidence_tsv}
}

locate_protect_evidence_pilot() {
    local run_dir=$1
    local protect_evidence_tsv=$(find -L ${run_dir}/protect_pilot_ckb/ -type f -name "protect.tsv")
    if [[ -z "${protect_evidence_tsv}" ]]; then
        error "Unable to locate PROTECT pilot evidence tsv in ${run_dir}."
    fi
    echo ${protect_evidence_tsv}
}

#################################### ORANGE ####################################

locate_orange_json() {
    local run_dir=$1
    local orange_json=""

    local orange_dir="${run_dir}/orange"
    if [[ -d "${orange_dir}" ]]; then
        orange_json=$(find -L ${orange_dir}/ -type f -name "*.orange.json")
    fi

    if [[ -z "${orange_json}" ]]; then
        error "Unable to locate ORANGE json in ${run_dir}."
    fi

    echo ${orange_json}
}

locate_orange_no_germline_json() {
    local run_dir=$1
    local orange_no_germline_json=""

    local orange_dir="${run_dir}/orange_no_germline"
    if [[ -d "${orange_dir}" ]]; then
        orange_no_germline_json=$(find -L ${orange_dir}/ -type f -name "*.orange.json")
    fi

    if [[ -z "${orange_no_germline_json}" ]]; then
        error "Unable to locate ORANGE no-germline json in ${run_dir}."
    fi

    echo ${orange_no_germline_json}
}

locate_orange_json_pilot() {
    local run_dir=$1
    local orange_json=""

    local orange_dir="${run_dir}/orange_pilot"
    if [[ -d "${orange_dir}" ]]; then
        orange_json=$(find -L ${orange_dir}/ -type f -name "*.orange.json")
    fi

    if [[ -z "${orange_json}" ]]; then
        error "Unable to locate ORANGE pilot json in ${run_dir}."
    fi

    echo ${orange_json}
}

locate_orange_no_germline_json_pilot() {
    local run_dir=$1
    local orange_no_germline_json=""

    local orange_dir="${run_dir}/orange_pilot_no_germline"
    if [[ -d "${orange_dir}" ]]; then
        orange_no_germline_json=$(find -L ${orange_dir}/ -type f -name "*.orange.json")
    fi

    if [[ -z "${orange_no_germline_json}" ]]; then
        error "Unable to locate ORANGE no-germline pilot json in ${run_dir}."
    fi

    echo ${orange_no_germline_json}
}

locate_orange_pdf() {
    local run_dir=$1
    local orange_pdf=""

    local orange_dir="${run_dir}/orange"
    if [[ -d "${orange_dir}" ]]; then
        orange_pdf=$(find -L ${orange_dir}/ -type f -name "*.orange.pdf")
    fi

    if [[ -z "${orange_pdf}" ]]; then
        error "Unable to locate ORANGE pdf in ${run_dir}."
    fi

    echo ${orange_pdf}
}

locate_orange_no_germline_pdf() {
    local run_dir=$1
    local orange_no_germline_pdf=""

    local orange_dir="${run_dir}/orange_no_germline"
    if [[ -d "${orange_dir}" ]]; then
        orange_no_germline_pdf=$(find -L ${orange_dir}/ -type f -name "*.orange.pdf")
    fi

    if [[ -z "${orange_no_germline_pdf}" ]]; then
        error "Unable to locate ORANGE no-germline pdf in ${run_dir}."
    fi

    echo ${orange_no_germline_pdf}
}

##################################### LIMS #####################################

locate_reporting_db_generate_tsv() {
    local reporting_db_tsv=/data/ops/lims/prod/reporting_db.tsv
    if [[ ! -f "${reporting_db_tsv}" ]]; then
        error "Unable to locate reporting db TSV."
    fi
    echo ${reporting_db_tsv}
}

locate_reporting_db_sharing_tsv() {
    local reporting_db_tsv=/data/ops/lims/prod/final_sharing_db.tsv
    if [[ ! -f "${reporting_db_tsv}" ]]; then
        error "Unable to locate reporting db TSV."
    fi
    echo ${reporting_db_tsv}
}

locate_reporting_db_tsv_pilot() {
    local reporting_db_tsv=/data/ops/lims/pilot/reporting_db.tsv
    if [[ ! -f "${reporting_db_tsv}" ]]; then
        error "Unable to locate pilot reporting db TSV."
    fi
    echo ${reporting_db_tsv}
}

locate_reporting_db_tsv() {
    local reporting_db_tsv=/data/ops/lims/prod/reporting_db.tsv
    if [[ ! -f "${reporting_db_tsv}" ]]; then
        error "Unable to locate reporting db TSV."
    fi
    echo ${reporting_db_tsv}
}

locate_shallow_tsv() {
    local shallow_seq_tsv=/data/ops/lims/prod/shallow_seq_purity.tsv
    if [[ ! -f "${shallow_seq_tsv}" ]]; then
        error "Unable to locate shallow seq TSV."
    fi
    echo ${shallow_seq_tsv}
}
