#!/usr/bin/env bash

# bash caller builtin returns '$line $filename'
caller=$(basename "$(caller | cut -d" " -f2)")

msg() {
    local msg_type=$1 && shift
    local msg_content=$* && shift
    echo "[${msg_type}] $(date +'%y%m%d %T') - ${msg_content}"
}

msg_with_caller() {
    local msg_type=$1 && shift
    local msg_content=$* && shift
    echo "[${msg_type}] $(date +'%y%m%d %T') (${caller}) - ${msg_content}"
}

error() {
    msg_with_caller "ERROR" "$@" >&2
    exit 1
}

die() {
    msg_with_caller "ERROR" "$@" >&2
    exit 1
}

warn() { 
    msg "WARN" "$@" >&2
}

info() {
    msg "INFO" "$@"
}

