#!/usr/bin/env bash

source message_functions || exit 1

host=$(hostname)

get_nas_rsyncuser_credentials () {
    # TODO: once datastore-out is done remove the option to get password from file
    if [[ "$host" == "datastore" ]]; then
        password=$(get_secret_from_file "/data/common/dbs/nas_credentials/rsyncuser")
    else
        password=$(get_secret_from_secret_manager "nas-credentials-rsyncuser")
    fi
    echo "${password}"
}

get_secret_from_secret_manager () {
    local secret_name=$1 && shift
    secret_contents=$(gcloud secrets versions access "latest" --secret="${secret_name}" --project=hmf-secrets)
    echo "${secret_contents}"
}

get_secret_from_file () {
    local file_path=$1 && shift
    secret_contents=$(cat "${file_path}")
    echo "${secret_contents}"
}