#!/usr/bin/env bash

source message_functions || exit 1

get_nextcloud_upload_user () {
    credentials=$(get_secret_from_secret_manager "nextcloud-credentials")
    user=$(awk '/^user/ {print $2}' <<< "${credentials}")
    echo "${user}"
}

get_nextcloud_upload_password () {
    credentials=$(get_secret_from_secret_manager "nextcloud-credentials")
    password=$(awk '/^pass/ {print $2}' <<< "${credentials}")
    echo "${password}"
}

get_nas_rsyncuser_credentials () {
    password=$(get_secret_from_secret_manager "nas-credentials-rsyncuser")
    echo "${password}"
}

get_secret_from_secret_manager () {
    local secret_name=$1 && shift
    secret_contents=$(gcloud secrets versions access "latest" --secret="${secret_name}" --project=hmf-secrets)
    echo "${secret_contents}"
}

get_secret_from_file () {
    local file_path=$1 && shift
    secret_contents=$(cat "${file_path}")
    echo "${secret_contents}"
}