#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting."
fi

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

info "Copying isofox to ${run_dir}/isofox"
cp -r "/data/actin/wts_pipeline_output/${tumor_sample}/isofox" "${run_dir}/"
if [[ ! -f "${run_dir}/isofox/${tumor_sample}.isf.pass_fusions.csv" ]]; then
    info "No pass fusions downloaded from rna analysis bucket. Will retrieve from local experiments."
    cp "/data/experiments/rna/samples/ACTN/${tumor_sample}.isf.pass_fusions.csv" "${run_dir}/isofox/"
fi