#!/usr/bin/env bash

source message_functions || exit 1
source api_functions || exit 1

set=$1

if [[ -z "${set}" ]]; then
    error "Provide a set. Exiting"
fi

run_info=$(load_run_info_for_set "${set}")
bucket=$(extract_bucket_from_run_info "${run_info}")
pipeline_version=$(extract_pipeline_version_from_run_info "${run_info}")
status=$(extract_status_from_run_info "${run_info}")
tumor_sample=$(load_tumor_sample_id_for_set "${set}")
ref_sample=$(load_ref_sample_id_for_set "${set}")

info "Testing HMF API functions on set ${set}"
info "Run Info = ${run_info}"
info "Run Bucket = ${bucket}"
info "Run Pipeline Version = ${pipeline_version}"
info "Run Status = ${status}"
info "Rerun V3 Info = <obsolete check>"
info "Rerun V4 Info = <obsolete check>"
info "Ref Name = ${ref_sample}"
info "Tumor Name = ${tumor_sample}"
info "Ref datasets CRAM = $(locate_reference_cram "${tumor_sample}")"
info "Tumor datasets CRAM = $(locate_tumor_cram "${tumor_sample}")"