#!/usr/bin/env bash

echo "count"
prefix=`dirname $(readlink $0 || echo $0)`
setname=$1 && shift
countSet=$1 && shift

echo ${countSet}
purity_pathology=/data/common/tools/purity_pathology_pilot/purity-pathology.jar

${prefix}/purity_pathology_set ${setname} ${countSet} ${purity_pathology}