#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift
genome_version=${1:-HG19}

if [[ ! -d "${run_dir}" ]]; then
    echo "[ERROR] ${run_dir} does not exist!" && exit 1
fi

echo "[INFO] Extracting run metadata information"
tum_sample=$(load_tumor_sample_from_metadata ${run_dir})
ref_sample=$(load_ref_sample_from_metadata ${run_dir})

tool_dir=/data/common/tools/cuplr_pilot
working_dir="${run_dir}/cuplr_pilot"
run_log="${working_dir}/run.log"
mkdir -p ${working_dir}

echo "[INFO] Determining run file locations"
## TODO: make functions in locate_files for all missing
somatic_vcf=$(locate_purple_somatics ${run_dir})
structural_vcf=$(locate_purple_structural_variants ${run_dir})
purple_purity=$(locate_purple_purity ${run_dir})
purple_cnv="${run_dir}/purple/${tum_sample}.purple.cnv.somatic.tsv"
linx_fus="${run_dir}/linx/${tum_sample}.linx.fusion.tsv"
linx_ins="${run_dir}/linx/${tum_sample}.linx.viral_inserts.tsv"
linx_vis="${run_dir}/linx/${tum_sample}.linx.vis_sv_data.tsv"
germline_vcf=$(locate_germline_variants ${run_dir} ${ref_sample})

cuplr_pilot.R \
  "${tool_dir}" \
  "${working_dir}" \
  "${tum_sample}" \
  "${somatic_vcf}" \
  "${structural_vcf}" \
  "${purple_purity}" \
  "${purple_cnv}" \
  "${linx_fus}" \
  "${linx_ins}" \
  "${linx_vis}" \
  "${germline_vcf}" \
  "${genome_version}" 2>&1 | tee "${run_log}"

expected_count=3
observed_count=$(find ${working_dir} -mindepth 1 -maxdepth 1 -type f | wc -l)
if [[ ${observed_count} -lt "${expected_count}" ]]; then
    echo "[ERROR] Expected ${expected_count} files but only $observed_count found!"
fi
