#!/usr/bin/env bash

load_ref_sample_from_metadata() {
    local run_dir=$1
    local ref_sample=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        # V5 format
        metadata=${run_dir}/metadata.json
        ref_sample=$(jq -r '.reference.sampleName' ${metadata})
    else
        # Pre-V5 format
        metadata=${run_dir}/metadata
        ref_sample=$(jq -r '.ref_sample' ${metadata})
    fi
    echo "${ref_sample}"
}

load_ref_sample_barcode_from_metadata() {
    local run_dir=$1
    local ref_sample_barcode=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        # V5 format
        metadata=${run_dir}/metadata.json
        ref_sample_barcode=$(jq -r '.reference.sampleId' ${metadata})
    fi
    echo "${ref_sample_barcode}"
}

imply_ref_sample_from_tumor_sample() {
    local tumor_sample=$1
    echo $(${tumor_sample} | cut -c1-12)R
}

load_tumor_sample_from_metadata() {
    local run_dir=$1
    local tum_sample=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        # V5 format
        metadata=${run_dir}/metadata.json
        tum_sample=$(jq -r '.tumor.sampleName' ${metadata})
    else
        # Pre-V5 format
        metadata=${run_dir}/metadata
        tum_sample=$(jq -r '.tumor_sample' ${metadata})
    fi
    echo "${tum_sample}"
}

load_tumor_sample_barcode_from_metadata() {
    local run_dir=$1
    local tumor_sample_barcode=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        # V5 format
        metadata=${run_dir}/metadata.json
        tumor_sample_barcode=$(jq -r '.tumor.sampleId' ${metadata})
    fi
    echo "${tumor_sample_barcode}"
}

load_joint_name_from_metadata() {
    local run_dir=$1
    local joint_name=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        metadata=${run_dir}/metadata.json
        ref_sample=$(jq -r '.reference.sampleName' ${metadata})
        tum_sample=$(jq -r '.tumor.sampleName' ${metadata})
        joint_name="${ref_sample}_${tum_sample}"
    else
        metadata=${run_dir}/metadata
        ref_sample=$(jq -r '.ref_sample' ${metadata})
        tum_sample=$(jq -r '.tumor_sample' ${metadata})
        joint_name="${ref_sample}_${tum_sample}"
    fi
    echo "${joint_name}"
}

