#!/bin/bash

load_ref_sample_from_metadata() {
    run_dir=$1
    metadata=${run_dir}/metadata
    echo $(jq -r '.ref_sample' ${metadata})
}

load_tumor_sample_from_metadata() {
    local run_dir=$1
    local metadata=${run_dir}/metadata
    echo $(jq -r '.tumor_sample' ${metadata})
}

load_joint_name_from_metadata() {
    local run_dir=$1
    local metadata=${run_dir}/metadata
    tumor=$(jq -r '.tumor_sample' ${metadata})
    reference=$(jq -r '.ref_sample' ${metadata})
    echo ${reference}_${tumor}
}


