#!/bin/bash

load_ref_sample_from_metadata() {
    local run_dir=$1
    local ref_sample=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        metadata=${run_dir}/metadata.json
        ref_sample=$(jq -r '.reference.sampleName' ${metadata})
    else
        metadata=${run_dir}/metadata
        ref_sample=$(jq -r '.ref_sample' ${metadata})
    fi
    echo "${ref_sample}"
}

load_tumor_sample_from_metadata() {
    local run_dir=$1
    local tum_sample=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        metadata=${run_dir}/metadata.json
        tum_sample=$(jq -r '.tumor.sampleName' ${metadata})
    else
        metadata=${run_dir}/metadata
        tum_sample=$(jq -r '.tumor_sample' ${metadata})
    fi
    echo "${tum_sample}"
}

load_joint_name_from_metadata() {
    local run_dir=$1
    local joint_name=""
    if [[ -f ${run_dir}/pipeline.version ]]; then
        metadata=${run_dir}/metadata.json
        ref_sample=$(jq -r '.reference.sampleName' ${metadata})
        tum_sample=$(jq -r '.tumor.sampleName' ${metadata})
        joint_name="${ref_sample}_${tum_sample}"
    else
        metadata=${run_dir}/metadata
        ref_sample=$(jq -r '.ref_sample' ${metadata})
        tum_sample=$(jq -r '.tumor_sample' ${metadata})
        joint_name="${ref_sample}_${tum_sample}"
    fi
    echo "${joint_name}"
}

