#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

if [ -z "${run_dir}" ]; then
    echo "[ERROR] No run dir configured. Exiting"
    exit 1
fi

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

echo "[INFO] Files that must exist in every circumstance"
echo "[INFO]  WGSMetrics Ref Sample: $(locate_wgs_metrics ${run_dir} ${ref_sample})"
echo "[INFO]  WGSMetrics Tumor Sample: $(locate_wgs_metrics ${run_dir} ${tumor_sample})"
echo "[INFO]  SAGE Somatic VCF: $(locate_sage_somatics ${run_dir})"
echo "[INFO]  Purple Somatic VCF: $(locate_purple_somatics ${run_dir})"
echo "[INFO]  Purple Purity: $(locate_purple_purity ${run_dir})"
echo "[INFO]  Purple Gene Copy Numbers: $(locate_purple_gene_copynumbers ${run_dir})"
echo "[INFO]  Purple Circos Plot: $(locate_purple_circos_plot ${run_dir})"
echo "[INFO]  Purple Structural VCF: $(locate_purple_structural_variants ${run_dir})"
echo "[INFO]  GRIDSS Filtered Structural VCF: $(locate_gridss_structural_variants ${run_dir})"
echo "[INFO]  GRIDSS Recovery Candidates VCF: $(locate_gridss_recovery_candidates ${run_dir})"
echo "[INFO]  LINX Fusions: $(locate_linx_reported_fusions ${run_dir})"
echo "[INFO]  LINX Disruptions: $(locate_linx_disruptions ${run_dir})"
echo "[INFO]  LINX Viral Integrations: $(locate_linx_viral_integrations ${run_dir})"
echo "[INFO]  LINX Drivers: $(locate_linx_drivers ${run_dir})"
echo "[INFO]  Bachelor Germline Variants: $(locate_bachelor_germline_variants ${run_dir})"
echo "[INFO]  CHORD Prediction File: $(locate_chord_prediction ${run_dir})"

echo ""
echo "[INFO] Files that are generated in pilot setting"
echo "[INFO]  Purple Pilot Somatic VCF: $(locate_purple_pilot_somatics ${run_dir})"
echo "[INFO]  Purple Pilot Purity: $(locate_purple_pilot_purity ${run_dir})"
echo "[INFO]  Purple Pilot Gene Copy Numbers: $(locate_purple_pilot_gene_copynumbers ${run_dir})"
echo "[INFO]  Purple Pilot Circos Plot: $(locate_purple_pilot_circos_plot ${run_dir})"
echo "[INFO]  Purple Pilot Structural VCF: $(locate_purple_pilot_structural_variants ${run_dir})"