#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source database_functions || exit 1

serve_db=$1 && shift

# Resources
serve_database_sql="/data/resources/crunch/serve/database/generate_serve_db.sql"

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_host=$(extract_database_host "${credentials}")

info "Rebuilding SERVE db '${serve_db}' on '${db_host} using ${serve_database_sql}"

mysql ${serve_db} --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${serve_database_sql}
