#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

serve_actionability_dir="/data/output/research_output_public_only"
serve_jar=$(locate_research_serve)

credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" "serve_public")

java -cp ${serve_jar} com.hartwig.hmftools.serve.dao.LoadServeDatabase \
    -serve_actionability_dir ${serve_actionability_dir} \
    -ref_genome_version 37 \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"