#!/usr/bin/env bash

GATK_JAR='/data/common/tools/gatk_v3.8.0/GenomeAnalysisTK.jar'
REF_FASTA='/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta'
DESIGN_DIR=$( dirname $0 )

designs=( 
    '32SNPtaq_design.vcf'
    '59SNPtaq_design.vcf'
    '81SNPmip_design.vcf'
)

bam_path=$1

if [[ ! -f "${bam_path}" ]]; then echo "[ERROR] Provide path to bam"; exit 1; fi
if [[ ! "${bam_path}" =~ \.bam$ ]]; then echo "[ERROR] Only BAM files as input"; exit 1; fi

echo "[INFO] SNPcheck Genotying Starting"

file_name=$(basename ${bam_path})
sample_name=$(echo ${file_name} | sed 's/\.bam//')

for design_file in "${designs[@]}"; do
    design_name=$( echo ${design_file} | sed 's/_design\.vcf//' )
    design_path=${DESIGN_DIR}'/'${design_file}
    out_file="${sample_name}_${design_name}_snpcheck.vcf"
    echo "[INFO] Genotying by ${design_name} for ${sample_name} to ${out_file}"
    java -Xms2g -Xmx9g -jar ${GATK_JAR} \
        -T UnifiedGenotyper \
        -R ${REF_FASTA} \
        -L ${design_path} \
        --output_mode EMIT_ALL_SITES \
        -I ${bam_path} \
        -o ${out_file}
done

echo "[INFO] SNPcheck Genotying Done"
