#!/usr/bin/env bash

vcfDirPath=$1

echo "[INFO] START with $(basename $0)"

if [[ -z ${vcfDirPath} || $1 == "-h" || $1 == "--help" ]]; then
  echo "---"
  echo " Usage: $(basename $0) \${pathToDirWithVCFs}"
  echo "    Eg: $(basename $0) /data/common/snpcheck/output/26SNPtaq/S19-0001_20190103_092420_BDF33/"
  echo "---"
  exit 1
fi

if [[ ! -d ${vcfDirPath} ]]; then echo "[ERROR] Dir does not exist (${vcfDirPath})" && exit 1; fi

qcLogsPath="/data/common/snpcheck/qc"
nasPath="/volume1/web/qc/snpcheck"

vcfDirName=$(basename ${vcfDirPath})
qcLogName="${vcfDirName}.qc"
qcLogPath="${qcLogsPath}/${qcLogName}"

echo "[INFO]  Performing QC (${qcLogName})"
perform_snpcheck.pl -qc -vcfDir "${vcfDirPath}" > "${qcLogPath}"
if [[ $? != 0 ]]; then echo "[ERROR] perform_snpcheck finished with non-zero exit code ($?)" && exit 1; fi

echo "[INFO]  Syncing log to NAS (${qcLogPath})"
rsync -ah "${qcLogPath}" "nas:${nasPath}/${qcLogName}"

echo "[INFO] DONE with $(basename $0)"

