#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

vcf_dir_path=$1

info "START with $(basename "$0")"

snpcheck_dir=$(locate_snpcheck_dir) || die "Could not find local snpcheck dir"

if [[ -z "${vcf_dir_path}" || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") \${pathToDirWithVCFs}"
    echo "    Eg: $(basename "$0") ${snpcheck_dir}output/26SNPtaq/S19-0001_20190103_092420_BDF33/"
    echo "---"
    exit 1
fi

if [[ ! -d "${vcf_dir_path}" ]]; then error "Dir does not exist (${vcf_dir_path})"; fi

qc_logs_path="${snpcheck_dir}qc"
nas_path="/volume1/web/qc/snpcheck"

vcf_dir_name=$(basename "${vcf_dir_path}")
qc_log_name="${vcf_dir_name}.qc"
qc_log_path="${qc_logs_path}/${qc_log_name}"

info " Performing QC (${qc_log_name})"
perform_snpcheck.pl -qc -vcfDir "${vcf_dir_path}" > "${qc_log_path}" || die "Processing of snp plate results failed ($?)"

info " Syncing log to NAS (${qc_log_path})"
copy_file_to_nas "${qc_log_path}" "${nas_path}" || die "Copying of qc to NAS failed ($?)"

info "DONE with $(basename "$0")"

