#!/usr/bin/env bash

source message_functions || exit 1

SOURCE='/volume1/machines/Experimenten/SNP\ check'
TARGET='/data/common/snpcheck/input'
SUFFIX='Results.csv'

plate_id=$1

if [[ -z "${plate_id}" || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename $0) \${plate_id}"
    echo "    Eg: $(basename $0) S19-0001"
    echo "---"
    exit 1
fi

## find at NAS
info "Searching for \"${plate_id}*${SUFFIX}\" results file in \"nas:${SOURCE}\""
result_files=()
while IFS=  read -r -d $'\0'; do
    result_files+=("$REPLY")
done < <(ssh nas find "${SOURCE}" -name "${plate_id}*${SUFFIX}" -print0)
if [[ ${#result_files[@]} -eq 0 ]]; then 
    error "No file found for '${plate_id}'!"
elif [[ ${#result_files[@]} -gt 1 ]]; then
    error "More than 1 file found for '${plate_id}'!"
fi

## sync and process
result_file_path="${result_files[0]}"
result_file_name=$(basename "${result_file_path}")
target_file_path="${TARGET}/${result_file_name}"

info "Found SNPcheck file at NAS ($result_file_name)"
info " syncing to datastore"
rsync --protect-args -ah "nas:${result_file_path}" "${target_file_path}"
if [[ $? != 0 ]]; then error "Rsync finished with non-zero exit code ($?)"; fi

info "  converting file VCFs"
create_sample_vcfs_from_csv "${target_file_path}"
if [[ $? != 0 ]]; then error "Conversion to VCF finished with non-zero exit code ($?)"; fi

