#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

plate=$1

if [[ -z "${plate}" || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") snpcheck_plate"
    echo "    Eg: $(basename "$0") S23-0012_20230324_084951_REJ07"
    echo "---"
    exit 1
fi

snpcheck_dir=$(locate_snpcheck_dir) || die "Could not find local snpcheck dir"

# log: /data/snpcheck/qc/S23-0012_20230324_084951_REJ07.qc
# plate: S23-0012_20230324_084951_REJ07
# id: REJ07
qc_log="${snpcheck_dir}/qc/${plate}.qc"
id=$(echo "${plate}" | rev | cut -d"_" -f1 | rev)
#passed_barcodes=$(grep '\[PASS\]' "${qc_log}" | rev | cut -d":" -f1 | rev | cut -d")" -f1)

failed_samples=$(grep '\[FAIL\]' "${qc_log}")

if [[ -z "${failed_samples}" ]]; then
  info "All SNPcheck PASS qc"
else
  info "SNPcheck failures found"
  echo "${failed_samples}"
  failed_barcodes=$(echo "${failed_samples}" | rev | cut -d":" -f1 | rev | cut -d")" -f1)
  for failed_barcode in ${failed_barcodes}; do
    info "Removing failed sample ${failed_barcode}"
    file_path="${snpcheck_dir}/gcp-sync/${plate}/${failed_barcode}_${id}_OpenArrayCalls.vcf"
    rm "${file_path}"
  done
fi

info "Finished $(basename "$0")"