#!/usr/bin/env bash

source message_functions || exit 1

if [[ $# -ne 3 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "-----"
    echo " Descr: Locates VCFs and prints the mv commands to perform"
    echo " Usage: $(basename $0) <barcode> <old_name> <new_name>"
    echo " Exmpl: $(basename $0) FR123 CPCT02old CPCT02new"
    echo "-----"
    exit 1
fi

barcode=$1 && shift
old_sample=$1 && shift
new_sample=$1 && shift

old_tag="${barcode}-${old_sample}"
new_tag="${barcode}-${new_sample}"

info "OLD tag: $old_tag"
info "NEW tag: $new_tag"
mapfile -t vcfs < <(find /data/common/snpcheck/ /data/gcp/snpcheckvcfupload/ -name "${old_tag}_*.vcf" -or -name "${old_tag}-Duplo_*.vcf")
vcf_count=${#vcfs[@]}

info "Printing rename code for ${vcf_count} VCFs (remember to sync to GCP afterwards!)"
for old_vcf_path in "${vcfs[@]}"; do
    new_vcf_path=${old_vcf_path/${old_tag}/${new_tag}}
    echo "mv $old_vcf_path $new_vcf_path"
done
