#!/bin/bash

NAS_DIR='/volume1/machines/Experimenten/SNP\ check'
DS_DIR='/data/common/snpcheck/input'

resultsFilePath=$( ssh nas ls "$NAS_DIR/*/*Results.csv" | head -1 )
resultsFileName=$( basename "${resultsFilePath}" )
resultsDirPath=$( dirname "${resultsFilePath}" )
resultsDirName=$( basename "${resultsDirPath}" )

echo "[INFO] Found following file on nas: ${resultsFilePath}"
echo "[INFO] Copying file from nas to datastore"

scp "nas:${NAS_DIR}/${resultsDirName}/${resultsFileName}" "${DS_DIR}"

echo "[INFO] Probable next action:"
echo " create_sample_vcfs_from_csv ${DS_DIR}/${resultsFileName}"

