#!/bin/bash

FROM_DIR="/volume1/machines/Experimenten/SNP\ check/"
TO_DIR="/data/common/snpcheck/input/32SNPtaq/"

## retrieve file
echo "[INFO] Running scp from nas to datastore"
scp "nas:${FROM_DIR}/*/*Results.csv" "${TO_DIR}"
echo "[INFO] Any copied files will be in: ${TO_DIR}"
echo "[INFO] Next step you might want is \"create_sample_vcfs_from_csv\""

