#!/usr/bin/env bash

source message_functions || exit 1

runs_directory=$1

if [[ -z "${runs_directory}" ]]; then
    error "No runs directory provided. Exiting"
fi

prefix=$(dirname $(readlink $0 || echo $0))

for run in ${runs_directory}/*; do
    info "Loading ${run} into testdb"
    ${prefix}/load_run_into_test_db ${run}
done