#!/usr/bin/env bash

source locate_files

serve_jar=$(locate_pilot_serve)

missing_doids_mapping_tsv=/data/common/dbs/serve/curation/missing_doids_mapping_pilot.tsv

ref_genome_37_fasta_file=$(locate_ref_genome_37_fasta_file)
ref_genome_38_fasta_file=$(locate_ref_genome_38_fasta_file)
ref_genome_37_to_38_chain=$(locate_ref_genome_37_to_38_chain)
ref_genome_38_to_37_chain=$(locate_ref_genome_38_to_37_chain)

driver_gene_37_tsv=$(locate_driver_gene_panel_37_tsv)
driver_gene_38_tsv=$(locate_driver_gene_panel_38_tsv)
known_fusion_37_file=$(locate_known_fusion_data_37_csv)
known_fusion_38_file=$(locate_known_fusion_data_38_csv)

java -Xms2G -Xmx16G -jar ${serve_jar} \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -ref_genome_37_fasta_file ${ref_genome_37_fasta_file} \
    -ref_genome_38_fasta_file ${ref_genome_38_fasta_file} \
    -ref_genome_37_to_38_chain ${ref_genome_37_to_38_chain} \
    -ref_genome_38_to_37_chain ${ref_genome_38_to_37_chain} \
    -driver_gene_37_tsv ${driver_gene_37_tsv} \
    -driver_gene_38_tsv ${driver_gene_38_tsv} \
    -known_fusion_37_file ${known_fusion_37_file} \
    -known_fusion_38_file ${known_fusion_38_file} \
    "$@"