#!/usr/bin/env bash

source locate_files

serve_jar=$(locate_pilot_serve)

missing_doids_mapping_tsv=/data/common/dbs/serve/curation/missing_doids_mapping.tsv

ref_genome_37_fasta_file=$(locate_ref_genome_37_fasta_file)
ref_genome_38_fasta_file=$(locate_ref_genome_38_fasta_file)
ref_genome_37_to_38_chain=$(locate_ref_genome_37_to_38_chain)
ref_genome_38_to_37_chain=$(locate_ref_genome_38_to_37_chain)

driver_gene_37_tsv=$(locate_driver_gene_panel_37_tsv)
driver_gene_38_tsv=$(locate_driver_gene_panel_38_tsv)
known_fusion_37_file=$(locate_known_fusion_data_37_csv)
known_fusion_38_file=$(locate_known_fusion_data_38_csv)

output_dir=/data/common/dbs/serve/pilot_output

refSeqMatch=/data/common/dbs/serve/static_sources/refseq/refseq_to_canonicalTranscript.tsv

if [[ -d "${output_dir}" ]]; then
    echo "[INFO] Output dir '${output_dir}' exist and will be cleaned!"
    rm -r ${output_dir}/*
else
    mkdir -p ${output_dir}
    echo "[INFO] Output dir created: ${output_dir}!"
fi

java -Xms2G -Xmx25G -jar ${serve_jar} \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -ref_genome_37_fasta_file ${ref_genome_37_fasta_file} \
    -ref_genome_38_fasta_file ${ref_genome_38_fasta_file} \
    -ref_genome_37_to_38_chain ${ref_genome_37_to_38_chain} \
    -ref_genome_38_to_37_chain ${ref_genome_38_to_37_chain} \
    -driver_gene_37_tsv ${driver_gene_37_tsv} \
    -driver_gene_38_tsv ${driver_gene_38_tsv} \
    -known_fusion_37_file ${known_fusion_37_file} \
    -known_fusion_38_file ${known_fusion_38_file} \
    -output_dir ${output_dir} \
    -refseq_tsv ${refSeqMatch} \
    "$@"