#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

ckb_dir=$(locate_ckb_flex_data_dir)
ckb_filter_tsv=/data/common/dbc/serve/curation/ckb_filters.tsv

output_dir=/data/common/dbs/serve/pilot_output_ckb_only

create_or_cleanup_dir ${output_dir}

do_run_serve_pilot -use_ckb -ckb_dir ${ckb_dir} -ckb_filter_tsv ${ckb_filter_tsv} -output_dir ${output_dir} "$@"