#!/usr/bin/env bash

source locate_files
source io_functions

ckb_dir=$(locate_ckb_flex_data_dir)

output_dir=/data/common/dbs/serve/pilot_output_ckb_only

create_or_cleanup_dir ${output_dir}

do_run_serve_pilot -use_ckb -ckb_dir ${ckb_dir} -output_dir ${output_dir} "$@"