#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_public_only_last"
create_or_cleanup_dir ${output_dir}

vicc_json=$(locate_vicc_json)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_tsv=$(locate_hartwig_cohort_tsv)
hartwig_curated_tsv=$(locate_hartwig_curated_tsv)
missing_doids_mapping_tsv=$(locate_public_missing_doids_mapping_tsv)

serve_jar="/data/kodu_serve_jar/serve.jar"

do_run_serve ${serve_jar} \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -output_dir ${output_dir} \
    "$@"