#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_kodu_public_sources"
create_or_cleanup_dir ${output_dir}

vicc_json=$(locate_vicc_json)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_tsv=$(locate_hartwig_cohort_tsv)
hartwig_curated_tsv=$(locate_hartwig_curated_tsv)
missing_doids_mapping_tsv=$(locate_public_missing_doids_mapping_tsv)

serve_jar="${HOME}/serve_jar/serve.jar"

ensembl_data_dir_37=$(locate_ensembl_data_dir_37)
ensembl_data_dir_38=$(locate_ensembl_data_dir_38)

ref_genome_37_fasta_file=$(locate_ref_genome_37_fasta_file)
ref_genome_38_fasta_file=$(locate_ref_genome_38_fasta_file)
ref_genome_37_to_38_chain=$(locate_ref_genome_37_to_38_chain)
ref_genome_38_to_37_chain=$(locate_ref_genome_38_to_37_chain)

driver_gene_37_tsv=$(locate_driver_gene_panel_37_tsv)
driver_gene_38_tsv=$(locate_driver_gene_panel_38_tsv)
known_fusion_37_file=$(locate_known_fusion_data_37_csv)
known_fusion_38_file=$(locate_known_fusion_data_38_csv)

# -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
java -Xms2G -Xmx16G -jar ${serve_jar} \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -output_dir ${output_dir} \
    -ensembl_data_dir_37 ${ensembl_data_dir_37} \
    -ensembl_data_dir_38 ${ensembl_data_dir_38} \
    -ref_genome_37_fasta_file ${ref_genome_37_fasta_file} \
    -ref_genome_38_fasta_file ${ref_genome_38_fasta_file} \
    -ref_genome_37_to_38_chain ${ref_genome_37_to_38_chain} \
    -ref_genome_38_to_37_chain ${ref_genome_38_to_37_chain} \
    -driver_gene_37_tsv ${driver_gene_37_tsv} \
    -driver_gene_38_tsv ${driver_gene_38_tsv} \
    -known_fusion_37_file ${known_fusion_37_file} \
    -known_fusion_38_file ${known_fusion_38_file} \
    "$@"
