#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir=/data/output/pilot_output_kodu_ckb_based
create_or_cleanup_dir ${output_dir}

ckb_dir=$(locate_ckb_flex_data_latest_dir)
ckb_filter_tsv=$(locate_ckb_filter_tsv)
missing_doids_mapping_tsv=$(locate_private_missing_doids_mapping_tsv)

serve_jar="${HOME}/serve_jar/serve.jar"

ensembl_data_dir=$(locate_ensembl_data_dir)

ref_genome_37_fasta_file=$(locate_ref_genome_37_fasta_file)
ref_genome_38_fasta_file=$(locate_ref_genome_38_fasta_file)
ref_genome_37_to_38_chain=$(locate_ref_genome_37_to_38_chain)
ref_genome_38_to_37_chain=$(locate_ref_genome_38_to_37_chain)

driver_gene_37_tsv=$(locate_driver_gene_panel_37_tsv)
driver_gene_38_tsv=$(locate_driver_gene_panel_38_tsv)
known_fusion_37_file=$(locate_known_fusion_data_37_csv)
known_fusion_38_file=$(locate_known_fusion_data_38_csv)

java -Xms2G -Xmx16G -jar ${serve_jar} \
    -ensembl_data_dir ${ensembl_data_dir} \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_ckb -ckb_dir ${ckb_dir} -ckb_filter_tsv ${ckb_filter_tsv} \
    -output_dir ${output_dir} \
    -ref_genome_37_fasta_file ${ref_genome_37_fasta_file} \
    -ref_genome_38_fasta_file ${ref_genome_38_fasta_file} \
    -ref_genome_37_to_38_chain ${ref_genome_37_to_38_chain} \
    -ref_genome_38_to_37_chain ${ref_genome_38_to_37_chain} \
    -driver_gene_37_tsv ${driver_gene_37_tsv} \
    -driver_gene_38_tsv ${driver_gene_38_tsv} \
    -known_fusion_37_file ${known_fusion_37_file} \
    -known_fusion_38_file ${known_fusion_38_file} \
    "$@"
