#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_ckb_actin_based"
create_or_cleanup_dir ${output_dir}

ckb_dir=$(locate_ckb_flex_data_latest_dir)
ckb_filter_tsv=$(locate_ckb_filter_tsv)
iclusion_trial_tsv=$(locate_prod_iclusion_trial_tsv)
actin_trial_tsv=$(locate_actin_trial_tsv)
actin_filter_tsv=$(locate_actin_filter_tsv)
missing_doids_mapping_tsv=$(locate_private_missing_doids_mapping_tsv)

do_run_serve_pilot \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_ckb -ckb_dir ${ckb_dir} -ckb_filter_tsv ${ckb_filter_tsv} \
    -use_iclusion -iclusion_trial_tsv ${iclusion_trial_tsv} \
    -use_actin -actin_trial_tsv ${actin_trial_tsv} -actin_filter_tsv ${actin_filter_tsv} \
    -output_dir ${output_dir} \
    "$@"