#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_actin_only"
create_or_cleanup_dir ${output_dir}

actin_trial_tsv=$(locate_actin_trial_tsv)
actin_filter_tsv=$(locate_actin_filter_tsv)

serve_jar="${HOME}/serve_jar/seve.jar"

ensembl_data_dir_37=$(locate_ensembl_data_dir_37)
ensembl_data_dir_38=$(locate_ensembl_data_dir_38)

ref_genome_37_fasta_file=$(locate_ref_genome_37_fasta_file)
ref_genome_38_fasta_file=$(locate_ref_genome_38_fasta_file)
ref_genome_37_to_38_chain=$(locate_ref_genome_37_to_38_chain)
ref_genome_38_to_37_chain=$(locate_ref_genome_38_to_37_chain)

driver_gene_37_tsv=$(locate_driver_gene_panel_37_tsv)
driver_gene_38_tsv=$(locate_driver_gene_panel_38_tsv)
known_fusion_37_file=$(locate_known_fusion_data_37_csv)
known_fusion_38_file=$(locate_known_fusion_data_38_csv)

java -Xms2G -Xmx16G -jar ${serve_jar} \
    -ensembl_data_dir_37 ${ensembl_data_dir_37} \
    -ensembl_data_dir_38 ${ensembl_data_dir_38} \
    -ref_genome_37_fasta_file ${ref_genome_37_fasta_file} \
    -ref_genome_38_fasta_file ${ref_genome_38_fasta_file} \
    -ref_genome_37_to_38_chain ${ref_genome_37_to_38_chain} \
    -ref_genome_38_to_37_chain ${ref_genome_38_to_37_chain} \
    -driver_gene_37_tsv ${driver_gene_37_tsv} \
    -driver_gene_38_tsv ${driver_gene_38_tsv} \
    -known_fusion_37_file ${known_fusion_37_file} \
    -known_fusion_38_file ${known_fusion_38_file} \
    -use_actin -actin_trial_tsv ${actin_trial_tsv} -actin_filter_tsv ${actin_filter_tsv} \
    -output_dir ${output_dir} \
    -log_debug \
    "$@"
