#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir=/data/outout/pilot_output_ckb_based
create_or_cleanup_dir ${output_dir}

ckb_dir=$(locate_ckb_flex_data_dir)

iclusion_trial_tsv=$(locate_prod_iclusion_trial_tsv)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_tsv=$(locate_hartwig_cohort_tsv)
hartwig_curated_tsv=$(locate_hartwig_curated_tsv)

do_run_serve_pilot \
    -use_ckb -ckb_dir ${ckb_dir}  \
    -use_iclusion -iclusion_trial_tsv ${iclusion_trial_tsv} \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -output_dir ${output_dir} \
    "$@"
