#!/usr/bin/env bash

source locate_files
source io_functions

output_dir=/data/common/dbs/serve/pilot_output_kodu_test_37_38

create_or_cleanup_dir ${output_dir}

hartwig_cohort_tsv=$HOME/serve/test_cohort.tsv

do_run_serve_pilot \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -output_dir ${output_dir} \
    "$@"