#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/prod_output_vicc_based"
create_or_cleanup_dir ${output_dir}

vicc_json=$(locate_vicc_json)
iclusion_trial_tsv=$(locate_prod_iclusion_trial_tsv)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_tsv=$(locate_hartwig_cohort_tsv)
hartwig_curated_tsv=$(locate_hartwig_curated_tsv)
missing_doids_mapping_tsv=$(locate_public_missing_doids_mapping_tsv)

do_run_serve_prod \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -use_iclusion -iclusion_trial_tsv ${iclusion_trial_tsv} \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -output_dir ${output_dir} \
    "$@"
