#!/usr/bin/env bash

source locate_files

serve_jar=$(locate_prod_serve)

vicc_json=$(locate_vicc_json)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_tsv=$(locate_hartwig_cohort_tsv)
hartwig_curated_tsv=$(locate_hartwig_curated_tsv)

missing_doids_mapping_tsv=/data/common/dbs/serve/curation/missing_doids_mapping.tsv

ref_genome_version=37
ref_genome_fasta_file=$(locate_ref_genome_37_fasta_file)
driver_gene_tsv=$(locate_driver_gene_panel_37_tsv)
known_fusion_file=$(locate_known_fusion_data_37_csv)

output_dir=/data/common/dbs/serve/prod_output_public_only

if [[ -d "${output_dir}" ]]; then
    echo "[INFO] Output dir '${output_dir}' exist and will be cleaned!"
    rm -r ${output_dir}/*
else
    mkdir -p ${output_dir}
    echo "[INFO] Output dir created: ${output_dir}!"
fi

java -Xms2G -Xmx8G -jar ${serve_jar} \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -ref_genome_version ${ref_genome_version} \
    -ref_genome_fasta_file ${ref_genome_fasta_file} \
    -driver_gene_tsv ${driver_gene_tsv} \
    -known_fusion_file ${known_fusion_file} \
    -output_dir ${output_dir} \
    "$@"