#!/usr/bin/env bash

source locate_files

output_dir=/data/common/dbs/serve/pilot_output_public_only

if [[ -d "${output_dir}" ]]; then
    if [[ "$(ls -A ${output_dir})" ]]; then
        echo "[INFO] Output dir '${output_dir}' exists and will be cleaned!"
        rm -r ${output_dir}/*
    fi
else
    mkdir -p ${output_dir}
    echo "[INFO] Output dir created: ${output_dir}!"
fi

vicc_json=$(locate_vicc_json)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_tsv=$(locate_hartwig_cohort_tsv)
hartwig_curated_tsv=$(locate_hartwig_curated_tsv)

do_run_serve_pilot \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -output_dir ${output_dir} \
    "$@"