#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting"
fi

run_protect_research_on_actin_db_for_cohort ${run_dir}

run_orange_research_on_actin_cohort ${run_dir}

actin_orange_interpreter_cohort ${run_dir}

create_actin_cohort_clinical_record_from_doid ${run_dir}
