#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1
source lims_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting."
fi

info "Running ACTIN cohort experiment for ${run_dir}"
tum_sample=$(basename ${run_dir})

run_actin_app_build_clinical_record ${tum_sample}

pipeline_dir=$(locate_rr_actin_pipeline_directory ${tum_sample})
#info "Creating temporary pipeline dir for orange rerun: '${pipeline_dir}'"
#create_or_cleanup_dir ${pipeline_dir}

info "Copying ${run_dir} to ${pipeline_dir} -- ALREADY DONE SKIPPING STEP"
#cp -r "${run_dir}/." "${pipeline_dir}/"

info "Replacing metrics output files with dummy output in correct format"
info "Old metrics files replaced are: *.wgsmetrics & *WGSMetrics.txt"
dummy_metric_dir="/data/experiments/rr_actin/dummy_metrics"
rm "${pipeline_dir}/${tum_sample}/bam_metrics/"*etrics*
cp "${dummy_metric_dir}/dummy.bam_metric.flag_counts.tsv" "${pipeline_dir}/${tum_sample}/bam_metrics/${tum_sample}.bam_metric.flag_counts.tsv"
cp "${dummy_metric_dir}/dummy.bam_metric.summary.tsv" "${pipeline_dir}/${tum_sample}/bam_metrics/${tum_sample}.bam_metric.summary.tsv"

ref_sample=$(imply_ref_sample_from_tumor_sample ${tum_sample})
rm "${pipeline_dir}/${ref_sample}/bam_metrics/"*etrics*
cp "${dummy_metric_dir}/dummy.bam_metric.flag_counts.tsv" "${pipeline_dir}/${ref_sample}/bam_metrics/${ref_sample}.bam_metric.flag_counts.tsv"
cp "${dummy_metric_dir}/dummy.bam_metric.summary.tsv" "${pipeline_dir}/${ref_sample}/bam_metrics/${ref_sample}.bam_metric.summary.tsv"

info "Replacing CHORD output files with expected extension"
mv "${pipeline_dir}/chord/${tum_sample}_chord_prediction.txt" "${pipeline_dir}/chord/${tum_sample}.chord.prediction.tsv"

info "Replacing PEACH output files with expected extension and file structure"
mv "${pipeline_dir}/peach/${tum_sample}.peach.genotype.tsv" "${pipeline_dir}/peach/${ref_sample}.peach.haplotypes.best.tsv"

run_orange_research_no_germline ${pipeline_dir}

info "Creating log files in ${logs_dir} to track samples successfully/unsuccessfully run through ACTIN"
logs_dir=$(locate_rr_actin_logs_directory)
sample_failed_log_file="$logs_dir/samples_failed.log"
sample_passed_log_file="$logs_dir/samples_passed.log"

info "Checking if orange completed successfully and created orange.json"
orange_json="$(locate_orange_no_germline_json ${pipeline_dir})"
if [[ -z "${orange_json}" ]]; then
    echo "${tum_sample}" >> "${sample_failed_log_file}"
    info "Orange failed. No orange.json present in ${pipeline_dir}."
    info "ACTIN run unsuccessful on ${tum_sample}."
    error "Sample name added to ${sample_failed_log_file} Exiting."
fi

run_actin_app_molecular_interpreter ${tum_sample}

info "Cleaning up temporary pipeline dir '${pipeline_dir}'"
rm -rf "${pipeline_dir}"

run_actin_app_molecular_loader ${tum_sample}
echo "${tum_sample}" >> "${sample_passed_log_file}"
info "ACTIN run successfully on ${tum_sample}. Sample name added to ${sample_passed_log_file}"