#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No rundir is provided to $(basename $0). Exiting."
fi

sample=$(basename "${run_dir}" | cut -d"_" -f4)
flagstat=$(locate_flagstats "${run_dir}" "${sample}")
wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${sample}")

java -Xmx4G -jar "/data/tools/health-checker/pilot/health-checker.jar" \
    -reference ${sample} \
    -ref_wgs_metrics_file ${wgs_metrics} \
    -ref_flagstat_file ${flagstat} \
    -do_not_write_evaluation_file
