#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No rundir is provided to $(basename $0). Exiting."
fi

# Load metadata
ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

# Set paths
purple_dir="${run_dir}/purple"
ref_flagstat=$(locate_flagstats "${run_dir}" "${ref_sample}")
tum_flagstat=$(locate_flagstats "${run_dir}" "${tumor_sample}")
ref_wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${ref_sample}")
tum_wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${tumor_sample}")

java -Xmx4G -jar "/data/tools/health-checker/pilot/health-checker.jar" \
    -reference ${ref_sample} \
    -tumor ${tumor_sample} \
    -ref_wgs_metrics_file ${ref_wgs_metrics} \
    -tum_wgs_metrics_file ${tum_wgs_metrics} \
    -ref_flagstat_file ${ref_flagstat} \
    -tum_flagstat_file ${tum_flagstat} \
    -purple_dir ${purple_dir} \
    -do_not_write_evaluation_file