#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source lims_functions || exit 1
source message_functions || exit 1
source api_functions || exit 1

run_dir=$1 && shift
sample=$1 && shift
barcode=$1 && shift
ref_sample=$1 && shift
ref_sample_barcode=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${sample}" || -z "${barcode}" ]]; then
    error "No tumor/reference information provided. Exiting"
fi

if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  ref_sample name: ${ref_sample}"
    warn "  ref sample barcode: ${ref_sample_barcode}"
    warn "  tumor_sample name: ${sample}"
    warn "  tum sample barcode: ${barcode}"
    exit 1;
fi

pipeline_version_file=${run_dir}/pipeline.version
purple_circos_plot=$(locate_purple_circos_plot ${run_dir})
cuppa_plot=$(locate_cuppa_chart_plot ${run_dir})
protect_evidence_tsv=$(locate_protect_evidence ${run_dir})
rose_tsv=$(locate_rose ${run_dir})
orange_json=$(locate_orange_json ${run_dir})

germline_reporting_tsv=$(locate_germline_reporting_prod)
sample_special_remark_tsv=$(locate_special_remark_patient_report_pilot)
known_fusion_file=$(locate_known_fusion_data_37_csv)

pilot_do_run_base_patient_reporter \
    -pipeline_version_file ${pipeline_version_file} \
    -purple_circos_plot ${purple_circos_plot} \
    -cuppa_plot ${cuppa_plot} \
    -protect_evidence_tsv ${protect_evidence_tsv} \
    -orange_json ${orange_json} \
    -add_rose \
    -rose_tsv ${rose_tsv} \
    -germline_reporting_tsv ${germline_reporting_tsv} \
    -sample_special_remark_tsv ${sample_special_remark_tsv} \
    -log_debug \
    "$@"