#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

protect_jar=$(locate_pilot_protect)

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

purple_purity_tsv=$(locate_purple_purity ${run_dir})
linx_fusion_tsv=$(locate_linx_reported_fusions ${run_dir})
purple_gene_cnv_tsv=$(locate_purple_gene_copynumbers ${run_dir})
somatic_variant_vcf=$(locate_purple_somatics ${run_dir})
chord_txt=$(locate_chord_prediction ${run_dir})

pilot_output_dir=${run_dir}/conclusion_pilot
if [ -d ${pilot_output_dir} ]; then
    rm -r ${pilot_output_dir}
    echo "[INFO] conclusion pilot dir exist. protect dir is just removed and will be replaced"
fi

mkdir ${pilot_output_dir}
conclusion_tsv=${pilot_output_dir}/${tumor_sample}_conclusion.tsv

java -jar ${protect_jar} \
    -tumor_sample_id ${tumor_sample} \
    -somatic_variant_vcf ${somatic_variant_vcf} \
    -purple_purity_tsv ${purple_purity_tsv} \
    -purple_gene_cnv_tsv ${purple_gene_cnv_tsv} \
    -linx_fusion_tsv ${linx_fusion_tsv} \
    -chord_txt ${chord_txt} \
    -conclusion_tsv ${conclusion_tsv} \
    "$@"