#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    echo "[ERROR] No run dir provided. Exiting" && exit 1;
fi

output_dir=${run_dir}/protect
protect_jar=$(locate_prod_protect)
credentials=$(locate_prod_database_credentials)

do_run_protect ${run_dir} ${output_dir} ${protect_jar} ${credentials}
