#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

serve_actionability_dir="/data/resources/private/serve/37"

output_dir="${run_dir}/protect_prod"
protect_jar=$(locate_prod_protect)

do_run_protect ${run_dir} ${output_dir} ${serve_actionability_dir} ${protect_jar} "$@"

