#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

# Temp until a better location has been found.
serve_actionability_dir=$HOME/serve_ckb

output_dir=${run_dir}/protect_pilot_ckb
protect_jar=$(locate_pilot_protect)

do_run_protect_pilot ${run_dir} ${output_dir} ${serve_actionability_dir} ${protect_jar} -log_debug
