#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

serve_actionability_dir="/data/resources/crunch/serve/pilot"

output_dir="${run_dir}/protect_2_1"
protect_jar="/data/tools/protect/2.1/protect.jar"

do_run_protect ${run_dir} ${output_dir} ${serve_actionability_dir} ${protect_jar} "$@"
