#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    echo "[ERROR] No run dir provided. Exiting" && exit 1;
fi

output_dir=${run_dir}/protect_pilot
protect_jar=$(locate_pilot_protect)

do_run_protect_pilot ${run_dir} ${output_dir} ${protect_jar}
