#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

# TODO Potentially replace with a non-ACTIN serve db
serve_actionability_dir="$(locate_actin_serve_db)"

output_dir="/home/lschoenmaker/jobs/protect"
protect_jar=$(locate_pilot_protect)

do_run_protect_pilot ${run_dir} ${output_dir} ${serve_actionability_dir} ${protect_jar} "$@"
