#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

clinical_json="$(locate_actin_clinical_json ${patient})"

molecular_json="$(locate_most_recent_actin_molecular_json ${patient})"
if [[ -z "${molecular_json}" ]]; then
    warn "No molecular json found for ${patient}. Falling back on minimal molecular json"
    molecular_json="$(locate_actin_minimal_molecular_json)"
fi

trial_database_directory="$(locate_actin_trial_database_directory)"
treatment_directory="$(locate_actin_treatment_db_directory)"
doid_json="$(locate_doid_json)"
atc_tsv="$(locate_atc_tsv)"
extended_efficacy_json="$(locate_extended_efficacy_json)"

output_directory="$(locate_actin_treatment_match_directory)"

actin_jar="$(locate_actin_jar_on_vm)"

info "Running ACTIN treatment matcher on ${patient}"

java -cp ${actin_jar} com.hartwig.actin.algo.TreatmentMatcherApplicationKt \
    -clinical_json ${clinical_json} \
    -molecular_json ${molecular_json} \
    -trial_database_directory ${trial_database_directory} \
    -treatment_directory ${treatment_directory} \
    -doid_json ${doid_json} \
    -atc_tsv ${atc_tsv} \
    -extended_efficacy_json ${extended_efficacy_json} \
    -output_directory ${output_directory} \
    "$@"
