#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting.";
fi

sample=$(basename ${run_dir})
patient=${sample:0:12}
clinical_json="$(locate_actin_cohort_clinical_directory)/${patient}.clinical.json"
molecular_json="$(locate_actin_cohort_molecular_directory ${run_dir})/actin/${sample}.molecular.json"

treatment_database_directory="$(locate_actin_cohort_treatment_database_directory)"
doid_json="$(locate_doid_json)"

output_directory="$(locate_actin_cohort_treatment_match_directory)"

actin_jar="$(locate_cohort_actin)"

info "Running ACTIN cohort treatment matcher on ${patient} for sample ${sample}"

java -cp ${actin_jar} com.hartwig.actin.algo.TreatmentMatcherApplication \
    -clinical_json ${clinical_json} \
    -molecular_json ${molecular_json} \
    -treatment_database_directory ${treatment_database_directory} \
    -doid_json ${doid_json} \
    -output_directory ${output_directory} \
    "$@"
