#!/bin/bash
run_dir=$1
sample=$(ls ${run_dir} | grep -E '^(CPCT|DRUP)[0-9]{8}[^R]')

circos_bin=/data/common/tools/circos_v0.69.5/bin
circos_conf=${run_dir}/purple/circos/${sample}.circos.conf
if [[ ! -e ${circos_conf} ]]; then
    echo "Unable to locate circos configuration " ${circos_conf}
    exit 1
fi

echo "Generating plot"
${circos_bin}/circos -nosvg \
    -conf ${circos_conf} \
    -outputdir ${run_dir}/purple/plot/ \
    -outputfile ${sample}.circos.png \
    -debug_group summary,timer > ${run_dir}/purple/circos/run.out
