#!/bin/bash
run_dir=$1

# Database details
credentials=/data/common/tools/patient-db_v1.0/credentials
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=mysql://localhost:3306/hmfpatients?serverTimezone=CET
purple_jar=/data/common/tools/purple_v1.0/purity-ploidy-estimator-1.0.jar

zipped=$(ls ${run_dir}/structuralVariants/manta/*/results/variants/somaticSV.vcf.gz)
java -Dorg.jooq.no-logo=true -cp ${purple_jar} com.hartwig.hmftools.purple.structural.LoadStructuralVariants -vcf_file ${zipped} -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url}

