#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

purple_jar=${base_path}/tools/purple_v2.17/purple.jar
purple_output=${run_dir}/purple
credentials=${base_path}/dbs/mysql_credentials/prod

somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
if [ -z ${somatic_vcf} ]; then
    echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
    exit 1
fi

structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
if [ -z ${structural_vcf} ]; then
    echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting."
    exit 1
fi

${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} $@
