#!/bin/bash

run_dir=$1 && shift
purple_jar=$1 && shift
purple_output=$1 && shift
credentials=$1 && shift

baf_file=$(ls ${run_dir}/amber/*.amber.baf)
if [ $? -ne 0 ]
then
    echo "Amber BAF unavailable. Exiting."
    exit 1
fi

somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.1.vcf.gz)
if [ $? -ne 0 ]
then
    echo "Unable to locate somatic variants. Exiting."
    exit 1
fi

do_run_bpi_prod ${run_dir}
structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf)
if [ $? -ne 0 ]
then
    echo "Unable to locate bpi structural variants. Exiting."
    exit 1
fi

do_run_amber ${run_dir}
do_run_cobalt ${run_dir}

mkdir -p ${purple_output}
rm -rf ${purple_output}/*

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

gc_profile=${base_path}/dbs/gc/GC_profile.1000bp.cnp

if [ -z "${credentials}" ]; then
    java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
        -jar ${purple_jar} \
        -threads 3 \
        -somatic_vcf ${somatic_vcf} \
        -structural_vcf ${structural_vcf} \
        -baf ${baf_file} \
        -circos ${base_path}/tools/circos_v0.69.6/bin/circos \
        -run_dir ${run_dir} \
        -gc_profile ${gc_profile} \
        -output_dir ${purple_output} \
        $@
else
    db_user=$(awk '/^user/ {print $2}' ${credentials})
    db_pass=$(awk '/^pass/ {print $2}' ${credentials})
    db_url=$(awk '/^url/ {print $2}' ${credentials})

    java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
        -jar ${purple_jar} \
        -threads 3 \
        -somatic_vcf ${somatic_vcf} \
        -structural_vcf ${structural_vcf} \
        -baf ${baf_file} \
        -circos ${base_path}/tools/circos_v0.69.6/bin/circos \
        -run_dir ${run_dir} \
        -output_dir ${purple_output} \
        -gc_profile ${gc_profile} \
        -db_enabled -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
        $@
fi