#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift

purple_output=${run_dir}/purple_pilot

purple_jar=$(locate_pilot_purple)
somatic_vcf=$(locate_strelka_somatics ${run_dir})
structural_vcf=$(locate_gridss_structural_variants ${run_dir})
sv_recovery_vcf=$(locate_gridss_recovery_candidates ${run_dir})
credentials=""

do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${sv_recovery_vcf} ${purple_output} ${credentials} "$@"
