#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

purple_jar=${base_path}/tools/purple_v2.5/purple.jar
purple_output=${run_dir}/purple

${prefix}/do_run_purple ${run_dir} ${purple_jar} ${purple_output}