#!/bin/bash

run_dir=$1 && shift
purple_jar=$1 && shift
somatic_vcf=$1 && shift
structural_vcf=$1 && shift
purple_output=$1 && shift
credentials=$1 && shift

if [ ! -f "$somatic_vcf" ]
then
    echo "[ERROR] Unable to locate somatic variants. Exiting."
    exit 1
fi

if [ ! -f "$structural_vcf" ]
then
    echo "[ERROR] Unable to locate structural variants. Exiting."
    exit 1
fi

sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.full.vcf.gz)
if [ -z ${sv_recovery_vcf} ]; then
    echo "[ERROR] Unable to locate recovery structural variants. Exiting."
    exit 1
fi

mkdir -p ${purple_output}
rm -rf ${purple_output}/*

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

gc_profile=${base_path}/dbs/gc/GC_profile.1000bp.cnp

db_args=""
if [ ! -z "${credentials}" ]; then
    db_user=$(awk '/^user/ {print $2}' ${credentials})
    db_pass=$(awk '/^pass/ {print $2}' ${credentials})
    db_url=$(awk '/^url/ {print $2}' ${credentials})
    db_args="-db_enabled -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url}"
fi

java -Dorg.jooq.no-logo=true -Xmx16G -Xms4G \
    -jar ${purple_jar} \
    -somatic_vcf ${somatic_vcf} \
    -structural_vcf ${structural_vcf} \
    -circos ${base_path}/tools/circos_v0.69.6/bin/circos \
    -run_dir ${run_dir} \
    -ref_genome hg19 \
    -output_dir ${purple_output} \
    -gc_profile ${gc_profile} \
    -sv_recovery_vcf ${sv_recovery_vcf} \
    ${db_args} \
    $@