#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

purple_jar=${base_path}/tools/purple_pilot/purple.jar
purple_output=${run_dir}/purple_pilot
credentials=${base_path}/dbs/mysql_credentials/pilot
somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed_v2.2.vcf.gz)
if [ -z ${somatic_vcf} ]
then
    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
    somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
    if [ -z ${somatic_vcf} ]
    then
        echo "Unable to locate post processed somatic variants. Exiting."
        exit 1
    fi
fi

${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${purple_output} ${credentials} $@
