#!/bin/bash
source locate_files

run_dir=$1 && shift
prefix=`dirname $(readlink $0 || echo $0)`


purple_output=${run_dir}/purple

purple_jar=$(locate_prod_purple)
credentials=$(locate_prod_database_credentials)
somatic_vcf=$(locate_sage_somatics ${run_dir})
structural_vcf=$(locate_gridss_structural_variants ${run_dir})

${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} $@
