#!/bin/bash
source load_metadata

run_dir=$1 && shift

# JOBA: Load metadata
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

amber_output=$(find -L ${run_dir}/amber/ -type f -name ${tumor_sample}.amber.baf)
if [ -z ${amber_output} ]
then
    echo "Amber BAF unavailable. Exiting."
    exit 1
fi

amber_pcf=${amber_output}.pcf
if [[ ! -e ${amber_pcf} ]]
then
    base_path="/data/common"
    if [ -z "`hostname | grep datastore`" ]; then
        # KODU: common folder does not exist on crunches...
        base_path="/data"
    fi

    column=$(head -1 ${amber_output} | cut -f 4)
    echo "Executing PCF Segmentation with command: Rscript ${base_path}/repos/scripts/analysisscripts/bafSegmentation.R ${amber_output} ${column} ${amber_pcf}"
    Rscript ${base_path}/repos/scripts/analysisscripts/bafSegmentation.R ${amber_output} ${column} ${amber_pcf}
    rm ${amber_pcf}1
fi

echo "Amber complete"

