#!/bin/bash
source locate_files

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

purple_output=${run_dir}/purple_pilot

purple_jar=$(locate_pilot_purple)
credentials=$(locate_pilot_database_credentials)
somatic_vcf=$(locate_sage_somatics ${run_dir})
structural_vcf=$(locate_gridss_structural_variants ${run_dir})
sv_recovery_vcf=$(locate_gridss_recovery_candidates ${run_dir})
ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${sv_recovery_vcf} ${purple_output} ${credentials} ${ref_genome} $@
