#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

services_sample=$1 && shift
actin_patient=$1 && shift

if [[ -z "${services_sample}" || -z "${actin_patient}" ]]; then
    error "Parameters missing. Exiting."
fi

clinical_json="$(locate_actin_clinical_json ${actin_patient})"

molecular_dir="$(locate_actin_molecular_directory_for_sample ${services_sample})"
orange_json="$(locate_orange_no_germline_json ${molecular_dir})"

serve_directory="$(locate_actin_serve_db)"
doid_json="$(locate_doid_json)"
dnds_driver_likelihood_onco="$(locate_dnds_driver_likelihood_onco)"
dnds_driver_likelihood_tsg="$(locate_dnds_driver_likelihood_tsg)"
ref_genome_fasta_file="$(locate_ref_genome_37_fasta_file)"
ensembl_data_dir="$(locate_ensembl_data_dir_37)"
driver_gene_panel="$(locate_driver_gene_panel_37_tsv)"

output_directory="$(locate_actin_patient_record_directory)"

actin_jar="$(locate_actin_jar_on_vm)"

info "Running ACTIN molecular interpreter on ${actin_patient} using ${services_sample}"

java -cp ${actin_jar} com.hartwig.actin.molecular.MolecularInterpreterApplicationKt \
    -clinical_json "${clinical_json}" \
    -orange_json "${orange_json}" \
    -serve_directory "${serve_directory}" \
    -doid_json "${doid_json}" \
    -onco_dnds_database_path "${dnds_driver_likelihood_onco}" \
    -tsg_dnds_database_path "${dnds_driver_likelihood_tsg}" \
    -ref_genome_fasta_file "${ref_genome_fasta_file}" \
    -ensembl_data_dir "${ensembl_data_dir}" \
    -driver_gene_panel "${driver_gene_panel}" \
    -output_directory "${output_directory}" \
    "$@"

