#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting."
fi

platinum_dir="$(locate_actin_platinum_directory_for_sample ${sample})"

orange_json="$(locate_orange_json ${platinum_dir})"
external_treatment_mapping_tsv="$(locate_actin_external_treatment_mapping_tsv)"

output_directory="${platinum_dir}/actin"
create_or_cleanup_dir ${output_directory}

actin_jar="$(locate_pilot_actin)"

info "Running ACTIN ORANGE interpreter on ${sample}"

java -cp ${actin_jar} com.hartwig.actin.molecular.orange.OrangeInterpreterApplication \
    -orange_json ${orange_json} \
    -external_treatment_mapping_tsv ${external_treatment_mapping_tsv} \
    -output_directory ${output_directory} \
    "$@"

