#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1
source actin_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting."
fi

molecular_dir="$(locate_actin_cohort_molecular_directory ${sample})"

orange_json="${molecular_dir}/${sample}.orange.json"
serve_directory="/data/resources/actin/cohort_analysis/serve_db"

patient=$(to_actin_patient ${sample})
clinical_json="$(locate_actin_cohort_clinical_directory)/${patient}.clinical.json"
doid_json="$(locate_doid_json)"

actin_jar="$(locate_cohort_actin)"

info "Running ACTIN ORANGE cohort interpreter on ${sample}"

java -cp ${actin_jar} com.hartwig.actin.molecular.MolecularInterpreterApplicationKt \
    -orange_json "${orange_json}" \
    -serve_directory "${serve_directory}" \
    -clinical_json "${clinical_json}" \
    -doid_json "${doid_json}" \
    -output_directory "${molecular_dir}" \
    "$@"

