#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting."
fi

clinical_json="$(locate_actin_clinical_json_for_sample ${sample})"

molecular_dir="$(locate_actin_molecular_directory_for_sample ${sample})"
orange_json="$(locate_orange_no_germline_json ${molecular_dir})"

serve_directory="$(locate_actin_serve_db)"
doid_json="$(locate_doid_json)"
dnds_driver_likelihood_onco="$(locate_dnds_driver_likelihood_onco)"
dnds_driver_likelihood_tsg="$(locate_dnds_driver_likelihood_tsg)"

output_directory="$(locate_actin_patient_record_directory)"

actin_jar="$(locate_actin_jar_on_vm)"

info "Running ACTIN ORANGE interpreter on ${sample}"

java -cp ${actin_jar} com.hartwig.actin.molecular.MolecularInterpreterApplicationKt \
    -clinical_json "${clinical_json}" \
    -orange_json "${orange_json}" \
    -serve_directory "${serve_directory}" \
    -doid_json "${doid_json}" \
    -onco_dnds_database_path "${dnds_driver_likelihood_onco}" \
    -tsg_dnds_database_path "${dnds_driver_likelihood_tsg}" \
    -output_directory "${output_directory}" \
    "$@"

