#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting."
fi

serve_bridge_tsv="$(locate_actin_serve_bridge_tsv)"
external_treatment_mapping_tsv="$(locate_actin_external_treatment_mapping_tsv)"


sample_cohort_dir="$(locate_actin_cohort_directory ${run_dir})"
orange_json="$(locate_orange_json ${sample_cohort_dir})"

output_directory="${sample_cohort_dir}/actin"
create_or_cleanup_dir ${output_directory}

actin_jar="$(locate_cohort_actin)"

info "Running ACTIN ORANGE cohort interpreter on ${sample}"

java -cp ${actin_jar} com.hartwig.actin.molecular.orange.OrangeInterpreterApplication \
    -orange_json ${orange_json} \
    -serve_bridge_tsv ${serve_bridge_tsv} \
    -external_treatment_mapping_tsv ${external_treatment_mapping_tsv} \
    -output_directory ${output_directory} \
    "$@"

