#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

actin_patient=$1 && shift

if [[ -z "${actin_patient}" ]]; then
    error "Parameters missing. Exiting."
fi

wgs_dir=$1 && shift
orange_cmd=""
if [[ ! -z "${wgs_dir}" ]]; then
    full_wgs_dir="$(locate_actin_wgs_directory)/${wgs_dir}"

    info "Using ORANGE json from ${full_wgs_dir}"
    orange_json="$(locate_orange_no_germline_json ${full_wgs_dir})"
    orange_cmd="-orange_json ${orange_json}"
else
    info "Assuming no WGS has been performed for ${actin_patient}"
fi

clinical_json="$(locate_actin_clinical_json ${actin_patient})"

serve_directory="$(locate_actin_serve_db)"
doid_json="$(locate_doid_json)"
dnds_driver_likelihood_onco="$(locate_dnds_driver_likelihood_onco)"
dnds_driver_likelihood_tsg="$(locate_dnds_driver_likelihood_tsg)"
ref_genome_fasta_file="$(locate_ref_genome_37_fasta_file)"
ensembl_data_dir="$(locate_ensembl_data_dir_37)"
driver_gene_panel="$(locate_driver_gene_panel_37_tsv)"
known_fusion_file="$(locate_known_fusion_data_37_csv)"

output_directory="$(locate_actin_patient_record_directory)"

actin_jar="$(locate_actin_jar_on_vm)"

info "Running ACTIN molecular interpreter on ${actin_patient}"

java -cp ${actin_jar} com.hartwig.actin.molecular.MolecularInterpreterApplicationKt \
    -clinical_json "${clinical_json}" \
    "${orange_cmd}" \
    -serve_directory "${serve_directory}" \
    -doid_json "${doid_json}" \
    -onco_dnds_database_path "${dnds_driver_likelihood_onco}" \
    -tsg_dnds_database_path "${dnds_driver_likelihood_tsg}" \
    -ref_genome_fasta_file "${ref_genome_fasta_file}" \
    -ensembl_data_dir "${ensembl_data_dir}" \
    -driver_gene_panel "${driver_gene_panel}" \
    -known_fusions_file "${known_fusion_file}" \
    -output_directory "${output_directory}" \
    "$@"

