#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting.";
fi

run_dir="$(locate_actin_molecular_directory)/${sample}"

# Rerun initial protect just to be sure we are comparing apples with apples.
info "Running PROTECT research on ${run_dir}"
run_protect_research ${run_dir} -log_debug
load_protect_data_prod ${run_dir}

# Run virus interpreter pilot required for PROTECT pilot.
info "Running virus interpreter pilot on ${run_dir}"
run_virus_interpreter_pilot ${run_dir}

info "Running PROTECT pilot on ${run_dir}"
run_protect_pilot_on_actin ${run_dir}
load_protect_data_pilot_actin ${run_dir}
