#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source io_functions || exit 1
source api_functions || exit

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Missing input parameters. Exiting";
fi

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
ref_sample=$(load_ref_sample_from_metadata ${run_dir})

work_dir="/data/experiments/lilac/actin/${tumor_sample}"

output_dir="${run_dir}/lilac_pilot"
create_or_cleanup_dir ${output_dir}

purple_gene_copy_number_tsv=$(locate_purple_gene_copynumbers ${run_dir})
purple_somatic_variant_vcf=$(locate_purple_somatic_variants ${run_dir})

java -jar /data/tools/lilac/pilot/lilac.jar \
    -sample ${tumor_sample} \
    -resource_dir /data/experiments/lilac/resources \
    -ref_genome /data/resources/bucket/reference_genome/37/Homo_sapiens.GRCh37.GATK.illumina.fasta \
    -reference_bam ${work_dir}/${ref_sample}.hla.bam \
    -tumor_bam ${work_dir}/${tumor_sample}.hla.bam \
    -output_dir ${output_dir} \
    -gene_copy_number_file ${purple_gene_copy_number_tsv} \
    -somatic_variants_file ${purple_somatic_variant_vcf} \
    "$@"
