#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting.";
fi

download_isofox_to_run_dir ${run_dir}
if [[ -d "${run_dir}/isofox" ]]; then
    # TODO First make sure the pass-fusions are produced as described in produce_rna_pass_fusions
    #   Also, the sample needs to be present in the sample metadata file for RNA.
    load_isofox_data_to_prod ${run_dir}

    run_cuppa_dna_rna_prod ${run_dir}
    generate_cup_dna_rna_report_pipeline ${run_dir}
fi

download_rna_bam_to_run_dir ${run_dir}
if [[ -d "$(locate_rna_bam_directory ${run_dir})" ]]; then
    annotate_somatic_variants_with_rna ${run_dir}
    load_rna_annotated_somatic_variants_to_prod ${run_dir}

    # TODO Also annotate germline VCF but that one is waiting on a purple upgrade.
fi
