#!/usr/bin/env bash

source message_functions || exit 1

dir="${HOME}/Downloads"

prefix="EMC Trial Database"

pull_local_actin_resource_repo

do_update_actin_ctc_config_file "${dir}/${prefix} - CTC unmapped cohorts.tsv" "${dir}/unmapped_cohorts.tsv"
do_update_actin_ctc_config_file "${dir}/${prefix} - CTC ignore studies.tsv" "${dir}/ignore_studies.tsv"
do_update_actin_ctc_config_file "${dir}/${prefix} - CTC database.tsv" "${dir}/ctc_database.tsv"

push_local_actin_resource_repo "Updated ACTIN CTC config files"
