#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

person=$1

if [[ -z "${person}" ]]; then
    error "Parameters missing. Exiting.";
elif [[ "${person}" != "nina" && "${person}" != "hebe" && "${person}" != "kd" ]]; then
    error "Wrong parameter. Exiting.";
fi

database_sql="${HOME}/hmf/repos/actin-personalization/database/src/main/resources/generate_database.sql"
views_sql="${HOME}/hmf/repos/actin-personalization/database/src/main/resources/generate_views.sql"
table_builder_python="${HOME}/hmf/repos/actin-personalization/database/src/main/resources/distant_metastasis_overview_builder.py"
table_aggregator_python="${HOME}/hmf/repos/actin-personalization/database/src/main/resources/distant_metastasis_overview_aggregator.py"

analysis_vm_name="actin-analysis-vm-${person}"
analysis_vm_location_database_sql="${analysis_vm_name}:$(locate_actin_personalization_database_sql_script)"
analysis_vm_location_views_sql="${analysis_vm_name}:$(locate_actin_personalization_database_views_sql_script)"

analysis_vm_location_table_builder_python="${analysis_vm_name}:$(locate_actin_personalization_table_builder_python_script)"
analysis_vm_location_table_aggregator_python="${analysis_vm_name}:$(locate_actin_personalization_table_aggregator_python_script)"

if [[ ! -f "${database_sql}" || ! -f "${views_sql}" ]]; then
    error "Could not locate expected sql files. Exiting."
fi

info "Copying ${database_sql}, ${tables_python} and ${views_sql} to ${analysis_vm_name}"

gcloud compute scp ${database_sql} ${analysis_vm_location_database_sql}
gcloud compute scp ${views_sql} ${analysis_vm_location_views_sql}

gcloud compute scp ${tables_python} ${analysis_vm_location_table_builder_python}
gcloud compute scp ${tables_python} ${analysis_vm_location_table_aggregator_python}