#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

sql_file_or_select_statement=$1 && shift
database_name=$1 && shift
credentials_cnf=$1 && shift
from_file='true'

if [[ ! -f "${sql_file_or_select_statement}" ]]; then
    if [[ ! "${sql_file_or_select_statement}" =~ ^(SELECT|select) ]]; then
        error "Provided sql is not an existing file but no SELECT statement either (${sql_file_or_select_statement}). Exiting."
    else
        from_file='false'
    fi
fi

if [[ -z "${database_name}" ]]; then
    error "No database name provided. Exiting."
fi

if [[ ! -f "${credentials_cnf}" ]]; then
    error "Unable to locate MySQL credentials .cnf file (${credentials_cnf}). Exiting."
fi

if [[ "${from_file}" == "true" ]]; then
    mysql --defaults-extra-file="${credentials_cnf}" "${database_name}" \
    < "${sql_file_or_select_statement}"
else
    mysql --defaults-extra-file="${credentials_cnf}" "${database_name}" \
    --execute="${sql_file_or_select_statement}" --batch
fi
