#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

file_with_sql_to_execute=$1 && shift
database_name=$1 && shift
credentials=$1 && shift

if [[ ! -f "${file_with_sql_to_execute}" ]]; then
    error "Unable to locate SQL file to execute. Exiting."
fi

if [[ -z "${database_name}" ]]; then
    error "No database name provided. Exiting."
fi

if [[ ! -f "${credentials}" ]]; then
    error "Unable to locate MySQL credentials. Exiting."
fi

db_host=$(locate_gcp_prod_database_host)
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})

mysql ${database_name} --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${file_with_sql_to_execute}
