#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

file_with_sql_to_execute=$1

if [[ ! -f "${file_with_sql_to_execute}" ]]; then
    error "Unable to locate SQL file to execute. Exiting."
fi

database_name="hmfpatients"
credentials=$(locate_gcp_prod_database_credentials)

db_host=$(cat /data/common/dbs/mysql_credentials/gcp_database_host)
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})

mysql --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${file_with_sql_to_execute}
