#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1
source actin_config || exit 1

sql_file_or_select_statement=$1 && shift

credentials="$(prod_reader_sql_credentials)"
database_name="$(emc_phase1_sql_database_name)"

do_execute_sql_on_database "${sql_file_or_select_statement}" "${database_name}" "${credentials}"