#!/usr/bin/env bash

patient="ACTN02020001"

actin_molecular_interpreter_crc_experiment ${patient}

echo ""

actin_treatment_matcher_crc_experiment ${patient}

echo ""

actin_reporter_crc_report ${patient}
