Setup and helper function
```{r}
library(purple)
detach("package:purple", unload=TRUE)
library(purple)
library(RMySQL)
source("../gridss/libgridss.R") # working directory needs to be scripts/analysisscripts
library(tidyverse)
library(Biostrings)
```
Load data
```{r}
# Update to your VCF and sample of choice
gridss_filename <- "CPCT02100145T.gridss.sv.vcf"
sampleId <- "CPCT02100145T"
raw_gridss_vcf <- readVcf(gridss_filename, "hg19")
raw_gridss_gr <- breakpointRanges(raw_gridss_vcf)
dbProd = dbConnect(MySQL(), dbname = "hmfpatients")
prodgr <- query_structural_variants_for_sample_as_granges(dbProd, sampleId)
prodgr$QUAL <- ifelse(is.na(prodgr$ploidy), prodgr$af, prodgr$ploidy)
raw_gridss_gr$somatic_af <- gridss_somatic_af(raw_gridss_gr, raw_gridss_vcf)
raw_gridss_gr$germline_af <- gridss_af(raw_gridss_gr, raw_gridss_vcf)
```

Adjust libgridss.R:gridss_filter() to see what effect changes will make:

```{r}
source("../gridss/libgridss.R") # reload the new definition (if changed)
# we might want to split out the somatic and qual filters into separate functions
raw_gridss_gr$pass_qual <- !gridss_filter(raw_gridss_gr, raw_gridss_vcf, somatic_filters=FALSE)
raw_gridss_gr$pass_qual_somatic <- !gridss_filter(raw_gridss_gr, raw_gridss_vcf, somatic_filters=TRUE)

fdf <- gr_join_to_df(raw_gridss_gr, raw_gridss_vcf, prodgr, NULL, suffix=c("", ".bpi"))

```

```{r}

ggplot(fdf) +
	aes(x=QUAL, fill=!is.na(start.bpi)) +
	geom_histogram() +
	scale_x_log10() +
	facet_wrap(~ pass_qual_somatic + pass_qual, scales = "free")

ggplot(fdf %>% filter(germline_af == 0)) +
	aes(x=QUAL, y=somatic_af, colour=pass_qual_somatic) +
	geom_point(size=0.1) +
	# overlay BPI matches over the top
	geom_point(data=fdf %>% filter(!is.na(af)), colour="purple", size=0.2) +
	scale_x_log10() +
	labs("BPI correspondence")

ggplot(fdf %>% filter(germline_af == 0)) +
	aes(x=QUAL, y=somatic_af, colour=pass_qual_somatic) +
	geom_point(size=0.1) +
	# overlay BPI matches over the top
	geom_point(data=fdf %>% filter(!is.na(af)), colour="purple", size=0.2) +
	scale_x_log10() +
	facet_wrap(~ orientation + (svLen < 1000)) +
	labs("BPI correspondence by event type and size")
```
