#!/bin/bash

source load_metadata
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift
sample=$(load_tumor_sample_from_metadata ${run_dir})


mkdir "/data/experiments/hrd_classifier_evaluation/output/${sample}"

somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
if [ $? -ne 0 ]
then
    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
    if [ $? -ne 0 ]
    then
        echo "Unable to locate post processed somatic variants. Exiting."
        exit 1
    fi
fi

structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf)
if [ $? -ne 0 ]
then
    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
    structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf.gz)
    if [ $? -ne 0 ]
    then
        echo "Unable to locate bpi structural variants. Exiting."
        exit 1
    fi
fi

cd "/data/experiments/hrd_classifier_evaluation/output/${sample}/"
HRD_sample ${somatic_vcf} ${structural_vcf} ${sample}

sampleFile=sample.txt
predict_HRD ${sampleFile}