#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    echo "[ERROR] No run dir provided. Exiting" && exit 1;
fi

purple_purity_tsv=$(locate_purple_purity ${run_dir})

do_run_qc_fail_patient_reporter \
    ${run_dir} "below_detection_threshold" -purple_purity_tsv ${purple_purity_tsv} "$@"
