#!/bin/bash
source locate_files
source load_metadata

run_dir=$1 && shift

prefix=`dirname $(readlink $0 || echo $0)`

knowledgebase_dir=/data/common/dbs/knowledgebases/output
drup_genes_csv=/data/common/dbs/drup/180905_drup_genes.csv
hotspot_tsv=$(locate_hotspot_tsv)

ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
high_confidence_bed=/data/common/dbs/GIAB_NIST_v3.2.2/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz

sample=$(load_tumor_sample_from_metadata ${run_dir})
fusion_csv=$(locate_variant_annotator_fusions ${run_dir})
disruption_csv=$(locate_variant_annotator_disruptions ${run_dir})

patient_reporter_dir=/data/common/tools/patientreporter_cf
report_dir=/data/cpct/pilot_reports

lims_dir=/data/lims
hospital_csv=/data/common/dbs/hospital/hospitals.csv
hospital_manual_csv=/data/common/dbs/hospital/sample_hospital_mapping.csv

tumor_location_csv=/data/common/dbs/ecrf_dumps_pilot/curated_tumor_locations

signature=/data/common/dbs/signature/signature.png
rva_logo=/data/common/dbs/rva_logo/L633_l_testlaboratoria_rva_en_color.jpeg

java -Dorg.jooq.no-logo=true -jar ${patient_reporter_dir}/patient-reporter.jar \
    -knowledgebase_path ${knowledgebase_dir} \
    -drup_genes_csv ${drup_genes_csv} \
    -hotspot_tsv ${hotspot_tsv} \
    -fasta_file_location ${ref_genome} \
    -high_confidence_bed ${high_confidence_bed} \
    -fusion_csv ${fusion_csv} \
    -disruption_csv ${disruption_csv} \
    -log_debug \
    -run_dir ${run_dir} \
    -report_dir ${report_dir} \
    -lims ${lims_dir} \
    -center_csv ${hospital_csv} \
    -center_manual_csv ${hospital_manual_csv} \
    -tumor_location_csv ${tumor_location_csv} \
    -signature ${signature} \
    -rva_logo ${rva_logo} \
    -comments "This is a CF pilot patient report, not validated"
