#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

output_dir_report=/data/cpct/patient_reports

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

do_patient_report_for_run ${run_dir} -output_dir_report ${output_dir_report} "$@"