#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source lims_functions || exit 1
source message_functions || exit 1
source api_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting.";
fi

orig_run_dir=/data/datasets/${sample}

if [[ ! -d ${orig_run_dir} ]]; then
    error "Run dir ${orig_run_dir} not present. Probably not downloaded yet?"
fi

run_dir=${HOME}/dataset_copy/${sample}
if [[ -d ${run_dir} ]]; then
    info "Cleaning up ${run_dir}"
    rm -r ${run_dir}
fi

info "Copying ${orig_run_dir} to ${run_dir}"
cp -r ${orig_run_dir} ${run_dir}

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
tumor_sample_barcode=$(load_tumor_sample_barcode_from_metadata ${run_dir})

if [[ -z "${tumor_sample_barcode}" ]]; then
    info "Could not load tumor sample barcode from metadata. Attempt to resolve from LIMS."
    tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
fi

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
ref_sample_barcode=$(load_ref_sample_barcode_from_metadata ${run_dir})

if [[ -z "${ref_sample_barcode}" ]]; then
    info "Could not load ref sample barcode from metadata. Attempting to resolve from LIMS."
    ref_sample_barcode=$(find_ref_barcode_for_sample_name ${tumor_sample})
fi

if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${tumor_sample_barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  ref_sample name: ${ref_sample}"
    warn "  ref sample barcode: ${ref_sample_barcode}"
    warn "  tumor_sample name: ${tumor_sample}"
    warn "  tum sample barcode: ${tumor_sample_barcode}"
    exit 1;
fi

output_dir_report=${HOME}/reports/prod

do_patient_report_for_run_data_vm ${run_dir} ${tumor_sample} ${tumor_sample_barcode} ${ref_sample} ${ref_sample_barcode} \
      -output_dir_report ${output_dir_report} \
      -output_dir_data ${output_dir_report} \
      -only_create_pdf "$@"
