#!/bin/sh

patient_reporter_dir=/data/common/tools/patientreporter_v3.16

cpct_ecrf=/data/ecrf/cpct_ecrf.xml
lims_json=/data/lims/lims.json
report_dir=/data/cpct/patient_reports
signature=/data/common/dbs/signature/signature.png
center_csv=/data/common/dbs/center/center.csv

exec java -Dorg.jooq.no-logo=true -Xmx16G -Xms4G \
    -jar "$patient_reporter_dir"/patient-reporter.jar \
    -lims_json "$lims_json" \
    -cpct_ecrf "$cpct_ecrf" \
    -report_dir "$report_dir" \
    -center_csv "$center_csv" \
    -signature "$signature" \
    "$@"
