#!/bin/sh

patient_reporter_dir=/data/common/tools/patientreporter_v3

cpct_ecrf=/data/ecrf/cpct_ecrf.xml
report_dir=/data/cpct/patient_reports

exec java -Xmx16G -Xms4G -jar "$patient_reporter_dir"/patient-reporter.jar -cpct_ecrf "$cpct_ecrf" -report_dir "$report_dir" "$@"
