#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`

patient_reporter_dir=/data/common/tools/patientreporter_v1.0
cpct_slicing_bed="$patient_reporter_dir"/bed/CPCT_Slicing.bed
high_confidence_bed="$patient_reporter_dir"/bed/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed
hmf_slicing_bed="$patient_reporter_dir"/bed/HMF_Slicing.bed

"$prefix"/do_run_base_patient_reporter -cpct_slicing_bed "$cpct_slicing_bed" -high_confidence_bed "$high_confidence_bed" -hmf_slicing_bed "$hmf_slicing_bed" "$@"