#!/usr/bin/env bash

tumor_sample=$1 && shift

if [[ -z ${tumor_sample} ]]; then
    echo "[ERROR] No tumor sample provided. Exiting"
    exit 1;
fi

do_run_qc_fail_patient_reporter ${tumor_sample} "insufficient_tissue_delivered" "$@"