#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`

patient_reporter_dir=/data/common/tools/patientreporter_v3.0
cpct_slicing_bed="$patient_reporter_dir"/bed/CPCT_Slicing.bed
high_confidence_bed="$patient_reporter_dir"/bed/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed

hmf_gene_panel="$patient_reporter_dir"/bed/hmf_gene_panel.tsv
drup_genes_csv="$patient_reporter_dir"/csv/drup_genes.csv
cosmic_csv=/data/common/dbs/cosmic_census/170529_grch37_cosmic_census.csv

"$prefix"/do_run_base_patient_reporter -cpct_slicing_bed "$cpct_slicing_bed" -high_confidence_bed "$high_confidence_bed" -hmf_gene_panel "$hmf_gene_panel" -drup_genes_csv "$drup_genes_csv" -cosmic_csv "$cosmic_csv" -run_dir "$@"
