#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`

drup_genes_csv=/data/common/tools/patientreporter_v3/csv/drup_genes.csv
cosmic_csv=/data/common/dbs/cosmic_census/170529_grch37_cosmic_census.csv
center_csv=/data/common/dbs/center/center.csv
signature=/data/common/dbs/signature/signature.png

"$prefix"/do_run_base_patient_reporter \
    -drup_genes_csv "$drup_genes_csv" \
    -cosmic_csv "$cosmic_csv" \
    -center_csv "$center_csv" \
    -signature "$signature" \
    -run_dir "$@"
