#!/usr/bin/env bash

source lims_functions || exit 1
source message_functions || exit 1

tumor_sample=$1 && shift
qc_fail_reason=$1 && shift
ref_sample_mandatory=$1 && shift

output_dir_report=${HOME}/reports/pilot

if [[ -z "${tumor_sample}" || -z "${qc_fail_reason}" ]]; then
    error "No tumor sample and/or QC fail reason provided. Exiting";
fi

ref_sample=$(imply_ref_sample_from_tumor_sample ${tumor_sample})
ref_sample_barcode=$(find_ref_barcode_for_sample_name ${tumor_sample})
tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})

if [[ -z "${tumor_sample_barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  tumor_sample name: ${tumor_sample}"
    warn "  tum sample barcode: ${tumor_sample_barcode}"
    exit 1;
fi

if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" ]]; then
    if [[ ${ref_sample_mandatory} == "1" ]]; then
        warn "Incomplete information for reporter. Exiting"
        warn "  ref_sample name: ${ref_sample}"
        warn "  ref_sample barcode: ${ref_sample_barcode}"
        warn "  tumor_sample name: ${tumor_sample}"
        warn "  tumor_sample barcode: ${tumor_sample_barcode}"
        exit 1;
    else
        warn "Ref sample information is incomplete!"

        pilot_do_run_base_patient_reporter \
            -output_dir_report ${output_dir_report} \
            -output_dir_data ${output_dir_report} \
            -qc_fail \
            -qc_fail_reason ${qc_fail_reason} \
            -tumor_sample_id ${tumor_sample} \
            -tumor_sample_barcode ${tumor_sample_barcode} \
            -ref_genome_version 37 \
            "$@"
    fi
else
    pilot_do_run_base_patient_reporter \
        -output_dir_report ${output_dir_report} \
        -output_dir_data ${output_dir_report} \
        -qc_fail \
        -qc_fail_reason ${qc_fail_reason} \
        -ref_sample_id ${ref_sample} \
        -ref_sample_barcode ${ref_sample_barcode} \
        -tumor_sample_id ${tumor_sample} \
        -tumor_sample_barcode ${tumor_sample_barcode} \
        -ref_genome_version 37 \
        "$@"
fi