#!/usr/bin/env bash

source locate_files

patient_reporter_jar=$(locate_pilot_patient_reporter)

reporting_db_tsv=/data/experiments/patient_reporter_version_7_19_verification/lims/reporting_db.tsv
primary_tumor_tsv=/data/common/dbs/clinical_data/curated_primary_tumor.tsv
lims_dir=/data/experiments/patient_reporter_version_7_19_verification/lims

rva_logo=/data/common/dbs/patient_reporter_images/L633_l_testlaboratoria_rva_en_color.jpeg
company_logo=/data/common/dbs/patient_reporter_images/hartwig_logo.jpg
signature=/data/common/dbs/patient_reporter_images/signature_edwin_transparant.png

java -jar ${patient_reporter_jar} \
    -reporting_db_tsv ${reporting_db_tsv} \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -rva_logo ${rva_logo} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -comments "This is a pilot patient report and is not meant for production purpose" \
    "$@"
