#!/bin/bash

patient_reporter_dir=/data/common/tools/patientreporter_pilot
report_dir=/data/cpct/pilot_reports

lims_dir=/data/lims
hospital_dir=/data/common/dbs/hospital

tumor_location_csv=/data/common/dbs/ecrf_dumps_pilot/curated_tumor_locations

signature=/data/common/dbs/signature/signature.png
rva_logo=/data/common/dbs/rva_logo/L633_l_testlaboratoria_rva_en_color.jpeg

java -Dorg.jooq.no-logo=true -jar ${patient_reporter_dir}/patient-reporter.jar \
    -report_dir ${report_dir} \
    -lims_dir ${lims_dir} \
    -hospital_dir ${hospital_dir} \
    -tumor_location_csv ${tumor_location_csv} \
    -signature ${signature} \
    -rva_logo ${rva_logo} \
    -comments "This is a pilot patient report, not validated" \
    "$@"
