#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    echo "[ERROR] No run dir provided. Exiting" && exit 1;
fi

comments="This is a pilot patient report and is not meant for production purpose."

purple_purity_tsv=$(locate_purple_purity ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
output_dir_data_report=${run_dir}/patient_report_pilot_data

if [[ ! -d "${output_dir_data_report}" ]]; then
    echo "[INFO] ${output_dir_data_report} does not exist yet, creating..."
    mkdir ${output_dir_data_report}
fi

pilot_do_run_qc_fail_patient_reporter \
    ${tumor_sample} "insufficient_tcp_deep_wgs" -output_dir_data_report ${output_dir_data_report} -comments "${comments}" -purple_purity_tsv ${purple_purity_tsv} "$@"
