#!/bin/bash

source locate_files
shallow_purity_csv=/data/common/dbs/shallowSeq/shallowSeqPurity.csv

prefix=`dirname $(readlink $0 || echo $0)`

${prefix}/pilot_do_run_base_patient_reporter \
    -not_analysable \
    -not_analysable_reason low_tumor_percentage \
    -not_analysable_sample \
    -file_shallowSeq_purity ${shallow_purity_csv} "$@"