#!/usr/bin/env bash

source message_functions || exit 1

source locate_files
source metadata_functions

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting" && exit 1;
fi

ref_sample_mandatory=1

purple_purity_tsv=$(locate_purple_purity ${run_dir})
purple_qc_file=$(locate_purple_qc ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
output_dir_data_report=${run_dir}/patient_report_pilot_data

if [[ ! -d "${output_dir_data_report}" ]]; then
    info "${output_dir_data_report} does not exist yet, creating..."
    mkdir ${output_dir_data_report}
fi

pilot_do_run_qc_fail_patient_reporter ${tumor_sample} "insufficient_tcp_deep_wgs" ${ref_sample_mandatory}  \
    -output_dir_data ${output_dir_data_report} \
    -purple_purity_tsv ${purple_purity_tsv} \
    -purple_qc_file ${purple_qc_file} \
    "$@"
