#!/usr/bin/env bash

run_dir=$1 && shift

if [[ -z ${run_dir} ]]; then
    echo "[ERROR] No run dir provided. Exiting"
    exit 1;
fi

comments="This is a pilot patient report and is not meant for production purpose."

pilot_do_run_qc_fail_patient_reporter ${run_dir} "post_analysis_fail" -comments "${comments}" "$@"
