#!/usr/bin/env bash

source message_functions || exit 1

tumor_sample=$1 && shift

if [[ -z "${tumor_sample}" ]]; then
    error "No tumor sample provided. Exiting"
fi

ref_sample_mandatory=0
pilot_create_patient_report_pre_pipeline_fail ${tumor_sample} "insufficient_dna" ${ref_sample_mandatory}