#!/usr/bin/env bash

source message_functions || exit 1

run_dir=$1 && shift

output_dir_report=/data/cpct/pilot_reports

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

pilot_do_patient_report_for_run ${run_dir} \
    -only_create_pdf \
    -output_dir_report ${output_dir_report} \
    -override_pipeline_version \
    "$@"