#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`

"$prefix"/do_run_base_patient_reporter \
    -not_sequenceable \
    -not_sequenceable_reason post_isolation_fail \
    -not_sequenceable_sample "$@"