#!/bin/bash

patient_reporter_dir=/data/common/tools/patientreporter_v2.0

cpct_slicing_bed="$patient_reporter_dir"/bed/CPCT_Slicing.bed
high_confidence_bed="$patient_reporter_dir"/bed/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed
hmf_slicing_bed="$patient_reporter_dir"/bed/slicing_info.csv
drup_genes_csv="$patient_reporter_dir"/csv/drup_genes.csv
cosmic_csv=/data/common/dbs/cosmic_census/170529_grch37_cosmic_census.csv

cpct_ecrf=/data/ecrf/cpct_ecrf.xml
lims_csv=/data/lims/lims_data.csv
report_logo="$patient_reporter_dir"/images/hartwig_logo.jpg
report_dir=/data/cpct/patient_reports_v2

exec java -Xmx16G -Xms4G -jar "$patient_reporter_dir"/patient-reporter.jar -cpct_ecrf "$cpct_ecrf" -lims_csv "$lims_csv" -report_logo "$report_logo" -report_dir "$report_dir" -cpct_slicing_bed "$cpct_slicing_bed" -high_confidence_bed "$high_confidence_bed" -hmf_slicing_bed "$hmf_slicing_bed" -drup_genes_csv "$drup_genes_csv" -cosmic_csv "$cosmic_csv" -run_dir "$@"
