#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`

${prefix}/do_run_base_patient_reporter \
    -not_analysable \
    -not_analysable_reason shallow_seq_low_purity \
    -not_analysable_sample "$@"