#!/usr/bin/env bash

source metadata_functions || exit 1
source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

run_dir=$1 && shift
ref_data_dir=$1 && shift
cuppa_jar=$1 && shift
cuppa_dir=$1 && shift

if [[ -z "${run_dir}" || -z "${ref_data_dir}" || -z ${cuppa_jar} || -z "${cuppa_dir}" ]]; then
    error "Missing params. Exiting"
fi

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

if [[ ! -d "${cuppa_dir}" ]]; then
    mkdir -p "${cuppa_dir}"
fi

tmp_sample_data_dir="${run_dir}/cuppa_sample_data_dna_rna_pilot"

info "Creating and populating sample data dir '${tmp_sample_data_dir}'"
create_or_cleanup_dir ${tmp_sample_data_dir}
cp -r ${run_dir}/purple/* ${tmp_sample_data_dir}/
cp -r ${run_dir}/linx/* ${tmp_sample_data_dir}/
if [[ -d "${run_dir}/virus_interpreter" ]]; then
    cp -r ${run_dir}/virus_interpreter/* ${tmp_sample_data_dir}/
else
    cp -r ${run_dir}/virusintrprtr/* ${tmp_sample_data_dir}/
fi
cp -r ${run_dir}/isofox/* ${tmp_sample_data_dir}/

info "Running Cuppa pilot DNA-RNA on ${run_dir}"
java -Xmx4G -jar ${cuppa_jar} \
    -categories ALT_SJ \
    -ref_data_dir ${ref_data_dir} \
    -sample ${tumor_sample} \
    -sample_data_dir ${tmp_sample_data_dir} \
    -output_dir ${cuppa_dir} \
    "$@"

info "Removing temporary data dir '${tmp_sample_data_dir}'"
rm -r ${tmp_sample_data_dir}
