#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

ref_dir=$1 && shift

if [[ -z "${ref_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

cuppa_jar=$(locate_pilot_cuppa)
cup_ref_dir=${ref_dir}

# Database details
credentials=$(locate_prod_database_credentials)
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

info "Running CUPPA Ref Data Builder"

java -cp ${cuppa_jar} com.hartwig.hmftools.cup.ref.RefDataBuilder \
    -ref_sample_data_file ${cup_ref_dir}/cup_ref_sample_data.csv \
    -output_dir ${cup_ref_dir} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -log_debug
