#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source database_functions || exit 1

ref_dir=$1 && shift

if [[ -z "${ref_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

cuppa_jar=$(locate_pilot_cuppa)
cup_ref_dir=${ref_dir}

# Database details
credentials=$(prod_reader_sql_credentials)

database_name="hmf_patients"
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" "${database_name}")

info "Running CUPPA Ref Data Builder"

java -cp ${cuppa_jar} com.hartwig.hmftools.cup.ref.RefDataBuilder \
    -ref_sample_data_file ${cup_ref_dir}/cup_ref_sample_data.csv \
    -output_dir ${cup_ref_dir} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -log_debug
