#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

ref_dir=$(locate_cuppa_ref_dir_dna)
cuppa_jar=$(locate_prod_cuppa)
cuppa_dir="${run_dir}/cuppa"

do_run_cuppa_dna ${run_dir} ${ref_dir} ${cuppa_jar} ${cuppa_dir} "$@"
