#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

ref_dir=/data/experiments/cup/ref/015
cuppa_dir=${run_dir}/cuppa_dna_rna_pilot
cuppa_jar=/data/experiments/tools/cuppa.jar

do_run_cuppa_dna_rna ${run_dir} ${ref_dir} ${cuppa_dir} ${cuppa_jar}