#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source database_functions || exit 1

# Database details
credentials=$(prod_reader_sql_credentials)

database_name="hmf_patients"
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_host=$(extract_database_host "${credentials}")
db_port=$(extract_database_port "${credentials}")
database_dependencies=$(extract_database_dependencies "${credentials}")
db_url=$( echo "mysql://${db_host}:${db_port}/${database_name}?serverTimezone=CET${database_dependencies}")

sampleId=$1

if [[ -z "${sampleId}" ]]; then
    error "No sample ID passed. Exiting"
fi

cup_ref_dir=/data/experiments/cup/ref/
cuppa_jar=/data/tools/cuppa_v1.4/cuppa.jar
output_dir=/data/experiments/nina_cup_experiments/cup_output_data/sample_data/
report_dir=/data/experiments/nina_cup_experiments/cup_output_data/reports/
report_script=/data/repos/scripts/hmftools/cuppa/CupGenerateReport_AddDisclaimer.R

echo "CUPPA analysis for ${sampleId}"
echo "Sample output: ${output_dir}"
echo "Reference data: ${cup_ref_dir}"
echo "Report_dir: ${report_dir}"
echo "Report_script: ${report_script}"

java -jar ${cuppa_jar} \
    -sample_data ${sampleId} \
    -categories DNA \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -ref_data_dir ${cup_ref_dir} \
    -output_dir ${output_dir} 

# Rscript /data/common/repos/analysis/cup/CupGenerateReport.R <sampleId> ./sample_data/ ./reports/
Rscript ${report_script} ${sampleId} ${output_dir} ${report_dir} true
