#!/bin/bash
starts_with=$1 && shift

for run_dir in /data/cpct/runs/*; do
    if [[ ${run_dir} == /data/cpct/runs/${starts_with}* ]]; then

        somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
        if [ $? -ne 0 ]
        then
            echo "[WARN] Somatic V2 unavailable for run:" ${run_dir}
        fi
    fi
done