#!/bin/bash
source load_metadata
run_dir=$1 && shift

### Dependencies
strelka_post_process_jar=/data/common/tools/strelka-post-process_v1.0/strelka-post-process.jar
high_confidence_bed=/data/common/dbs/GIAB_NIST_v3.2.2/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz

### Output Directory
output_dir=${run_dir}/somaticVariants/postStrelka
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

### Input
merged_passed=${output_dir}/passed.somatics.merged.vcf

### Output
post_processed=${output_dir}/passed.somatics.post_processed.vcf

if [[ ! -e ${post_processed} ]]
then
    java -jar ${strelka_post_process_jar} \
        -v ${merged_passed} \
        -hc_bed ${high_confidence_bed} \
        -t ${tumor_sample} \
        -o ${post_processed}
else
    echo "${post_processed} already exists!"
fi
