#!/bin/bash
source load_metadata
input_vcf=$1 && shift
output_vcf=$1 && shift

### Tools
bcftools=/data/common/tools/bcftools_v1.3/bcftools
tabix=/data/common/tools/tabix_v0.2.6/tabix

### Dependencies
MAPPABILITY_BED=/data/common/dbs/hg19_mappability_tracks/out_150_hg19.mappability.bed.gz
CALLING_DBSNP=/data/common/dbs/GATK_bundle_v2.8/dbsnp_138.b37.vcf.gz
ANNOTATE_IDDB=/data/common/dbs/cosmic_v76/CosmicCodingMuts_v76.vcf.gz
GERMLINE_PON=/data/common/dbs/PON_v2.0/GERMLINE_PON.vcf.gz
SOMATIC_PON=/data/common/dbs/PON_v2.0/SOMATIC_PON.vcf.gz

### Intermediate Files
ann1=${output_vcf}.tmp1
ann2=${output_vcf}.tmp2
ann3=${output_vcf}.tmp3
ann4=${output_vcf}.tmp4

echo "Annotating DBSNP -" $(date)
${bcftools} annotate -a ${CALLING_DBSNP} -c ID ${input_vcf} -o ${ann1} -O z
${tabix} ${ann1} -p vcf

echo "Annotating IDDB -" $(date)
${bcftools} annotate -a ${ANNOTATE_IDDB} -c =ID ${ann1} -o ${ann2} -O z
${tabix} ${ann2} -p vcf

echo "Annotating Mappability -" $(date)
${bcftools} annotate -a ${MAPPABILITY_BED} -h ~/strelka/mappability.hdr -c CHROM,FROM,TO,-,MAPPABILITY  ${ann2} -o ${ann3} -O z
${tabix} ${ann3} -p vcf

echo "Annotating Germline PON -" $(date)
${bcftools} annotate -a ${GERMLINE_PON} -c GERMLINE_PON_COUNT ${ann3} -o ${ann4} -O z
${tabix} ${ann4} -p vcf

echo "Annotating Somatic PON -" $(date)
${bcftools} annotate -a ${SOMATIC_PON} -c SOMATIC_PON_COUNT ${ann4} -o ${output_vcf} -O z
${tabix} ${output_vcf} -p vcf

### Clean up
rm ${ann1}*
rm ${ann2}*
rm ${ann3}*
rm ${ann4}*

#do_strelka_annotation \
#    /data/cpct/runs/171029_HMFregCPCT_FR15414420_FR15414585_CPCT02290017/somaticVariants/postStrelka/passed.somatics.post_processed.mnvs.snpEff.vcf.gz \
#    /data/cpct/runs/171029_HMFregCPCT_FR15414420_FR15414585_CPCT02290017/somaticVariants/postStrelka/annotated.vcf.gz