#!/bin/bash
source load_metadata
run_dir=$1 && shift

#### Tools
tabix=/data/common/tools/tabix_v0.2.6/tabix

#### Output Directories
sample=$(load_tumor_sample_from_metadata ${run_dir})
joint_name=$(load_joint_name_from_metadata ${run_dir})
output_dir=${run_dir}/somaticVariants/${joint_name}
working_dir=${output_dir}/postStrelka
mkdir -p ${working_dir}

#### Output Files
merged_vcf=${working_dir}/merged.vcf
post_processed_vcf=${working_dir}/post_processed.vcf
mnv_vcf=${working_dir}/mnv.vcf
snpEff_vcf=${working_dir}/snpEff.vcf
snpEff_vcf_gz=${snpEff_vcf}.gz
annotated_vcf_gz=${working_dir}/annotated.vcf.gz
final_vcf_gz=${output_dir}/${joint_name}_post_processed.v2.vcf.gz

#### Execution
if [[ ! -e ${final_vcf_gz} ]]
then

    if [[ ! -e ${merged_vcf} ]]
    then
        do_strelka_merge ${run_dir} ${merged_vcf}
    fi

    if [[ ! -e ${post_processed_vcf} ]]
    then
        do_strelka_post_process ${sample} ${merged_vcf} ${post_processed_vcf}
    fi

    if [[ ! -e ${mnv_vcf} ]]
    then
        do_strelka_mnv ${sample} ${post_processed_vcf} ${mnv_vcf}
    fi

    if [[ ! -e ${snpEff_vcf} ]]
    then
        do_strelka_snpeff ${sample} ${mnv_vcf} ${snpEff_vcf}
    fi

    bgzip ${snpEff_vcf}
    ${tabix} -p vcf ${snpEff_vcf_gz}

    do_strelka_annotation ${snpEff_vcf_gz} ${annotated_vcf_gz}
    do_strelka_pon_filter ${annotated_vcf_gz} ${final_vcf_gz}

    rm -rf ${working_dir}
fi

echo "Complete -" $(date)
