#!/bin/bash

MNV_DETECTOR=/data/common/tools/mnvdetector_v1.0/mnv-detector.jar
MNV_VALIDATOR=/data/common/tools/mnvdetector_v1.0/mnv-validator.jar
BAM_SLICER_SCRIPT=/data/common/repos/scripts/hmftools/bamslicer/bam_slicer

SAMPLE=$1 && shift
VCF=$1 && shift
FINAL_VCF=$1 && shift

## MIVO: some sanity checks
if [[ ! -f "${VCF}" ]]; then echo "[EXIT] Vcf not found" && exit 1; fi
if [[ -z "${SAMPLE}" ]]; then echo "[EXIT] Sample not found" && exit 1; fi

OUTPUT_DIR=`dirname ${VCF}`
SLICED_BAM="${OUTPUT_DIR}/${SAMPLE}_dedup.realigned.sliced.bam"
VCF_NAME="${VCF%.*}"
MNV_BED="${VCF_NAME}.mnvs.bed"
MNV_VCF="${VCF_NAME}.potential_mnvs.vcf"

if ! java -jar ${MNV_DETECTOR} \
    -v ${VCF} \
    -bed_out ${MNV_BED} \
    -vcf_out ${MNV_VCF} ;
then exit 1
fi

rm "${MNV_VCF}.idx"

if ! ${BAM_SLICER_SCRIPT} ${SAMPLE} ${MNV_BED} ;
then exit 1
fi

if ! java -jar ${MNV_VALIDATOR} \
    -v ${VCF} \
    -b ${SLICED_BAM} \
    -o ${FINAL_VCF} ;
then exit 1
fi

rm "${FINAL_VCF}.idx"
