#!/usr/bin/env bash

source message_functions || exit 1

suffix=$1 && shift

if [[ -z "${suffix}" ]]; then
    error "VM name suffix missing. Exiting."
fi

vm_name="actin-analysis-vm-${suffix}"

info "Creating ACTIN analysis VM '${vm_name}'"
# NOTE: Below requires "${scripts_repo}/gcp" to be on your $PATH!
make_vm -n ${vm_name} -i actin-analysis-base -p hmf-crunch -c actin

#  In addition, you need to take the following steps on the VM:
#   - Start up the jupyterlab service: sudo systemctl start jupyterlab.service
#   - Create an SSH key via ssh-keygen and register public key (~/.ssh/id_rsa.pub) in your github settings on github.com
#   - Switch ownership of .git folders to your user in /data/repos/personalization/: sudo chown -R ${usr}:users .git*
#   - Up the permissions in this directory so your user can write: sudo chmod -R 775 /data/repos/actin-personalization
