#!/usr/bin/env bash

source locate_files

######################
#Edit me
fingerprinting_dir="/data/experiments/fingerprinting_for_aumc_DR089"
gatk_jar="/data/common/tools/gatk_v3.8.0/GenomeAnalysisTK.jar"
ref_genome=$(locate_ref_genome_fasta_file)

######################

#input data
germline_vcf=$1 && shift
sample_id=$1 && shift

output_vcf="${fingerprinting_dir}/output/${sample_id}.vcf"

if [[ ! -f ${output_vcf} ]]; then
    echo "[INFO] Running fingerprinting on sample ${sample_id} using germline vcf ${germline_vcf}"
    cd ${fingerprinting_dir}

    java -Xmx8g -jar ${gatk_jar} \
        -T SelectVariants \
        --removeUnusedAlternates \
        -R "${ref_genome}" \
        -L "${fingerprinting_dir}/inputs/snp_filtered.vcf" \
        -V "${germline_vcf}" \
        -selectType SNP \
        -o "${fingerprinting_dir}/output/${sample_id}.vcf"
else
    echo "[INFO] Skipping fingerprinting on ${sample_id}. Output already exists."
fi