#!/usr/bin/env bash

source message_functions || exit 1

remote_base_path="serve-vm-actin-1:/data/output/research_output_ckb_evidence_and_trials"
local_base_path="${HOME}/hmf/repos/actin-resources-private"

info "Pulling SERVE resources from ${remote_base_path} into ${local_base_path}"

gcloud compute --project hmf-crunch scp ${remote_base_path}/*37*tsv ${local_base_path}/serve_db/37/
gcloud compute --project hmf-crunch scp ${remote_base_path}/*38*tsv ${local_base_path}/serve_db/38/