#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source actin_config || exit 1

remote_base_path="$(production_actin_serve_vm):$(locate_serve_output_actin_nl)"
local_base_path="${HOME}/hmf/repos/actin-resources-private/serve_db"

info "Pulling SERVE resources from ${remote_base_path} into ${local_base_path}"

gcloud compute --project hmf-crunch scp ${remote_base_path}/*json ${local_base_path}/