#!/usr/bin/env bash

source message_functions || exit 1

command -v realpath > /dev/null || die "Utility 'realpath' not found"
command -v gsutil > /dev/null || die "Utility 'gsutil' not found"

bucket="gs://hmf-ops-data/sequencer_archive/"

if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo " Usage: $(basename $0) <path-to-flowcell-directory>"
    echo "        $(basename $0) /data1/illumina_data/210402_NB500902_0301_AH2V53BGXJ"
    echo " Descr: Syncs complete flowcell directory to bucket ${bucket} excluding BCL, images, logs"
    echo "-----"
    exit 1
fi
flowcell_dir=$1

# use absolute path and strip trailing slash if present
flowcell_dir=$(realpath "${flowcell_dir}")
flowcell_name="${flowcell_dir##*/}"
target_dir="${bucket}/${flowcell_name}"

# sanity checks
[[ -d "${flowcell_dir}" ]] || die "Directory not found (${flowcell_dir})"

# perform sync
info "Starting sync of ${flowcell_dir} to bucket path ${target_dir} (excluding BCL and images)"
gsutil -m rsync -r \
  -x ".*\.bcl\.gz$" \
  -x ".*\.cbcl$" \
  -x ".*Data/Intensities/BaseCalls/L0.*$" \
  -x ".*\.fastq\.gz$" \
  -x ".*Images.*$" \
  -x ".*Read.*Cycle.*\.log$" \
  -x ".*RTALogs/.*FileCopyLog.*\.tsv$" \
  -x ".*RTALogs/.*GlobalLog.*\.tsv$" \
"${flowcell_dir}" "${target_dir}" || die "Rsync of '${flowcell_dir}' failed!"
info "Finished syncing ${flowcell_dir}"
