#!/usr/bin/env bash

source gcp_functions || exit 1
source message_functions || exit 1

command -v gsutil > /dev/null || die "Utility 'gsutil' not found"

TMP_LOCAL_BASE_DIR="/data/tmp/flowcells"
BUCKET_BASE_DIR="gs://hmf-ops-archive/sequencer_archive"

SCRIPT_NAME="$(basename "$0")"

if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo " Usage: ${SCRIPT_NAME} <crunch-name> <flowcell-path>"
    echo "        ${SCRIPT_NAME} crunch2.prod-1 /data1/illumina_data/210402_NB500902_0301_AH2V53BGXJ"
    echo " Descr: Syncs sequencing config files and conversion logs of a flowcell to bucket ${BUCKET_BASE_DIR}. Run this on the ops VM."
    echo "-----"
    exit 1
fi
crunch=$1 && shift
flowcell_dir=${1%/} && shift  # remove trailing slash, if present

# sanity checks
[[ -n ${crunch} ]] || die "No crunch server provided: crunch=${crunch}"
[[ -n ${flowcell_dir} ]] || die "No flowcell dir provided: flowcell_dir=${flowcell_dir}"

flowcell_name="${flowcell_dir##*/}"
tmp_local_dir="${TMP_LOCAL_BASE_DIR}/${flowcell_name}"
target_bucket_dir="${BUCKET_BASE_DIR}/${flowcell_name}"

# check whether flowcell already exists in bucket
if gsutil -q stat "${target_bucket_dir}/SampleSheet.csv"; then
  die "Flowcell already exists in bucket. To delete, run: gsutil -mq rm -r ${target_bucket_dir}"
fi

# ensure local dir is clean
if [[ -d ${tmp_local_dir} ]]; then
  rm -r "${tmp_local_dir}"
fi
mkdir --parents "${tmp_local_dir}"

# perform sync to local
info "Starting sync config files of ${flowcell_dir} to local path ${tmp_local_dir}"
rsync -trh --info=progress2 -f '- /*/' \
"${crunch}:${flowcell_dir}/" "${tmp_local_dir}/" || die "Rsync1 of '${flowcell_dir}' to local dir failed!"

info "Starting sync conversion logs of ${flowcell_dir} to local path ${tmp_local_dir}"
rsync -trh --info=progress2 --exclude "*fastq.gz" \
"${crunch}:${flowcell_dir}/Fastq" "${tmp_local_dir}/" || die "Rsync2 of '${flowcell_dir}' to local dir failed!"
info "Finished syncs of ${flowcell_dir}"

# perform sync to bucket
info "Starting sync of ${flowcell_name} to bucket path ${target_bucket_dir}"
gsutil -mq rsync -r "${tmp_local_dir}" "${target_bucket_dir}" || die "Rsync of '${flowcell_dir}' failed!"
info "Finished sync of ${flowcell_name} to bucket"

# delete local tmp dir
info "Delete local tmp dir ${tmp_local_dir}"
rm -r "${tmp_local_dir}" || die "Could not remove local data dir"
info "Deleted local tmp dir"

info "Finished syncing ${flowcell_name}"
