#!/usr/bin/env bash

MAX_CHAR=64

function main () {
    echo ""
    grep_ps "[a]ws"
    grep_ps "[g]sutil"
    grep_ps "[r]sync" "gsutil"
    grep_ps "[m]d5sum"
    grep_ps "[b]am2fastq"
    grep_ps "[b]cl2fastq"
    echo ""
}

function grep_ps () {
    local string=$1 && shift
    local exclude=$1 && shift
    local tag=$(echo "${string}" | sed 's/[]\[]//g')

    ps_cmd="ps -ef | grep -P '${string}' | tr -s ' '"
    if [[ "${exclude}" != "" ]]; then 
        ps_cmd="ps -ef | grep '${string}' | grep -v "${exclude}" | tr -s ' '"
    fi
    ps_cmd_exec="${ps_cmd} | cut -d' ' -f1,5,8- | cut -c 1-$MAX_CHAR | sort | uniq"

    echo "-----> Searching for ${tag} ($ps_cmd)"
    eval $ps_cmd_exec
    echo ""
}

main
