#!/usr/bin/env bash

source message_functions || exit 1

MAX_DF_PERC=95
NA="NA"
script=$(basename "$0")

function main {
    [[ "$(hostname)" =~ datastore ]] || die "[ERROR] Only run this script at datastore!"
    info "Starting with ${script}"
    check_datastore
    check_crunches
    info "Finished with ${script}"
}

function check_datastore {
    header "datastore"
    diskUsage "/home"
    diskUsage "/data"
    toolVsn "gsutil" ""
}

function check_crunches {
    for crunch in crunch00{2,3}; do
        header ${crunch}
        diskUsage "/home"  "ssh ${crunch}"
        diskUsage "/data1" "ssh ${crunch}"
        diskUsage "/data2" "ssh ${crunch}"
        gitRepVsn "/data/repos/scripts" "ssh ${crunch}"
          toolVsn "gsutil" "ssh ${crunch}"
    done
}

function header {
    local msg=$1
    info "=== ${msg} ==="
}

function toolVsn {
    local tool_name=$1
    local cmd_prefix=$2
    local version=${NA}
    local location=${NA}
    version=$(${cmd_prefix} "${tool_name}" --version)
    location=$(${cmd_prefix} which "${tool_name}")
    info "TOOL: ${version} (${location})"
}

function gitRepVsn {
    local repos_dir=$1
    local cmd_prefix=$2
    local commit=${NA}
    local dryrun=${NA}
    commit=$(${cmd_prefix} "cd ${repos_dir}; git log | head -1")
    dryrun=$(${cmd_prefix} "cd ${repos_dir}; git pull --dry-run 2>&1 | wc -l")
    if [[ "${dryrun}" -gt 0 ]]; then
        info "REPO: ${repos_dir} is OUTDATED (${commit})"
    else
        info "REPO: ${repos_dir} is at most recent commit"
    fi
}

function diskUsage {
    local mount=$1
    local cmd_prefix=$2
    local available=${NA}
    local percentage_string=${NA}
    local percentage=${NA}
    available=$(${cmd_prefix} df -h "${mount}" | tail -1 | tr -s ' ' | cut -d" " -f 4)
    percentage_string=$(${cmd_prefix} df -h "${mount}" | tail -1 | tr -s ' ' | cut -d" " -f 5)
    percentage=${percentage_string/\%/}
    info "${percentage_string} used with ${available} space left for mount ${mount}"
    if [[ "${percentage}" -gt "${MAX_DF_PERC}" ]]; then
        warn "  Disk usage (${percentage}%) for mount ${mount} higher than ${MAX_DF_PERC}!"
    fi
}

main

