#!/usr/bin/env bash

MAX_DF_PERC=95
NA="NA"

function main {
    if [[ ! "$(hostname)" =~ datastore ]]; then
        echo "[ERROR] Only run this script at datastore!" && exit 1
    fi

    title "SYSTEMS CHECK"
    header "datastore"
    diskUsage "/home"
    diskUsage "/data"
    toolVsn "gsutil" ""
    crunches
    echo ""
}

function crunches {
    for crunch in crunch00{2,3}; do
        header ${crunch}
        diskUsage "/home"  "ssh ${crunch}"
        diskUsage "/data1" "ssh ${crunch}"
        diskUsage "/data2" "ssh ${crunch}"
        gitRepVsn "/data/repos/scripts" "ssh ${crunch}"
          toolVsn "gsutil" "ssh ${crunch}"
    done
}

function title {
    local msg=$1
    echo "=== ${msg} ==="
}

function header {
    local msg=$1
    echo -e "\n[${msg}]"
}

function toolVsn {
    local tool_name=$1
    local cmd_prefix=$2
    local version=${NA}
    local location=${NA}
    version=$(${cmd_prefix} "${tool_name}" --version)
    location=$(${cmd_prefix} which "${tool_name}")
    echo "TOOL: ${version} (${location})"
}

function gitRepVsn {
    local repos_dir=$1
    local cmd_prefix=$2
    local commit=${NA}
    local dryrun=${NA}
    commit=$(${cmd_prefix} "cd ${repos_dir}; git log | head -1")
    dryrun=$(${cmd_prefix} "cd ${repos_dir}; git pull --dry-run 2>&1 | wc -l")
    if [[ "${dryrun}" -gt 0 ]]; then
        echo "REPO: ${repos_dir} is OUTDATED (${commit})"
    else
        echo "REPO: ${repos_dir} is at most recent commit"
    fi
}

function diskUsage {
    local mount=$1
    local cmd_prefix=$2
    local available=${NA}
    local percentage_string=${NA}
    local percentage=${NA}
    available=$(${cmd_prefix} df -h "${mount}" | tail -1 | tr -s ' ' | cut -d" " -f 4)
    percentage_string=$(${cmd_prefix} df -h "${mount}" | tail -1 | tr -s ' ' | cut -d" " -f 5)
    percentage=${percentage_string/\%/}
    echo "${percentage_string} used with ${available} space left for mount ${mount}"
    if [[ "${percentage}" -gt "${MAX_DF_PERC}" ]]; then
        warn "Disk usage (${percentage}%) for mount ${mount} higher than ${MAX_DF_PERC}!"
    fi
}

function log {
    local level=$1
    local msg=$2
    echo "[${level}] ${msg}"
}

function warn {
    log "WARN" "$1"
}

main

