#!/usr/bin/env bash

MAX_CHAR=64

function main () {
    echo ""
    grep_ps "[a]ws"
    grep_ps "[g]sutil"
    grep_ps "[r]sync"
    grep_ps "[m]d5sum"
    grep_ps "[b]am2fastq"
    grep_ps "[b]cl2fastq"
    echo ""
}

function grep_ps () {
    local string=$1 && shift
    ps_cmd="ps -ef | grep '${string}' | tr -s ' ' | cut -d' ' -f1,5,8- | cut -c 1-$MAX_CHAR | sort | uniq"
    echo "# Executing ps ($ps_cmd)"
    eval $ps_cmd
}

main
