#!/usr/bin/env bash

chown_dir=$1

function main {
    if [[ -z "${chown_dir}" ]]; then
        print_usage
    fi

    ./chown_directory_contents "${chown_dir}" "${USER}" "users" 
}

print_usage() {
    echo "---"
    echo " Descr: Recursively chown content in \${directory} to $USER:users"
    echo " Usage: $(basename ${0}) \${directory}"
    echo "---"
    exit 1
}

main
