#!/usr/bin/env bash

chownDir=$1

function main {
    if [[ -z "$chownDir" ]]; then
        print_usage
    elif [[ ! -d "$chownDir" ]]; then
        echo "[EXIT] Is not a directory (${chownDir})!"
        print_usage
    fi
    echo "[INFO] Searching content that is not owned by root yet (${chownDir})"
    nonRootCount=$(find ${chownDir} -mindepth 1 -maxdepth 1 \! -user root | wc -l)
    echo "[INFO] Found $nonRootCount to chown in $chownDir"

    if [[ "${nonRootCount}" -gt 0 ]]; then
        echo "[INFO] First 20 records:"
        find ${chownDir} -mindepth 1 -maxdepth 1 \! -user root | head -20
        read -p "[INFO] Press enter to start chown action"
        find ${chownDir} -mindepth 1 -maxdepth 1 \! -user root -exec sudo chown root:root {} +
    fi
}

print_usage(){
  echo "---"
  echo " Descr: Recursively chown non-root content in \${directory} to root:root"
  echo " Usage: $(basename ${0}) \${directory}"
  echo "---"
  exit 1
}

main
