#!/usr/bin/env bash

file=$1 && shift

if [[ -z "${file}" || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename $0) \${nameOfTheFileOnNas}"
    echo "    Eg: $(basename $0) New_SampleSheet.csv"
    echo "---"
    exit 1
fi

nas_dir_path="/volume1/machines/BFX/upload"
nas_file_path="nas:${nas_dir_path}/${file}"

echo "[INFO] Running scp on ${nas_file_path}"
scp "${nas_file_path}" ./
