#!/usr/bin/env bash

source message_functions || exit 1

for i in {2,3}; do
    if [[ "$(hostname)" == "crunch00${i}" ]]; then
      sample_sheets_info=$(check_samplesheets) \
          || die "Could not check samplesheets from crunch00${i} directly"
    elif [[ "$(hostname)" == "datastore" ]]; then
      sample_sheets_info=$(ssh "crunch00${i}" check_samplesheets) \
          || die "Could not check samplesheets info over ssh from crunch00${i}"
    else
      sample_sheets_info=$(ssh "crunch${i}.prod-1" check_samplesheets) \
          || die "Could not check samplesheets info over ssh from crunch00${i}"
    fi
    echo "${sample_sheets_info}" | \
    grep -Po "(X|NO|NS|IS)\d{2}\-.+_.+_.+_.+" | \
    while read -r crunch_info; do
        fc_run_name=$(echo "${crunch_info}" | cut -f1)
        fc_dir_name=$(echo "${crunch_info}" | cut -f2)
        fc_run_date=$(echo "${fc_dir_name}" | cut -d"_" -f1)

        query="flowcells?name=${fc_run_name}"
        response=$(hmf_api_get "${query}")
        gcp_info="GCP=Unknown"
        if [[ $(echo "${response}" | jq length) -eq 1 ]]; then
            gcp_status=$(echo "${response}" | jq -r '.[-1].status')
            gcp_qc=$(echo "${response}" | jq -r '.[-1].undet_rds_p_pass')
            gcp_info="GCP=${gcp_status}(qc=${gcp_qc})"
        fi
        echo -e "${fc_run_date}\t${crunch_info},${gcp_info}"
    done     
done | sort -r -k1 -k2 | cut -f2-
