#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "---"
    echo " Descr: Search SampleSheets for string (perl style grep based matching)"
    echo " Usage: `basename $0` <string> [<string2 <stringn>]"
    echo "        `basename $0` CPCT02020000T"
    echo "        `basename $0` FR12345678"
    echo "        `basename $0` CPCT02021234R CPCT02021234T"
    echo "---"
    exit 1
fi

SEARCH_STRINGS=( "$@" )

for SEARCH in "${SEARCH_STRINGS[@]}"; do
  
  for sheet in $( grep -l $SEARCH /data/samplesheets/*_SampleSheet.csv ); do 
    
    SHEETFILE=$( basename ${sheet} ) 
    SEQRUNDIR=$( echo $SHEETFILE | sed 's#_SampleSheet.csv##g' )
    HMFRUNDIR="/data/sequencer_archive/${SEQRUNDIR}"      
    HMFRUN=$( grep -o -P "X\d{2}\-\d{4}" $sheet ); 

    cat $sheet | grep -P "$SEARCH" | cut -d"," -f 2,3,8 | sort | uniq | while read line; do
      SAMPLEID=$( echo $line | cut -d ',' -f 1 )
      SAMPLENAME=$( echo $line | cut -d ',' -f 2 )
      SUBM=$( echo $line | cut -d ',' -f 3 )
      echo "$SAMPLENAME,$SAMPLEID,$SUBM,$HMFRUN,$HMFRUNDIR"
    done

  done

done | sort

