#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source locate_gcp_files || exit 1

search_remote=FALSE
dir1=$(locate_snpcheck_dir) || die "Could not find local snpcheck dir"
dir2=$(locate_snpcheck_vcf_upload_dir) || die "Could not get snpcheck upload dir"
vcf_gcp_bucket=$(locate_snpcheck_vcfs_at_gcp) || die "Could not get snpcheck vcf location at GCP"
ops_vm_backup_bucket="gs://hmf-ops-data/snpcheck"

print_usage(){
    echo "-----"
    echo " Descr: Searches for SNPcheck VCFs locally."
    echo "   1. $dir1"
    echo "   2. $dir2"
    echo " Usage: $(basename $0) \$search_string"
    echo "        $(basename $0) FR12345678"
    echo "        $(basename $0) -r FR12345678"
    echo " Options:"
    echo "   -r   Also search bucket location for VCFs and LOGs (${vcf_gcp_bucket} and ${ops_vm_backup_bucket})"
    echo "-----"
    exit 1
}

while getopts ':r:' flag; do
    case "$flag" in
        r) search_remote=TRUE && shift;;
        *) print_usage
        exit 1 ;;
    esac
done
search=$1 # eg FR12345678
[[ -n "${search}" ]] || print_usage

echo ""
info "Searching for snpcheck files matching '${search}'"
count1=$(find "${dir1}" -name "*${search}*.vcf" | wc -l)
info "Found ${count1} local VCFs in archive at ops-vm (${dir1})"
find "${dir1}" -name "*${search}*.vcf"
echo ""

count2=$(find "${dir2}" -name "*${search}*.vcf" | wc -l)
info "Found ${count2} local VCFs in sync location at ops-vm (${dir2})"
find "${dir2}" -name "*${search}*.vcf"
echo ""

if [[ "${search_remote}" == "TRUE" ]]; then

    info "Checking remote location for VCFs (${vcf_gcp_bucket})"
    gsutil ls "${vcf_gcp_bucket}/*/*${search}*"
    echo ""

    info "Checking ops VM backup directory (${ops_vm_backup_bucket})"
    gsutil ls "${ops_vm_backup_bucket}**${search}**"
    echo ""

    # since January 2021 logs are no longer written to the snpchecklogs
    #info "Checking remote location for LOGs (gs://hmf-snpcheck/snpchecklogs/)"
    #gsutil ls "gs://hmf-snpcheck/snpchecklogs/*${search}*"
    #echo ""
fi