#!/usr/bin/env bash

source message_functions || exit 1

gcp_bucket='hmf-snpcheck'
gcp_key=$( gcloud secrets versions access "latest" --secret=gcp-hmf-ops-u-hmf-database --project=hmf-secrets )

print_usage(){
    echo "-----"
    echo " Descr: Searches for SNPcheck VCFs in GCP (gs://hmf-snpcheck/snpcheckvcfs/)."
    echo " Usage: $(basename $0) \$search_string"
    echo "        $(basename $0) FR12345678"
    echo "-----"
    exit 1
}

search=$1
[[ -n "${search}" ]] || print_usage


gcloud auth activate-service-account --no-user-output-enabled --key-file "${gcp_key}"

echo ""
#info "Checking remote location for VCFs (gs://${gcp_bucket})"
gsutil ls "gs://hmf-snpcheck/snpcheckvcfs/*/*${search}*"
echo ""

# since January 2021 logs are no longer written to the snpchecklogs
#info "Checking remote location for LOGs (gs://${gcp_bucket})"
#gsutil ls "gs://hmf-snpcheck/snpchecklogs/*${search}*"
#echo ""
