#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

function main() {
    local tool_dir=${1:-/data/tools} && shift
    local alias_file=${1:-~/tool_aliases} && shift

    if [[ ! -d "${tool_dir}" ]]; then
        echo "ERROR: ${tool_dir} is not a directory"
        exit 1
    fi

    local temp_file="${alias_file}.tmp"
    while IFS= read -r -d '' tool_bin; do
        local tool_name
        tool_name=$(basename "${tool_bin}")
        if [[ ${tool_name} == "configure" ]]; then
            echo "ignoring ${tool_bin}"
        else
            echo "alias ${tool_name}='${tool_bin}'" >> "${temp_file}"
        fi
    done < <(find "${tool_dir}" -maxdepth 3 -type f -executable -print0)

    if [[ -s "${temp_file}" ]]; then
        local dups
        dups=$(cut -d= -f1 "${temp_file}" | sort | uniq -d)
        if [[ -n $dups ]]; then
            echo "WARN: duplicate tools found (not replacing ${alias_file}):"
            echo
            echo "$dups"
        else
            mv "${temp_file}" "${alias_file}"
        fi
        rm -f "${temp_file}"
    else
        echo "WARN: no tools found"
    fi
}

main "$@"
