#!/usr/bin/env bash

source message_functions || exit 1

RNA_FASTQ_DIR="/data/data_archive/rna_seq/fastq"

if [[ -z ${1} || $1 == "-h" || $1 == "--help" ]]; then
  echo "---"
  echo " Usage: $(basename $0) \${flowcell_path}"
  echo "---"
  exit 1
fi

flowcell_path=$1

echo "## Start of script $(basename $0) on flowcell path $flowcell_path"

if [[ ! "$flowcell_path" =~ ^\/ ]]; then
    error "Please provide full path to flowcell dir ($flowcell_path)"
fi
if [[ ! -d "$flowcell_path" ]]; then
    error "Provided flowcell dir path does not exist ($flowcell_path)"
fi
if [[ ! -w $RNA_FASTQ_DIR ]]; then
    error "Destination dir is not writeable ($RNA_FASTQ_DIR)"
fi

## Check samples in LIMS: should be skipped if not RNAseq sample
check_bcl2fastq_conversion.pl -run_dir "${flowcell_path}" | grep ^SAMPLE | while read line; do 
    barcode=$(echo "${line}" | cut -f9)
    sample=$(echo "${line}" | cut -f10)
    project=$(echo "${line}" | cut -f11)
    barcode_sample="${barcode}_${sample}"
    lims_sample_json=$(query_lims.pl -rna -type samples -filter "sample_id=${barcode}" -json)
    lims_sample_name=$(echo "$lims_sample_json" | jq -r '.[0].sample_name')
    lims_sample_type=$(echo "$lims_sample_json" | jq -r '.[0].analysis_type')
    if [[ ! "$lims_sample_type" == "RNAanalysis" ]]; then
        warn "Sample is not RNAanalysis but $lims_sample_type ($barcode $lims_sample_name) SKIPPING"
        continue
    fi

    echo "# ---"
    echo "# Checking sample $sample with barcode $barcode"
    find $RNA_FASTQ_DIR -mindepth 1 -maxdepth 1 -name "*${barcode}_*" -printf '# WARNING: Existing DIR found: %p\n'
    old_fq_dir="$flowcell_path/Fastq/${project}/${barcode}"
    new_fq_dir="${RNA_FASTQ_DIR}/${barcode_sample}"
    if [[ ! -d $old_fq_dir ]]; then
        error "Dir does not exist ($old_fq_dir)"
    elif [[ ! -w $old_fq_dir ]]; then
        error "Dir is not writable ($old_fq_dir)"
    elif [[ -e $new_fq_dir && ! -w $new_fq_dir ]]; then
        error "Dir exists but is not writable ($new_fq_dir)"
    elif [[ $sample != "${lims_sample_name}" ]]; then
        error "Name of sample not same in LIMS ($sample vs $lims_sample_name)"
    fi
    echo " mkdir $new_fq_dir"
    echo " echo \"[INFO] Moving fastq from $old_fq_dir to $new_fq_dir\""
    echo " mv ${old_fq_dir}/*.fastq.gz ${new_fq_dir}/"
done
