#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

repo_path=$1
if [[ -z ${repo_path} ]]; then
    die "No repo path provided. $(basename $0) requires a repo name as an argument"
fi

if [[ ! -d "${repo_path}" ]]; then
    die "Dir does not exist (${repo_path})"
fi

info "Change dir (to ${repo_path})"
cd "${repo_path}" || die "Could not switch dir to repo ${repo_path}"

info "Performing pull (in ${repo_path})"
sudo -u ops git pull || die "Pull to ${repo_path} failed"

