#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

repo=$1
[[ -z ${repo} ]] && die "$(basename $0) requires a repository name as an argument" 

if [ ${repo} != "scripts" -a ${repo} != "peach" ] ; then
    die "Only allowed to be used on scripts and peach repos. Other repos are set to a fixed version on purpose."
fi

pull_repo $(locate_repo_dir "${repo}")
