#!/usr/bin/env bash

source message_functions || exit 1

SCRIPT_NAME="$(basename "$0")"

repo_name=$1 && shift

if [[ -z ${repo_name} ]]; then
    die "No repo name provided. ${SCRIPT_NAME} requires a repo name as an argument"
fi

if [[ ${repo_name} != "scripts" ]] && [[ ${repo_name} != "peach" ]]; then
    die "Only allowed to be used on scripts and peach repos. Other repos are set to a fixed version on purpose."
fi

repo_root="/data/repos"
work_path=$(pwd)

if [[ "${USER}" == "root" ]]; then
    die "This script should not be executed as user root"
fi

if [[ "$(hostname)" == "datastore" ]]; then
    repo_root=/data/common/repos
fi

repo_path="${repo_root}/${repo_name}"

if [[ ! -d "${repo_path}" ]]; then
    die "Dir does not exist (${repo_path})"
fi

info "Change dir (to ${repo_path})"
cd "${repo_path}" || die "Could not switch dir to repo ${repo_path}"

info "Performing pull (in ${repo_path})"
git pull

info "Change dir (to ${work_path})"
cd "${work_path}" || die "Could not switch dir back to work path ${work_path}"
