#!/usr/bin/env bash

if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo " Usage: $(basename $0) <path-to-seq-run1> [<path-to-seq-run2 etc>]"
    echo "        $(basename $0) /data1/illumina_data/18*"
    echo " Descr: Get Rsync cmd to sync sequence run dirs to datastore excluding BCL, images, etc."
    echo "-----"
    exit 1
fi

echo "[INFO] Execute to start sync:"
rsync_cmd="rsync -trhP"
rsync_cmd=${rsync_cmd}" --exclude \"*.bcl.gz\""
rsync_cmd=${rsync_cmd}" --exclude \"*.cbcl\""
rsync_cmd=${rsync_cmd}" --exclude \"*Data/Intensities/BaseCalls/L0*\""
rsync_cmd=${rsync_cmd}" --exclude \"*.fastq.gz\""
rsync_cmd=${rsync_cmd}" --exclude \"*Images*\""
rsync_cmd=${rsync_cmd}" --exclude \"*Read*Cycle*.log\""
rsync_cmd=${rsync_cmd}" --exclude \"*RTALogs/*FileCopyLog*.tsv\""
rsync_cmd=${rsync_cmd}" --exclude \"*RTALogs/*GlobalLog*.tsv\""
rsync_cmd=${rsync_cmd}" --stats"
rsync_cmd=${rsync_cmd}" $@"
rsync_cmd=${rsync_cmd}" ds:/data/sequencer_archive/"

echo ${rsync_cmd}

