#!/bin/bash

if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo " Usage: `basename $0` <path-to-seq-run1> [<path-to-seq-run2 etc>]"
    echo "        `basename $0` /data1/illumina_data/17*"
    echo " Descr: Get Rsync cmd to sync sequencerundirs to datastore excluding BCL, images, etc."
    echo "-----"
    exit 1
fi

echo "[INFO] Execute to start sync:"
rsynccmd="nohup rsync -trhP"
rsynccmd=${rsynccmd}" --exclude \"*.bcl.gz\""
rsynccmd=${rsynccmd}" --exclude \"*.cbcl\""
rsynccmd=${rsynccmd}" --exclude \"*Data/Intensities/BaseCalls/L0*\""
rsynccmd=${rsynccmd}" --exclude \"*Undetermined_*fastq.gz\""
rsynccmd=${rsynccmd}" --exclude \"*Thumbnail_Images*\""
rsynccmd=${rsynccmd}" --stats"
rsynccmd=${rsynccmd}" $@"
rsynccmd=${rsynccmd}" ds:/data/sequencer_archive/ > \$RSYNC_LOG &"

echo $rsynccmd

#rsync -trhPn --exclude "*.bcl.gz" --exclude "*Data/Intensities/BaseCalls/L0*" --exclude "*Undetermined_*fastq.gz" --exclude "*Thumbnail_Images*" \
#--stats "${runPaths}" ds:/data/sequencer_archive/
