#!/usr/bin/env bash

if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo " Usage: `basename $0` /data2/processed/<path-to-seq-run> "
    echo " Descr: Get Rsync cmd to sync shallow seq run dirs to datastore excluding bams"
    echo "-----"
    exit 1
fi

currDate=$( date +'%y%m%d' )

echo "[INFO] Execute to start sync:"
rsynccmd=" nohup rsync -ahP"
rsynccmd=${rsynccmd}" --exclude \"*.bam\""
rsynccmd=${rsynccmd}" --stats"
rsynccmd=${rsynccmd}" $@"
rsynccmd=${rsynccmd}" ds:/data/data_archive/shallow_seq_pipelines/"
rsynccmd=${rsynccmd}" > ~/logs/${currDate}_rsync_$@_to_ds"

echo ${rsynccmd}