#!/usr/bin/env bash

currDate=$( date +'%y%m%d' )

echo "[INFO] Execute to start sync:"
rsynccmd=" nohup rsync -ahPn"
rsynccmd=${rsynccmd}" --exclude \"*.bam\""
rsynccmd=${rsynccmd}" --stats"
rsynccmd=${rsynccmd}" $@"
rsynccmd=${rsynccmd}" ds:/data/data_archive/shallow_seq_pipelines/"
rsynccmd=${rsynccmd}" > ~/logs/${currDate}_rsync_$@_to_ds"

echo ${rsynccmd}