#!/usr/bin/env bash

source message_functions || exit 1

local_sheets_dir=/data/samplesheets
crunch_seq_runs_dir=/data1/illumina_data

for i in {2,3}; do
    crunch_name="crunch00${i}"
    info "Checking ${crunch_name} for samplesheets"

    ssh ${crunch_name} find ${crunch_seq_runs_dir} -type f -mindepth 2 -maxdepth 2 -name "SampleSheet.csv" |
    while read sheet_path; do
        run_path=$(dirname ${sheet_path})
        run_name=$(basename ${run_path})
        dest_path="${local_sheets_dir}/${run_name}_SampleSheet.csv"
        info "  Executing rsync for ${run_name}"
        rsync_log_line_count=$(rsync -rtv ${crunch_name}:${sheet_path} ${dest_path} | wc -l)
        if [[ "${rsync_log_line_count}" -gt 4 ]]; then
            info "   Synced to ${dest_path}"
        fi
    done
done
