#!/usr/bin/env bash

source gcp_functions || exit 1
source message_functions || exit 1

switch_to_hmf_ops_service_account || die "Could not switch to hmf ops"

for i in {2,3}; do
    crunch_name="crunch${i}.prod-1"
    info "Checking ${crunch_name} for samplesheets"
    ssh ${crunch_name} sync_samplesheets_to_bucket
done


