#!/usr/bin/env bash

source message_functions || exit 1
command -v execute_sql_on_prod || die "Command not found (execute_sql_on_prod)"

YYMMDD=$(date '+%y%m%d')

nas_loc="nas:/volume1/web/overviews/rnaseq/"

out_dir="/tmp"
task="rna_overview"
prefix="${out_dir}/${task}"
sql_out="${prefix}_sql.tsv"
api_out="${prefix}_api.json"
sql_samples_tsv="${prefix}_samples_sql.tsv"
api_samples_tsv="${prefix}_samples_api.tsv"
out_sum="${prefix}_summary.txt"
err_log="${prefix}_error.log"

if [[ ! -d "${out_dir}" ]]; then error "OUTPUT DIR does not exist (${out_dir})"; fi
if [[ ! -w "${out_dir}" ]]; then error "OUTPUT DIR not writable (${out_dir})"; fi

info "Starting with ${task} creation ($YYMMDD)" | tee ${out_sum}
info "Writing err log to ${err_log}" | tee -a ${out_sum}

execute_sql_on_prod "SELECT sampleId FROM rnaStatistics;" > "${sql_out}"
hmf_api_get "samples?type=tumor-rna" > "${api_out}"

cut -f3 "${sql_out}" | grep -v sampleId | sort | uniq > "${sql_samples_tsv}"
jq -r '.[] | [.name,.status] | @tsv' "${api_out}" | sort | uniq > "${api_samples_tsv}"

sample_count_sql=$(wc -l "${sql_samples_tsv}")
sample_count_api=$(wc -l "${api_samples_tsv}")

info "Number of samples from SQL: ${sample_count_sql}" | tee -a ${out_sum}
info "Number of samples from API: ${sample_count_api}" | tee -a ${out_sum}

info "Syncing results to NAS (${nas_loc})"
rsync "${sql_out}" "${api_out}"  ${nas_loc}/

info "Finished with ${task}" | tee -a ${out_sum}
