#!/usr/bin/env bash

source message_functions || exit 1
command -v execute_sql_on_prod >/dev/null 2>&1 || die "Command not found (execute_sql_on_prod)"

YYMMDD=$(date '+%y%m%d')

nas_loc="/volume1/web/overviews/rnaseq"

task="rna_overview_${YYMMDD}"
tmp_dir="/tmp/${task}"
sql_tsv="${tmp_dir}/sql.txt"
api_runs_jsn="${tmp_dir}/api_runs.json"
api_runs_tsv="${tmp_dir}/api_runs.txt"
api_samples_jsn="${tmp_dir}/api_samples.json"
api_samples_tsv="${tmp_dir}/api_samples.txt"
sum_out="${tmp_dir}/summary.txt"

[[ -d "${tmp_dir}" ]] || mkdir "${tmp_dir}"
[[ -d "${tmp_dir}" ]] || die "OUTPUT DIR does not exist (${tmp_dir})"
[[ -w "${tmp_dir}" ]] || die "OUTPUT DIR not writable (${tmp_dir})"

info "Starting with ${task} creation ($YYMMDD)" | tee "${sum_out}"
info "Writing output to directory ${tmp_dir}" | tee "${sum_out}"

execute_sql_on_prod "SELECT sampleId AS '#sampleId',readLength,totalFragments FROM rnaStatistics" > "${sql_tsv}"
hmf_api_get "samples?type=tumor-rna" > "${api_samples_jsn}"
hmf_api_get "runs?ini=Rna.ini" > "${api_runs_jsn}"

printf "#%s\t%s\t%s\t%s\t%s\n" "name" "barcode" "status" "yield" "q30" > "${api_samples_tsv}"
jq -r '.[] | [.name,.barcode,.status,.yld,.q30,.createTime] | @tsv' "${api_samples_jsn}" | sort | uniq >> "${api_samples_tsv}"

printf "#%s\t%s\t%s\t%s\t%s\n" "setname" "tumor_sample" "tumor_barcode" "cohort" "date" > "${api_runs_tsv}"
jq -r '.[] | [.set.name, .set.tumor_sample, .set.tumor_isolation_barcode, (.set.name | split("_")[1]), (.set.createTime | split("T")[0]) ] | @tsv' api_runs_jsn.json | sort | uniq | grep ^2 > api_runs_jsn.tsv
count_sql_all=$(grep -vc ^# "${sql_tsv}")
count_api_all=$(grep -vc ^# "${api_samples_tsv}")
count_api_rdy=$(grep -v ^# "${api_samples_tsv}" | grep -cP "Ready|Unregistered")
count_api_ins=$(grep -v ^# "${api_samples_tsv}" | grep -cPv "Ready|Unregistered")
count_api_val_runs=$(grep -v ^# "${api_runs_tsv}" | grep -cP "Validated")
sql_api_diff=$((count_api_all - count_sql_all))

info "Number of Validated runs from API: ${count_api_val_runs}" | tee -a "${sum_out}"
info "Number of samples from API: ${count_api_all}" | tee -a "${sum_out}"
info "  Of which ready/unregistered: ${count_api_rdy}" | tee -a "${sum_out}"
info "  Of which insufficient: ${count_api_ins}" | tee -a "${sum_out}"
info "Number of samples from SQL: ${count_sql_all}" | tee -a "${sum_out}"
info "Difference between API and SQL: ${sql_api_diff}" | tee -a "${sum_out}"

info "Finished with ${task}" | tee -a "${sum_out}"

info "Syncing results to NAS (${nas_loc})"
sync_dir_to_nas "${tmp_dir}" "${nas_loc}/"