#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

SCRIPT_NAME="$(basename "$0")"

main() {
  info "Started ${SCRIPT_NAME}"

  # Parse args
  local key
  local peach_repo_base_dir
  local venv_dir
  while [[ $# -gt 0 ]]
  do
  key="$1" && shift
  case $key in
      -r|--repodir)
      peach_repo_base_dir="$1" && shift  # Optional argument
      ;;
      -v|--venv)
      venv_dir="$1" && shift  # Optional argument
      ;;
      *)    # Unknown option
      OTHER_OPTIONS+=("$key") # Save it in an array for later
      ;;
  esac
  done

  # Default values for arguments
  if [[ -z ${venv_dir} ]]; then
    venv_dir=$(locate_peach_venv_dir) || die "Could not get default venv dir"
  fi
  if [[ -z ${peach_repo_base_dir} ]]; then
    peach_repo_base_dir=$(locate_repo_dir "peach") || die "Could not get default peach repo base dir"
  fi

  # Sanity checks
  [[ "${#OTHER_OPTIONS[@]}" -eq 0 ]] || die "Unrecognized options! : ${OTHER_OPTIONS[*]}"
  [[ -d ${peach_repo_base_dir} ]] || die "peach_repo_base_dir should be a dir: ${peach_repo_base_dir}."
  [[ -d ${venv_dir} ]] || die "venv_dir should be a dir: ${venv_dir}."

  info "Activate PEACH venv"
  source "${venv_dir}/bin/activate" || die "Could not activate PEACH venv"

  # Add paths to environment variables
  export PYTHONPATH="${PYTHONPATH}:${peach_repo_base_dir}/src/"
  export MYPYPATH="${MYPYPATH}:${peach_repo_base_dir}/src/"

  "${peach_repo_base_dir}/test_peach"

  info "Finished ${SCRIPT_NAME}"
}

main "$@"