#!/usr/bin/env bash

# Replace "test" with the actualDR number in format "xxx" (eg, "102" for DR-102)
# Do note that this only works for initial DR handouts. Otherwise you need to manually update the request_name.
dr_id="xxx"

dr_name="DR-${dr_id}"
request_name="DR-${dr_id}"
patient_selection_sql="/data/common/repos/scripts/datarequest/selection/DR${dr_id}.sql"

include_somatics=0
include_germline=0
include_tumor_bam_jsons=0
include_ref_bam_jsons=0
include_rna=0
build_rna_tar=0
include_tumor_clinical_data=0
include_patient_clinical_data=0
include_treatment_response_clinical_data=0
include_pre_treatment_clinical_data=0
include_rano_measurement_by_patient=0
include_tumor_markers_by_patient=0

compose_datarequest ${dr_name} ${request_name} ${patient_selection_sql} \
    ${include_somatics} ${include_germline} ${include_tumor_bam_jsons} ${include_ref_bam_jsons} ${include_rna} ${build_rna_tar} \
    ${include_tumor_clinical_data} ${include_patient_clinical_data} ${include_treatment_response_clinical_data} \
    ${include_pre_treatment_clinical_data} ${include_rano_measurement_by_patient} ${include_tumor_markers_by_patient}