#!/usr/bin/env bash

dr_name="DR-test"
request_name="DR-test1"
patient_selection_sql="/data/data_archive/datarequests/procedure/patient_selection_sql/test.sql"

include_somatics=0
include_germline=0
include_tumor_bam_jsons=0
include_ref_bam_jsons=0
include_rna=0
include_tumor_clinical_data=0
include_patient_clinical_data=0
include_treatment_response_clinical_data=0
include_pre_treatment_clinical_data=0
include_rano_measurement_by_patient=0

compose_datarequest ${dr_name} ${request_name} ${patient_selection_sql} \
    ${include_somatics} ${include_germline} ${include_tumor_bam_jsons} ${include_ref_bam_jsons} ${include_rna} \
    ${include_tumor_clinical_data} ${include_patient_clinical_data} ${include_treatment_response_clinical_data} \
    ${include_pre_treatment_clinical_data} ${include_rano_measurement_by_patient}