#!/usr/bin/env bash

load_run_info_for_set() {
    local set=$1
    local run_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic.ini\|CPCT.ini" | grep "Validated\|SnpCheck\|Failed" `
    echo ${run_info}
}

load_rerun_v3_info_for_set() {
    set=$1
    # KODU: The v3 rerun ini was called 'Somatic_Rerun.bam" so below will always get v3 reruns
    rerun_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic_Rerun_bam.ini" | grep "Validated" `
    if [ -z "${rerun_info}" ]; then
        run_info=$(load_run_info_for_set ${set})
        run_is_v3_or_v4=`echo ${run_info} | cut -d ' ' -f8 | grep "v4\|v3"`
        if [ -z "run_is_v3_or_v4" ]; then
            rerun_info=""
        else
            rerun_info=${run_info}
        fi
    fi
    echo ${rerun_info}
}

load_rerun_v4_info_for_set() {
    set=$1
    # Allow for failure of v4 rerun since v4 rerun runs the health checks.
    rerun_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic_Rerun_v4.ini" | grep "Validated\|Failed" `
    if [ -z "${rerun_info}" ]; then
        run_info=$(load_run_info_for_set ${set})
        run_is_v4=`echo ${run_info} | cut -d ' ' -f8 | grep "v4"`
        if [ -z "run_is_v4" ]; then
            rerun_info=""
        else
            rerun_info=${run_info}
        fi
    fi
    echo ${rerun_info}
}