#!/usr/bin/env bash

source api_functions

set_name=$1

if [ -z "${set_name}" ]; then
    echo "[ERROR] Provide a set name"
    exit 1
fi

echo "[INFO] Testing SBP API functions on ${set_name}"
echo "[INFO] Run Info = $(load_run_info_for_set ${set_name})"
echo "[INFO] Rerun V3 Info = $(load_rerun_v3_info_for_set ${set_name})"
echo "[INFO] Rerun V4 Info = $(load_rerun_v4_info_for_set ${set_name})"
echo "[INFO] Tumor Sample Name = $(load_tumor_sample_name_for_set ${set_name})"
echo "[INFO] Ref Sample Name = $(load_ref_sample_name_for_set ${set_name})"
echo "[INFO] Tumor BAM = $(locate_tumor_bam_for_set_in_bucket ${set_name})"
echo "[INFO] Ref BAM = $(locate_ref_bam_for_set_in_bucket ${set_name})"
