#!/usr/bin/env bash

do_cleanup_destination=$1

if [ ${do_cleanup_destination} == "--cleanup_destination" ]; then
    echo "[INFO] Destination will be cleaned up as part of the archive job!"
    delete_flag="-c"
fi

echo "[INFO] Archiving RNA Data"
do_archive_directory_to_sbp -l "/data/data_archive/rna_seq" -d "rna_seq" ${delete_flag}

echo "[INFO] Archiving Sequencer Archive"
do_archive_directory_to_sbp -l "/data/sequencer_archive" -d "sequencer_archive" ${delete_flag}

echo "[INFO] Archiving Patient Reports"
do_archive_directory_to_sbp -l "/data/cpct/final_reports" -d "patient_reports/final" ${delete_flag}
do_archive_directory_to_sbp -l "/data/cpct/old_cpct_reports" -d "patient_reports/old" ${delete_flag}
do_archive_directory_to_sbp -l "/data/core/final_reports" -d "patient_reports/core" ${delete_flag}

#echo "[INFO] Archiving Data Requests"
#do_archive_directory_to_sbp -l "/data/data_archive/datarequests" -d "data_requests" ${delete_flag}

echo "[INFO] Archiving Submissions"
do_archive_directory_to_sbp -l "/data/submissions" -d "submissions" ${delete_flag}

echo "[INFO] Archiving Shallow Seq Pipelines"
do_archive_directory_to_sbp -l "/data/data_archive/shallow_seq_pipelines" -d "shallow_seq_pipelines" ${delete_flag}