#!/usr/bin/env bash

local_path='/data/cpct'
remote_path='s3://hmf_archive/patientreports'
aws_profile='hmf_archive'

sbp s3 sync "${local_path}/final_reports/" "${remote_path}/final/" \
    --delete \
    --profile ${aws_profile} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL}

sbp s3 sync "${local_path}/old_cpct_reports/" "${remote_path}/old/" \
    --delete \
    --profile ${aws_profile} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL}