#!/bin/bash

local_path='/data/schuberg/snpcheckvcfupload'
remote_path='s3://hmf_archive/snpcheckvcfs'
aws_profile='hmf_archive'

sbp s3 sync ${local_path} ${remote_path} \
    --delete \
    --profile ${aws_profile} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL}