#!/usr/bin/env bash

YYMMDD=$(date +'%y%m%d')
archive_path="/data/data_archive/shallow_seq_pipelines"

## query and store
echo "## ShallowSeq Check (${YYMMDD})"
query_sbp_api -type runs -filter 'ini=ShallowSeq.ini' -json | jq -r '.[] | "\(.name) \(.status)"' | while read line; do 
    run_name=$(echo "${line}" | cut -d" " -f1)
    run_status=$(echo "${line}" | cut -d" " -f2)

    if [[ "${run_name}" =~ "190314-testR" ]]; then continue
    elif [[ "${run_name}" =~ "_HMFregVAL_" ]]; then continue
    elif [[ -d "${archive_path}/${run_name}" ]]; then continue
    elif [[ "${run_status}" =~ ^(Waiting|Pending|Processing)$ ]]; then echo "## PROCESSING: ${run_name} (status=${run_status})"
    elif [[ "${run_status}" =~ Failed ]]; then echo "## FAILED: ${run_name} (status=${run_status})"
    else echo " process_shallow_run -s ${run_name} # (status=${run_status})"
    fi
done | sort
