#!/bin/bash

RUN_NAME=$1

sbp_new s3 sync /data/schuberg/archivesymlinks/${RUN_NAME} s3://${ARCHIVE_BUCKET}/${RUN_NAME}/ --profile ${ARCHIVE_PROFILE} --grants read=id=${HMF_DOWNLOAD_CANONICAL_NEW},id=${SBP_PORTAL_CANONICAL_NEW} readacl=id=${HMF_DOWNLOAD_CANONICAL_NEW}
