#!/usr/bin/env bash

do_cleanup_destination=false;

usage() {
    echo "---"
    echo "Usage: `basename $0` -l <local_path> -d <destination> [-c]" 1>&2;
    echo "       `basename $0` -l /data/sequencer_archive -d sequencer_archive" 1>&2;
    echo "---"
    exit 1
}

while getopts ":l:d:c" o; do
    case "${o}" in
        l)
            local_path=${OPTARG} || usage
            ;;
        d)
            destination=${OPTARG} || usage
            ;;
        c)
            do_cleanup_destination=true || usage
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${local_path}" || -z "${destination}" ]]; then
    usage
fi

if [ ${do_cleanup_destination} = true ]; then
    potential_delete_command='--delete'
fi

bucket='hmf_archive'
aws_profile='hmf_archive'

sbp s3 sync ${local_path} s3://${bucket}/${destination} \
    --profile ${aws_profile} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL} \
    --no-follow-symlinks \
    ${potential_delete_command}