#!/usr/bin/env bash

do_cleanup_destination=false;

usage() {
    echo "---"
    echo "Usage: do_archive_directory_to_sbp -l <localpath> -d <destination> [-c]" 1>&2;
    echo "       do_archive_directory_to_sbp -l /data/sequencer_archive/ -d sequencer_archive" 1>&2;
    echo "---"
    exit 1
}

while getopts ":l:d:c" o; do
    case "${o}" in
        l)
            localpath=${OPTARG} || usage
            ;;
        d)
            destination=${OPTARG} || usage
            ;;
        c)
            do_cleanup_destination=true || usage
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${localpath}" || -z "${destination}" ]]; then
    usage
fi

if [ ${do_cleanup_destination} = true ]; then
    potential_delete_command='--delete'
fi

bucket='hmf_archive'
aws_profile='hmf_archive'

echo ${do_cleanup_destination}
echo ${localpath}
echo ${destination}
echo ${potential_delete_command}

sbp s3 sync ${localpath} s3://${bucket}/${destination} \
    --profile ${aws_profile} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL} \
    ${potential_delete_command}