#!/bin/bash

RUN_NAME=$1

sbp_old s3 sync /data/schuberg/archivesymlinks/${RUN_NAME} s3://${ARCHIVE_BUCKET}/${RUN_NAME}/ --profile ${ARCHIVE_PROFILE} --grants read=id=${HMF_DOWNLOAD_CANONICAL_OLD},id=${SBP_PORTAL_CANONICAL_OLD} readacl=id=${HMF_DOWNLOAD_CANONICAL_OLD}
