#!/usr/bin/env bash

source sbp_api_functions

usage() {
    echo "---"
    echo "Usage: $(basename $0) -s <set> -p <path>" 1>&2;
    echo "       $(basename $0) -s 170101_HMFregCPCT_etc -p /data/schuberg/cpct_drup_downloads" 1>&2;
    echo "---"
    exit 1
}

while getopts ":s:p:" o; do
    case "${o}" in
        s)
            set=${OPTARG} || usage
            ;;
        p)
            localpath=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${set}" || -z "${localpath}" ]]; then
    usage
fi

run_info=$(load_run_info_for_set ${set})
if [ -z "${run_info}" ]; then
    echo "[ERROR] No run info found for set ${set}. Exiting"
    exit 1
fi

rerun_v3_info=$(load_rerun_v3_info_for_set ${set})
if [ -z "${rerun_v3_info}" ]; then
    echo "[ERROR] No v3 rerun found for set ${set}. Exiting."
    exit 1
fi

rerun_v4_info=$(load_rerun_v4_info_for_set ${set})
if [ -z "${rerun_v4_info}" ]; then
    echo "[ERROR] No v4 rerun found for set ${set}. Exiting."
    exit 1
fi

run_bucket=$(extract_bucket_from_run_info "${run_info}")
run_is_v5=$(echo ${run_info} | cut -d ' ' -f8 | grep "v5")

if [ ! -z "${run_is_v5}" ]; then
    echo "[INFO] Downloading v5 run ${set} from ${run_bucket} to ${localpath}"
    sbp s3 sync s3://${run_bucket}/${set}/ ${localpath}/${set}/ \
        --exclude "*.bam" \
        --profile download
else
    echo "[INFO] Downloading pre-v5 run ${set} from ${run_bucket} to ${localpath}"
    v3_rerun_bucket=$(echo ${rerun_v3_info} | cut -d ' ' -f5)
    v4_rerun_bucket=$(echo ${rerun_v4_info} | cut -d ' ' -f5)

    sbp s3 sync s3://${run_bucket}/${set}/ ${localpath}/${set}/ \
        --exclude "*" \
        --include "*snpcheck*" \
        --include "*mapping*flagstat*" \
        --include "settings.config" \
        --profile download

    sbp s3 sync s3://${v3_rerun_bucket}/${set}/ ${localpath}/${set}/ \
        --exclude "*" \
        --include "*mapping*flagstat*" \
        --include "*recal_data*" \
        --include "*damageEstimate*" \
        --profile download

    sbp s3 sync s3://${v4_rerun_bucket}/${set}/ ${localpath}/${set}/ \
        --exclude "*" \
        --include "*annotated.vcf.gz*" \
        --include "*QCStats*" \
        --include "*amber*" \
        --include "*cobalt*" \
        --include "*purple*" \
        --include "*somaticVariants*post_processed*" \
        --include "*somaticVariants*strelka*" \
        --include "*structuralVariants*gridss*gridss.vcf.gz*" \
        --include "*structuralVariants*gridss*assembly.bam.gridss.working*" \
        --include "*metadata*" \
        --include "*logs*submitlog*" \
        --include "*HealthCheck.out*" \
        --include "*logs*PipelineCheck.log*" \
        --include "*logs*Pipeline.success" \
        --include "*logs*unhandled_job_errors" \
        --profile download
fi