#!/usr/bin/env bash

script=$( basename $0 )

usage() {
    echo "---"
    echo "Usage: $script -s <set> -p <path>" 1>&2;
    echo "       $script -s 170101_HMFregCPCT_etc -p /data/schuberg/cpct_drup_downloads" 1>&2;
    echo "---"
    exit 1
}

while getopts ":s:p:" o; do
    case "${o}" in
        s)
            set=${OPTARG} || usage
            ;;
        p)
            localpath=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${set}" || -z "${localpath}" ]]; then
    usage
fi

run_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic.ini\|CPCT.ini" | grep "Validated" `
if [ -z "$run_info" ]; then
    # KODU: For new sets it can happen that snpcheck cannot be performed @ SBP.
    run_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic.ini\|CPCT.ini" | grep "SnpCheck"`
    if [ -z "$run_info" ]; then
        echo "[WARN] No validated or snpcheck runs found with a Somatic/CPCT .ini file for set ${set}."
        exit 1
    else
        echo "[INFO] No validated set found for ${set}. Using set with SnpCheck status instead."
    fi
fi

rerun_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic_Rerun_bam.ini" | grep "Validated" `
if [ -z "$rerun_info" ]; then
    run_is_v3=`echo ${run_info} | cut -d ' ' -f8 | grep "v3"`
    if [ -z "run_is_v3" ]; then
        echo "[WARN] No validated rerun found while original run is not v3. Exiting."
        exit 1
     else
        rerun_info=${run_info}
     fi
fi

run_bucket=`echo ${run_info} | cut -d ' ' -f5`
rerun_bucket=`echo ${rerun_info} | cut -d ' ' -f5`