#!/usr/bin/env bash

#!/bin/bash

source api_functions

script=$( basename $0 )

usage() {
    echo "---"
    echo "Usage: $script -s <set>" 1>&2;
    echo "       $script -s 170101_HMFregCPCT_etc " 1>&2;
    echo "---"
    exit 1
}

while getopts ":s:" o; do
    case "${o}" in
        s)
            set=${OPTARG} || usage
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${set}" ]]; then
    usage
fi

localpath=/data/schuberg/reruns_v4

rerun_info=$(load_rerun_v4_info_for_set ${set})
if [ -z "$rerun_info" ]; then
    echo "[WARN] No v4 rerun found for set ${set}. Exiting."
    exit 1
fi

rerun_bucket=`echo ${rerun_info} | cut -d ' ' -f5`

sbp s3 sync s3://${rerun_bucket}/${set}/ ${localpath}/${set}/ --profile download