#!/bin/bash

source api_functions

script=$( basename $0 )

usage() {
    echo "---"
    echo "Usage: $script -s <set> " 1>&2;
    echo "       $script -s 170101_HMFregCPCT_etc" 1>&2;
    echo "---"
    exit 1
}

while getopts ":s:" o; do
    case "${o}" in
        s)
            set=${OPTARG} || usage
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${set}" ]]; then
    usage
fi

run_info=$(load_run_info_for_set ${set})
if [ -z "$run_info" ]; then
    echo "[WARN] No run info found for set ${set}. Exiting"
    exit 1
fi

run_bucket=`echo ${run_info} | cut -d ' ' -f5`

s3path="s3://${run_bucket}/${set}"
dspath="/data/schuberg/bam_downloads/${set}"

echo "[INFO] Getting REF bam from ${s3path}"
sbp s3 sync ${s3path}/ ${dspath}/ \
    --exclude "*" \
    --include "*/mapping/*R_dedup.realigned.bam*" \
    --profile download
