#!/usr/bin/env bash

usage() {
    echo "---"
    echo "Usage: $(basename $0) -s <setname> -b <bucket>" 1>&2;
    echo "       $(basename $0) -s 170101_HMFregCPCT_etc -b hmf-output-2017-52" 1>&2;
    echo "---"
    exit 1
}

while getopts ":s:b:p:" o; do
    case "${o}" in
        s)
            setname=${OPTARG} || usage
            ;;
        b)
            bucket=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${setname}" || -z "${bucket}" ]]; then
    usage
fi

localpath="/data/schuberg/qc_fail_runs"

sbp s3 sync s3://${bucket}/${setname}/ ${localpath}/${setname}/ \
    --exclude "*.bam" \
	  --profile download
