#!/bin/bash

script=$( basename $0 )

usage() {
    echo "---"
    echo "Usage: $script -s <set> -l <localpath>" 1>&2;
    echo "       $script -s 170101_HMFregCPCT_etc  -l /data/schuberg/fromweekly" 1>&2;
    echo "---"
    exit 1
}

while getopts ":s:l:" o; do
    case "${o}" in
        s)
            set=${OPTARG} || usage
            ;;
        l)
            localpath=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

if [[ -z "${set}" || -z "${localpath}" ]]; then
    usage
fi

run_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic.ini\|CPCT.ini" | grep "Validated" | grep "v3"`
rerun_info=`query_sbp_api -type runs | grep -P "${set}" | grep "Somatic_Rerun_Bam.ini" | grep "Validated" | grep "v3"`

if [ -z "$run_info" ];
  then
    echo "No runs found with a Somatic/CPCT .ini file for set ${set}. Exiting."
    exit 1
fi

run_bucket=`echo ${run_info} | cut -d ' ' -f5`
rerun_bucket=`echo ${rerun_info} | cut -d ' ' -f5`


exit

sbp s3 sync s3://${run_bucket}/${set}/ ${localpath}/${set}/ \
	--exclude "*" \
	--include "*annotated.vcf*" \
	--include "*filtered*GoNLv5.vcf*" \
	--include "*snpcheck*" \
	--include "*.kinship" \
	--include "QCStats*" \
	--include "*mapping*flagstat*" \
	--include "*HealthCheck.out*" \
	--include "settings.config" \
	--profile download

sbp s3 sync s3://${rerun_bucket}/${set}/ ${localpath}/${set}/ \
	--exclude "*" \
	--include "*mapping*flagstat*" \
	--include "*recal_data*" \
	--include "*damageEstimate*" \
	--include "*amber*" \
	--include "*cobalt*" \
	--include "*purple*" \
	--include "*somaticVariants*post_processed*" \
	--include "*somaticVariants*strelka*" \
	--include "*structuralVariants*bpi*bpi_stats*" \
	--include "*structuralVariants*bpi*somaticSV*" \
	--include "*structuralVariants*bpi*sliced.bam*" \
	--include "*structuralVariants*manta*somaticSV.vcf*" \
	--include "*metadata*" \
	--include "*logs*submitlog*" \
	--include "*logs*PipelineCheck.log*" \
	--include "*logs*perform_pipeline_qc*" \
	--profile download