#!/usr/bin/env bash

if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename $0) \${sampleName}"
    echo "    Eg: $(basename $0) CPCT02010001T"
    echo "        (searches for \${sampleName}_*.fastq.gz"
    echo "---"
    exit 1
fi

sample_name=$1

out_name="${sample_name}_fastq"
out_path="/data/schuberg/tmp/${out_name}"
profile="hmf_fastq"
bucket="hmf-fastq-storage"

cmd="sbp s3 sync --dryrun s3://${bucket}/ ${out_path}/ --exclude \"*\" --include ${sample_name}_*.fastq.gz --profile ${profile}"

echo "[INFO] Run the following to list all to be synced files:"
echo "${cmd}"
