#!/usr/bin/env bash

source metadata_functions

set=$1

if [ -z "$set" ]; then
    echo "[ERROR] No set provided to process_finished_run. Exiting"
    exit 1
fi

download_path=/data/schuberg/downloaded_runs
echo "[INFO] Downloading set ${set} to ${download_path}"
download_set -s ${set} -p ${download_path}

if [ ! -f ${download_path}/${set}/metadata.json ]; then
    echo "[ERROR] No metadata file found. Probably something wrong with the downloading of the run. Exiting"
    exit 1;
fi

processed_path=/data/schuberg/processed_runs
echo "[INFO] Copying set ${set} to processed path ${processed_path}"
set_path=${processed_path}/${set}
cp -r ${download_path}/${set} ${set_path}

tumor_sample=$(load_tumor_sample_from_metadata ${set})

if [[ ${tumor_sample} =~ ^CORE ]]; then
    echo "[INFO] Data not loaded into database for ${set}. It is a CORE sample!"
else
    echo "[INFO] Loading data into database for ${set}"
    load_run_into_prod_db ${set_path}
fi