#!/bin/bash

bucket=$1
set=$2
path=/data/schuberg/fromweekly
download_set_partially_from_bucket -b ${bucket} -s ${set} -l ${path}
do_run_bpi_prod ${path}/${set}
do_run_cobalt ${path}/${set}
do_run_purple_prod ${path}/${set}
do_load_somatic_variants_prod ${path}/${set}