#!/bin/bash

set=$1

if [ -z "$set" ]; then
    echo "[ERROR] No set provided to process_finished_run. Exiting"
    exit 1
fi

download_path=/data/schuberg/downloaded_runs
echo "[INFO] Downloading set ${set} to ${download_path}"
download_set -s ${set} -p ${download_path}

processed_path=/data/schuberg/processed_runs
echo "[INFO] Copying set ${set} to processed path ${processed_path}"
set_path=${processed_path}/${set}
cp -r ${download_path}/${set} ${set_path}

# TODO Can be removed once pre v5.2 pipelines have been processed and reported.
echo "[INFO] Running purple on ${set}"
do_run_purple_no_db ${set_path}

echo "[INFO] Running viral annotation ${set}"
do_run_gridss_viral_annotate_prod ${set_path}

echo "[INFO] Running repeatmasker annotation ${set}"
do_run_gridss_repeatmasker_insertion_annotate_prod ${set_path}

echo "[INFO] Symlinking germline VCF for bachelor"
germline_vcf_path=$( find "${set_path}" -name "*.germline.vcf.gz" )
symlink_path="${set_path}/symlink_for_bachelor.annotated.vcf.gz"
ln -rs "${germline_vcf_path}" "${symlink_path}"
ln -rs "${germline_vcf_path}.tbi" "${symlink_path}.tbi"

echo "[INFO] Running bachelor for ${set}"
run_bachelor_prod ${set_path}

echo "[INFO] Running CHORD for ${set}"
run_chord_prod ${set_path}

echo "[INFO] Loading amber into database for ${set}"
do_load_amber_data_prod ${set_path}

echo "[INFO] Loading purple into database for ${set}"
do_load_purple_data_prod ${set_path}

echo "[INFO] Loading somatics into database for ${set}"
do_load_somatic_variants_prod ${set_path}

echo "[INFO] Loading structural variants into database for ${set}"
do_run_load_sv_prod ${set_path}

echo "[INFO] Running linx for ${set}"
do_run_linx_prod ${set_path}

echo "[INFO] Creating symlinks for metric files for ${set}"
create_symlink_metric_file ${set_path}

echo "[INFO] Loading metrics into database for ${set}"
do_load_metrics_data_prod ${set_path}

echo "[INFO} Loading chord into database for ${set}"
do_load_chord_data_prod ${set_path}
