#!/bin/bash

set=$1

if [ -z "$set" ]; then
    echo "[ERROR] No set provided to process_finished_run. Exiting"
    exit 1
fi

download_path=/data/schuberg/downloaded_runs
echo "[INFO] Downloading set ${set} to ${download_path}"
download_set -s ${set} -p ${download_path}

processed_path=/data/schuberg/processed_runs
echo "[INFO] Copying set ${set} to processed path ${processed_path}"
set_path=${processed_path}/${set}
cp -r ${download_path}/${set} ${set_path}

echo "[INFO] Running gridss somatic filtering for ${set}"
do_run_gridss_somatic_filter ${set_path}

echo "[INFO] Running gridss assembly alignment backport for ${set}"
do_run_gridss_2_1_0_breakpoint_position_backport ${set_path} /data/common/tools/gridss_v2.2.2/gridss.jar

echo "[INFO] Slicing and downloading bam hotspots for ${set}"
do_download_hotspot_bams ${set_path}

echo "[INFO] Running sage for ${set}"
do_run_hotspot_caller ${set_path}

echo "[INFO] Running latest purple for ${set}"
do_run_purple_no_db ${set_path}

echo "[INFO] Running viral annotation ${set}"
do_run_gridss_viral_annotate_prod ${set_path}

echo "[INFO] Running repeatmasker annotation ${set}"
do_run_gridss_repeatmasker_insertion_annotate_prod ${set_path}

echo "[INFO] Running bachelor for ${set}"
bachelor_prod ${set_path}

echo "[INFO] Running CHORD for ${set}"
run_chord_prod ${set_path}

echo "[INFO] Loading purple into database for ${set}"
do_load_purple_data_prod ${set_path}

echo "[INFO] Loading somatics into database for ${set}"
do_load_somatic_variants_prod ${set_path}

echo "[INFO] Loading structural variants into database for ${set}"
do_run_sv_loader_prod ${set_path}

echo "[INFO] Loading metrics into database for ${set}"
do_load_metrics_data_prod ${set_path}

echo "[INFO} Loading chord into database for ${set}"
do_load_chord_data_prod ${set_path}