#!/bin/bash

bucket=$1
set=$2
path=/data/schuberg/fromweekly
download_set_partially_from_bucket -b ${bucket} -s ${set} -l ${path}
# KODU: Purple script also triggers reruns of BPI, amber and cobalt
do_run_purple_prod ${path}/${set}
do_load_somatic_variants_prod ${path}/${set}