#!/bin/bash

LOCAL_PATH='/data/sequencer_archive/'
REMOTE_PATH='s3://hmf_archive/sequencer_archive/'
AWS_PROFILE='hmf_archive'

sbp s3 sync "${LOCAL_PATH}" "${REMOTE_PATH}" \
--profile ${AWS_PROFILE} \
--grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL}