#!/usr/bin/env bash

local_path='/data/schuberg/snpcheckvcfupload'

bucket='hmf-snpcheck'
destination='snpcheckvcfs'

echo "[INFO] Syncing snpcheck data to GCP!"

gcloud auth activate-service-account --key-file /home/sbpext/hmf-snpcheck
gsutil rsync -dr ${local_path} gs://${bucket}/${destination}