#!/usr/bin/env bash

local_path='/data/schuberg/snpcheckvcfupload'

bucket='hmf_archive'
destination='snpcheckvcfs'
aws_profile='hmf_archive'

echo "Syncing snpcheck data to SBP!"

sbp s3 sync ${local_path} s3://${bucket}/${destination} \
    --profile ${aws_profile} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL} \
    --delete