#!/bin/bash

LOCAL_PATH='/data/data_archive/rna_seq'
REMOTE_PATH='s3://hmf_archive/rna_seq'
AWS_PROFILE='hmf_archive'

sbp s3 sync "${LOCAL_PATH}" "${REMOTE_PATH}" \
--profile ${AWS_PROFILE} \
--grants read=id=${HMF_DOWNLOAD_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL}