#!/bin/bash

report_path=$1
set=$2

if [ -z "report_path" ] || [ -z "set" ] ;
  then
    echo "Usage: $ ./upload_patient_report report_path set"
    echo "  report_path	The path towards the patient report to be uploaded"
    echo "  set The name of the set to upload the report to."
    exit 1
fi

echo "[WARN] Do not use this script for now"

exit 1

sbp s3 cp ${report_path} s3://${ARCHIVE_BUCKET}/${set}/ \
    --profile ${ARCHIVE_PROFILE} \
    --grants read=id=${HMF_DOWNLOAD_CANONICAL},id=${SBP_PORTAL_CANONICAL} readacl=id=${HMF_DOWNLOAD_CANONICAL}