#!/usr/bin/env bash

file_path=$1 && shift

if [ -z "${file_path}" ]; then
    echo "[ERROR] Please provide a file path. Exiting"
    exit 1
fi

destination="s3://hmf_experiments/share/"

echo "[INFO] Uploading ${file_path} to ${destination}"
sbp s3 cp ${file_path} ${destination} --profile download
