#!/bin/bash

count=0
cd /data/cpct/runs/
sets=$( ls | tail -n 3 | tr "\n" " " )
for set in ${sets}
do
	count=$[${count}+1]
	purity_pathology_set_pilot ${set} ${count}
done
echo "Finished calculations on different sets!"