select sampleId, fitMethod, qcStatus, purity from purity where sampleId = "XXX";
select * from driverCatalog where sampleId = "XXX";
select * from svFusion where sampleId = "XXX" and reported = 1;
select * from svBreakend where sampleId = "XXX"  and reportedDisruption = 1;
select * from virusAnnotation where sampleId = "XXX" and reported = 1;
select * from peachGenotype where sampleId = "XXX";
select * from chord where sampleId = "XXX";
select sampleId, msIndelsPerMb, msStatus from purity where sampleId = "XXX";
select sampleId, tml, tmlStatus from purity where sampleId = "XXX";
select * from protect where sampleId ="XXX" and reported = 1;