#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift

if [[ -z "${run_dir}" || -z "${output_dir}" ]]; then
    error "Inputs missing. Exiting";
fi

pipeline_version_file="${run_dir}/pipeline.version"
pipeline_version_cmd=""
if [[ -f "${pipeline_version_file}" ]]; then
    pipeline_version_cmd="-pipeline_version_file ${pipeline_version_file}"
fi

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
tumor_sample_wgs_metrics_file="$(locate_wgs_metrics ${run_dir} ${tumor_sample})"
tumor_sample_flagstat_file="$(locate_flagstats ${run_dir} ${tumor_sample})"
sage_somatic_dir="$(locate_sage_somatic_data_directory ${run_dir})"
purple_dir="$(locate_purple_data_directory ${run_dir})"
purple_plot_dir="$(locate_purple_plot_directory ${run_dir})"
linx_somatic_dir="$(locate_linx_somatic_data_directory ${run_dir})"
linx_somatic_plot_dir="$(locate_linx_plot_directory ${run_dir})"
lilac_dir="$(locate_lilac_data_directory ${run_dir})"

info "Running ORANGE pilot in targeted-mode on ${run_dir}"

do_run_orange_pilot \
    ${run_dir} \
    ${output_dir} \
    ${pipeline_version_cmd} \
    -ref_genome_version ${ref_genome_version} \
    -tumor_sample_wgs_metrics_file "${tumor_sample_wgs_metrics_file}" \
    -tumor_sample_flagstat_file "${tumor_sample_flagstat_file}" \
    -sage_dir "${sage_somatic_dir}" \
    -purple_dir "${purple_dir}" \
    -purple_plot_dir "${purple_plot_dir}" \
    -linx_dir "${linx_somatic_dir}" \
    -linx_plot_dir "${linx_somatic_plot_dir}" \
    -lilac_dir "${lilac_dir}" \
    "$@"
