#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift
output_dir=$1 && shift

if [[ -z "${run_dir}" || -z "${output_dir}" ]]; then
    error "Inputs missing. Exiting";
fi

pipeline_version_file="${run_dir}/pipeline.version"
pipeline_version_cmd=""
if [[ -f "${pipeline_version_file}" ]]; then
    pipeline_version_cmd="-pipeline_version_file ${pipeline_version_file}"
fi

tumor_sample_wgs_metrics_file="$(locate_wgs_metrics ${run_dir} ${tumor_sample})"
tumor_sample_flagstat_file="$(locate_flagstats ${run_dir} ${tumor_sample})"
sage_somatic_tumor_sample_bqr_plot="$(locate_sage_bqr_plot ${run_dir} ${tumor_sample})"
purple_data_directory="$(locate_purple_data_directory ${run_dir})"
purple_plot_directory="$(locate_purple_plot_directory ${run_dir})"
linx_somatic_data_directory="$(locate_linx_somatic_data_directory ${run_dir})"
linx_plot_directory="$(locate_linx_plot_directory ${run_dir})"
lilac_result_csv="$(locate_lilac_results ${run_dir})"
lilac_qc_csv="$(locate_lilac_qc ${run_dir})"

annotated_virus_tsv="$(locate_virus_annotation_tsv ${run_dir})"
chord_prediction_txt="$(locate_chord_prediction ${run_dir})"
if [[ -d "${run_dir}/cuppa_dna_rna" ]]; then
    cuppa_result_csv="$(locate_cuppa_dna_rna_result_csv ${run_dir})"
    cuppa_summary_plot="$(locate_cuppa_dna_rna_summary_plot ${run_dir})"
    cuppa_feature_plot="$(locate_cuppa_dna_rna_feature_plot ${run_dir})"
    cuppa_chart_plot="$(locate_cuppa_dna_rna_chart_plot ${run_dir})"
else
    cuppa_result_csv="$(locate_cuppa_result_csv ${run_dir})"
    cuppa_summary_plot="$(locate_cuppa_summary_plot ${run_dir})"
    cuppa_feature_plot="$(locate_cuppa_feature_plot ${run_dir})"
    cuppa_chart_plot="$(locate_cuppa_chart_plot ${run_dir})"
fi

cuppa_feature_plot_cmd=""
if [[ ! -z ${cuppa_feature_plot} ]]; then
    cuppa_feature_plot_cmd="-cuppa_feature_plot ${cuppa_feature_plot}"
fi

sigs_allocation_tsv="$(locate_sigs_allocation_tsv ${run_dir})"

info "Running ORANGE pilot panel on ${run_dir}"

do_run_orange_pilot \
    ${pipeline_version_cmd} \
    -tumor_sample_wgs_metrics_file "${tumor_sample_wgs_metrics_file}" \
    -tumor_sample_flagstat_file "${tumor_sample_flagstat_file}" \
    -sage_somatic_tumor_sample_bqr_plot "${sage_somatic_tumor_sample_bqr_plot}" \
    -purple_data_directory "${purple_data_directory}" \
    -purple_plot_directory "${purple_plot_directory}" \
    -linx_somatic_data_directory "${linx_somatic_data_directory}" \
    -linx_plot_directory "${linx_plot_directory}" \
    -lilac_result_csv "${lilac_result_csv}" \
    -lilac_qc_csv "${lilac_qc_csv}" \
    -sigs_allocation_tsv "${sigs_allocation_tsv}" \
    "$@"