#!/usr/bin/env bash

source secrets_functions || exit 1

collection_date_for_sample() {
    sample=$1 && shift

    collection_date=$(lama -j tumor-sample sample-id/${sample} | jq -r '.samplingDate')

    # Convert format yyyy-mm-dd to yymmdd
    echo "${collection_date:2:2}${collection_date:5:2}${collection_date:8:2}"
}