#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

orange_jar=$(locate_pilot_orange)

credentials=$(prod_writer_sql_credentials)
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" "hmfpatients")

# Note: This application has quite a number of hardcoded paths. Please check code for reference
java -cp ${orange_jar} com.hartwig.hmftools.orange.cohort.application.CohortMapperEvaluator \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"