#!/usr/bin/env bash

source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting";
fi

if [[ ! -d ${run_dir}/linx/plot ]]; then
    # LINX plot dir does not get propagated through GS in case of no drivers - see also DEV-2201
    warn "No linx plot dir found. Assume no drivers were found."
    mkdir -p ${run_dir}/linx/plot
fi

# To correct for the missing SIG data - see also DEV-2196
run_cuppa_prod ${run_dir}

# To generate the CUPPA report as a picture (png) - see also DEV-2195
generate_cup_report_pipeline ${run_dir}

# Run standard ORANGE in production - see also DEV-2027
run_orange_prod ${run_dir} -max_evidence_level C

# No germline is generated to be able to share externally with people who do not wish to see germline.
do_run_orange_prod ${run_dir} ${run_dir}/orange_no_germline -max_evidence_level C -disable_germline