#!/usr/bin/env bash

source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting";
fi

output_dir="${run_dir}/orange_pilot_tumor_only"

do_run_orange_pilot_tumor_only ${run_dir} ${output_dir} "$@"