#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting";
fi

output_dir="${run_dir}/orange_pilot_targeted"
ref_genome_version="38"

do_run_orange_pilot_targeted ${run_dir} ${output_dir} ${ref_genome_version} "$@"
