#!/usr/bin/env bash

source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting";
fi

run_orange_pilot ${run_dir} -max_evidence_level C