#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

orange_jar=$(locate_pilot_orange)

doid_json="/data/resources/public/disease_ontology/doid.json"
cohort_mapping_tsv=$(locate_cohort_mapping_tsv)
output_directory="/data/experiments/disease_ontology/orange_cohort"

credentials=$(prod_writer_sql_credentials)
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" "hmfpatients")

java -cp ${orange_jar} com.hartwig.hmftools.orange.cohort.application.OrangeCohortGenerator \
    -doid_json ${doid_json} \
    -cohort_mapping_tsv ${cohort_mapping_tsv} \
    -output_directory ${output_directory} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -log_debug \
    "$@"