#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

iclusion_importer_jar=$1 && shift
iclusion_trial_tsv=$1 && shift
iclusion_db=$1 && shift

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${iclusion_db})

java -cp ${iclusion_importer_jar} com.hartwig.hmftools.iclusion.daoLoadIclusionDatabase \
    -iclusion_db_tsv ${iclusion_trial_tsv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"