#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source database_functions || exit 1

iclusion_db=$1 && shift

# Resources
iclusion_database_sql="/data/resources/crunch/serve/iclusion/generate_iclusion_db.sql"

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_host=$(extract_database_host "${credentials}")

info "Rebuilding iClusion db '${iclusion_db}' on '${db_host} using ${iclusion_database_sql}"

mysql ${iclusion_db} --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${iclusion_database_sql}
