#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

iclusion_trial_tsv=$(locate_prod_iclusion_trial_tsv)
iclusion_importer_jar=$(locate_pilot_iclusion_importer)

do_load_iclusion_db ${iclusion_importer_jar} ${iclusion_trial_tsv} "iclusion_pilot"