#!/usr/bin/env bash

source message_functions || exit 1

confirmation_order=$1

if [[ -z "${confirmation_order}" ]]; then
    error "Provide a confirmation_order. Exiting"
fi

curl -s -X 'POST' -H 'accept: */*' "http://lama.prod-1/api/hss/order-confirmation/${confirmation_order}/complete"
