#!/usr/bin/env bash

set -euo pipefail

SUBMISSION=$1
WORKING_DIR="/data/submissions/$SUBMISSION"

gather_confirmation_order "$SUBMISSION"
gather_confirmation_order_aria_config "$SUBMISSION" > "$WORKING_DIR/gather_aria.log"
generate_final_test_report.py -i "$WORKING_DIR/report.txt" -o "$WORKING_DIR/" -n 'Kasper Wolsink'
wkhtmltopdf --enable-local-file-access "$WORKING_DIR/$SUBMISSION.html" "$WORKING_DIR/$SUBMISSION.pdf"
upload_files_to_nextcloud_research "$WORKING_DIR/aria2/$SUBMISSION.aria.txt"
upload_files_to_nextcloud_research "$WORKING_DIR/$SUBMISSION.pdf"