#!/usr/bin/env bash

source locate_files

runs_dir=/data/gcp/shallow_runs
patient_db_jar=$(locate_pilot_patient_db)

shallow_seq_tsv=/data/lims/shallow_seq_purity_pilot.tsv
purple_purity_p4_tsv=".purple.purity"
purple_purity_p5_tsv=".purple.purity.tsv"
purple_qc_file=".purple.qc"
pipeline_version_file="pipeline.version"

java -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.CreateShallowSeqDB \
    -runs_dir ${runs_dir} \
    -shallow_seq_tsv ${shallow_seq_tsv} \
    -purple_purity_p4_tsv ${purple_purity_p4_tsv} \
    -purple_purity_p5_tsv ${purple_purity_p5_tsv} \
    -purple_qc_file ${purple_qc_file} \
    -pipeline_version_file ${pipeline_version_file} \
    "$@"