#!/usr/bin/env bash

prefix=`dirname $(readlink $0 || echo $0)`
sample=$1 && shift
credentials=/data/common/dbs/mysql_credentials/pilot
patient_db_jar=/data/common/tools/patient-db_pilot/patient-db.jar

${prefix}/do_delete_sample_of_database ${sample} ${credentials} ${patient_db_jar}
