#!/usr/bin/env bash

source locate_files

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    echo "[ERROR] No sample is provided to $(basename $0). Exiting." && exit 1
fi

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_delete_sample_from_database ${sample} ${credentials} ${patient_db_jar}