#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source database_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "No sample is provided to $(basename $0). Exiting."
fi

credentials=$(prod_writer_sql_credentials)
patient_db_jar=$(locate_research_patient_db)
database="pipeline_v5_validation"

do_delete_sample_from_database ${sample} ${database} "${credentials}" ${patient_db_jar}