#!/usr/bin/env bash

source locate_files

prefix=$(dirname $(readlink $0 || echo $0))
sample=$1 && shift

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

${prefix}/delete_sample_from_database ${sample} ${credentials} ${patient_db_jar}