#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift
patient_db_jar=$1 && shift
linx_jar=$1 && shift
credentials=$1 && shift

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

amber_dir=$(locate_amber_directory ${run_dir})
somatic_vcf=$(locate_purple_somatics ${run_dir})
structural_vcf=$(locate_purple_structural_variants ${run_dir})
chord_prediction_file=$(locate_chord_prediction ${run_dir})
protect_evidence_tsv=$(locate_protect_evidence ${run_dir})
ref_metrics_file=$(locate_wgs_metrics ${run_dir} ${ref_sample})
tumor_metrics_file=$(locate_wgs_metrics ${run_dir} ${tumor_sample})

bachelor_jar=$(locate_prod_bachelor)

do_load_amber_data ${tumor_sample} ${amber_dir} ${credentials} ${patient_db_jar}
do_load_purple_data ${tumor_sample} ${run_dir}/purple ${credentials} ${patient_db_jar}
do_load_somatic_variants ${tumor_sample} ${ref_sample} ${somatic_vcf} ${credentials} ${patient_db_jar}
do_load_structural_variants ${tumor_sample} ${structural_vcf} ${credentials} ${patient_db_jar}
do_load_linx_data ${tumor_sample} ${run_dir}/linx ${credentials} ${linx_jar}
do_load_metrics_data ${tumor_sample} ${ref_metrics_file} ${tumor_metrics_file} ${credentials} ${patient_db_jar}
do_load_chord_data ${tumor_sample} ${chord_prediction_file} ${credentials} ${patient_db_jar}
# TODO Add below command on upgrade to patient db v3.57
# do_load_protect_evidence ${tumor_sample} ${protect_evidence_tsv} ${credentials} ${patient_db_jar}
do_load_bachelor_data ${tumor_sample} ${run_dir}/bachelor ${credentials} ${bachelor_jar}
do_load_snv_signatures ${tumor_sample} ${credentials}


