#!/usr/bin/env bash

source locate_files

sample=$1 && shift
somatic_vcf=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

# File Locations
high_confidence_bed=/data/common/dbs/GIAB_NIST_v3.2.2/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz
hotspot_tsv=$(locate_hotspot_tsv)

echo "[INFO] Loading somatic variant data for sample: ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadSomaticVariants \
    -high_confidence_bed ${high_confidence_bed} \
    -vcf_file ${somatic_vcf} \
    -sample ${sample} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -hotspot ${hotspot_tsv} \
    "$@"