#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

sample=$1 && shift
peach_calls_tsv=$1 && shift
peach_genotype_tsv=$1 && shift
database_name=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_host=$(extract_database_host "${credentials}")
db_port=$(extract_database_port "${credentials}")
db_dependencies=$(extract_database_dependencies "${credentials}")
db_url=$( echo "mysql://${db_host}:${db_port}/${database_name}?serverTimezone=CET${db_dependencies}")

info "Loading PEACH data for ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadPeachData \
    -sample ${sample} \
    -peach_calls_txt ${peach_calls_tsv} \
    -peach_genotype_txt ${peach_genotype_tsv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"