#!/bin/bash
source locate_files
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/pilot
patient_db_jar=/data/common/tools/purple_pilot/purple.jar

somatic_vcf=$(locate_purple_pilot_somatics ${run_dir})
sample=$(load_tumor_sample_from_metadata ${run_dir})
${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar} $@
