#!/bin/bash
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/prod
patient_db_jar=/data/common/tools/purple_v2.15/purple.jar

somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
if [ $? -ne 0 ]
then
    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
    if [ $? -ne 0 ]
    then
        echo "Unable to locate post processed somatic variants. Exiting."
        exit 1
    fi
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar} $@