#!/bin/bash
run_dir=$1 && shift
credentials=$1 && shift
patient_jar=$1 && shift

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

# File Locations
high_confidence_bed=/data/common/dbs/GIAB_NIST_v3.2.2/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed
ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

# Files
somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf)
if [ $? -ne 0 ]
then
	echo "Unable to locate post processed VCF. Reverting to manually PON filtered."
    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*melted_consensus_filtered_pon.vcf)
    if [ $? -ne 0 ]
    then
        echo "Unable to locate somatic variants. Exiting."
        exit 1
    fi
fi

sample=$(ls ${run_dir} | grep -E '^(CPCT|DRUP)[0-9]{8}[^R]')
echo "Loading variant data for sample: ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_jar} com.hartwig.hmftools.patientdb.LoadSomaticVariants \
    -ref_genome ${ref_genome} \
    -high_confidence_bed ${high_confidence_bed} \
    -vcf_file ${somatic_vcf} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    $@
