#!/usr/bin/env bash

sample=$1 && shift
run_dir=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

knowledgebase_dir=/data/common/dbs/knowledgebases/output
tumor_location_csv=/data/common/dbs/ecrf_dumps/curated_tumor_locations

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Loading evidence data for ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadEvidenceData \
    -sample ${sample} \
    -run_dir ${run_dir} \
    -knowledgebase_dir ${knowledgebase_dir} \
    -tumorlocation_file ${tumor_location_csv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"
