#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/pilot
patient_db_jar=/data/common/tools/purple_pilot/purple.jar

${prefix}/do_load_purple_data ${run_dir} ${credentials} ${patient_db_jar}