#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

sample=$1 && shift
reference=$1 && shift
somatic_vcf=$1 && shift
database_name=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

info "Loading somatic variant data for ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadSomaticVariants \
    -sample ${sample} \
    -reference ${reference} \
    -somatic_vcf ${somatic_vcf} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"