#!/bin/bash

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/prod
patient_db_jar=/data/common/tools/purple_v2.6/purple.jar

somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.1.vcf.gz)
if [ $? -ne 0 ]
then
    echo "Unable to locate post processed somatic variants. Exiting."
    exit 1
fi

${prefix}/do_load_somatic_variants ${run_dir} ${credentials} ${patient_db_jar} ${somatic_vcf} $@