#!/usr/bin/env bash

source locate_files
source load_metadata

prefix=$(dirname $(readlink $0 || echo $0))
run_dir=$1 && shift

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

somatic_vcf=$(locate_purple_pilot_somatics ${run_dir})
sample=$(load_tumor_sample_from_metadata ${run_dir})
${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar} "$@"
