#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

sample=$1 && shift
protect_evidence_tsv=$1 && shift
database_name=$1 && shift
credentials=$1 && shift
oncoact_db_jar=$1 && shift

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

info "Loading PROTECT data for ${sample} to ${database_name}"

java -Dorg.jooq.no-logo=true -cp ${oncoact_db_jar} com.hartwig.hmftools.patientdb.LoadProtectData \
    -sample ${sample} \
    -protect_evidence_tsv ${protect_evidence_tsv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"