#!/usr/bin/env bash

source locate_files

sample=$1 && shift
run_dir=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

knowledgebase_dir=/data/common/dbs/knowledgebases/output
tumor_location_csv=/data/common/dbs/clinical_data/curated_tumor_locations.csv

purple_driver_catalog_tsv=$(locate_purple_drivers ${run_dir})
linx_fusion_tsv=$(locate_linx_fusions ${run_dir})
purple_gene_cnv_tsv=$(locate_purple_gene_copynumbers ${run_dir})
somatic_variant_vcf=$(locate_purple_somatics ${run_dir})

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Loading evidence data for ${sample}"

java -Xmx16G -Xms4G -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadEvidenceData \
    -sample ${sample} \
    -knowledgebase_dir ${knowledgebase_dir} \
    -tumor_location_csv ${tumor_location_csv} \
    -somatic_variant_vcf ${somatic_variant_vcf} \
    -purple_gene_cnv_tsv ${purple_gene_cnv_tsv} \
    -linx_fusion_tsv ${linx_fusion_tsv} \
    -purple_driver_catalog_tsv ${purple_driver_catalog_tsv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"
