#!/bin/bash
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/pilot
patient_db_jar=/data/common/tools/purple_pilot/purple.jar

somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
if [ $? -ne 0 ]
then
    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
    if [ $? -ne 0 ]
    then
        echo "Unable to locate post processed somatic variants. Exiting."
        exit 1
    fi
fi

hotspot=/data/common/dbs/somatic_hotspot_v2/Hotspot.tsv
somatic_pon=/data/common/dbs/PON_v2.0/SOMATIC_PON.vcf.gz
germline_pon=/data/common/dbs/PON_v2.0/GERMLINE_PON.vcf.gz

sample=$(load_tumor_sample_from_metadata ${run_dir})
${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar} -hotspot ${hotspot} -somatic_pon ${somatic_pon} -germline_pon ${germline_pon} $@
