#!/usr/bin/env bash

source locate_files

sample=$1 && shift
pgx_calls_txt=$1 && shift
pgx_genotype_txt=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Loading pgx data for ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadPgxData \
    -sample ${sample} \
    -pgx_calls_txt ${pgx_calls_txt} \
    -pgx_genotype_txt ${pgx_genotype_txt} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"