#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

function backwardsCompatibleResultsArg() {
    case "$1" in
     *3.72*) cuppa_results_arg="-cuppa_results_csv ${cuppa_results_csv}" ;;
     *) cuppa_results_arg="-cuppa_conclusion_txt ${cuppa_results_csv}" ;;
    esac
}

sample=$1 && shift
cuppa_results_csv=$1 && shift
database_name=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

info "Loading CUPPA data for ${sample}"
backwardsCompatibleResultsArg $patient_db_jar
java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadCuppa \
    -sample ${sample} \
    ${cuppa_results_arg} \ \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"
