#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

function backwardsCompatibleDataType() {
    case "$1" in
     *3.71*) datatype_arg=-somatic_only ;;
     *) datatype_arg="-data_type \"somatic\"" ;;
    esac
}

sample=$1 && shift
linx_dir=$1 && shift
database_name=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

info "Loading linx somatic data for ${sample}"
backwardsCompatibleDataType $patient_db_jar
java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadLinxData \
    -sample ${sample} \
    -linx_dir ${linx_dir} \
    ${datatype_arg} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"