#!/usr/bin/env bash

source load_metadata
source locate_files

prefix=$(dirname $(readlink $0 || echo $0))
run_dir=$1 && shift

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_purple)

sample=$(load_tumor_sample_from_metadata ${run_dir})
${prefix}/do_load_purple_data ${sample} ${run_dir}/purple ${credentials} ${patient_db_jar}