#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

sample=$1 && shift
virus_annotation_tsv=$1 && shift
database_name=$1 && shift
credentials=$1 && shift
patient_db_jar=$1 && shift

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

info "Loading Virus Interpreter data for ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadVirusInterpreter \
    -sample ${sample} \
    -virus_annotation_tsv ${virus_annotation_tsv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"
