#!/bin/bash
source locate_files
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

somatic_vcf=$(locate_purple_somatics ${run_dir})
sample=$(load_tumor_sample_from_metadata ${run_dir})
${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar} -ref_genome ${ref_genome} $@