#!/usr/bin/env bash

source locate_files
source metadata_functions

prefix=$(dirname $(readlink $0 || echo $0))
run_dir=$1 && shift

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

${prefix}/do_load_metrics_data ${ref_sample} ${tumor_sample} ${run_dir} ${credentials} ${patient_db_jar}