#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

ref_flagstat_file=$(locate_flagstats ${run_dir} ${ref_sample})
tumor_flagstat_file=$(locate_flagstats ${run_dir} ${tumor_sample})

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_flagstat_data ${tumor_sample} ${ref_flagstat_file} ${tumor_flagstat_file} ${credentials} ${patient_db_jar}