#!/bin/bash
source locate_filess
source load_metadata

run_dir=$1 && shift
patient_db_jar=$(locate_pilot_patient_db)
credentials=/data/common/dbs/mysql_credentials/pipeline_v5
sample=$(load_tumor_sample_from_metadata ${run_dir})

load_genomic_data_for_run_into_db ${run_dir} ${patient_db_jar} ${credentials} ${sample}