#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift
patient_db_jar=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

if [[ -n ${patient_db_jar} ]]; then
  patient_db_jar=$(locate_prod_patient_db)
fi
database="compare_refgenome"

info "Loading in '${run_dir}' into ${database} db with jar '${patient_db_jar}'"

credentials=$(prod_writer_sql_credentials)

do_load_run_into_db "${run_dir}" "${patient_db_jar}" "${database}" "${credentials}"
