#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
structural_vcf=$(locate_purple_structural_variants ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_structural_variants ${sample} ${structural_vcf} ${credentials} ${patient_db_jar} "$@"
