#!/usr/bin/env bash

source locate_files

run_dir=$1 && shift

patient_db_jar=$(locate_pilot_patient_db)
linx_jar=$(locate_prod_linx)
credentials=$(locate_pilot_database_credentials)

do_load_run_into_db ${run_dir} ${patient_db_jar} ${linx_jar} ${credentials}
