#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})
molecular_tissue_origin_txt=$(locate_cuppa_conclusion_txt ${run_dir})

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_cuppa_data ${sample} ${molecular_tissue_origin_txt} ${credentials} ${patient_db_jar}
