#!/bin/bash
source locate_files

run_dir=$1 && shift
patient_db_jar=$1 && shift
credentials=$1 && shift
sample=$1 && shift

prefix=`dirname $(readlink $0 || echo $0)`

somatic_vcf=$(locate_purple_somatics ${run_dir})

echo "[INFO] Loading purple data"
${prefix}/do_load_purple_data ${run_dir}/purple ${credentials} ${patient_db_jar} ${sample} $@

echo "[INFO] Loading somatic variants"
${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar}

echo "[INFO] Loading metrics"
${prefix}/do_load_metrics_data ${run_dir} ${credentials} ${patient_db_jar}

echo "[INFO] Loading CHORD"
${prefix}/do_load_chord_data ${run_dir} ${credentials} ${patient_db_jar}
