#!/usr/bin/env bash

source metadata_functions
source locate_files

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
linx_dir=${run_dir}/linx_pilot/

credentials=$(locate_pilot_database_credentials)
linx_jar=$(locate_pilot_linx)

do_load_linx_data ${sample} ${linx_dir} ${credentials} ${linx_jar} "$@"
