#!/usr/bin/env bash

source locate_files || exit 1

run_dir=$1 && shift

patient_db_jar=$(locate_pilot_patient_db)
credentials=$(locate_pilot_database_credentials)

do_load_run_into_db_v3_60 ${run_dir} ${patient_db_jar} ${credentials}
