#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})
prediction_file=$(locate_chord_pilot_prediction ${run_dir})

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_chord_data ${sample} ${prediction_file} ${credentials} ${patient_db_jar}
