#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
ref_sample=$(load_ref_sample_from_metadata ${run_dir})
germline_vcf=$(locate_purple_germline_variants ${run_dir})

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_germline_variants ${sample} ${ref_sample} ${germline_vcf} ${credentials} ${patient_db_jar} "$@"
