#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

ref_metrics_file=$(locate_wgs_metrics ${run_dir} ${ref_sample})
tumor_metrics_file=$(locate_wgs_metrics ${run_dir} ${tumor_sample})

database="hmfpatients_pilot"
credentials=$(prod_writer_sql_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_metrics_data ${tumor_sample} ${ref_metrics_file} ${tumor_metrics_file} ${database} "${credentials}" ${patient_db_jar}