#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
molecular_tissue_origin_txt=$(locate_cuppa_txt ${run_dir})

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_virusbreakend_data ${sample} ${molecular_tissue_origin_txt} ${credentials} ${patient_db_jar}
