#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

database="hmfpatients"
patient_db_jar=$(locate_research_patient_db)
credentials=$(prod_writer_sql_credentials)

do_load_purple_data ${sample} ${run_dir}/purple ${database} "${credentials}" ${patient_db_jar}