#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})
linx_dir=${run_dir}/linx

database="hmfpatients"
credentials=$(prod_writer_sql_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_linx_somatic_data ${sample} ${linx_dir} ${database} "${credentials}" ${patient_db_jar} "$@"
