#!/bin/bash

run_dir=$1 && shift
credentials=/data/common/dbs/mysql_credentials/DR022
metadata=/data/data_archive/datarequests/DR-022/DR-022_metadata.tsv

base_run_dir=$(basename ${run_dir})
sample=$(grep ${base_run_dir} ${metadata} | cut -f 3)

load_genomic_data_for_run_into_db ${run_dir} ${credentials} ${sample}