#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

ref_flagstat_file=$(locate_flagstats ${run_dir} ${ref_sample})
tumor_flagstat_file=$(locate_flagstats ${run_dir} ${tumor_sample})

database_name="hmfpatients_pilot"
patient_db_jar=$(locate_pilot_patient_db)
credentials=$(prod_writer_sql_credentials)

# Database details
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

info "Loading flagstats data for ${sample}"

java11 -Dorg.jooq.no-logo=true -Dorg.jooq.no-tips=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadFlagstatData \
    -sample ${sample} \
    -ref_flagstat_file ${ref_flagstat_file} \
    -tumor_flagstat_file ${tumor_flagstat_file} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"