#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
prediction_file=$(locate_chord_prediction ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_germline_driver_catalog ${sample} ${prediction_file} ${credentials} ${patient_db_jar}