#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_evidence_items_data ${tumor_sample} ${run_dir} ${credentials} ${patient_db_jar}