#!/usr/bin/env bash

source metadata_functions
source locate_files

run_dir=$1 && shift

amber_dir=$(locate_amber_directory ${run_dir})
sample=$(load_tumor_sample_from_metadata ${run_dir})
credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_purple)

do_load_amber_data ${sample} ${amber_dir} ${credentials} ${patient_db_jar}