#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
prediction_file=$(locate_chord_prediction ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_chord_data ${sample} ${prediction_file} ${credentials} ${patient_db_jar}