#!/bin/bash

run_dir=$1 && shift
patient_db_jar=$1 && shift
credentials=$1 && shift
sample=$1 && shift

prefix=`dirname $(readlink $0 || echo $0)`

sv_jar=/data/common/tools/variantannotator_v2.4/variant-annotator.jar

# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
if [ $? -ne 0 ]
then
    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
    if [ $? -ne 0 ]
    then
        echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
        exit 1
    fi
fi

gridss_filtered_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
if [ -z ${gridss_filtered_vcf} ]; then
    echo "[ERROR] No GRIDSS filtered somatic vcf found. Exiting."
    exit 1
fi

structural_vcf=$(find -L ${run_dir}/purple/ -type f -name *.purple.sv.vcf.gz)
if [ -z ${structural_vcf} ]
then
    echo "[ERROR] Unable to locate gridss structural variants. Exiting."
    exit 1
fi

echo "[INFO] Loading purple data"
${prefix}/do_load_purple_data ${run_dir}/purple ${credentials} ${patient_db_jar} ${sample} $@

echo "[INFO] Loading somatic variants"
${prefix}/do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar}

echo "[INFO] Loading sv variants"
${prefix}/../svloader/do_run_sv_loader ${sample} ${structural_vcf} ${credentials} ${sv_jar}

echo "[INFO] Loading metrics"
${prefix}/do_load_metrics_data ${run_dir} ${credentials} ${patient_db_jar}

echo "[INFO] Loading CHORD"
${prefix}/do_load_chord_data ${run_dir} ${credentials} ${patient_db_jar}
