#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

amber_dir=$(locate_amber_directory ${run_dir})
sample=$(load_tumor_sample_from_metadata ${run_dir})
credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_amber_data ${sample} ${amber_dir} ${credentials} ${patient_db_jar}