#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
somatic_vcf=$(locate_purple_somatics ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_somatic_variants ${sample} ${somatic_vcf} ${credentials} ${patient_db_jar} "$@"
