#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
ref_sample=$(load_ref_sample_from_metadata ${run_dir})
somatic_vcf=$(locate_purple_somatic_variants ${run_dir})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

do_load_somatic_variants ${sample} ${ref_sample} ${somatic_vcf} ${credentials} ${patient_db_jar} "$@"
