#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift

ref_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

ref_flagstat_file=$(locate_flagstats ${run_dir} ${ref_sample})
tumor_flagstat_file=$(locate_flagstats ${run_dir} ${tumor_sample})

credentials=$(locate_prod_database_credentials)
patient_db_jar=$(locate_prod_patient_db)

echo "[WARN] Loading flagstats not yet supported in prod. Coming in patient-db v3.60!"
exit 1

# do_load_flagstat_data ${tumor_sample} ${ref_flagstat_file} ${tumor_flagstat_file} ${credentials} ${patient_db_jar}