#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir passed. Exiting"
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})
cuppa_result_csv=$(locate_cuppa_result_csv ${run_dir})

database="hmfpatients_pilot"
patient_db_jar=$(locate_pilot_patient_db)
credentials=$(prod_writer_sql_credentials)

do_load_cuppa_data ${sample} ${cuppa_result_csv} ${database} "${credentials}" ${patient_db_jar}
