#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

vcf_gz=$(locate_sage_germline_variants_pilot ${run_dir})
sample=$(load_tumor_sample_from_metadata ${run_dir})
reference=$(echo sample | cut -c1-12)R
rna=$(echo $sample | cut -c1-12)RNA

credentials=/data/common/dbs/mysql_credentials/pilot
patient_db_jar=/data/common/tools/purple_pilot/purple.jar

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Loading somatic variant data for ${sample}"

java -Dorg.jooq.no-logo=true -cp ${patient_db_jar} com.hartwig.hmftools.patientdb.LoadGermlineVariants \
   -sample ${sample} -reference ${reference} \
   -germline_vcf ${vcf_gz} \
   -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
   "$@"