#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1 && shift

sample=$(load_tumor_sample_from_metadata ${run_dir})
pgx_calls_txt=$(locate_pgx_pilot_calls ${run_dir})
pgx_genotype_txt=$(locate_pgx_pilot_genotype ${run_dir})

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

do_load_pgx ${sample} ${pgx_calls_txt} ${pgx_genotype_txt} ${credentials} ${patient_db_jar} "$@"