#!/usr/bin/env bash

source locate_files

patient_db_jar=$(locate_pilot_patient_db)
runs_dir=/data/cpct/runs
pipeline_version_file="pipeline.version"
reporting_db_tsv=$(locate_reporting_db_tsv)

# Force UTF-8 to deal with non-standard characters, see DEV-275
# Note that we should only "do_process_wide_clinical_data" in case of pilot.
java -Dorg.jooq.no-logo=true -Xmx8G -Xms2G -jar ${patient_db_jar} \
    -runs_dir ${runs_dir} \
    -pipeline_version_file ${pipeline_version_file} \
    -cpct_ecrf /data/ecrf/cpct_ecrf.xml \
    -cpct_form_status_csv /data/ecrf/cpct_form_status.csv \
    -drup_ecrf /data/ecrf/drup_ecrf.xml \
    -do_process_wide_clinical_data \
    -wide_pre_avl_treatment_csv /data/ecrf/wide_pre_avl_treatments.csv \
    -wide_biopsy_csv /data/ecrf/wide_biopsies.csv \
    -wide_avl_treatment_csv /data/ecrf/wide_avl_treatments.csv \
    -wide_response_csv /data/ecrf/wide_responses.csv \
    -wide_five_days_csv /data/ecrf/wide_five_days.csv \
    -lims_dir /data/ops/lims/prod \
    -curated_primary_tumor_tsv /data/common/dbs/clinical_data/pilot_curated_primary_tumor.tsv \
    -patient_tumor_curation_status_tsv /data/common/dbs/clinical_data/pilot_patient_tumor_curation_status.tsv \
    -doid_json /data/common/dbs/disease_ontology/201015_doid.json \
    -tumor_location_mapping_tsv /data/common/dbs/clinical_curation/pilot_tumor_location_mapping.tsv \
    -tumor_location_overrides_tsv /data/common/dbs/clinical_curation/pilot_tumor_location_overrides.tsv \
    -treatment_mapping_tsv /data/common/dbs/clinical_curation/treatment_mapping.tsv \
    -biopsy_mapping_tsv /data/common/dbs/clinical_curation/biopsy_site_mapping.tsv \
    -reporting_db_tsv ${reporting_db_tsv} \
    "$@"