#!/usr/bin/env bash

source locate_files

patient_db_jar=$(locate_prod_patient_db)
runs_dir=/data/cpct/runs
pipeline_version_file="pipeline.version"

# Force UTF-8 to deal with non-standard characters, see DEV-275
java -Dorg.jooq.no-logo=true -Xmx8G -Xms2G -Dfile.encoding=UTF-8 \
    -jar ${patient_db_jar} \
    -pipeline_version_file ${pipeline_version_file} \
    -runs_dir ${runs_dir} \
    -cpct_ecrf /data/ecrf/cpct_ecrf.xml \
    -cpct_form_status_csv /data/ecrf/cpct_form_status.csv \
    -drup_ecrf /data/ecrf/drup_ecrf.xml \
    -lims_dir /data/ops/lims/prod \
    -curated_primary_tumor_tsv /data/common/dbs/clinical_data/curated_primary_tumor.tsv \
    -doid_json /data/common/dbs/disease_ontology/201015_doid.json \
    -tumor_location_mapping_tsv /data/common/dbs/clinical_curation/tumor_location_mapping.tsv \
    -treatment_mapping_csv /data/common/dbs/clinical_curation/treatment_mapping.csv \
    -biopsy_mapping_csv /data/common/dbs/clinical_curation/biopsy_site_mapping.csv \
    "$@"

#TODO: remove when curated_primary_tumor.tsv is supported in new patient report
cut -f 1,2,3,4,5,6,7,9 /data/common/dbs/clinical_data/curated_primary_tumor.tsv > /data/common/dbs/clinical_data/curated_tumor_locations.tsv
