#!/bin/bash
patient_db_dir=/data/common/tools/patient-db_v1.0

credentials="$patient_db_dir"/credentials
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=mysql://localhost:3306/hmfpatients?serverTimezone=CET

exec java \
    -jar "$patient_db_dir"/patient-db.jar \
    -runs_dir /data/cpct/runs/ \
    -ecrf /data/ecrf/cpct_ecrf.xml \
    -form_status_csv /data/ecrf/cpct_form_status.csv \
    -db_user ${db_user} \
    -db_pass ${db_pass} \
    -db_url ${db_url} \
    -treatment_types_csv "$patient_db_dir"/csv/treatment_types.csv \
    -lims_json /data/lims/lims.json \
    -pre_lims_arrival_dates_csv /data/lims/pre_lims_arrival_dates.csv \
    -do_load_raw_ecrf