#!/bin/bash
db_user=$1
db_pass=$2

patient_db_dir=/data/common/tools/patient-db_v1.0

java -jar "$patient_db_dir"/patient-db.jar -somatic -runs_dir /data/cpct/runs/ -db_user $db_user -db_pass $db_pass -db_url mysql://localhost:3306/hmfpatients?serverTimezone=CET -high_confidence_bed "$patient_db_dir"/bed/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed -extreme_confidence_bed "$patient_db_dir"/bed/CPCT_Slicing.bed