#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

# Database details
credentials=$(prod_writer_sql_credentials)

database_name="hmfpatients_pilot"
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" ${database_name})

run_clinical_patient_db_pilot -do_load_clinical_data -db_user "${db_user}" -db_pass "${db_pass}" -db_url "${db_url}" "$@"