#!/usr/bin/env bash

source message_functions || exit 1

echo ""
echo "-- UPDATE LIMS -- "
update_lims

echo ""
echo "-- UPDATE CLINICAL CURATION FILES -- "
# updates the files curated_primary_tumor.tsv & patient_tumor_curation_status.tsv
run_clinical_patient_db_prod

echo ""
echo "-- UPDATE DOID IN API -- "
timestamp="$(date +%y%m%d_%H%M)"
script_name="update_ptum_doids_in_api"
log="/data/ops/logs/${timestamp}_${script_name}.log"
${script_name} -m patch > "${log}" 2>&1