#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift
is_pass=$1 && shift

credentials=$(locate_pilot_database_credentials)
patient_db_jar=$(locate_pilot_patient_db)

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

do_update_snpcheck_status ${tumor_sample} ${is_pass} ${credentials} ${patient_db_jar}