#!/usr/bin/env bash

source message_functions || exit 1

echo ""
echo "-- UPDATE LIMS -- "
update_lims

echo ""
echo "-- UPDATE CLINICAL CURATION FILES -- "
# updates the files curated_primary_tumor.tsv & patient_tumor_curation_status.tsv
run_clinical_patient_db_prod_gcp
