#!/usr/bin/env bash

source message_functions || exit 1

process=$1 && shift
isolationBarcode=$1 && shift

print_usage(){
    script=$(basename "$0")
    echo "---"
    echo "Usage: process $isolationBarcode"
    echo "Usage:"
    echo " $script help" #For find the usage of this script
    echo " $script check_reports" #Check for processing all reports
    echo " $script check_pipelines" #Check for processing reporting pipelines
    echo " $script fail_report FR123" #Generate fail reports
    echo " $script upload_for_share FR123" #Upload reports to nextcloud
    echo " $script share_panel" # Upload panel reports to bucket
    echo " $script portal_api FR123" #New call to portal api
    exit 1
}

if [[ (-z "${process}" && -z "${isolationBarcode}") ||  $process == "help" ]]; then
    print_usage >&2
elif [[ -z "${process}" ]]; then
    error "No process provided. Exiting"
elif  [[ ("${process}" != "check_reports" && -z "${isolationBarcode}") && ("${process}" != "check_pipelines" && -z "${isolationBarcode}" ) ]]; then
    error "No sampleBarcode provided. Exiting"
fi

echo -e "Process mode: \033[1;32m $process \033[00m"

if [[ $isolationBarcode != "" ]]; then
    sampleBarcode=$(lama_get_patient_reporter_data ${isolationBarcode} | jq .tumorSampleBarcode | tr -d '"')
    echo -e "Isolation barcode: \033[1;32m ${isolationBarcode} \033[00m"
    echo -e "Sample barcode: \033[1;32m ${sampleBarcode} \033[00m"
fi

if [[ "${process}" == "check_reports" ]]; then
    python3 /data/repos/scripts/oncoact/patientreporter/reporting_pipeline/check_report_and_run_status.py --profile prod
elif [[ "${process}" == "check_pipelines" ]]; then
    check_process_pipelines
elif [[ "${process}" == "fail_report" ]]; then
    python3 /data/repos/scripts/oncoact/patientreporter/reporting_pipeline/generate_fail_report.py ${sampleBarcode} --profile prod
elif [[ "${process}" == "upload_for_share" ]]; then
    python3 /data/repos/scripts/oncoact/patientreporter/reporting_pipeline/reports_to_nc_for_sharing.py ${sampleBarcode}
elif [[ "${process}" == "share_panel" ]]; then
    python3 /data/repos/scripts/oncoact/patientreporter/reporting_pipeline/share_panel_to_bucket.py ${sampleBarcode} --profile prod
elif [[ "${process}" == "portal_api" ]]; then
        python3 /data/repos/scripts/oncoact/patientreporter/reporting_pipeline/update_api.py ${sampleBarcode} --publish --notify-users --profile prod
else
    error "Unknown process type is used as input"
fi