#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift
genome_version=${1:-HG19}

if [[ ! -d "${run_dir}" ]]; then
    error "${run_dir} does not exist!"
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

chord_dir="/data/tools/chord/2.02_1.14"
working_dir="${run_dir}/chord"
mkdir -p "${working_dir}"

somatic_vcf=$(locate_purple_somatic_variants ${run_dir})
structural_vcf=$(locate_purple_structural_variants ${run_dir})

info "CHORD is using somatic vcf: ${somatic_vcf}"
info "CHORD is using structural vcf: ${structural_vcf}"

## R script that produces _chord_signatures.txt and _chord_prediction.txt
${chord_dir}/extractSigPredictHRD.R \
  "${chord_dir}" \
  "${working_dir}" \
  "${sample}" \
  "${somatic_vcf}" \
  "${structural_vcf}" \
  "${genome_version}"

count_files_chord=$(ls ${working_dir} | wc -l)

if [[ ${count_files_chord} -lt 2 ]]; then
    error "Not all files for chord present!"
fi
