#!/usr/bin/env bash

genesCKB=/data/experiments/check_ensembl_versus_CKB_genes/input/210910_CKB_genes.tsv
genes_map_37_89=/data/experiments/check_ensembl_versus_CKB_genes/input/genes_map_37_89.tsv
genes_map_38_104=/data/experiments/check_ensembl_versus_CKB_genes/input/genes_map_38_104.tsv
genes_map_38_89=/data/experiments/check_ensembl_versus_CKB_genes/input/genes_map_38_89.tsv

echo "geneSymbol;geneSynonyms;genes_map_37_89;genes_map_37_89_synonym" > /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_37_89.csv
echo "geneSymbol;geneSynonyms;genes_map_38_104;genes_map_38_104_synonym" > /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_38_104.csv
echo "geneSymbol;geneSynonyms;genes_map_38_89;genes_map_38_89_synonym" > /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_38_89.csv

##checking genes of CKB present in ensembl
sed 1d ${genesCKB} | while IFS= read genes; do

    geneSymbol=$( echo ${genes} | awk '{print $1}')
    synonym=$( echo ${genes} | awk '{print $2}')
    present_genes_map_37_89=$( cat ${genes_map_37_89} | awk '{print $2}' | grep -w ${geneSymbol} | wc -l)
    present_genes_map_38_104=$( cat ${genes_map_38_104} | awk '{print $2}' | grep -w ${geneSymbol} | wc -l)
    present_genes_map_38_89=$( cat ${genes_map_38_89} | awk '{print $2}' | grep -w ${geneSymbol} | wc -l)


    echo $synonym | tr "," "\n" | while read checkSynonym; do
      synonymPresent37_89=$(cat ${genes_map_37_89} | grep -w ${checkSynonym} | wc -l)
      synonymPresent_38_104=$(cat ${genes_map_37_89} | grep -w ${checkSynonym} | wc -l)
      synonymPresent38_89=$(cat ${genes_map_37_89} | grep -w ${checkSynonym} | wc -l)

      synonym37_89=","
      synonym38_104=","
      synonym38_89=","
      if [[ ${synonymPresent37_89} -eq 1 ]]; then
        synonym37_89+="true,"
      else
        synonym37_89+="false,"
      fi

      if [[ ${synonymPresent_38_104} -eq 1 ]]; then
        synonym38_104+="true,"
      else
        synonym38_104+="false,"
      fi

      if [[ ${synonymPresent38_89} -eq 1 ]]; then
        synonym38_89+="true,"
      else
        synonym38_89+="false,"
      fi
    done

    if [[ ${present_genes_map_37_89} -eq 1 ]]; then
    	echo "${geneSymbol};${synonym};true${synonym37_89}" >> /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_37_89.csv
    else
      echo "${geneSymbol};${synonym};false${synonym37_89}" >> /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_37_89.csv
    fi

    if [[ ${present_genes_map_38_104} -eq 1 ]]; then
    	echo "${geneSymbol};${synonym};true${synonym38_104}" >> /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_38_104.csv
    else
      echo "${geneSymbol};${synonym};false${synonym38_104}" >> /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_38_104.csv
    fi

    if [[ ${present_genes_map_38_89} -eq 1 ]]; then
    	echo "${geneSymbol};${synonym};true${synonym38_89}" >> /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_38_89.csv
    else
      echo "${geneSymbol};${synonym};false${synonym38_89}" >> /data/experiments/check_ensembl_versus_CKB_genes/output/CKB_versus_genes_map_38_89.csv
    fi

done < ${genesCKB}

###checking genes of ensembl 37_89 present in CKB
#echo "geneSymbol;genes_map_37_89" > /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_37_89_versus_CKB.csv
#
#sed 1d ${genes_map_37_89} | while IFS= read genes; do
#
#    geneSymbol=$( echo ${genes} | awk '{print $2}')
#    present_CKB_genes=$( cat ${genesCKB} | awk '{print $1}' | grep -w ${geneSymbol} | wc -l)
#
#    if [[ ${present_CKB_genes} -eq 1 ]]; then
#    	echo "${geneSymbol};true" >> /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_37_89_versus_CKB.csv
#    else
#	    echo "${geneSymbol};false" >> /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_37_89_versus_CKB.csv
#    fi
#
#done < ${genes_map_37_89}
#
###checking genes of ensembl 38_104 present in CKB
#echo "geneSymbol;genes_map_38_104" > /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_38_104_versus_CKB.csv
#
#sed 1d ${genes_map_37_89} | while IFS= read genes; do
#
#    geneSymbol=$( echo ${genes} | awk '{print $2}')
#    present_CKB_genes=$( cat ${genesCKB} | awk '{print $1}' | grep -w ${geneSymbol} | wc -l)
#
#    if [[ ${present_CKB_genes} -eq 1 ]]; then
#    	echo "${geneSymbol};true" >> /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_38_104_versus_CKB.csv
#    else
#	    echo "${geneSymbol};false" >> /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_38_104_versus_CKB.csv
#    fi
#
#done < ${genes_map_37_89}
#
###checking genes of ensembl 38_89 present in CKB
#echo "geneSymbol;genes_map_38_89" > /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_38_89_versus_CKB.csv
#
#sed 1d ${genes_map_37_89} | while IFS= read genes; do
#
#    geneSymbol=$( echo ${genes} | awk '{print $2}')
#    present_CKB_genes=$( cat ${genesCKB} | awk '{print $1}' | grep -w ${geneSymbol} | wc -l)
#
#    if [[ ${present_CKB_genes} -eq 1 ]]; then
#    	echo "${geneSymbol};true" >> /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_38_89_versus_CKB.csv
#    else
#	    echo "${geneSymbol};false" >> /data/experiments/check_ensembl_versus_CKB_genes/output/genes_map_38_89_versus_CKB.csv
#    fi
#
#done < ${genes_map_37_89}