#!/usr/bin/env bash

file_name=$1

if [[ -z "${file_name}" ]]; then
    echo "[ERROR] No log file name. Exiting"
    exit 1
fi

cat ${file_name} | grep -Pi "error|excep|fail" | grep -Pv "^#.*(E|e)rrors :.*\(" | grep -Pv "errorCorrection|OnFirstError|download:|\.error"