#!/bin/bash

## Descr: determines the percentage of variants with dbsnp id
## Usage: count_dbsnp_somvars /path/to/pipelineDir
##        count_dbsnp_somvars <dir1> <dir2>

searchDirs=($@)

echo -e "#patient\ttotal\ttotalPASS\tdbsnpCount\tdbsnpCountPASS\tinputDir"
for searchDir in "${searchDirs[@]}"; 
do
  patient=$( echo ${searchDir} | grep -Po 'CPCT\d{8}' )
  dirName=$( basename ${searchDir} )
  meltedFile=$( find $searchDir -name "*_melted.vcf" | head -1 )
 
  if [[ ! -f ${meltedFile} ]]; then echo "[WARNING] Melted file not found for ${dirName}"; continue; fi

      total=$( cat ${meltedFile} | grep -v "^#" | wc -l )
  totalPASS=$( cat ${meltedFile} | grep -v "^#" | cut -f7 | grep -P 'PASS|\.' | wc -l )
      dbsnp=$( cat ${meltedFile} | grep -v "^#" | awk '$3 ~ /rs/ && $3 !~ /COSM/' | wc -l )
  dbsnpPASS=$( cat ${meltedFile} | grep -v "^#" | awk '$3 ~ /rs/ && $3 !~ /COSM/ && $7 ~ /PASS|\./' | wc -l )
  
       PASSPerc=$( echo "scale=0;($totalPASS*100/$total)" | bc )
      dbsnpPerc=$( echo "scale=0;($dbsnp*100/$total)" | bc )
  dbsnpPASSPerc=$( echo "scale=0;($dbsnpPASS*100/$totalPASS)" | bc )
  
  echo -e "${patient}\t${total}\t${totalPASS} (${PASSPerc}%)\t${dbsnp} (${dbsnpPerc}%)\t${dbsnpPASS} (${dbsnpPASSPerc}%)\t${dirName}"
done
