#!/usr/bin/env bash

source metadata_functions

set_path=$1
set_name=$(basename $set_path)

if [[ ! -d ${set_path} ]]; then
    echo "[ERROR] Dir does not exist (${set_path})"
    exit 1;
fi

ref_sample=$(load_ref_sample_from_metadata ${set_path})
tum_sample=$(load_tumor_sample_from_metadata ${set_path})

ref_symlink=${set_path}/${ref_sample}.wgsmetrics
tum_symlink=${set_path}/${tum_sample}.wgsmetrics

source_file_ref_P4=${set_path}/QCStats/${ref_sample}_dedup/${ref_sample}_dedup_WGSMetrics.txt
source_file_tum_P4=${set_path}/QCStats/${tum_sample}_dedup/${tum_sample}_dedup_WGSMetrics.txt

source_file_ref_P5=${set_path}/${ref_sample}/bam_metrics/${ref_sample}.wgsmetrics
source_file_tum_P5=${set_path}/${tum_sample}/bam_metrics/${tum_sample}.wgsmetrics

if [[ -f $source_file_ref_P5 ]]; then
    if [[ ! -f  $source_file_tum_P5 ]]; then
        echo "[ERROR] Ref P5 metrics file was found but tumor one absent (${source_file_tum_P5})" && exit 1
    else
        echo "[INFO] Creating symlinks to P5 metric files for ${set_name}"
        ln -rsf ${source_file_ref_P5} ${ref_symlink}
        ln -rsf ${source_file_tum_P5} ${tum_symlink}
    fi
elif [[ -f $source_file_ref_P4 ]]; then
    if [[ ! -f $source_file_tum_P4 ]]; then
        echo "[ERROR] Ref P4 metrics file was found but tumor one absent (${source_file_tum_P4})" && exit 1
    else
        echo "[INFO] Creating symlinks to P4 metric files for ${set_name}"
        ln -rsf ${source_file_ref_P4} ${ref_symlink}
        ln -rsf ${source_file_ref_P4} ${tum_symlink}
    fi
else
    echo "[ERROR] No P4 or P5 metrics files found so unable to create symlinks" && exit 1
fi

