#!/usr/bin/env bash

source metadata_functions || exit 1
source lims_functions || exit 1
source message_functions || exit 1

source_path=/data/cpct/reportable_runs
process_runs=$(ls ${source_path})

for run in ${process_runs}; do
    sample_id=$(load_tumor_sample_from_metadata ${source_path}/${run})
    summary_present=$(cat /data/common/dbs/summary_patient_report/summary_samples.tsv | grep -w ${sample_id} | wc -l)

    tumor_barcode=$(find_barcode_for_sample_name ${sample_id})
    cohort=$(find_cohort_type ${tumor_barcode})

    if [[ ${summary_present} -ge 1 ]]; then
        if [[ ${cohort} == "CORE" || ${cohort} == "CORELR11" || ${cohort} == "CORESC11" ]]; then
            info "Create patient report for ${run}"
            create_patient_report_for_run /data/cpct/reportable_runs/${run}
            info "Removing run ${run} from /data/cpct/reportable_runs/"
            rm -r /data/cpct/reportable_runs/${run}
        elif [[ ${cohort} == "WIDE"* ]]; then
            info "Create patient report for ${run}"
            create_patient_report_for_run /data/cpct/reportable_runs/${run}
            info "Removing run ${run} from /data/cpct/reportable_runs/"
            rm -r /data/cpct/reportable_runs/${run}
        fi
    elif [[ ${summary_present} -eq 0 ]]; then
        info "No summary present for run ${source_path}/${run}"
    fi
done
