#!/bin/bash

# input file of select chromosome, position, ref, alt from somaticVariant where sampleId='XXX';

cat SomaticVariants.csv | sed -e 's/chromosome,position,ref,alt/chr,pos,ref,alt/g' > changeHeader.txt
cat changeHeader.txt | sed 's/,/ /g' | sed -e 's/^/chr/' | sed "1s/chrchr pos ref alt/chr pos ref alt/" | tr "[:blank:]" "\t" > inputFileCancerGenomeInterpreter.txt

rm changeHeader.txt