#!/usr/bin/env bash

# fraction is fraction that you keep, expressed in format like "0.25"
# seed is seed for RNG, integer expressed in format such as "100"
seqtk_path=$1 && shift
source_dir=$1 && shift
output_dir=$1 && shift
fraction=$1 && shift
seed=$1 && shift

if [[ -z ${seqtk_path} ]] || [[ -z "${source_dir}" ]] || [[ -z "${output_dir}" ]] || [[ -z "${fraction}" ]] || [[ -z "${seed}" ]]; then
    echo "[ERROR] Not all input parameters provided. Should include seqtk_path, source_dir, output_dir, fraction and seed. Exiting"
    exit 1
fi 

# echo "seqtk_path: ${seqtk_path}"
# echo "source_dir: ${source_dir}"
# echo "output_dir: ${output_dir}"
# echo "fraction to keep: ${fraction}"
# echo "seed: ${seed}"

ref_output_dir=${output_dir}/REF
downsampled_output_dir=${output_dir}/${fraction}
tmp_dir=${output_dir}/${fraction}/tmp

mkdir --parents "${ref_output_dir}"
mkdir --parents "${downsampled_output_dir}"
rm -rf "${tmp_dir}"
mkdir --parents "${tmp_dir}"

for file in "${source_dir}"/*.fastq.gz
do
    file_name=$(basename "${file}")
    sample_id=${file_name%%_*}
    sample_type=${sample_id: -1}

    echo "[INFO] Handling ${file_name} for fraction ${fraction}"

    if [ "${sample_type}" = "R" ]; then
	if [ ! -f "${ref_output_dir}"/"${file_name}" ]; then
            echo "[INFO] Copying ref sample file: ${file_name} to ${ref_output_dir}"
            cp "${file}" "${ref_output_dir}"
        else
            echo "[INFO] File ${file_name} already in REF directory"
	fi
    elif [ "${sample_type}" = "T" ]; then
        # these paths are for the uncompressed files
        downsampled_file_path=${downsampled_output_dir}/${file_name%???}
        tmp_downsampled_file_path=${tmp_dir}/${file_name%???}
        if [ ! -f "${downsampled_file_path}" ] && [ ! -f "${downsampled_file_path}.gz" ]; then
            echo "[INFO] Downsampling ${file_name} to ${fraction}"
            rm -f "${tmp_downsampled_file_path}"
            eval "${seqtk_path} sample -s${seed} ${file} ${fraction} > ${tmp_downsampled_file_path}"
            mv "${tmp_downsampled_file_path}" "${downsampled_file_path}"
	          rm -f "${tmp_downsampled_file_path}"
        else
            echo "[INFO] Do not need to downsample ${file_name} to ${fraction} again"
        fi
    else
        echo "[WARNING] Sample type of fastq file not recognized: ${file_name}. Ignored"
    fi
done

echo "[INFO] Start zipping fastq files to fastq.gz for fraction ${fraction}"
# use 80 percent of cpus for zipping of fastq to fastq.gz
cpu_count=$( expr "$(grep -c processor /proc/cpuinfo)" / 10 \* 8)
pigz -p "${cpu_count}" "${downsampled_output_dir}"/*.fastq

rm -rf "${tmp_dir}"

echo "[INFO] Finished downsample_fastq for ${fraction}"
