#!/usr/bin/env bash

run_dir=$1 && shift

info "Running virus interpreter on ${run_dir}"
run_virus_interpreter_prod_datastore ${run_dir}

info "Running protect on ckb data on ${run_dir}"
run_protect_pilot_on_ckb_ds ${run_dir}

info "Generating CKB report on ${run_dir}"
create_patient_report_pdf_for_run_with_ckb_ds ${run_dir}