#!/usr/bin/env bash

source metadata_functions

path=/data/gcp/processed_runs
process_runs=$(ls ${path})

for run in ${process_runs}; do
    run_dir=${path}/${run}

    tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
    if [[ -f "${run_dir}/health_checker/${tumor_sample}.HealthCheckSucceeded" ]]; then
        echo "[INFO] HealthChecker has succeeded for ${run}"
    elif [[ -f "${run_dir}/health_checker/${tumor_sample}.HealthCheckFailed" ]]; then
        echo "[WARN] HealthChecker has failed for ${run}!!"
    else
        echo "[ERROR] HealthChecker has not been run for ${run}"
    fi

    # Printing purple version just for double-checking!
    purple_version=$(cat ${run_dir}/purple/purple.version | grep version)
    echo "[INFO] This analysis has been done with purple ${purple_version}"
done