#!/usr/bin/env bash

source load_metadata

path=/data/schuberg/processed_runs/
process_runs=$(ls ${path})

for run in ${process_runs}; do
    #run_health_checker_prod /data/schuberg/processed_runs/${run}

    tumor_sample=$(load_tumor_sample_from_metadata ${run})
    if [ -f "${run}/health_checker/${tumor_sample}.HealthCheckSucceeded" ] ; then
            echo "[INFO] check healthcheck has run for set ${run}"
    elif [ -f "${run}/health_checker/${tumor_sample}.HealthCheckFailed" ]; then
            echo "[ERROR] check healthcheck has fail for set ${run}"
    else
            echo "[ERROR] check healthcheck has not run for set ${run}"
    fi

done

echo "TODO: check if every healthcheck is correct"