#!/usr/bin/env bash

input_file=$1
delim_char=${2:-"\t"}

## retrieve header line
field_string=$(cat ${input_file} | grep -v "^##" | grep -v "^\*" | head -1 | tr "${delim_char}" " ");

## convert into array
header_fields=(${field_string})

## print to screen
for i in "${!header_fields[@]}"; do
    printf "%s\t%s\n" "$(expr $i + 1)" "${header_fields[$i]}"
done
