#!/usr/bin/env bash

source locate_files

month=$1

reporting_db_tsv=$(locate_reporting_db_tsv)

echo " [INFO] Creating 20_${month}_overview_tmp.tsv file"
header=$(head -n 1 ${reporting_db_tsv})

echo ${header} | tr " " \\t > "/data/lims/montly_overview_reporting_db/20_${month}_overview.tsv"
cat ${reporting_db_tsv} | grep ${month}-2020 >> "/data/lims/montly_overview_reporting_db/20_${month}_overview.tsv"

echo " [INFO] File /data/lims/montly_overview_reporting_db/20_${month}_overview.tsv is created"
