#!/usr/bin/env bash

source locate_files

month=$1

reporting_db_tsv=$(locate_reporting_db_tsv)

header=$(head -n 1 ${reporting_db_tsv})
output_file=$(cat ${reporting_db_tsv} | grep "${month}-2019" )

purity=$(echo ${output_file} | awk '{print $5 /100}' )

sample_data=$(echo ${output_file} | awk '{ print $1, $2, $3, $4}' )
sample_purple=$(echo ${output_file} | awk '{ print $6 $7} ')

echo ${header} > "/data/lims/montly_overview_reporting_db/19_${month}_overview.tsv"
echo ${sample_data} ${purity} ${sample_purple} >> "/data/lims/montly_overview_reporting_db/19_${month}_overview.tsv"
cat "/data/lims/montly_overview_reporting_db/19_${month}_overview.tsv" | tr " " \\t > "/data/lims/montly_overview_reporting_db/19_${month}_overview.tsv"