#!/usr/bin/env bash

month=$1

report_dates_tsv=/data/lims/report_dates_lims_pilot.tsv

if [ -z "${report_dates_tsv}" ]; then
    echo "[ERROR] No report dates tsv. Exiting"
    exit 1
fi

cat ${report_dates_tsv} | grep /${month}/2019