#!/usr/bin/env bash

health_check_processed_runs

process_runs=$(ls /data/schuberg/processed_runs)
for run in ${process_runs}; do
    patientId=$(echo ${run} | tr "_" " " | awk '{print $5}')
    if [[ ${patientId} == "CORE"* ]]; then
        echo "[INFO] Moving set ${run} to /data/core/runs"
	      mv /data/schuberg/processed_runs/${run} /data/core/runs/
	      echo "[INFO] Create patient report for ${run}"
	      patient_report_for_run /data/core/runs/${run}
    else
        echo "[INFO] Moving set ${run} to /data/cpct/runs"
	      mv /data/schuberg/processed_runs/${run} /data/cpct/runs/
	      echo "[INFO] Create patient report for ${run}"
	      patient_report_for_run /data/cpct/runs/${run}
    fi
done
