#!/usr/bin/env bash

health_check_processed_runs

echo "[INFO] Count HealthChecker succeeded"
health_check_processed_runs | grep -c "HealthChecker has succeeded for"

echo "[INFO] Count analysis purple version"
health_check_processed_runs | grep -c "This analysis has been done with purple version=2.45"

source_path=/data/gcp/processed_runs

process_runs=$(ls ${source_path})
for run in ${process_runs}; do
    patient_id=$(echo ${run} | tr "_" " " | awk '{print $5}')
    if [[ ${patient_id} == "CORELR02"* || ${patient_id} == "CORERI02"* ]]; then
        echo "[INFO] Moving set ${run} to /data/core/runs"
        mv ${source_path}/${run} /data/core/runs/
        echo "[INFO] Create patient report for ${run}"
        patient_report_for_run /data/core/runs/${run}
    elif [[ ${patient_id} == "CPCT"* || ${patient_id} == "DRUP"* ]]; then
        echo "[INFO] Moving set ${run} to /data/cpct/runs"
        mv ${source_path}/${run} /data/cpct/runs/
        echo "[INFO] Create patient report for ${run}"
        patient_report_for_run /data/cpct/runs/${run}
        echo "[INFO] rerun set"
        rerun_processed_set /data/cpct/runs/${run}
    else
        # This is for patients that require a summary (WIDE, some CORE)
        echo "[INFO] Moving set ${run} to /data/cpct/reportable_runs"
        mv ${source_path}/${run} /data/cpct/reportable_runs/
        echo "[INFO] Create patient report for ${run}"
        patient_report_for_run /data/cpct/reportable_runs/${run}
    fi
done
