#!/usr/bin/env bash

source message_functions || exit 1

run_dir=$1 && shift

info "Re-run PROTECT with updated tumor location of run ${run_dir}"
run_protect_prod_on_vicc ${run_dir}

info "Loading updated PROTECT data to database of ${run_dir}"
load_protect_data_prod ${run_dir}

info "Create patient report of ${run_dir}"
create_patient_report_for_run ${run_dir}