#!/usr/bin/env bash

path_of_dir_to_tar=$1

out_root="/data2/processed"
YYMMDD="$(date '+%y%m%d')"

if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Descr: Creates tar of flowcell including BCL (excluding Images/Logs/FASTQ)"
    echo " Usage: $(basename $0) /path/to/flowcell/directory/"
    echo " Exmpl: nohup $(basename $0) /data1/illumina_data/flowcell/ > tar.log &"
    echo "---"
    exit 1
fi

in_root=$(dirname ${path_of_dir_to_tar})
tar_dir_name=$(basename ${path_of_dir_to_tar})
out_tar_name="${YYMMDD}_${tar_dir_name}_BCL.tar"
out_tar_path="${out_root}/${out_tar_name}"
out_cnt_path="${out_tar_path}.content"
out_md5_path="${out_tar_path}.md5"

## sanity checks
if [[ -e "${out_tar_path}" ]]; then
    echo "[ERROR] Provided output tar file already exists (${out_tar_path})" && exit 1
fi
if [[ ! -e "${path_of_dir_to_tar}" ]]; then
    echo "[ERROR] Provided dir to tar does not exist (${path_of_dir_to_tar})" && exit 1
fi
if [[ $(find ${path_of_dir_to_tar} -type f -name "*.bcl.bgzf" -or -name "*.cbcl" | wc -l) -lt 1 ]]; then
    echo "[ERROR] Provided dir to tar does not contain BCL or CBCL files (${path_of_dir_to_tar})" && exit 1
fi

## construct tar command
tar_cmd="tar"
tar_cmd+=" --exclude *Images*"
tar_cmd+=" --exclude *Logs*"
tar_cmd+=" --exclude *Fastq*"
tar_cmd+=" --exclude *conversion*.txt"
tar_cmd+=" --exclude *.fastq.gz"
tar_cmd+=" -cf ${out_tar_path}"
tar_cmd+=" ${tar_dir_name}"

## create output files
echo "[INFO] Changing dir to in root (${in_root})"
cd ${in_root} || exit 1

echo "[INFO] Creating tar file (${out_tar_path})"
${tar_cmd} || exit 1
du_of_tar=$(du -h "${out_tar_path}" | cut -f1)

echo "[INFO] Creating content file (${out_cnt_path})"
tar -tf "${out_tar_path}" > "${out_cnt_path}"

echo "[INFO] Changing dir to out root (${out_root})"
cd ${out_root} || exit 1

echo "[INFO] Creating md5 file (${out_md5_path})"
md5sum "${out_tar_name}" > "${out_md5_path}"

echo "[INFO] Output files ready:"
echo "[INFO]  ${out_tar_path} (${du_of_tar})"
echo "[INFO]  ${out_cnt_path}"
echo "[INFO]  ${out_md5_path}"
echo "[INFO] Cmd to sync output files to datastore:"
echo "  rsync -ahP --stats ${out_tar_path} ${out_cnt_path} ${out_md5_path} ds:/data/tmp/"
echo ""
