#!/usr/bin/env bash

path_of_dir_to_tar=$1 && shift

YYMMDD="$(date '+%y%m%d')"

if [[ -z ${path_of_dir_to_tar} || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Descr: Prints tar commands to screen (for any number of provided flowcell paths)"
    echo " Usage: $(basename $0) /path/to/directory/with/fastq/files"
    echo " Exmpl: $(basename $0) /path/to/HMFregXXXX"
    echo "---"
    exit 1
fi

in_root=$(dirname ${path_of_dir_to_tar})
out_root="/data2/processed"

name_of_dir_to_tar=$(basename ${path_of_dir_to_tar})
out_tar_name="${YYMMDD}_${name_of_dir_to_tar}_FASTQ"
out_tar_path="${out_root}/${out_tar_name}.tar"
out_cnt_path="${out_tar_path}.content"
out_md5_path="${out_tar_path}.md5"
tar_log_path="${HOME}/logs/${YYMMDD}_create_iseq_tar_${out_tar_name}.log"

## some sanity checks
if [[ -e "${out_tar_path}" ]]; then
    echo "[ERROR] Provided output tar file already exists (${out_tar_path})" && exit 1
fi
if [[ ! -e "${path_of_dir_to_tar}" ]]; then
    echo "[ERROR] Provided directory to tar does not exist (${path_of_dir_to_tar})" && exit 1
fi
if [[ $(find ${path_of_dir_to_tar} -type f -name "*.fastq.gz" | wc -l) -lt 1 ]]; then
    echo "[ERROR] Provided directory to tar does not contain fastq.gz files (${path_of_dir_to_tar})" && exit 1
fi

## build tar command
tar_cmd="tar"
tar_cmd+=" -cf ${out_tar_path}"
tar_cmd+=" ${name_of_dir_to_tar}"

## do stuff
echo "[INFO] Changing dir"
cd ${in_root} || exit 1

echo "[INFO] Running tar cmd (${tar_cmd})"
echo "[INFO] You can check progress in ${tar_log_path}"
${tar_cmd} > "${tar_log_path}" || exit 1
du_of_tar=$(du -h "${out_tar_path}" | cut -f1)

echo "[INFO] Creating content file"
tar -tf "${out_tar_path}" > "${out_cnt_path}"

echo "[INFO] Creating md5 file"
md5sum "${out_tar_path}" > "${out_md5_path}"

echo "[INFO] Output files ready (tar=${du_of_tar})"
echo "[INFO] Inspect content:"
echo " less ${out_cnt_path}"
echo "[INFO] Sync output files:"
echo " rsync -ahP --stats ${out_tar_path} ${out_cnt_path} ${out_md5_path} ds:/data/tmp/"
echo ""

