#!/usr/bin/env bash

source message_functions || exit 1

[[ -n "${file}" ]] || die "Usage: $(basename $0) <file1> [<fileN>]"

nextcloud_dir="STAGING/Reports-To-Share"

info "Uploading ${file} to Nextcloud for sharing."
do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "$@"