#!/usr/bin/env bash

source message_functions || exit 1

set=$1 && shift

[[ -n "${set}" ]] || die "No set provided. Exiting"

#Searching and selecting run (including ${inc_inis} and excluding ${exc_buckets})
inc_inis="Somatic.ini|PipelineV5.ini|CPCT.ini"
exc_buckets="research-pipeline-output-prod"
runs_json=$(
  hmf_api_get "runs?set_name=${set}" | \
  jq --arg inis "$inc_inis" --arg buckets "$exc_buckets" \
  '[.[] | select(.ini | test($inis)) | select(.bucket | test($buckets)|not)]'
)
run_count=$(jq 'length' <<< "${runs_json}")
sample=$( echo $runs_json | jq -r '.[].set.tumor_sample' )

[[ "${run_count}" -eq 1 ]] || warn "Multiple runs were encountered for this set (${run_count}). Info is from the most recent run!"

if [[ ${run_count} == 0 ]]; then
    warn "No run was found for ${set} on gcp."
    exit 1
fi

report=$( gsutil ls gs://patient-reporter-prod-1/ | grep ${sample} | grep dna_analysis_report.pdf )
report=$( echo ${report#"gs://patient-reporter-prod-1/"} )
xml=$( gsutil ls gs://patient-reporter-prod-1/ | grep ${sample} | grep _oncoact.xml )
xml=$( echo ${xml#"gs://patient-reporter-prod-1/"} )


### upload report to NC
upload_file_to_nc_new_reports_viewing gs://patient-reporter-prod-1/ $report &> /dev/null
upload_file_to_nc_new_reports_viewing gs://patient-reporter-prod-1/ $xml &> /dev/null
info "The report $report en xml $xml is uploaded from gs://patient-reporter-prod-1/ to nextcloud STAGING/New-Reports-Viewing for visual inspection and further processing"
