#!/usr/bin/env bash

bucket=$1 && shift

[[ -n "${bucket}" ]] || die "No bucket provided. Exiting"

nextcloud_dir="STAGING/Validations/SERVE_biweekly_proces_validatie"
temp_folder_path_file=$( pwd )"/temp_reports"
mkdir $temp_folder_path_file

for path  in $(gsutil ls ${bucket})
do
  report=$(gsutil ls ${path}patient-reporter/ | grep .pdf)
  #echo ${report}
  postfix=$(echo ${path#*-} | tr -d "/")
  gsutil cp ${report}  $temp_folder_path_file/
  name=$(echo ${report} | awk -F '/' '{print $6}')
  #echo ${name}
  mv $temp_folder_path_file/${name}  $temp_folder_path_file/${postfix}_${name}
  #echo ${postfix}_${name}
  do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "$temp_folder_path_file/${postfix}_${name}"
done

rm -r $temp_folder_path_file