#!/usr/bin/env bash

nextcloud_dir="STAGING/Reports-For-Summary"
for report in /data/cpct/patient_reports/*.pdf; do
    echo "[INFO] Uploading ${report} to Nextcloud for summary creation"
    do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "${report}"
done
