#!/usr/bin/env bash

nextcloud_dir="STAGING/Reports-KMBP-EMC/Finished reports"
for report in /data/cpct/patient_reports/*.pdf; do
    echo "[INFO] Uploading ${report} to Nextcloud for KMBP EMC finished reports"
    do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "${report}"
done