#!/usr/bin/env bash

source message_functions || exit 1

file=$1 && shift

[[ -n "${file}" ]] || die "No file name provided. Exiting"

nextcloud_dir="STAGING/Reports-To-Share"

info "Uploading ${file} to Nextcloud for sharing."
do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "${file}"