#!/usr/bin/env bash

source locate_files

credentials=$(locate_nextcloud_upload_reports_credentials)
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})

for report in /data/cpct/patient_reports/*.pdf; do
    echo "[INFO] Uploading ${report} to Nextcloud for checking and sharing"
    curl -u "${db_user}:${db_pass}" -T "${report}" https://nextcloud.hartwigmedicalfoundation.nl/remote.php/webdav/STAGING/Reports-To-Check-and-Share/
done