#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run_dir=$1 && shift
purple_jar=$1 && shift
somatic_vcf=$1 && shift
structural_vcf=$1 && shift
sv_recovery_vcf=$1 && shift
purple_output_dir=$1 && shift
database=$1 && shift

reference_sample=$(load_ref_sample_from_metadata ${run_dir})
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
amber_dir=$(locate_amber_directory ${run_dir})

if [[ ! -d "${amber_dir}" ]]; then
    error "Unable to locate AMBER data. Exiting."
fi

if [[ ! -f "${somatic_vcf}" ]]; then
    error "Unable to locate somatic variants. Exiting."
fi

if [[ ! -f "${structural_vcf}" ]]; then
    error "Unable to locate structural variants. Exiting."
fi

if [[ ! -f "${sv_recovery_vcf}" ]]; then
    error "Unable to locate sv recovery variants. Exiting."
fi

if [[ -d "${purple_output_dir}" ]]; then
    rm -r "${purple_output_dir}"/*
else
    mkdir -p "${purple_output_dir}"
    if [[ $? = 1 ]]; then
        error "Could not create directory ${purple_output_dir}. Exiting."
    fi
fi

base_path="/data"

gc_profile=${base_path}/dbs/archive/gc_profiles/GC_profile.1000bp.37.cnp
ref_genome=$(locate_ref_genome_37_fasta_file)
somatic_hotspot_vcf=${base_path}/dbs/serve/hotspots/210502/KnownHotspots.somatic.37.vcf.gz
germline_hotspot_vcf=${base_path}/dbs/archive/sage/KnownHotspots.germline.37.vcf.gz
driver_gene_panel=$(locate_driver_gene_panel_37_tsv)

db_args=""
if [[ ! -z "${database}" ]]; then
   credentials=$(prod_writer_sql_credentials)

   db_user=$(extract_database_user "${credentials}")
   db_pass=$(extract_database_password "${credentials}")
   db_url=$(construct_database_url "${credentials}" ${database})

   db_args="-db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url}"
fi

info "Running purple for ${tumor_sample}"

java -Dorg.jooq.no-logo=true -Xmx16G -Xms4G \
    -jar ${purple_jar} \
    -somatic_vcf ${somatic_vcf} \
    -structural_vcf ${structural_vcf} \
    -circos ${base_path}/tools/circos_v0.69.6/bin/circos \
    -reference ${reference_sample} \
    -tumor ${tumor_sample} \
    -amber ${amber_dir} \
    -cobalt ${run_dir}/cobalt \
    -ref_genome ${ref_genome} \
    -output_dir ${purple_output_dir} \
    -gc_profile ${gc_profile} \
    -sv_recovery_vcf ${sv_recovery_vcf} \
    -driver_catalog \
    -somatic_hotspots ${somatic_hotspot_vcf} \
    -germline_hotspots ${germline_hotspot_vcf} \
    -driver_gene_panel ${driver_gene_panel} \
    -ref_genome_version 37 \
    ${db_args} \
    "$@"