#!/usr/bin/env bash

source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

base_path="/data"

cobalt_jar=${base_path}/tools/cobalt_v1.4/cobalt.jar
gc_profile=${base_path}/dbs/gc_profiles/GC_profile.1000bp.37.cnp
output_dir=${run_dir}/cobalt

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
reference_sample=$(load_ref_sample_from_metadata ${run_dir})

tumor_ratio=$(find -L ${run_dir}/cobalt/ -type f -name ${tumor_sample}.cobalt)
if [[ -z "${tumor_ratio}" ]]; then
    rm -f ${output_dir}/*.len

    info "Calculating cobalt ratios for sample" ${tumor_sample}
    java -Xmx8G -Xms4G \
        -jar ${cobalt_jar} \
        -threads 2 \
        -reference ${reference_sample} \
        -tumor ${tumor_sample} \
        -output_dir ${output_dir} \
        -gc_profile ${gc_profile}

    rm -f ${output_dir}/*.pcf1
    rm -f ${output_dir}/*.ratio
    rm -f ${output_dir}/*.ratio.gc
    rm -f ${output_dir}/*.count
fi

info "Cobalt complete"