#!/usr/bin/env bash

source locate_files || exit 1

run_dir=$1 && shift

purple_output=${run_dir}/purple_pilot

purple_jar=$(locate_pilot_purple)
somatic_vcf=$(locate_sage_filtered_somatic_variants ${run_dir})
structural_vcf=$(locate_gripss_structural_variants ${run_dir})
sv_recovery_vcf=$(locate_gripss_recovery_candidates ${run_dir})
database=""

do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${sv_recovery_vcf} ${purple_output} ${database} "$@"
