#!/usr/bin/env bash

#put SQL selectie query file path at $1 (for all use: all_patients_eligible_datarequests.sql, otherwise: DRXXX.sql) or
#put path metadata file at $1

if [[ $1 != *".sql" ]]; then
    execute_sql_on_prod /data/common/repos/scripts/datarequest/selection/$1 | sort | uniq > temp_datarequest.tsv
    awk -F"\t" 'FNR > 1 {print $1}' temp_datarequest.tsv | sort | uniq > testfile.tmp && mv testfile.tmp temp_datarequest.tsv
else
    csvcut -t -e iso-8859-1 -c '#patientId' $1  | csvformat -T | tail -n +2 | sort | uniq > temp_number_check/temp_datarequest.tsv
fi

#wc -l /data/ops/lims/prod/patient_blacklist.tsv
#wc -l temp_datarequest.tsv
echo "[INFO] Overlap between blacklisted patients and patients in selected for DR (should be zero):"
comm -1 -2 <(sort /data/ops/lims/prod/patient_blacklist.tsv) <(sort temp_datarequest.tsv) | wc -l

rm temp_datarequest.tsv