#!/usr/bin/env bash

#put metadata file path at $1.
#put manifest file path at $2.
#For DNA: put 0 when you do not want to see unique mismatching identifiers, and 1 if you want to see them, at $3.
#For RNA: put 0 when you do not want to see unique mismatching identifiers, and 1 if you want to see them, at $4.

# make dir for temporary files
mkdir temp_GCP_check

### Read in patients and samples selected for DR
csvcut -t -e iso-8859-1 -c '#patientId' $1  | csvformat -T | tail -n +2 | sort | uniq > temp_GCP_check/patientId_metadata.tsv
csvcut -t -e iso-8859-1 -c 'sampleId' $1  | csvformat -T | tail -n +2 | sort | uniq > temp_GCP_check/sampleId_metadata.tsv


echo ''
###############
echo 'LOOK AT OVERLAP BETWEEN PATIENTS SELECTED FOR THE DATA REQUEST AND DNA FILES SHARED IN THE GCP MANIFEST'
echo ''

wc -l temp_GCP_check/patientId_metadata.tsv

jq '.data | .[] | select(.samples | .[] | .data | .[] | .tags | .[]=="DNA") | .patientId'  $2 > temp_GCP_check/patientId_DNA_GCP.tsv
sed 's/\"//g' temp_GCP_check/patientId_DNA_GCP.tsv  > testfile.tmp && mv testfile.tmp temp_GCP_check/patientId_DNA_GCP.tsv
cat temp_GCP_check/patientId_DNA_GCP.tsv | sort | uniq  > testfile.tmp && mv testfile.tmp temp_GCP_check/patientId_DNA_GCP.tsv
wc -l temp_GCP_check/patientId_DNA_GCP.tsv

echo 'Overlap between two files:'
comm -1 -2 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_DNA_GCP.tsv) | wc -l
echo 'Number of extra patients patientId_metadata.tsv:'
comm -2 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_DNA_GCP.tsv) | wc -l
if [ $3 -ne 0 ]
then
  comm -2 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_DNA_GCP.tsv)
fi
echo 'Number of extra patients patientId_DNA_GCP.tsv:'
comm -1 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_DNA_GCP.tsv) | wc -l
if [ $3 -ne 0 ]
then
  comm -1 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_DNA_GCP.tsv)
fi

#######
echo ''
#######

wc -l temp_GCP_check/sampleId_metadata.tsv

jq '.data | .[] | .samples | .[] | select(.data | .[] | .tags | .[]=="DNA") | .sampleId' $2 > temp_GCP_check/sampleId_DNA_GCP.tsv
sed 's/\"//g' temp_GCP_check/sampleId_DNA_GCP.tsv  > testfile.tmp && mv testfile.tmp temp_GCP_check/sampleId_DNA_GCP.tsv
cat temp_GCP_check/sampleId_DNA_GCP.tsv | sort | uniq  > testfile.tmp && mv testfile.tmp temp_GCP_check/sampleId_DNA_GCP.tsv
wc -l temp_GCP_check/sampleId_DNA_GCP.tsv

echo 'Overlap between two files:'
comm -1 -2 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_DNA_GCP.tsv) | wc -l
echo 'Number of extra samples sampleId_metadata.tsv:'
comm -2 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_DNA_GCP.tsv) | wc -l
if [ $3 -ne 0 ]
then
  comm -2 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_DNA_GCP.tsv)
fi
echo 'Number of extra samples sampleId_DNA_GCP.tsv:'
comm -1 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_DNA_GCP.tsv) | wc -l
if [ $3 -ne 0 ]
then
  comm -1 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_DNA_GCP.tsv)
fi

#######
echo ''
#######

jq '.data | .[] | .samples | .[] | .data | .[] | .tags | select(.[]=="DNA") | .[]' $2  > temp_GCP_check/files_GCP.tsv



echo 'number of seperate DNA files shared within GCP:'
grep -c 'DNA' temp_GCP_check/files_GCP.tsv
echo 'of which are CRAM (should be 2 times the number of samples: per sample one for tumor and one for normal):'
grep -c 'CRAM' temp_GCP_check/files_GCP.tsv
echo 'of which are CRAI (should be the same number as CRAM files):'
grep -c 'CRAI' temp_GCP_check/files_GCP.tsv


echo ''
echo ''
###############
echo 'LOOK AT OVERLAP BETWEEN PATIENTS SELECTED FOR THE DATA REQUEST AND RNA FILES SHARED IN THE GCP MANIFEST'
echo ''

wc -l temp_GCP_check/patientId_metadata.tsv

jq '.data | .[] | select(.samples | .[] | .data | .[] | .tags | .[]=="RNA") | .patientId'  $2 > temp_GCP_check/patientId_RNA_GCP.tsv
sed 's/\"//g' temp_GCP_check/patientId_RNA_GCP.tsv  > testfile.tmp && mv testfile.tmp temp_GCP_check/patientId_RNA_GCP.tsv
cat temp_GCP_check/patientId_RNA_GCP.tsv |  sort | uniq  > testfile.tmp && mv testfile.tmp temp_GCP_check/patientId_RNA_GCP.tsv
wc -l temp_GCP_check/patientId_RNA_GCP.tsv

echo 'Overlap between two files:'
comm -1 -2 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_RNA_GCP.tsv) | wc -l
echo 'Number of extra patients patientId_metadata.tsv:'
comm -2 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_RNA_GCP.tsv) | wc -l
if [ $4 -ne 0 ]
then
  comm -2 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_RNA_GCP.tsv)
fi
echo 'Number of extra patients patientId_DNA_GCP.tsv:'
comm -1 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_RNA_GCP.tsv) | wc -l
if [ $4 -ne 0 ]
then
  comm -1 -3 <(sort temp_GCP_check/patientId_metadata.tsv) <(sort temp_GCP_check/patientId_RNA_GCP.tsv)
fi

#######
echo ''
#######

wc -l temp_GCP_check/sampleId_metadata.tsv

jq '.data | .[] | .samples | .[] | select(.data | .[] | .tags | .[]=="RNA") | .sampleId' $2 > temp_GCP_check/sampleId_RNA_GCP.tsv
sed 's/\"//g' temp_GCP_check/sampleId_RNA_GCP.tsv  > testfile.tmp && mv testfile.tmp temp_GCP_check/sampleId_RNA_GCP.tsv
cat temp_GCP_check/sampleId_RNA_GCP.tsv |  sort | uniq  > testfile.tmp && mv testfile.tmp temp_GCP_check/sampleId_RNA_GCP.tsv
wc -l temp_GCP_check/sampleId_RNA_GCP.tsv

echo 'Overlap between two files:'
comm -1 -2 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_RNA_GCP.tsv) | wc -l
echo 'Number of extra samples patientId_metadata.tsv:'
comm -2 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_RNA_GCP.tsv) | wc -l
if [ $4 -ne 0 ]
then
  comm -2 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_RNA_GCP.tsv)
fi
echo 'Number of extra samples patientId_DNA_GCP.tsv:'
comm -1 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_RNA_GCP.tsv) | wc -l
if [ $4 -ne 0 ]
then
  comm -1 -3 <(sort temp_GCP_check/sampleId_metadata.tsv) <(sort temp_GCP_check/sampleId_RNA_GCP.tsv)
fi

#######
echo ''
#######


jq '.data | .[] | .samples | .[] | .data | .[] | .tags | select(.[]=="RNA") | .[]' $2  > temp_GCP_check/files_GCP.tsv

echo 'number of seperate RNA FASTQ files shared within GCP:'
grep -c 'FASTQ' temp_GCP_check/files_GCP.tsv


# remove all temporary files
rm -r temp_GCP_check