#!/usr/bin/env bash

source locate_files
source metadata_functions

source_set_path=$1 && shift
dest_set_base_path=$1 && shift

set_name=$(basename ${source_set_path})
dest_set_path=${dest_set_base_path}/${set_name}
dest_set_path_gatk=${dest_set_path}/gatk
dest_set_path_purple=${dest_set_path}/purple

ref_sample=$(load_ref_sample_from_metadata ${source_set_path})

## init
mkdir -p ${dest_set_path}

## init gatk
mkdir -p ${dest_set_path_gatk}


## gather germline info
echo "[DEBUG] Symlinking gatk germline VCF (and tbi index) for ${set_name}"
ln -s $(locate_gatk_germline_variants ${source_set_path} ${ref_sample}) ${dest_set_path_gatk}
ln -s $(locate_gatk_germline_variants ${source_set_path} ${ref_sample}).tbi ${dest_set_path_gatk}
expected_file_count=2

## init purple
mkdir -p ${dest_set_path_purple}
purple_version=$(cat ${source_set_path}/purple/purple.version | grep version)

## gather germline info
echo "[DEBUG] Symlinking germline files for ${set_name} with having purple '${purple_version}'"
#ln -s $(locate_purple_germline_variants ${source_set_path}) ${dest_set_path_purple}
#ln -s $(locate_purple_germline_variants ${source_set_path}).tbi ${dest_set_path_purple}
ln -s ${source_set_path}/purple/*.purple.cnv.germline.tsv ${dest_set_path_purple}
#ln -s $(locate_purple_germline_driver_catalog ${source_set_path}) ${dest_set_path_purple}
expected_file_count=$( expr ${expected_file_count} + 1)

germline_file_count_gatk=$(ls ${dest_set_path_gatk} | wc -l)
germline_file_count_purple=$(ls ${dest_set_path_purple} | wc -l)
germline_file_count=$( expr ${germline_file_count_gatk} + ${germline_file_count_purple})
if [[ ${germline_file_count} -ne 3 ]]; then
    echo "[WARN] Found ${germline_file_count} which is different than expected for ${set_name} Please manually inspect!"
fi

