#!/usr/bin/env bash

metadata_tsv=$1 && shift
germline_dir=$1 && shift

cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
    set_path=/data/cpct/runs/${set_name}
    collect_germline_set_data ${set_path} ${germline_dir}
done