#!/usr/bin/env bash

source message_functions || exit 1

if [[ "$#" -ne 6 ]]; then
    echo "Usage: $(basename $0)"
    echo "      - dr_name (eg LUMC)"
    echo "      - request_name (eg LUMC_request_20200303)"
    echo "      - sample_selection_sql (eg /home/sandra/jobs/SQL_scripts/LUMC_request_20200303.sql)"
    echo "      - include_somatics (1 or 0)"
    echo "      - include_germline (1 or 0)"
    echo "      - include_tumor_patient_treatment_response_metadata (1 or 0)"
    exit 1
fi

dr_name=$1 && shift
request_name=$1 && shift
sample_selection_sql=$1 && shift
include_somatics=$1 && shift
include_germline=$1 && shift
include_tumor_patient_treatment_response_metadata=$1 && shift # This will become non-optional at some point.

base_path=/data/data_archive/datarequests

dr_base_path=${base_path}/${dr_name}
dr_path=${dr_base_path}/${request_name}

info "Composing hospital request ${request_name} in ${dr_path}"
info "   dr_name=${dr_name}"
info "   request_name=${request_name}"
info "   sample_selection_sql=${sample_selection_sql}"
info "   include_somatics=${include_somatics}"
info "   include_germline=${include_germline}"
info "   include_tumor_patient_treatment_response_metadata=${include_tumor_patient_treatment_response_metadata}"

create_base_directory_for_datarequest ${dr_path}
if [[ $? = 0 ]]; then
    log_dir=${dr_path}/logs
    mkdir -p ${log_dir}

    info "Selecting patients to include for ${request_name}..."
    cp ${sample_selection_sql} ${log_dir}/selectSamples.sql
    sample_selection_tsv=${log_dir}/selectSamples.tsv
    execute_sql_on_old_prod ${log_dir}/selectSamples.sql > ${sample_selection_tsv}
    patient_count=$(grep -cv "^#" ${sample_selection_tsv})
    info "Created ${sample_selection_tsv} with ${patient_count} samples"

    info "Creating metadata for ${request_name}..."
    metadata_dir_name=metadata
    metadata_dir=${dr_path}/${metadata_dir_name}
    mkdir -p ${metadata_dir}
    metadata_tsv=${metadata_dir}/metadata.tsv
    generate_metadata_hospital_request \
        ${sample_selection_tsv} \
        ${log_dir} \
        ${metadata_tsv} \
        ${include_tumor_patient_treatment_response_metadata}

    if [[ $? = 1 ]]; then
        # Propogate error upstream to caller of this function.
        exit 1;
    fi

    sample_count=$(grep -cv "^#" ${metadata_tsv})
    info "Created ${metadata_tsv} with ${sample_count} samples"

    if [[ ${include_somatics} == "1" ]]; then
        info "Collecting somatic data for ${request_name}..."
        somatic_dir_name=somatics
        somatics_dir=${dr_path}/${somatic_dir_name}
        mkdir -p ${somatics_dir}
        collect_all_somatic_set_data_for_request ${metadata_tsv} ${somatics_dir} ${include_germline}
        somatics_sample_count=$(ls ${somatics_dir} | wc -l)
        somatic_tar_file=${dr_base_path}/${request_name}.somatics.tar
        info "Done collecting somatics for DR. Found ${somatics_sample_count} samples. Creating TAR at ${somatic_tar_file}"
        create_tar_file ${somatic_tar_file} ${dr_path} ./${somatic_dir_name} ${log_dir}/tar_${request_name}_somatics.log
    else
        info "Skipped somatics collection as not deemed relevant for ${request_name}"
    fi

    if [[ ${include_germline} == "1" ]]; then
        info "Collecting germline data for ${request_name}..."
        germline_dir_name=germline
        germline_dir=${dr_path}/${germline_dir_name}
        mkdir -p ${germline_dir}
        collect_all_germline_set_data_for_request ${metadata_tsv} ${germline_dir}
        germline_sample_count=$(ls ${germline_dir} | wc -l)
        germline_tar_file=${dr_base_path}/${request_name}.germline.tar
        info "Done collecting germline data for DR. Found ${germline_sample_count} samples. Creating TAR at ${germline_tar_file}"
        create_tar_file ${germline_tar_file} ${dr_path} ./${germline_dir_name} ${log_dir}/tar_${request_name}_germline.log
    else
        info "Skipped germline collection as not deemed relevant for ${request_name}"
    fi

    metadata_tar_file=${dr_base_path}/${request_name}.metadata.tar
    info "Creating metadata TAR file at ${metadata_tar_file}"
    create_tar_file ${metadata_tar_file} ${dr_path} ./${metadata_dir_name} ${log_dir}/tar_${request_name}_metadata.log

    info "Composing datarequest for ${request_name} completed!"
else
    error "Could not create base directory structure for DR ${dr_name}"
fi

