#!/usr/bin/env bash

source message_functions || exit 1

dr_path=$1 && shift

if [[ -z "${dr_path}" ]]; then
    echo "Usage: $(basename $0) dr_path"
    echo "   eg $(basename $0) /data/data_archive/datarequests/DR-028/DR-028-update2"
    exit 1
fi

info "Creating base directory structure at ${dr_path}"
if [[ -d "${dr_path}" ]]; then
    error "Directory already exists: ${dr_path}. Exiting"
fi

mkdir -p "${dr_path}"

info "Finished creating DR base directory at ${dr_path}"