#!/usr/bin/env bash

dr_path=$1 && shift

if [[ -z "${dr_path}" ]]; then
    echo "Usage: $(basename $0) dr_path"
    echo "   eg $(basename $0) /data/data_archive/datarequests/DR-028/DR-028-update2"
    exit 1
fi

echo "[DEBUG] Creating base directory structure at ${dr_path}"
if [[ -d "${dr_path}" ]]; then
    echo "[WARN] Directory already exists: ${dr_path}. Exiting" && exit 1
fi

mkdir -p "${dr_path}"

echo "[DEBUG] Finished creating DR base directory at ${dr_path}"