#!/usr/bin/env bash

prefix=$(dirname $(readlink $0 || echo $0))

metadata_tsv=$1 && shift
log_dir=$1 && shift
metadata_dir=$1 && shift

do_generate_extra_clinical_data ${metadata_tsv} ${log_dir} ${metadata_dir} "rano_measurements_by_patient" ${prefix}/sql_rano_measurements_by_patient.sql