#!/usr/bin/env bash

print_usage(){
    echo "-----"
    echo " Descr: Get data from BizzMine"
    echo " Usage: $(basename $0) -i <dr-id>"
    echo " Exmpl: $(basename $0) -i 'DR-001'"
    echo "-----"
    exit 1
}

while getopts ':i:' flag; do
    case "${flag}" in
        i) dr_id=${OPTARG} ;;
        *) print_usage
        exit 1 ;;
    esac
done

if [[ -z "${dr_id}" ]]; then
    echo "[ERROR] script get_data_from_BizzMine did not run, check usage below:"
    print_usage
fi


api_url=$"https://api.bizzmine.cloud/collection/DataRequests/"
api_token=$"/data/common/dbs/api_credentials/bizzmine/api_token"

## quick input checks
[[ ! -z "${dr_id}" && "${dr_id}" =~ ^DR ]] || die "dr-id incorrect (${dr_id})?"

release_id=$"${dr_id}"

## start with script
echo ""
echo "[START] get_data_from_BizzMine: $(date +"%y%m%d (%T)")"
echo ""

datarequest_id=$( curl get -s -H "x-token: ${api_token}" -H "x-tenant: hartwigmedicalfoundation" https://api.bizzmine.cloud/collection/DataRequests/instances | jq --arg DR_select "$release_id" '.[] | select(.DataRequests_DR_1_0_Datarequest_referencenumber==$DR_select) | .DataRequests_DataRequestsID | .[]')
curl get -s -H "x-token: ${api_token}" -H "x-tenant: hartwigmedicalfoundation" https://api.bizzmine.cloud/collection/DataRequests/instance/${datarequest_id} | jq .[]
