#!/usr/bin/env bash

echo ""
gcloud config set project hmf-share


base_path="/data/data_archive/validation_data/latest_tooling_pipeline_runs"
colo_folder=$( ls ${base_path} | grep "COLO" )
source_set_path="${base_path}/${colo_folder}"
#
dest_base_path="/data/data_archive/datarequests/colo"
#
colo_exists=$( ls $dest_base_path | grep ${colo_folder})
if [[ "$colo_exists" == "" ]]; then
    echo ""
    echo "[START] REFRESH COLO DATA ON GCP: $(date +"%y%m%d (%T)")"
    echo ""
    mkdir ${dest_base_path}/${colo_folder}
    dest_set_base_path="${dest_base_path}/${colo_folder}"
    #
    somatic_tar_file="${dest_base_path}/${colo_folder}.somatics.tar"
    germline_tar_file="${dest_base_path}/${colo_folder}.germline.tar"
    #
    include_germline=1
    
    collect_somatic_set_data ${source_set_path} ${dest_set_base_path}/somatics ${include_germline}
    create_tar_file ${somatic_tar_file} ${dest_base_path} ${dest_set_base_path}/somatics ${dest_set_base_path}/tar_${colo_folder}_somatics.log
    
    collect_germline_set_data ${source_set_path} ${dest_set_base_path}/germline
    create_tar_file ${germline_tar_file} ${dest_base_path} ${dest_set_base_path}/germline  ${dest_set_base_path}/tar_${colo_folder}_germline.log

    gsutil -u hmf-share rm gs://hmf-dr-colo/*
    gsutil -u hmf-share cp ${dest_base_path}/*.tar gs://hmf-dr-colo/
    echo "[INFO] latest version added to hmf-dr-colo on GCP."
    echo "[INFO] Files in the bucket hmf-dr-colo:"
    gsutil -u hmf-share du -h gs://hmf-dr-colo/
    echo ""

    echo ""
    echo "[START] REFRESH COLO DATA ON NEXT CLOUD: $(date +"%y%m%d (%T)")"
    echo ""
    #tar -cvf "DR-COLO-Example.tar.gz" ${somatic_tar_file} ${germline_tar_file} /at the moment only somatic data since very large file!
    tar -cvf "DR-COLO-Example.tar.gz" ${somatic_tar_file}
    do_upload_files_to_nextcloud_directory UPLOAD DR-COLO-Example.tar.gz
    echo "[INFO] The DR-COLO-Example.tar.gz file has been uploaded on NextCloud to the UPLOAD folder. Please move manually to PUBLIC/Data-Access-Requests."
    echo ""
else
    echo ""
    echo "[START] NO REFRESH NEEDED, lATEST VERSION ALREADY ON GCP AND NEXTCLOUD."
    echo ""
    echo "[INFO] Files in the GCP bucket hmf-dr-colo:"
    gsutil -u hmf-share du -h gs://hmf-dr-colo/
    echo ""
    echo "[INFO] Check NextCloud (PUBLIC/Data-Access-Requests) manually to be sure the DR-COLO-Example.tar.gz file is there with the latest data."
    echo ""
fi




