#!/usr/bin/env bash

source locate_files

sample=$1 && shift
credentials=$1 && shift

if [[ -z "${sample}" || -z "${credentials}" ]]; then
    echo "[ERROR] No sample and/or credentials provided. Exiting."
    exit 1
fi

db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

sig_analyser=/data/common/tools/sig-analyser_pilot/sig-analyser.jar
cosmic_signatures=/data/common/dbs/sigs/snv_cosmic_sigs.csv
output_dir=/this/does/not/exist

echo "[INFO] Loading sv signatures data for ${sample}"

java -cp ${sig_analyser} com.hartwig.hmftools.sig_analyser.fitter.SampleFitter \
    -sample ${sample} \
    -signatures_file ${cosmic_signatures} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -position_bucket_size 500000 -max_sample_count 20000 \
    -output_dir ${output_dir} \
    -log_debug