#!/usr/bin/env bash

source locate_files
source metadata_functions

run_dir=$1

if [[ -z "${run_dir}" ]]; then
    echo "[ERROR] No run directory provided. Exiting."
    exit 1
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

credentials=$(locate_prod_database_credentials)
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

sig_analyser=/data/common/tools/sig-analyser_pilot/sig-analyser.jar
cosmic_signatures=/data/common/dbs/sigs/snv_cosmic_sigs.csv
output_dir=/this/does/not/exist

java -cp ${sig_analyser} com.hartwig.hmftools.sig_analyser.fitter.SampleFitter \
    -sample ${sampleId} \
    -signatures_file ${snv_cosmic_sigs} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -position_bucket_size 500000 -max_sample_count 20000 \
    -output_dir ${output_dir} \
    -log_debug