#!/usr/bin/env bash

source metadata_functions || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run directory provided. Exiting."
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

sigs_jar=/data/common/tools/sigs_pilot/sigs.jar
cosmic_signatures=/data/common/dbs/sigs/snv_cosmic_sigs.csv
output_dir=${run_dir}/sigs_pilot

info "Running sigs for ${sample}"

java -cp ${sigs_jar} com.hartwig.hmftools.sigs.fitter.SampleFitter \
    -sample ${sample} \
    -signatures_file ${cosmic_signatures} \
    -position_bucket_size 500000 -max_sample_count 20000 \
    -output_dir ${output_dir} \
    -log_debug