#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run directory provided. Exiting."
fi

sigs_jar=$(locate_pilot_sigs)
output_dir=$(locate_sigs_pilot_dir ${run_dir})

info "Running sigs pilot for on ${run_dir}"

do_run_sigs ${run_dir} ${sigs_jar} ${output_dir}
