#!/usr/bin/env bash

source message_functions || exit 1

if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
    echo "-----"
    echo " Usage: $(basename $0) <CRAM file>"
    echo "-----"
    exit 1
fi

cram=$1

## use 90 percent of available threads
threads=$(($(nproc) * 9 / 10))
samtools="/opt/tools/samtools/1.10/samtools" # GCP VMs path

## reset paths for use at various VMs based on base-vm
if [[ ! -f "$samtools" ]]; then
    samtools="/data/tools/samtools/1.10/samtools"
fi

main() {
    info "Starting with $(basename $0)"
    
    ## sanity checks
    command -v "${samtools}" >/dev/null 2>&1 || error "${samtools} not found"
    [[ -f "${cram}" ]] || error "File not found (${cram})"
    [[ "${cram}" =~ cram$ ]] || error "Not a CRAM file (${cram})"

    ## variables setup
    bam=$(echo "${cram}" | sed 's/cram$/bam/')

    ## jobs
    info "Config: using samtools (${samtools})"
    info "Converting ${cram} to ${bam} (with samtools view)"
    ${samtools} view -O bam -o "${bam}" --threads "${threads}" "${cram}"

    info "Creating flagstat for ${cram}"
    cram_flagstat="${cram}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}"

    info "Creating flagstat for ${bam}"
    bam_flagstat="${bam}.flagstat"
    ${samtools} flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}"

    total_cram=$(cat ${cram_flagstat} | head -1 | cut -d" " -f1)
    total_bam=$(cat ${bam_flagstat} | head -1 | cut -d" " -f1)

    info "File ${cram_flagstat} shows ${total_cram} total reads"
    info "File ${bam_flagstat} shows ${total_bam} total reads"

    info "Running diff on flagstats"
    diff ${cram_flagstat} ${bam_flagstat}
    if [[ $? -ne 0 ]]; then 
        warn "Flagstat diff failed: check result before using downstream!!"
    fi

    info "Finished with $(basename $0)"
}

main
