#!/usr/bin/env bash

bam=$1 && shift

if [[ ! -f "${bam}" ]]; then
    echo "[ERROR] Bam is not a file: ${bam}. Exiting" && exit 1
fi

java -cp /data/common/tools/gridss_v2.9.3/gridss.jar gridss.analysis.CollectGridssMetrics I=${bam} O=${bam} THRESHOLD_COVERAGE=50000
