#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

cram=$1 && shift

if [[ ! -f "${cram}" ]]; then
    error "Cram is not a file: ${cram}. Exiting"
fi

samtools=/data/common/tools/samtools_v1.10/samtools
ref_genome=$(locate_ref_genome_37_fasta_file_ds)

echo "-----"
echo "## Printing header part"
${samtools} view -H "${cram}"

echo "-----"
echo "## Printing data part (head 3) with -T ref genome"
${samtools} view -T ${ref_genome} "${cram}" | head -3

echo "-----"
echo "## Printing data part (head 3) without -T ref genome"
${samtools} view "${cram}" | head -3
