#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/prod_output_ckb_latest_based"
create_or_cleanup_dir ${output_dir}

ckb_dir="$(locate_ckb_flex_data_latest_dir)"
ckb_filter_tsv="$(locate_ckb_filter_tsv)"
ckb_drug_class_curation_tsv="$(locate_ckb_drug_class_curation_tsv)"
iclusion_trial_tsv="$(locate_prod_iclusion_trial_tsv)"
iclusion_filter_tsv="$(locate_iclusion_filter_tsv)"
docm_tsv="$(locate_docm_tsv)"
hartwig_cohort_tsv="$(locate_hartwig_cohort_hotspots_tsv)"
hartwig_curated_tsv="$(locate_hartwig_curated_hotspots_tsv)"
missing_doids_mapping_tsv="$(locate_private_missing_doids_mapping_tsv)"

do_run_serve_prod \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_ckb -ckb_dir ${ckb_dir} -ckb_filter_tsv ${ckb_filter_tsv} -ckb_drug_curation_tsv ${ckb_drug_class_curation_tsv} \
    -use_iclusion -iclusion_trial_tsv ${iclusion_trial_tsv} -iclusion_filter_tsv ${iclusion_filter_tsv} \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -output_dir ${output_dir} \
    -skip_hotspot_resolving \
    "$@"
