#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_all_sources"
create_or_cleanup_dir ${output_dir}

ckb_dir=$(locate_ckb_flex_data_latest_dir)
ckb_filter_tsv=$(locate_ckb_filter_pilot_tsv)
ckb_drug_class_curation_tsv=$(locate_ckb_drug_class_curation_tsv)
iclusion_trial_tsv=$(locate_latest_iclusion_trial_tsv)
iclusion_filter_tsv=$(locate_iclusion_filter_tsv)
vicc_json=$(locate_vicc_json)
docm_tsv=$(locate_docm_tsv)
hartwig_cohort_hotspot_tsv=$(locate_hartwig_cohort_hotspots_tsv)
hartwig_curated_hotspot_tsv=$(locate_hartwig_curated_hotspots_tsv)
hartwig_curated_gene_tsv=$(locate_hartwig_curated_genes_tsv)
missing_doids_mapping_tsv=/data/resources/crunch/serve/curation/all_doids_mapping.tsv

#TODO (ACTIN-4) Add hartwig_curated_gene_tsv
do_run_serve_pilot \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_ckb -ckb_dir ${ckb_dir} -ckb_filter_tsv ${ckb_filter_tsv} -ckb_drug_curation_tsv ${ckb_drug_class_curation_tsv} \
    -use_iclusion -iclusion_trial_tsv ${iclusion_trial_tsv} -iclusion_filter_tsv ${iclusion_filter_tsv} \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort_hotspots -hartwig_cohort_hotspot_tsv ${hartwig_cohort_hotspot_tsv} \
    -use_hartwig_curated_hotspots -hartwig_curated_hotspot_tsv ${hartwig_curated_hotspot_tsv} \
    -use_hartwig_driver_genes \
    -use_hartwig_curated_genes -hartwig_curated_gene_tsv ${hartwig_curated_gene_tsv} \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -output_dir ${output_dir} \
    -skip_hotspot_resolving \
    "$@"
