#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/research_output_public_only"
create_or_cleanup_dir ${output_dir}

vicc_json="$(locate_vicc_json)"
docm_tsv="$(locate_docm_tsv)"
hartwig_cohort_hotspot_tsv="$(locate_hartwig_cohort_hotspots_tsv)"
hartwig_curated_hotspot_tsv="$(locate_hartwig_curated_hotspots_tsv)"
hartwig_curated_gene_tsv="$(locate_hartwig_curated_genes_tsv)"
missing_doids_mapping_tsv="$(locate_public_missing_doids_mapping_tsv)"

do_run_serve_research \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_hartwig_cohort -hartwig_cohort_tsv ${hartwig_cohort_tsv} \
    -use_hartwig_curated -hartwig_curated_tsv ${hartwig_curated_tsv} \
    -use_hartwig_cohort_hotspots -hartwig_cohort_hotspot_tsv ${hartwig_cohort_hotspot_tsv} \
    -use_hartwig_curated_hotspots -hartwig_curated_hotspot_tsv ${hartwig_curated_hotspot_tsv} \
    -use_hartwig_driver_genes \
    -use_hartwig_curated_genes -hartwig_curated_gene_tsv ${hartwig_curated_gene_tsv} \
    -output_dir ${output_dir} \
    "$@"
