#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/actin_output_hartwig_only"
create_or_cleanup_dir ${output_dir}

hartwig_cohort_hotspot_tsv="$(locate_hartwig_cohort_hotspots_tsv)"
hartwig_curated_hotspot_tsv="$(locate_hartwig_curated_hotspots_tsv)"
hartwig_curated_gene_tsv="$(locate_hartwig_curated_genes_tsv)"

do_run_serve_actin \
    -use_hartwig_cohort_hotspots -hartwig_cohort_hotspot_tsv ${hartwig_cohort_hotspot_tsv} \
    -use_hartwig_curated_hotspots -hartwig_curated_hotspot_tsv ${hartwig_curated_hotspot_tsv} \
    -use_hartwig_driver_genes \
    -use_hartwig_curated_genes -hartwig_curated_gene_tsv ${hartwig_curated_gene_tsv} \
    -output_dir ${output_dir} \
    "$@"