#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_ckb_based"
create_or_cleanup_dir ${output_dir}

ckb_dir="$(locate_ckb_flex_data_latest_dir)"
ckb_molecular_profile_filter_tsv="$(locate_ckb_molecular_profile_filter_pilot_tsv)"
ckb_evidence_filter_tsv="$(locate_ckb_evidence_filter_pilot_tsv)"
ckb_trial_filter_tsv="$(locate_ckb_trial_filter_pilot_tsv)"
ckb_drug_curation_tsv="$(locate_ckb_drug_curation_tsv)"
ckb_regions_to_include_tsv="$(locate_ckb_regions_actin_nl_tsv)"
ckb_facility_curation_name_tsv="$(locate_ckb_facility_curation_name_tsv)"
ckb_facility_curation_zip_tsv="$(locate_ckb_facility_curation_zip_tsv)"
ckb_facility_curation_manual_tsv="$(locate_ckb_facility_curation_manual_tsv)"

vicc_json="$(locate_vicc_json)"
vicc_missing_doids_mapping_tsv="$(locate_vicc_missing_doids_mapping_tsv)"

docm_tsv="$(locate_docm_tsv)"
hartwig_cohort_hotspot_tsv="$(locate_hartwig_cohort_hotspots_tsv)"
hartwig_curated_hotspot_tsv="$(locate_hartwig_curated_hotspots_tsv)"
hartwig_curated_gene_tsv="$(locate_hartwig_curated_genes_tsv)"

do_run_serve_pilot \
    -use_ckb -ckb_dir ${ckb_dir} \
    -ckb_molecular_profile_filter_tsv ${ckb_molecular_profile_filter_tsv} \
    -ckb_evidence_filter_tsv ${ckb_evidence_filter_tsv} \
    -ckb_trial_filter_tsv ${ckb_trial_filter_tsv} \
    -ckb_regions_to_include_tsv ${ckb_regions_to_include_tsv} \
    -ckb_drug_curation_tsv ${ckb_drug_curation_tsv} \
    -ckb_facility_curation_name_tsv ${ckb_facility_curation_name_tsv} \
    -ckb_facility_curation_zip_tsv ${ckb_facility_curation_zip_tsv} \
    -ckb_facility_curation_manual_tsv ${ckb_facility_curation_manual_tsv} \
    -use_docm -docm_tsv ${docm_tsv} \
    -use_vicc -vicc_json ${vicc_json} -vicc_sources cgi,civic \
    -vicc_missing_doids_mapping_tsv ${vicc_missing_doids_mapping_tsv} \
    -use_hartwig_cohort_hotspots -hartwig_cohort_hotspot_tsv ${hartwig_cohort_hotspot_tsv} \
    -use_hartwig_curated_hotspots -hartwig_curated_hotspot_tsv ${hartwig_curated_hotspot_tsv} \
    -use_hartwig_driver_genes \
    -use_hartwig_curated_genes -hartwig_curated_gene_tsv ${hartwig_curated_gene_tsv} \
    -output_dir ${output_dir} \
    "$@"
