#!/usr/bin/env bash

source locate_files || exit 1
source io_functions || exit 1

output_dir="/data/output/pilot_output_ckb_trials_only"
create_or_cleanup_dir ${output_dir}

ckb_dir="$(locate_ckb_flex_data_latest_dir)"
ckb_blacklist_molecular_profile_tsv="$(locate_ckb_blacklist_molecular_profile_pilot_tsv)"
ckb_blacklist_studies_tsv="$(locate_ckb_blacklist_studies_pilot_tsv)"
ckb_drug_curation_tsv="$(locate_ckb_drug_curation_tsv)"
ckb_facility_city_tsv="$(locate_ckb_facility_city_tsv)"
ckb_facility_name_tsv="$(locate_ckb_facility_name_tsv)"
ckb_facility_zip_tsv="$(locate_ckb_facility_zip_tsv)"
ckb_regions_tsv="$(locate_ckb_regions_tsv)"

missing_doids_mapping_tsv="$(locate_private_missing_doids_mapping_tsv)"

do_run_serve_pilot \
    -missing_doids_mapping_tsv ${missing_doids_mapping_tsv} \
    -use_ckb_trials -ckb_dir ${ckb_dir} -ckb_blacklist_molecular_profile_tsv ${ckb_blacklist_molecular_profile_tsv} -ckb_drug_curation_tsv ${ckb_drug_curation_tsv} -ckb_blacklist_trial_tsv ${ckb_blacklist_studies_tsv} -ckb_region_tsv ${ckb_regions_tsv}\
    -ckb_facility_city_tsv ${ckb_facility_city_tsv} -ckb_facility_name_tsv ${ckb_facility_name_tsv} -ckb_facility_zip_tsv ${ckb_facility_zip_tsv} \
    -output_dir ${output_dir} \
    "$@"
