#!/usr/bin/env bash

source message_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

echo "Running ACTIN in historic mode"

actin_treatment_matcher_pilot ${patient} -run_historically

echo ""

load_actin_treatment_match_pilot ${patient}