#!/usr/bin/env bash

source message_functions || exit 1

patient=$1 && shift
sample_postfix=$1 && shift

if [[ -z "${patient}" || -z "${sample_postfix}" ]]; then
    error "Parameters missing. Exiting.";
fi

actin_treatment_matcher_pilot ${patient} ${sample_postfix}

echo ""

create_actin_evaluation_data_for_sample ${patient} ${sample_postfix}

echo ""

actin_reporter_pilot ${patient} ${sample_postfix}

echo ""

load_actin_treatment_match_pilot ${patient}