#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

mcgi_patient=$1 && shift

if [[ -z "${mcgi_patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

actin_molecular_interpreter_mcgi ${mcgi_patient} "$@"

echo ""

actin_treatment_matcher_mcgi ${mcgi_patient}

echo ""

actin_reporter_mcgi ${mcgi_patient}