#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

info "Running ACTIN in historic mode"

sample=$(locate_most_recent_actin_molecular_sample ${patient})

actin_molecular_interpreter_pilot ${sample}

echo ""

actin_treatment_matcher_pilot ${patient} -run_historically
