#!/usr/bin/env bash

source message_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting.";
fi

actin_treatment_matcher_pilot ${sample}

echo ""

actin_reporter_pilot ${sample}