#!/usr/bin/env bash

patient_id=$1
project_id=${2:-actin-prod}

if [[ -z "${patient_id}" ]]; then
    error "Parameters missing. Exiting.";
fi

gcloud pubsub topics publish projects/${project_id}/topics/analysis-pipeline.pending \
    --message="{\"patientId\": \"${patient_id}\", \"trigger\": \"MANUAL\"}"