#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source message_functions || exit 1
source database_functions || exit 1

run=$1 && shift
sample=$1 && shift

if [[ -z "${run}" ]]; then
    error "No run passed. Exiting"
fi

if [[ -z "${sample}" ]]; then
    error "No sample passed. Exiting"
fi
protect_evidence_tsv=$(find -L /data/experiments/verification/verification_reporting_gene_panel_1_0_6/pilot_beta13/${run}/protect -type f -name "protect.tsv")

database="hmfpatients_pilot"
credentials=$(diagnostic_writer_sql_credentials)
patient_db_jar="/data/experiments/pilot_tools/database_oncoact/database-jar-with-dependencies.jar"

do_load_protect_data ${sample} ${protect_evidence_tsv} ${database} "${credentials}" ${patient_db_jar}