#!/bin/bash

consensus_rule_dir=/data/common/tools/consensusrulefilter_v1.0
high_confidence_bed="$consensus_rule_dir"/bed/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed
extreme_confidence_bed="$consensus_rule_dir"/bed/CPCT_Slicing.bed

exec java -Xmx16G -Xms8G \
    -jar "$consensus_rule_dir"/consensus-rule-filter.jar \
    -high_confidence_bed "$high_confidence_bed" \
    -extreme_confidence_bed "$extreme_confidence_bed" \
    "$@"