#!/usr/bin/env bash

source locate_files || exit 1

ckb_flex_directory="$(locate_actin_ckb_flex_directory)"

actin_jar="$(locate_pilot_actin)"

info "Running ACTIN CKB-Database Reader on ${ckb_flex_directory}"

java -cp ${actin_jar} com.hartwig.actin.ckb.CkbDatabaseReaderApplication  \
    -ckb_flex_directory ${ckb_flex_directory} \
    "$@"

