#!/usr/bin/env bash

for d in $(find /data/repos/scripts/* -type d | grep -v '\.git'); do
    export PATH="${PATH}:$d"
done

mkdir -p ~/.mvn
cp /data/repos/scripts/mvn/extensions.xml ~/.mvn/

# Collection of handy aliases
alias cronjobs='echo "# /etc/cron.d/hmfcrons" && cat /etc/cron.d/hmfcrons'
alias format='datamash transpose | column -t'
