#!/usr/bin/env bash

source locate_files || exit 1

actin_nki_config_file="$(locate_actin_nki_config_file)"

do_run_actin_trial_creation "nki_config_directory" "-override_yaml" "${actin_nki_config_file}"
