#!/usr/bin/env bash

source locate_files

iclusion_api_credentials=$1 && shift

knowledgebase_importer_jar=$(locate_pilot_knowledgebase_importer)

iclusion_endpoint=$(awk '/^endpoint/ {print $2}' ${iclusion_api_credentials})
iclusion_client_id=$(awk '/^client_id/ {print $2}' ${iclusion_api_credentials})
iclusion_client_secret=$(awk '/^client_secret/ {print $2}' ${iclusion_api_credentials})
iclusion_user=$(awk '/^username/ {print $2}' ${iclusion_api_credentials})
iclusion_password=$(awk '/^password/ {print $2}' ${iclusion_api_credentials})

ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

input_dir=/data/common/dbs/knowledgebases/input
cgi_biomarkers_file=${input_dir}/cgi_biomarkers_per_variant_181127.tsv
cgi_validated_file=${input_dir}/cgi_catalog_of_validated_oncogenic_mutations_181127.tsv
onco_annotated_file=${input_dir}/onco_allAnnotatedVariants_181127.csv
onco_actionable_file=${input_dir}/onco_allActionableVariants_181127.csv
doid_file=${input_dir}/doid_181127.owl
cosmic_fusions_file=${input_dir}/171127_cosmic_gene_fusions.csv
civic_evidence_file=${input_dir}/civic_01-Nov-2018-ClinicalEvidenceSummaries_181127.tsv
civic_variants_file=${input_dir}/civic_01-Nov-2018-VariantSummaries_181127.tsv

transvar_command=transvar
treatment_type_mapping_file=/data/common/dbs/knowledgebases/pilot_treatmentTypes.tsv
output_dir=/data/common/dbs/knowledgebases/pilot_output

rm -r ${output_dir}
java -jar ${knowledgebase_importer_jar} \
    -reference ${ref_genome} \
    -transvar_location ${transvar_command} \
    -doid_owl_location ${doid_file} \
    -treatment_type_mapping_location ${treatment_type_mapping_file} \
    -onco_annotated_location ${onco_annotated_file} \
    -onco_actionable_location ${onco_actionable_file} \
    -cgi_validated_location ${cgi_validated_file} \
    -cgi_biomarkers_location ${cgi_biomarkers_file} \
    -civic_variants_location ${civic_variants_file} \
    -civic_evidence_location ${civic_evidence_file} \
    -cosmic_fusions_location ${cosmic_fusions_file} \
    -iclusion_endpoint ${iclusion_endpoint} \
    -iclusion_client_id ${iclusion_client_id} \
    -iclusion_client_secret ${iclusion_client_secret} \
    -iclusion_user ${iclusion_user} \
    -iclusion_password ${iclusion_password} \
    -output_dir ${output_dir} \
    "$@"