#!/usr/bin/env bash

current_dir=`dirname $(readlink $0 || echo $0)`
iclusion_api_credentials=/data/common/dbs/api_credentials/iclusion_pilot

${current_dir}/do_run_knowledgebase_importer_pilot ${iclusion_api_credentials}