#!/usr/bin/env bash

prefix=$(dirname $(readlink $0 || echo $0))
iclusion_api_credentials=/data/common/dbs/api_credentials/iclusion_prod

${prefix}/do_run_knowledgebase_importer_pilot ${iclusion_api_credentials}