#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift
virus_interpreter_jar=$1 && shift
output_dir=$1 && shift

sample_id=$(load_tumor_sample_from_metadata ${run_dir})
virus_breakend_tsv=$(locate_virus_breakend_tsv ${run_dir})

taxonomy_db_tsv="/data/resources/public/virus_interpreter/taxonomy_db.tsv"
virus_reporting_db_tsv="/data/resources/public/virus_interpreter/virus_reporting_db_v1_1.tsv"

purple_purity_tsv=$(locate_purple_purity ${run_dir})
purple_qc_file=$(locate_purple_qc ${run_dir})
tumor_sample_wgs_metrics_file=$(locate_wgs_metrics ${run_dir} ${sample_id})

java -jar ${virus_interpreter_jar} \
    -sample_id ${sample_id} \
    -virus_breakend_tsv ${virus_breakend_tsv} \
    -taxonomy_db_tsv ${taxonomy_db_tsv} \
    -virus_reporting_db_tsv ${virus_reporting_db_tsv} \
    -purple_purity_tsv ${purple_purity_tsv} \
    -purple_qc_file ${purple_qc_file} \
    -tumor_sample_wgs_metrics_file ${tumor_sample_wgs_metrics_file} \
    -output_dir ${output_dir} \
    "$@"