#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

output_dir=${run_dir}/virusbreakend
virus_interpreter_jar=/data/common/tools/virus-interpreter_v1.0/virus-interpreter.jar

do_run_virus_interpreter ${run_dir} ${virus_interpreter_jar} ${output_dir}
