#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source io_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

output_dir="${run_dir}/virus_interpreter"
create_or_cleanup_dir ${output_dir}

virus_interpreter_jar=$(locate_pilot_virus_interpreter)

do_run_virus_interpreter ${run_dir} ${virus_interpreter_jar} ${output_dir} -log_debug
