#!/usr/bin/env bash

source_set_path=$1 && shift
dest_set_base_path=$1 && shift

set_name=$( basename ${source_set_path} )
dest_set_path=${dest_set_base_path}/${set_name}

## init
mkdir -p ${dest_set_path}

## gather germline info
echo "[DEBUG] Symlinking Germline VCF (and tbi index) for ${set_name}"
for germline_vcf_path in $( find ${source_set_path} -mindepth 1 -maxdepth 1 -name "*.annotated.vcf.gz" ); do
    ln -s ${germline_vcf_path} ${dest_set_path}
    ln -s ${germline_vcf_path}.tbi ${dest_set_path}
done

germline_file_count=$( ls ${dest_set_path} | wc -l)
if [ ${germline_file_count} > 2 ]; then
    echo "[WARN] Found more than 2 germline files for ${set_name}. Please manually inspect!"
fi

