#!/usr/bin/env bash

dr_path=$1 && shift

if [ -z "${dr_path}" ]; then
    echo "Usage: create_base_directory_structure_for_data_request dr_path"
    echo "   eg create_base_directory_structure_for_data_request /data/data_archive/datarequests/DR-028/DR-028-update2"
    exit 1
fi

echo "[INFO] Creating base directory structure at ${dr_path}"
if [ -d ${dr_path} ]; then
    echo "[WARN] Directory already exists: ${dr_path}. Exiting"
    exit 1
fi

# Create directories which always exist for every DR
mkdir -p ${dr_path}
mkdir ${dr_path}/logs
mkdir ${dr_path}/metadata

echo "[INFO] Finished creating structure at ${dr_path}"