#!/usr/bin/env bash

setPath=$1
setName=$( basename ${setPath} )
destDir=./somatics/${setName}

if [[ ! -d ${setPath} ]]; then echo "[EXIT] From dir not found ($setPath)" && exit 1; fi
if [[ ! -w $PWD ]]; then echo "[EXIT] Dir not writable ($PWD)" && exit 1; fi

## init
mkdir -p ${destDir}

## start symlinking
echo "[INFO] Symlinking files for ${setName}"
ln -s ${setPath}/purple/purple.version ${destDir}
# TODO Remove germline if only somatic access granted.
ln -s ${setPath}/purple/*.purple.cnv.germline.tsv ${destDir}
ln -s ${setPath}/purple/*.purple.cnv.somatic.tsv ${destDir}
ln -s ${setPath}/purple/*.purple.cnv.gene.tsv ${destDir}
ln -s ${setPath}/purple/*.purple.purity.tsv ${destDir}
ln -s ${setPath}/purple/*.purple.purity.range.tsv ${destDir}
ln -s ${setPath}/purple/*.purple.qc ${destDir}
ln -s ${setPath}/purple/*.purple.sv.ann.vcf.gz ${destDir}
ln -s ${setPath}/purple/*.purple.sv.ann.vcf.gz.tbi ${destDir}
ln -s ${setPath}/purple/plot/*.circos.png ${destDir}
ln -s ${setPath}/purple/*.purple.somatic.vcf.gz ${destDir}
ln -s ${setPath}/purple/*.purple.somatic.vcf.gz.tbi ${destDir}