#!/usr/bin/env bash

vicc_file=$1 && shift
credentials=$1 && shift
vicc_jar=$1 && shift

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Loading vicc into SQL"

mysql vicc_db --user=${db_user} --password=${db_pass} < /data/experiments/knowledgebase_vicckb/create_vicc_database.sql

java -Dorg.jooq.no-logo=true -cp ${vicc_jar} com.hartwig.hmftools.vicc.ViccJsonToSQLImporter \
    -vicc_file ${vicc_file} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"
