#!/usr/bin/env bash

source locate_files

vicc_json=/data/common/dbs/vicc/all.json
credentials=$(locate_vicc_database_credentials)
vicc_jar=$(locate_pilot_vicc)

do_load_vicc_knowledgebase ${vicc_json} ${credentials} ${vicc_jar}