#!/usr/bin/env bash

source database_functions || exit 1

ckb_jar=$1 && shift
ckb_db=$1 && shift
ckb_dir=$1 && shift

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" "${ckb_db}")

info "Loading CKB database into ${db_url}"

java -Xms2G -Xmx10G -jar ${ckb_jar} \
    -ckb_dir ${ckb_dir} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"