#!/usr/bin/env bash

source message_functions || exit 1

MIN_ARRIVAL_DATE="2022-01-01"
LAMA_API_URL="http://lama-preview.prod-1/api"
REPORT_SHARED_TSV="/data/ops/lims/prod/sharing_db_generated.tsv"
UNREPORTABLE_TSV="/data/ops/lims/prod/samples_without_pdf_report.tsv"
LAMA_FINISHED_STATUS="FINISHED"

info "Retrieving samples from LAMA with arrival date [$MIN_ARRIVAL_DATE] or later"
info "  LAMA url: $LAMA_API_URL"
samples=$(curl --silent "${LAMA_API_URL}/tumor-samples/between?start-date=${MIN_ARRIVAL_DATE}")
sample_count=$(jq 'length' <<< "$samples")

function main (){
    info "Starting unreported check for $sample_count samples"
    counter=0
    jq -c '.[]' <<< "$samples" | while read -r sample_info; do
        counter=$((counter+1))
        sampleId=$(jq -r '.sampleId' <<< "$sample_info")
        [[ $((counter%50)) == "0" ]] && info "At sample [$counter] of [$sample_count]"
        report_count=$(grep -cE "${sampleId}\W+" "$REPORT_SHARED_TSV")
        if [[ "$report_count" -lt 1 ]]; then
            check_unreported_sample "$sampleId"
        fi
    done
    info "Finished with unreported check"
}

function check_unreported_sample() {
    local sampleId=$1 && shift

    api_info=$(hmf_api_get "samples?name=${sampleId}&type=tumor")
    lama_info=$(curl --silent "http://lama-preview.prod-1/api/statuses?sampleId=${sampleId}")
    api_status=$(jq -r '.[-1].status' <<< "$api_info")
    finished_prep_count=$(jq -r '.[].libraryPrepStatus' <<< "$lama_info" | grep -c "$LAMA_FINISHED_STATUS")
    unreportable_count=$(grep -cE "^${sampleId}$" "$UNREPORTABLE_TSV")

    if [[ "$finished_prep_count" -eq 0 ]]; then
        info "Sample [$sampleId] has no $LAMA_FINISHED_STATUS prep"
    elif [[ "$unreportable_count" -gt 0 ]]; then
        info "Sample [$sampleId] is deemed un-reportable"
    elif [[ "$api_status" == "Expected" ]]; then
        info "Sample [$sampleId] has finished prep but ignorable api status [$api_status]"
    else
        warn "Sample [$sampleId] has finished prep and non-ignorable api status [$api_status]! Please check!"
    fi
}

main