#!/usr/bin/env bash

source message_functions || exit 1
source actin_config || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting."
fi

vm="$(pilot_vm)"
project="$(pilot_project)"

do_download_actin_report_to_tmp ${patient} ${vm} ${project}