#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

database_sql="${HOME}/hmf/repos/actin/database/src/main/resources/generate_database.sql"

if [[ ! -f "${database_sql}" ]]; then
    error "Could not locate ACTIN sql. Exiting"
fi

gcloud compute scp ${database_sql} data-vm-prod-2:$(locate_actin_database_sql_script)