#!/usr/bin/env bash

source message_functions || exit 1

actin_database_jar=${HOME}/hmf/repos/actin/actin-database/target/actin-database-*-jar-with-dependencies.jar

info "Copying ${actin_database_jar} to gs://common-tools/"
gsutil cp ${actin_database_jar} gs://common-tools/actin-database/pilot/actin-database.jar

info "Copying ${actin_database_jar} to data-vm-prod-1"
gcloud compute scp ${actin_database_jar} data-vm-prod-1:/data/tools/actin-database/pilot/actin-database.jar