#!/usr/bin/env bash

source message_functions || exit 1

source_file=$1 && shift
target_file=$1 && shift

if [[ -z "${source_file}" || -z "${target_file}" ]]; then
    error "Missing parameters. Exiting."
fi

target_dir="/data/resources/custom/actin/clinical_curation"

do_update_actin_resource_file "${source_file}" "${target_file}" "${target_dir}"