#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

patient=$1

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting."
fi

local_dir="${HOME}/hmf/tmp/orange_germline"
if [[ ! -d "${local_dir}" ]]; then
    mkdir -p "${local_dir}"
fi

gcloud compute scp data-vm-prod-1:$(locate_actin_molecular_directory)/*${patient}*/orange/*.pdf ${local_dir}/