#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Missing parameters. Exiting."
fi

local_dir="${HOME}/hmf/tmp/orange_pilot"
if [[ ! -d "${local_dir}" ]]; then
    mkdir -p "${local_dir}"
fi

gcloud compute scp data-vm-prod-2:$(locate_actin_molecular_directory)/*${sample}*/orange_pilot/*.pdf ${local_dir}/