#!/usr/bin/env bash

source message_functions || exit 1

dir=$1 && shift

if [[ -z "${dir}" ]]; then
    error "Parameters missing. Exiting."
fi

no_consent_patients=("ACTN-01-02-0015" "ACTN-01-02-0059" "ACTN-01-02-0067" "ACTN-01-02-0073" "ACTN-01-02-0083" "ACTN-01-02-0086" \
    "ACTN-01-02-0090" "ACTN-01-02-0092" "ACTN-01-02-0096" "ACTN-01-02-0097" "ACTN-01-02-0099" "ACTN-01-02-0119" "ACTN-01-02-0128" \
    "ACTN-01-02-0131" "ACTN-01-02-0133")

for file in ${dir}/*.tsv; do
    for patient in ${no_consent_patients[@]}; do
        count=$(cat ${file} | grep -c ${patient})
        if [[ count -gt 0 ]]; then
            error "Found ${patient} in ${file} ${count} times. Exiting."
        fi
    done
done

to_check_patients=("ACTN-01-02-0098" "ACTN-01-02-0112" "ACTN-01-02-0129" "ACTN-01-02-0135")

for file in ${dir}/*.tsv; do
    for patient in ${to_check_patients[@]}; do
        count=$(cat ${file} | grep -c ${patient})
        if [[ count -gt 0 ]]; then
            error "Found ${patient} in ${file} ${count} times. Exiting."
        fi
    done
done

# Check header position
for file in ${dir}/*.tsv; do
    header=$(head -1 ${file} | grep "subject")
    if [[ -z "${header}" ]]; then
    error "Detection of malformed header(s) in ${file}. Exiting."
    fi
done

# Sort by first column and rename files
(head -n 1 "${dir}/ACTIN_Data_Questionnaire.tsv" && tail -n +2 "${dir}/ACTIN_Data_Questionnaire.tsv" | sort) > "${dir}/questionnaire.tsv"
(head -n 1 "${dir}/ACTIN_Data_Patient.tsv" && tail -n +2 "${dir}/ACTIN_Data_Patient.tsv" | sort) > "${dir}/patient.tsv"
(head -n 1 "${dir}/ACTIN_Data_Metingen.tsv" && tail -n +2 "${dir}/ACTIN_Data_Metingen.tsv" | sort) > "${dir}/vital_function.tsv"
(head -n 1 "${dir}/ACTIN_Data_Medicatie.tsv" && tail -n +2 "${dir}/ACTIN_Data_Medicatie.tsv" | sort) > "${dir}/medication.tsv"
(head -n 1 "${dir}/ACTIN_Data_Labwaarden.tsv" && tail -n +2 "${dir}/ACTIN_Data_Labwaarden.tsv" | sort) > "${dir}/lab.tsv"
(head -n 1 "${dir}/ACTIN_Data_Encounters.tsv" && tail -n +2 "${dir}/ACTIN_Data_Encounters.tsv" | sort) > "${dir}/encounter.tsv"
(head -n 1 "${dir}/ACTIN_Data_AllergyIntollerance.tsv" && tail -n +2 "${dir}/ACTIN_Data_AllergyIntollerance.tsv" | sort) > "${dir}/intolerance.tsv"
(head -n 1 "${dir}/ACTIN_Data_Gewicht.tsv" && tail -n +2 "${dir}/ACTIN_Data_Gewicht.tsv" | sort) > "${dir}/bodyweight.tsv"

# Remove old files
rm "${dir}/ACTIN_Data_"*tsv