#!/usr/bin/env bash

dir=$1

if [[ -z ${dir} ]]; then
    echo "No dir passed" && exit 1
fi

mv "${dir}/Actin_Data_Extractie-Questionnaire.tsv" "${dir}/questionnaire.tsv"
mv "${dir}/Actin_Data_Extractie-Patient.tsv" "${dir}/patient.tsv"
mv "${dir}/Actin_Data_Extractie-Metingen.tsv" "${dir}/bloodpressure.tsv"
mv "${dir}/Actin_Data_Extractie-Medicatie.tsv" "${dir}/medication.tsv"
mv "${dir}/Actin_Data_Extractie-Labwaarden.tsv" "${dir}/lab.tsv"
mv "${dir}/Actin_Data_Extractie-Encounters.tsv" "${dir}/encounter.tsv"
mv "${dir}/Actin_Data_Extractie-ComplicatiesDiagnoses.tsv" "${dir}/complication.tsv"
mv "${dir}/Actin_Data_Extractie-AllergyIntollerance.tsv" "${dir}/intolerance.tsv"