#!/usr/bin/env bash

dir=$HOME/Downloads

prefix="EMC EHR Data Curation"

do_update_actin_curation_file "${dir}/${prefix} - Primary Tumor.tsv" "${dir}/primary_tumor.tsv"
do_update_actin_curation_file "${dir}/${prefix} - Biopsy Location.tsv" "${dir}/biopsy_location.tsv"
do_update_actin_curation_file "${dir}/${prefix} - Oncological History.tsv" "${dir}/oncological_history.tsv"
do_update_actin_curation_file "${dir}/${prefix} - Non-oncological History.tsv" "${dir}/non_oncological_history.tsv"
do_update_actin_curation_file "${dir}/${prefix} - ECG.tsv" "${dir}/ecg.tsv"
do_update_actin_curation_file "${dir}/${prefix} - Cancer Related Complication.tsv" "${dir}/cancer_related_complication.tsv"
do_update_actin_curation_file "${dir}/${prefix} - Toxicity.tsv" "${dir}/toxicity.tsv"
