#!/usr/bin/env bash

dir="${HOME}/Downloads"

prefix="EMC Trial Database"

do_update_actin_treatment_config_file "${dir}/${prefix} - Trial Definition.tsv" "${dir}/trial_definition.tsv"
do_update_actin_treatment_config_file "${dir}/${prefix} - Cohort Definition.tsv" "${dir}/cohort_definition.tsv"
do_update_actin_treatment_config_file "${dir}/${prefix} - Inclusion Criteria.tsv" "${dir}/inclusion_criteria.tsv"
