#!/usr/bin/env bash

dir=$HOME/Downloads

prefix="EMC Trial Database"

do_update_actin_treatment_file "${dir}/${prefix} - Trial.tsv" "${dir}/trial.tsv"
do_update_actin_treatment_file "${dir}/${prefix} - Cohort.tsv" "${dir}/cohort.tsv"
do_update_actin_treatment_file "${dir}/${prefix} - Inclusion Criteria.tsv" "${dir}/inclusion_criteria.tsv"
