#!/usr/bin/env bash

dir="${HOME}/Downloads"

prefix="EMC EHR Data Curation"

pull_actin_changes_in_crunch_repo

do_update_actin_clinical_curation_file "${dir}/${prefix} - Primary Tumor.tsv" "${dir}/primary_tumor.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Oncological History.tsv" "${dir}/oncological_history.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Second Primary.tsv" "${dir}/second_primary.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Lesion Location.tsv" "${dir}/lesion_location.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Non-oncological History.tsv" "${dir}/non_oncological_history.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - ECG.tsv" "${dir}/ecg.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Infection.tsv" "${dir}/infection.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Complication.tsv" "${dir}/complication.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Toxicity.tsv" "${dir}/toxicity.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Molecular Test.tsv" "${dir}/molecular_test.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Medication Name.tsv" "${dir}/medication_name.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Medication Dosage.tsv" "${dir}/medication_dosage.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Medication Category.tsv" "${dir}/medication_category.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Intolerance.tsv" "${dir}/intolerance.tsv"

do_update_actin_clinical_curation_file "${dir}/${prefix} - Administration Route Translation.tsv" "${dir}/administration_route_translation.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Laboratory Translation.tsv" "${dir}/laboratory_translation.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Toxicity Translation.tsv" "${dir}/toxicity_translation.tsv"
do_update_actin_clinical_curation_file "${dir}/${prefix} - Blood Transfusion Translation.tsv" "${dir}/blood_transfusion_translation.tsv"

push_actin_changes_in_crunch_repo