#!/usr/bin/env bash

source locate_files || exit 1
source actin_config || exit 1
source message_functions || exit 1
source io_functions || exit 1

gcp_project=$1 && shift
namespace=$1

if [[ -z "${gcp_project}" ]]; then
    error "Missing project parameter. Exiting"
fi

if [[ "${gcp_project}" == "$(production_actin_emc_project)" ]]; then
    if [[ -z "${namespace}" ]]; then
        error "Missing namespace [$(actin_emc_namespaces)]"
        exit 1
    fi
fi

info "Syncing ACTIN trials for ${gcp_project} ${namespace} to $(hostname)"

output_directory=$(locate_actin_trial_database_directory)
gsutil -m rsync -r $(locate_actin_trial_database_bucket ${gcp_project} ${namespace}) ${output_directory}

info "Done"