#!/usr/bin/env bash

source locate_files || exit 1
source actin_config || exit 1

gcp_project="$(production_actin_nki_project)"
clinical_feed_input_bucket="$(locate_actin_clinical_feed_input_bucket ${gcp_project})"

do_sync_actin_input_data_to_vm ${gcp_project} ${clinical_feed_input_bucket}

if [[ "$(hostname)" == "$(production_actin_nki_ops_vm)" ]]; then
    info "Syncing NKI actin config file ..."

    actin_nki_config_directory=$(dirname "${actin_nki_config_file}")
    create_or_cleanup_dir ${actin_nki_config_directory}

    config_map_content="$(kubectl get configmap actin-config -o jsonpath='{.data.actin-config\.yaml}')"
    echo "${config_map_content}" > "$(locate_actin_nki_config_file)"
else
    warn "Cannot sync NKI actin config file, only supported on NKI ops VM"
fi

