#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source actin_config || exit 1
source io_functions || exit 1

gcp_project=$1 && shift
actin_clinical_input_feed_bucket=$1 && shift
namespace=$1

if [[ -z "${gcp_project}" || -z "${actin_clinical_input_feed_bucket}" ]]; then
    error "Missing parameters. Exiting"
fi

if [[ "${gcp_project}" == "$(production_actin_emc_project)" ]]; then
    if [[ -z "${namespace}" ]]; then
        error "Missing namespace [$(actin_emc_namespaces)]"
        exit 1
    fi
fi

info "Syncing ACTIN input and config data for ${gcp_project} ${namespace} to $(hostname)"

info "Syncing trial config (excluding diffs)..."
trial_config_directory=$(locate_actin_trial_config_directory)
create_or_cleanup_dir ${trial_config_directory}
gsutil -m rsync -x "^202" -r $(locate_actin_trial_config_bucket ${gcp_project} ${namespace}) ${trial_config_directory}

info "Syncing trial status (excluding diffs)..."
trial_status_directory=$(locate_actin_trial_status_directory)
create_or_cleanup_dir ${trial_status_directory}
gsutil -m rsync -x "^202" -r $(locate_actin_trial_status_bucket ${gcp_project} ${namespace}) ${trial_status_directory}

info "Syncing ACTIN trial database..."
trial_database_directory=$(locate_actin_trial_database_directory)
create_or_cleanup_dir ${trial_database_directory}
gsutil -m rsync -r $(locate_actin_trial_database_bucket ${gcp_project} ${namespace}) ${trial_database_directory}

info "Syncing feed input (excluding diffs)..."
feed_input_directory=$(locate_actin_clinical_input_feed_directory)
create_or_cleanup_dir ${feed_input_directory}
gsutil -m rsync -x "^202" -r ${actin_clinical_input_feed_bucket} ${feed_input_directory}

info "Syncing (current) transformed feed..."
transformed_feed_directory=$(locate_actin_transformed_feed_directory)
create_or_cleanup_dir ${transformed_feed_directory}
gsutil -m rsync -x "^202" -r $(locate_actin_transformed_feed_bucket ${gcp_project} ${namespace})/current ${transformed_feed_directory}

info "Syncing clinical curation config (excluding diffs)..."
clinical_curation_directory=$(locate_actin_clinical_curation_directory)
create_or_cleanup_dir ${clinical_curation_directory}
gsutil -m rsync -x "^202" -r $(locate_actin_clinical_curation_bucket ${gcp_project} ${namespace}) ${clinical_curation_directory}

info "Syncing SERVE output..."
serve_directory=$(locate_actin_serve_directory)
create_or_cleanup_dir ${serve_directory}
gsutil -m rsync -r $(locate_actin_serve_bucket ${gcp_project} ${namespace}) ${serve_directory}

if [[ $(hostname) != "$(pilot_actin_vm)" ]]; then
    info "Syncing actin config file ..."

    environment_config_yaml="$(locate_actin_environment_config_yaml)"
    environment_config_directory=$(dirname "${environment_config_yaml}")
    create_or_cleanup_dir ${environment_config_directory}

    # This command does require the context to be set for the specific user. Way to get this is via:
    # gcloud container clusters get-credentials ${env}-cluster-patient-processing --region europe-west4 --project actin-${env}
    config_map_content="$(kubectl get configmap actin-config -n ${namespace} -o jsonpath='{.data.actin-config\.yaml}')"

    if [[ -z "${config_map_content}" ]]; then
        echo "WARNING: failed to fetch environment_config_yaml. File is empty. Retrying..."
        config_map_content="$(kubectl get configmap actin-config -n ${namespace} -o jsonpath='{.data.actin-config\.yaml}')"

        if [[ -z "${config_map_content}" ]]; then
            error "Second try to fetch environment_config_yaml failed. File remains empty."
        fi
    fi

    echo "${config_map_content}" > "${environment_config_yaml}"

else
    warn "Cannot sync actin config file on $(pilot_actin_vm), only supported on prod ops VMs!"
fi

info "Done"