#!/usr/bin/env bash

source locate_files || exit 1
source actin_config || exit 1
source message_functions || exit 1
source io_functions || exit 1

gcp_project=$1 && shift
namespace=$1

if [[ -z "${gcp_project}" ]]; then
    error "Missing project parameter. Exiting"
fi

if [[ "${gcp_project}" == "$(production_actin_emc_project)" ]]; then
    if [[ -z "${namespace}" ]]; then
        error "Missing namespace [$(actin_emc_namespaces)]"
        exit 1
    fi
fi

info "Syncing ACTIN wgs pipeline and actin analysis output for ${gcp_project} ${namespace} to $(hostname)"

info "Syncing ACTIN clinical output..."
clinical_output_directory=$(locate_actin_curated_clinical_directory)
create_or_cleanup_dir "${clinical_output_directory}"
gsutil -m rsync -r $(locate_actin_clinical_output_bucket ${gcp_project} ${namespace}) ${clinical_output_directory}

info "Syncing ACTIN wgs pipeline output..."
actin_wgs_directory=$(locate_actin_wgs_directory)
create_or_cleanup_dir "${actin_wgs_directory}"
gsutil -m rsync -r -x ".*\.bam$|.*\.cram$" $(locate_actin_wgs_pipeline_bucket ${gcp_project} ${namespace}) ${actin_wgs_directory}

info "Syncing diagnostics wgs pipeline output..."
actin_wgs_diagnostic_directory=$(locate_actin_wgs_diagnostic_directory)
create_or_cleanup_dir "${actin_wgs_diagnostic_directory}"
gsutil -m rsync -r -x ".*\.bam$|.*\.cram$" $(locate_actin_wgs_diagnostic_pipeline_bucket ${gcp_project} ${namespace}) ${actin_wgs_diagnostic_directory}

info "Syncing ACTIN patient records..."
patient_record_directory=$(locate_actin_patient_record_directory)
create_or_cleanup_dir "${patient_record_directory}"
gsutil -m rsync -r $(locate_actin_analysis_bucket ${gcp_project} ${namespace})/molecular/ ${patient_record_directory}

info "Syncing ACTIN treatment match output..."
treatment_match_directory=$(locate_actin_treatment_match_directory)
create_or_cleanup_dir "${treatment_match_directory}"
gsutil -m rsync -r $(locate_actin_analysis_bucket ${gcp_project} ${namespace})/algo/ ${treatment_match_directory}

info "Syncing ACTIN reports..."
reports_directory=$(locate_actin_reports_directory)
create_or_cleanup_dir "${reports_directory}"
gsutil -m rsync -r $(locate_actin_analysis_bucket ${gcp_project} ${namespace})/report/ ${reports_directory}

info "Done"
