#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source metadata_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Missing params. Exiting";
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

reference="${sample}_RNA"
reference_bam="${run_dir}/rna_bam/${sample}.sorted.dups.bam"
reference_genome=$(locate_ref_genome_37_fasta_file)

input_vcf=$(locate_purple_somatic_variants ${run_dir})
out_vcf="${run_dir}/purple/${sample}.purple.somatic.with_rna.vcf.gz"

sage_jar=$(locate_prod_sage)

# With SAGE v2.9+ the package of the append app will change to com.hartwig.hmftools.sage.apps
java -Xms4G -Xmx32G -cp ${sage_jar} com.hartwig.hmftools.sage.SageAppendApplication \
    -reference ${reference} -reference_bam ${reference_bam} \
    -ref_genome ${reference_genome} \
    -input_vcf ${input_vcf} \
    -out ${out_vcf}
