#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source metadata_functions || exit 1
source io_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Missing params. Exiting";
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

reference="${sample}_RNA"
reference_bam=$(locate_rna_bam ${run_dir})
ref_genome=$(locate_ref_genome_37_fasta_file)
sage_jar=$(locate_prod_sage)

rna_sage_directory=$(locate_rna_sage_directory ${run_dir})
create_or_cleanup_dir ${rna_sage_directory}

germline_input_vcf=$(locate_purple_germline_variants ${run_dir})
germline_out="${rna_sage_directory}/${sample}.purple.germline.with_rna.vcf.gz"

info "Running SAGE RNA annotation on germline variants for ${sample}"
java -Xms4G -Xmx32G -cp ${sage_jar} com.hartwig.hmftools.sage.SageAppendApplication \
    -reference ${reference} -reference_bam ${reference_bam} \
    -ref_genome ${ref_genome} \
    -input_vcf ${germline_input_vcf} \
    -out ${germline_out}

somatic_input_vcf=$(locate_purple_somatic_variants ${run_dir})
somatic_out="${rna_sage_directory}/${sample}.purple.somatic.with_rna.vcf.gz"

info "Running SAGE RNA annotation on somatic variants for ${sample}"
java -Xms4G -Xmx32G -cp ${sage_jar} com.hartwig.hmftools.sage.SageAppendApplication \
    -reference ${reference} -reference_bam ${reference_bam} \
    -ref_genome ${ref_genome} \
    -input_vcf ${somatic_input_vcf} \
    -out ${somatic_out}