#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source metadata_functions || exit 1
source io_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Missing params. Exiting";
fi

sample=$(load_tumor_sample_from_metadata ${run_dir})

reference="${sample}_RNA"
reference_bam=$(locate_rna_bam ${run_dir})
ref_genome=$(locate_ref_genome_37_fasta_file)

input_vcf=$(locate_purple_germline_variants ${run_dir})
rna_sage_germline_directory=$(locate_rna_sage_germline_directory ${run_dir})

create_or_cleanup_dir ${rna_sage_germline_directory}

out="${rna_sage_germline_directory}/${sample}.purple.germline.with_rna.vcf.gz"

sage_jar=$(locate_pilot_sage)

info "Running SAGE RNA annotation on germline variants for ${sample}"
java -Xms4G -Xmx32G -cp ${sage_jar} com.hartwig.hmftools.sage.append.SageAppendApplication \
    -reference ${reference} -reference_bam ${reference_bam} \
    -ref_genome ${ref_genome} \
    -input_vcf ${input_vcf} \
    -out ${out}
