#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1
source metadata_functions || exit 1

run_dir1=$1 && shift
run_dir2=$1 && shift
output_dir=$1 && shift

if [[ -z "${run_dir1}" || -z "${run_dir2}" || -z "${output_dir}" ]]; then
    error "Missing params. Exiting";
fi

sample=$(load_tumor_sample_from_metadata ${run_dir1})

sage_somatic_output1=$(locate_sage_filtered_somatic_variants ${run_dir1})
sage_somatic_output2=$(locate_sage_filtered_somatic_variants ${run_dir2})

sage_jar="$(locate_pilot_sage)"

info "Running SAGE compare VCFs between ${run_dir1} and ${run_dir2}"

java -cp ${sage_jar} com.hartwig.hmftools.sage.utils.SageCompareVcfs \
    -sample ${sample} \
    -original_vcf ${sage_somatic_output1} \
    -new_vcf ${sage_somatic_output2} \
    -output_dir ${output_dir} \
    -output_id ${sample}_compare

