#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

input_file=$1 && shift
output_hla_bam=$1 && shift

if [[ -z "${input_file}" || -z "${output_hla_bam}" ]]; then
    error "Parameters missing. Exiting.";
fi

ref_genome_fasta=$(locate_ref_genome_37_fasta_file)
samtools="/data/tools/samtools/1.10/samtools"
hla_bed="/data/experiments/lilac/resources/hla_v37.bed"

${samtools} view \
    -T ${ref_genome_fasta} \
    -L ${hla_bed} -u -@ 5 -M \
    -o ${output_hla_bam} \
    ${input_file} \

${samtools} index ${output_hla_bam}


