#!/bin/bash

exec java -Xmx3200m -Xms800m -jar /data/common/tools/ecrfanalyser_v1.0/ecrf-analyser.jar -ecrf /data/ecrf/cpct_ecrf.xml -fields BASELINE.CARCINOMA.CARCINOMA.PTUMLOC -print_to_std_out -patients "$@"