#!/usr/bin/env bash

source message_functions || exit 1

set -e

source_repo_url="us-docker.pkg.dev/accelerated-compute/artifactory-4411761"
target_repo_url="europe-west4-docker.pkg.dev/hmf-build/hmf-docker/project-x"
pull_account="sa-partner-data-share-4411761@accelerated-compute.iam.gserviceaccount.com"

tag="${1:-0.19.0-a508ce0}"

tools=(
    "bwa-mem-samtools:${tag}"
    "bwa-mem-samtools-alignment:${tag}"
    "demux-collapser-with-metrics:${tag}"
    "fastqsplitter:${tag}"
    "gatk:${tag}"
    "giraffe:${tag}"
    "metrics:${tag}"
    "metrics-with-alignment-metrics:${tag}"
    "nextflow-driver:${tag}"
    "pigz:${tag}"
    "read_collapser:${tag}"
    "sbx-rnd-pipeline:${tag}"
    "small-variant-caller-samtools:${tag}"
)

function main() {

    current_account=$(gcloud config get account) || die "Unable to get current authenticated account [gcloud config get account]"

    info "Will copy docker images from x to hartwig"
    info "  SRC repo = ${source_repo_url}"
    info "  DST repo = ${target_repo_url}"
    info "These accounts will be used:"
    info "  PULL account = ${pull_account}"
    info "  PUSH account = ${current_account}"
    info "The following tools will be pulled and pushed:"
    for tool in "${tools[@]}"; do
        info "  $tool"
    done

    info "Press [ENTER] to continue..."
    read -r -s

    info "Switching to pull account [${pull_account}]"
    gcloud config set account "${pull_account}"

    info "Docker pull step  [${source_repo_url}]"
    for tool in "${tools[@]}"; do
        info "Pulling [${tool}]" && docker image pull "${source_repo_url}/${tool}"
    done

    info "Docker tag step"
    for tool in "${tools[@]}"; do
        info "Tagging [${tool}]" && docker tag "${source_repo_url}/${tool}" "${target_repo_url}/${tool}"
    done

    info "Switching to push account [${current_account}]"
    gcloud config set account "${current_account}"

    info "Docker push step [${target_repo_url}]"
    for tool in "${tools[@]}"; do
        info "Pushing [${tool}]" && docker push "${target_repo_url}/${tool}"
    done
}

main