#!/usr/bin/env bash

set -e

source actin_config || exit 1

trap 'echo "ERROR, exiting." >&2; exit 1' ERR

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting" >&2
    exit 1
fi

gcp_project=$(production_actin_nki_project)
analysis_pipeline_bucket="gs://${gcp_project}-analysis-pipeline-output"
clinical_pipeline_bucket="gs://${gcp_project}-clinical-pipeline-output"
target_bucket="gs://${gcp_project}-shared-data-external"

report="${analysis_pipeline_bucket}/report/${patient}.actin.pdf"
treatment_match="${analysis_pipeline_bucket}/algo/${patient}.treatment_match.json"
clinical="${clinical_pipeline_bucket}/${patient}.clinical.json"

hash="$(lookup_nki_hash_for_actin_id "${patient}")"

check_and_copy_file() {
    local file_path=$1
    local sub_dir=$2
    local bn="$(basename ${file_path})"
    local ext="${bn#*.}"

    if ! gsutil -q stat "${file_path}"; then
        echo "Cannot find \"${file_path}\"" >&2
        return 1
    fi

    if ! gsutil cp -n "${file_path}" "${target_bucket}/${sub_dir}/${hash}.${ext}"; then
        echo "Failed copying ${file_path} to ${target_bucket}/${sub_dir}/${hash}.${ext}" >&2
        return 1
    fi
}

check_and_copy_file "${report}" "reports"
check_and_copy_file "${treatment_match}" "algo"
check_and_copy_file "${clinical}" "clinical"

echo "Copied files to ${target_bucket}"
exit 0
