#!/usr/bin/env bash

source actin_config || exit 1
source locate_files || exit 1
source shared_data_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing patient parameter. Exiting"
    exit 1
fi

gcp_project=$(production_actin_nki_project)
hospital_id="$(lookup_nki_hospital_id_for_actin_id "${patient}")"
shared_actin_data_external_uri="$(locate_next_actin_shared_data_external_uri_gcp "${gcp_project}" "${hospital_id}")"

actin_report_pdf="$(locate_actin_report_pdf_gcp "${gcp_project}" "${patient}")"
patient_record_json="$(locate_actin_patient_record_json_gcp "${gcp_project}" "${patient}")"
treatment_match_json="$(locate_actin_treatment_match_json_gcp "${gcp_project}" "${patient}")"

if [[ -z "${patient_record_json}" || -z "${treatment_match_json}" || -z "${actin_report_pdf}" ]]; then
    error "Missing ACTIN data or report for ${patient}"
fi

info "Copying ACTIN data for ${patient} to ${shared_actin_data_external_uri}"
destination_prefix="${shared_actin_data_external_uri}/${hospital_id}"
gsutil cp "${patient_record_json}" "${destination_prefix}.patient_record.json"
gsutil cp "${treatment_match_json}" "${destination_prefix}.treatment_match.json"
gsutil cp "${actin_report_pdf}" "${destination_prefix}.pdf"

write_shared_data_latest_path_manifest "${shared_actin_data_external_uri}"

echo "Copied files to ${shared_actin_data_external_uri}"