#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source lims_functions || exit 1
source message_functions || exit 1
source api_functions || exit 1

run_dir=$1 && shift
tumor_sample=$1 && shift
tumor_sample_barcode=$1 && shift
ref_sample=$1 && shift
ref_sample_barcode=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting"
fi

if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${tumor_sample}" || -z "${tumor_sample_barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  ref_sample name: ${ref_sample}"
    warn "  ref sample barcode: ${ref_sample_barcode}"
    warn "  tumor_sample name: ${tumor_sample}"
    warn "  tum sample barcode: ${tumor_sample_barcode}"
    exit 1;
fi

pipeline_version_file="${run_dir}/pipeline.version"
orange_json="$(locate_orange_json ${run_dir})"

# TODO Switch to actual cuppa conclusion plot
# cuppa_plot="$(locate_cuppa_conclusion_plot ${run_dir})"
cuppa_plot="data/resources/custom/cuppa-chart/empty.cuppa.chart.png"

# TODO Switch to PROD once PROTECT v3.0 has become production version
protect_evidence_tsv="$(locate_protect_evidence_pilot ${run_dir})"

# TODO Switch to PROD once ROSE v2.0 has become production version
rose_tsv="$(locate_rose_pilot ${run_dir})"

germline_reporting_tsv="$(locate_germline_reporting_prod)"
sample_special_remark_tsv="$(locate_special_remark_patient_report_pilot)"
known_fusion_file="$(locate_known_fusion_data_37_csv)"

pilot_do_run_base_patient_reporter \
    -ref_sample_id ${ref_sample} \
    -ref_sample_barcode ${ref_sample_barcode} \
    -tumor_sample_id ${tumor_sample} \
    -tumor_sample_barcode ${tumor_sample_barcode} \
    -pipeline_version_file ${pipeline_version_file} \
    -orange_json ${orange_json} \
    -cuppa_plot ${cuppa_plot} \
    -protect_evidence_tsv ${protect_evidence_tsv} \
    -add_rose \
    -rose_tsv ${rose_tsv} \
    -known_fusion_file ${known_fusion_file} \
    -germline_reporting_tsv ${germline_reporting_tsv} \
    -sample_special_remark_tsv ${sample_special_remark_tsv} \
    -log_debug \
    "$@"