name: "oncoact-panel-remarks"
version: "0.0.1-beta.20"
storagePath: "gs://oncoact-panel-remarks-output"
externalInputs:
  - name: input-bucket
    location: "${input_bucket_uri}"
stages:
  - name: "remarks"
    image: "europe-west4-docker.pkg.dev/hmf-build/hmf-docker-crunch/oncoact-panel-remarks"
    version: "0.0.19"
    options:
      backoffLimit: 2
      annotations:
        gke-gcsfuse/ephemeral-storage-request: 400Gi
      stageTimeoutMinutes: 120
      resources:
        requests:
          cpu: 8
          memory: 16Gi
          storage: 20Gi
      node:
        spot: true
        pool: "n2d-standard-16-pool-1"
    inputStages:
      - input-bucket
    arguments: >-
      --input-directory /in/input-bucket
      --run-names ${run_names}
      --excluded-exons /data/resources/ops/panel/excludedExons.tsv
      --output-file /out/remarks.tsv
