#!/usr/bin/env bash

source message_functions || exit 1

tool=$1 && shift
vm=$1 && shift

if [[ -z ${tool} || -z ${vm} ]]; then
    error "Not enough parameters provided. Exiting"
fi

tool_jar=${HOME}/hmf/repos/hmftools/${tool}/target/${tool}-*-jar-with-dependencies.jar

if [ ! -f ${tool_jar} ]; then
    error "Could not locate ${tool} jar!"
fi

info "Copying ${tool_jar} to gs://common-tools/"
gsutil cp ${tool_jar} gs://common-tools/${tool}/pilot/${tool}.jar

info "Copying ${tool_jar} to ${vm}"
gcloud compute scp ${tool_jar} ${vm}:/data/tools/${tool}/pilot/${tool}.jar