#!/usr/bin/env bash

source message_functions || exit 1

tool=$1 && shift
version=$1 && shift

if [[ -z ${tool} || -z ${version} ]]; then
    error "No tool or version provided. Exiting"
fi

do_deploy_prod_tool ${tool} ${version} "data-vm-prod-2"