#!/usr/bin/env bash

source message_functions || exit 1

command -v 'lama' >/dev/null 2>&1 || error "Command not found [lama]"
command -v 'hmf_api_get' >/dev/null 2>&1 || error "Command not found [hmf_api_get]"

actin_submission="HMFregACTN"
actin_cohort="ACTIN"

main () {
    info "Querying LAMA regarding ACTIN samples"
    lama 'statuses/cohorts' "$actin_cohort" | grep -E "#sampleId|Processing"
    echo ""

    info "Querying API regarding ACTIN samples"
    actin_samples=$(hmf_api_get "samples?submission=${actin_submission}")
    non_deleted_actin_samples=$(jq '[.[] | select(.status != "Deleted")]' <<< "${actin_samples}")
    printf "#%s\t%s\t%s\t%s\n" barcode name type status
    jq -c '.[]' <<< "$non_deleted_actin_samples" | while read -r sample_info; do
        barcode=$(jq -r '.barcode' <<< "$sample_info")
        if [[ $(shared_report_count_for_barcode "$barcode") -lt 1 ]]; then
            jq -r '[.barcode,.name,.type,.status] | join("\t")' <<< "$sample_info"
        fi
    done | sort -k3
    echo ""

    info "Querying API regarding diagnostic ACTIN runs"
    all_actin_runs=$(hmf_api_get "runs?submission=${actin_submission}")
    printf "#%s\t%s\t%s\t%s\n" set_name ini status bucket
    jq -r '.[] | select(.bucket//"NA"|match("diagnostic")) | [.set.name,.ini,.status,.bucket] | join("\t")' <<< "$all_actin_runs"
    echo ""

    info "Querying API regarding research ACTIN runs"
    printf "#%s\t%s\t%s\t%s\n" set_name ini status bucket
    jq -r '.[] | select(.bucket//"NA"|match("research")) | [.set.name,.ini,.status,.bucket] | join("\t")' <<< "$all_actin_runs"
}

shared_report_count_for_barcode () {
    local barcode=$1 && shift
    count=0
    created_reports=$(hmf_api_get "reports/created?barcode=${barcode}")
    while read -r created_report; do
        created_report_id=$(jq -r '.id' <<< "${created_report}")
        shared_reports=$(hmf_api_get "reports/shared?report_created_id=${created_report_id}")
        has_shared_report=$(jq 'length > 0' <<< "${shared_reports}")
        if [[ "$has_shared_report" == "true" ]]; then
            count=$((count+1))
        fi
    done < <(jq -cr '.[]' <<< "$created_reports")
    echo "$count"
}

main