#!/usr/bin/env bash

source message_functions || exit 1

actin_submission="HMFregACTN"

info "Querying LIMS regarding ACTIN samples"
query_lims.pl -rna -type samples -filter "submission=${actin_submission}" -filter "lab_status=process" | grep -v "^##"
echo ""

info "Querying API regarding ACTIN samples"
#api samples "${actin_submission}" submission
all_actin_samples=$(hmf_api_get "samples?submission=HMFregACTN")
jq -r '.[] | select(.status != "Deleted") | [.barcode,.name,.type,.status] | join(" ")' <<< "$all_actin_samples" | sort -k3
echo ""

info "Querying API regarding ACTIN runs"
#api runs "${actin_submission}" submission
all_actin_runs=$(hmf_api_get "runs?submission=HMFregACTN")
jq -r '.[] | select(.bucket//"NA"|match("research")) | [.set.name,.ini,.status,.bucket] | join(" ")' <<< "${all_actin_runs}"
