#!/usr/bin/env bash

source message_functions || exit 1

command -v 'lama' >/dev/null 2>&1 || error "Command 'lama' not found"

actin_submission="HMFregACTN"
actin_cohort="ACTIN"

info "Querying LAMA regarding ACTIN samples"
lama 'statuses/cohorts' "$actin_cohort" | grep -E "#sampleId|Processing"
echo ""

info "Querying API regarding ACTIN samples"
all_actin_samples=$(hmf_api_get "samples?submission=${actin_submission}")
printf "#%s\t%s\t%s\t%s\n" barcode name type status
jq -r '.[] | select(.status != "Deleted") | [.barcode,.name,.type,.status] | join("\t")' <<< "$all_actin_samples" | sort -k3
echo ""

info "Querying API regarding diagnostic ACTIN runs"
all_actin_runs=$(hmf_api_get "runs?submission=${actin_submission}")
printf "#%s\t%s\t%s\t%s\n" set_name ini status bucket
jq -r '.[] | select(.bucket//"NA"|match("diagnostic")) | [.set.name,.ini,.status,.bucket] | join("\t")' <<< "$all_actin_runs"
echo ""

info "Querying API regarding research ACTIN runs"
printf "#%s\t%s\t%s\t%s\n" set_name ini status bucket
jq -r '.[] | select(.bucket//"NA"|match("research")) | [.set.name,.ini,.status,.bucket] | join("\t")' <<< "$all_actin_runs"
