#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

patient=$1 && shift
sample_postfix=${1} && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

if [[ -z "${sample_postfix}" ]]; then
    sample_postfix="T"
fi

shared_actin_data_uri="$(locate_next_actin_shared_data_uri_gcp ${patient})"

clinical_json="$(locate_actin_clinical_json_gcp ${patient})"
treatment_match_json="$(locate_actin_treatment_match_json_gcp ${patient})"
evaluation_details_tsv="$(locate_actin_evaluation_details_gcp ${patient})"
evaluation_summary_tsv="$(locate_actin_evaluation_summary_gcp ${patient})"
actin_report_pdf="$(locate_actin_report_pdf_gcp ${patient})"

if [[ -z "${clinical_json}" || -z "${treatment_match_json}" || -z "${actin_report_pdf}" ||
    -z "${evaluation_details_tsv}" || -z "${evaluation_summary_tsv}" ]]; then
    error "Missing ACTIN data, report or evaluation details for ${sample}"
fi

info "Archiving ACTIN data for ${patient} to ${shared_actin_data_uri}"
gsutil cp "${clinical_json}" "${shared_actin_data_uri}/"
gsutil cp "${treatment_match_json}" "${shared_actin_data_uri}/"
gsutil cp "${actin_report_pdf}" "${shared_actin_data_uri}/"
gsutil cp "${evaluation_details_tsv}" "${shared_actin_data_uri}/"
gsutil cp "${evaluation_summary_tsv}" "${shared_actin_data_uri}/"

sample=${patient}${sample_postfix}
orange_json="$(locate_actin_orange_no_germline_json_gcp ${sample})"
orange_pdf="$(locate_actin_orange_no_germline_pdf_gcp ${sample})"
molecular_json="$(locate_actin_molecular_json_gcp ${sample})"

if [[ -z "${orange_json}" && -z "${orange_pdf}" && -z "${molecular_json}" ]]; then
    warn "Skipping archiving of ORANGE data and ACTIN molecular interpretation for ${patient} as they do not exist"
else
    info "Archiving ORANGE data, report and ACTIN interpretation for ${sample} to ${shared_actin_data_uri}"
    gsutil cp "${orange_json}" "${shared_actin_data_uri}/"
    gsutil cp "${orange_pdf}" "${shared_actin_data_uri}/"
    gsutil cp "${molecular_json}" "${shared_actin_data_uri}/"
fi