#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

shared_orange_data_uri="$(locate_next_orange_shared_data_uri_gcp ${patient})"

orange_no_germline_json="$(locate_actin_orange_no_germline_json_gcp ${patient})"
orange_no_germline_pdf="$(locate_actin_orange_no_germline_pdf_gcp ${patient})"

info "Archiving ORANGE (no germline) data for ${patient} to ${shared_orange_data_uri}"
gsutil cp "${orange_no_germline_json}" "${shared_orange_data_uri}/"
gsutil cp "${orange_no_germline_pdf}" "${shared_orange_data_uri}/"