#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting.";
fi

shared_reports_bucket="$(locate_actin_shared_reports_bucket)"
orange_no_germline_pdf="$(locate_actin_orange_no_germline_pdf_gcp ${sample})"

info "Archiving ORANGE (no germline) report for ${sample}"
gsutil cp "${orange_no_germline_pdf}" "${shared_reports_bucket}/orange/"