#!/usr/bin/env bash

coredbnr=$1 && shift

if [[ -z "${coredbnr}" ]]; then
    error "This script takes a COREDB T-number as an argument"
fi

patient_id=$(lama -j patient "${coredbnr}" | jq .'hospitalPatientId' | tr -d '"')
salt=$(gcloud secrets versions access "latest" --secret="nki-secret-salt" --project=actin-nki)
to_hash="$patient_id"_"$salt"
hashed_id=$(echo -n "$to_hash" | openssl dgst -binary -sha256 | openssl base64 -A)

echo -e "IDs that you might need:"
echo -e "CORE-DB numer:\t${coredbnr}"
echo -e "Patient ID:\t${patient_id}"
echo -e "Hashed ID:\t${hashed_id}"