#!/bin/bash

source message_functions || exit 1

version=$1 && shift

if [[ -z "${version}" ]]; then
    error "Version missing. Exiting.";
fi

mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:get \
    -DremoteRepositories=artifactregistry://europe-west4-maven.pkg.dev/hmf-build/hmf-maven \
    -Dartifact=com.hartwig.actin:actin:${version} \
    -Dtransitive=false \
    -Ddest=/data/actin/system/