#!/bin/bash

source message_functions || exit 1

version=$1 && shift

if [[ -z "${version}" ]]; then
    error "Version missing. Exiting.";
fi

mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:get \
    -DremoteRepositories=artifactregistry://europe-west4-maven.pkg.dev/actin-build/build-registry-maven \
    -Dartifact=com.hartwig.actin:system:${version} \
    -Dtransitive=false

cp ~/.m2/repository/com/hartwig/actin/system/${version}/system-${version}.jar /data/actin/system/actin.jar

cat "[$(id -un)] deployed [${version}] on [$(date)]" >> /data/actin/system/deployment.history