#!/usr/bin/env bash

run_dir=$1 && shift

if [[ -z "${run_dir}" || -z "${cuppa_dir}" ]]; then
    error "Missing params. Exiting"
fi

tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

info "Downloading isofox to ${run_dir}/isofox"
gsutil -m cp -r gs://hmf-rna-analysis/samples/${tumor_sample}/isofox ${run_dir}/
