#!/usr/bin/env bash

source message_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting."
fi

match_run=""
for run in $(locate_actin_wgs_pipeline_output_directory); do
    sample_match_count=$(ls ${run} | grep -c ${sample})
    if [[ ${sample_match_count} -gt 0 ]]; then
        if [[ ! -z "${match_run}" ]]; then
            error "Found multiple WGS runs for sample '${sample}'!"
        fi
        match_run=${run}
    fi
done

echo ${match_run}
