#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting."
fi

info "Running ACTIN WGS post process for ${patient}"

sequenced_sample=$(locate_sequenced_sample_for_actin_patient_gcp ${patient})

match_run=""
for run in $(locate_actin_wgs_pipeline_output_directory)/*; do
    sample_match_count=$(ls ${run} | grep -c ${sequenced_sample})
    if [[ ${sample_match_count} -gt 0 ]]; then
        if [[ ! -z "${match_run}" ]]; then
            error "Found multiple WGS runs for sample '${sequenced_sample}'!"
        fi
        match_run="${run}"
    fi
done

if [[ -z "${match_run}" ]]; then
    error "Could not find matching run for sample '${sequenced_sample}' in WGS pipeline output"
fi

# KD: Not ideal, assume we can always map to "T" sample.
actin_sample="${patient}T"
run_dir="$(locate_actin_molecular_directory_for_sample ${actin_sample})"
if [[ -d "${run_dir}" ]]; then
    info "Cleaning up ${run_dir}"
    rm -r "${run_dir}"
fi

info "Copying ${match_run} to ${run_dir}"
cp -r "${match_run}" "${run_dir}"

info "Done!"

