#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting.";
fi

shared_actin_data_uri="$(locate_next_actin_shared_data_uri_gcp ${patient})"

shared_actin_data_external_uri="$(locate_next_actin_shared_data_external_uri_gcp ${patient})"

clinical_json="$(locate_actin_clinical_json_gcp ${patient})"
treatment_match_json="$(locate_actin_treatment_match_json_gcp ${patient})"
evaluation_details_tsv="$(locate_actin_evaluation_details_gcp ${patient})"
evaluation_summary_tsv="$(locate_actin_evaluation_summary_gcp ${patient})"
actin_report_pdf="$(locate_actin_report_pdf_gcp ${patient})"

if [[ -z "${clinical_json}" || -z "${treatment_match_json}" || -z "${actin_report_pdf}" ||
    -z "${evaluation_details_tsv}" || -z "${evaluation_summary_tsv}" ]]; then
    error "Missing ACTIN data, report or evaluation details for ${patient}"
fi

info "Sharing ACTIN report for ${patient} to ${shared_actin_data_external_uri}"
gsutil cp "${actin_report_pdf}" "${shared_actin_data_external_uri}/"

info "Archiving ACTIN data for ${patient} to ${shared_actin_data_uri}"
gsutil cp "${clinical_json}" "${shared_actin_data_uri}/"
gsutil cp "${treatment_match_json}" "${shared_actin_data_uri}/"
gsutil cp "${actin_report_pdf}" "${shared_actin_data_uri}/"
gsutil cp "${evaluation_details_tsv}" "${shared_actin_data_uri}/"
gsutil cp "${evaluation_summary_tsv}" "${shared_actin_data_uri}/"

orange_no_germline_json="$(locate_actin_orange_no_germline_json_gcp ${patient})"
orange_no_germline_pdf="$(locate_actin_orange_no_germline_pdf_gcp ${patient})"
patient_record_json="$(locate_actin_patient_record_json_gcp ${patient})"

sample=$(locate_sequenced_sample_for_actin_patient_gcp ${patient})

if [[ -z "${orange_no_germline_json}" && -z "${orange_no_germline_pdf}" && -z "${patient_record_json}" ]]; then
    warn "Skipping archiving of ORANGE data and ACTIN patient record for ${patient} as they do not exist"
else
    info "Archiving ORANGE data, report and ACTIN interpretation for ${sample} (${patient}) to ${shared_actin_data_uri}"
    gsutil cp "${orange_no_germline_json}" "${shared_actin_data_uri}/"
    gsutil cp "${orange_no_germline_pdf}" "${shared_actin_data_uri}/"
    gsutil cp "${patient_record_json}" "${shared_actin_data_uri}/"
fi