#!/usr/bin/env bash

PROJECT="actin-nki"
SOURCE_BUCKET="gs://${PROJECT}-analysis-pipeline-output"
TARGET_BUCKET="gs://${PROJECT}-shared-data"
LOOKUP_CMD="$(dirname "$0")/lookup_hash_for_actin_id"

[[ $# -ne 1 ]] && echo "Provide the ACTIN id for the report" >&2 && exit 1

report="${SOURCE_BUCKET}/report/${1}.actin.pdf"

hash="$($LOOKUP_CMD "$1")"
bn="$(basename $report)"
ext="${bn#*.}"
gsutil -q stat $report 
[[ $? -ne 0 ]] && echo "Cannot find \"$report\"" >&2 && exit 1
gsutil cp -n "$report" "${TARGET_BUCKET}/${hash}.${ext}"
echo "Copied ${hash}.${ext}"
