#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

curr_host=$(hostname)
if [[ "${curr_host}" == "prod-vm-operations" ]]; then
    error "ACTIN data is not supposed to synced to the prod VM"
fi

info "Syncing ACTIN input and config data to local VM"
gsutil -m rsync -r $(locate_actin_clinical_feed_input_bucket) $(locate_actin_clinical_input_feed_directory)
gsutil -m rsync -r $(locate_actin_clinical_curation_bucket) $(locate_actin_clinical_curation_directory)
gsutil -m rsync -r $(locate_actin_clinical_output_bucket) $(locate_actin_curated_clinical_directory)
gsutil -m rsync -r $(locate_actin_trial_config_bucket) $(locate_actin_trial_config_directory)
gsutil -m rsync -r $(locate_actin_ctc_config_bucket) $(locate_actin_ctc_config_directory)

info "Done"