#!/usr/bin/env bash

iclusion_importer_jar=$1 && shift
iclusion_trial_tsv=$1 && shift

iclusion_api_credentials=$(pull_iclusion_credentials)

iclusion_endpoint=$(extract_credentials_value "${iclusion_api_credentials}" endpoint)
iclusion_client_id=$(extract_credentials_value "${iclusion_api_credentials}" client_id)
iclusion_client_secret=$(extract_credentials_value "${iclusion_api_credentials}" client_secret)
iclusion_user=$(extract_credentials_value "${iclusion_api_credentials}" username)
iclusion_password=$(extract_credentials_value "${iclusion_api_credentials}" password)

java -jar ${iclusion_importer_jar} \
    -iclusion_endpoint ${iclusion_endpoint} \
    -iclusion_client_id ${iclusion_client_id} \
    -iclusion_client_secret ${iclusion_client_secret} \
    -iclusion_username ${iclusion_user} \
    -iclusion_password ${iclusion_password} \
    -iclusion_trial_tsv ${iclusion_trial_tsv} \
    "$@"
