#!/usr/bin/env bash

iclusion_importer_jar=$1 && shift
iclusion_trial_tsv=$1 && shift

iclusion_api_credentials=/data/common/dbs/iclusion/iclusion_api_credentials

iclusion_endpoint=$(awk '/^endpoint/ {print $2}' ${iclusion_api_credentials})
iclusion_client_id=$(awk '/^client_id/ {print $2}' ${iclusion_api_credentials})
iclusion_client_secret=$(awk '/^client_secret/ {print $2}' ${iclusion_api_credentials})
iclusion_user=$(awk '/^username/ {print $2}' ${iclusion_api_credentials})
iclusion_password=$(awk '/^password/ {print $2}' ${iclusion_api_credentials})

java -jar ${iclusion_importer_jar} \
    -iclusion_endpoint ${iclusion_endpoint} \
    -iclusion_client_id ${iclusion_client_id} \
    -iclusion_client_secret ${iclusion_client_secret} \
    -iclusion_username ${iclusion_user} \
    -iclusion_password ${iclusion_password} \
    -iclusion_trial_tsv ${iclusion_trial_tsv} \
    "$@"
