#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting."
fi

base_dir="/data/experiments/240424_cb_crc_report"

patient_json="${base_dir}/${patient}.patient_record.json"
treatment_match_json="${base_dir}/${patient}.treatment_match.json"

actin_jar="$(locate_actin_jar_on_vm)"

java -cp ${actin_jar} com.hartwig.actin.report.ReporterApplicationKt \
    -patient_json "${patient_json}" \
    -treatment_match_json "${treatment_match_json}" \
    -output_directory "${base_dir}" \
    -profile "CRC" \
    "$@"

echo ""

java -cp ${actin_jar} com.hartwig.actin.report.ReporterApplicationKt \
    -patient_json "${patient_json}" \
    -treatment_match_json "${treatment_match_json}" \
    -output_directory "${base_dir}" \
    -enable_extended_mode \
    -profile "CRC" \
    "$@"

