#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source lims_functions || exit 1
source message_functions || exit 1
source api_functions || exit 1

run_dir=$1 && shift
output_dir_report=$1 && shift
patient_reporter_jar=$1 && shift
# output_dir_report=/data/tmp/210907_david_DEV-2140_anonymyzation-patientreporter/
# patient_reporter_jar=/data/tmp/210907_david_DEV-2140_anonymyzation-patientreporter/patient-reporter-7.24-jar-with-dependencies.jar

primary_tumor_tsv=/data/dbs/clinical_data/curated_primary_tumor.tsv
lims_dir=/data/ops/lims/prod

rva_logo=/data/dbs/patient_reporter_images/L633_l_testlaboratoria_rva_en_color.jpeg
company_logo=/data/dbs/patient_reporter_images/hartwig_logo.jpg
signature=/data/dbs/patient_reporter_images/signature_edwin_transparant.png


if [[ -z "${run_dir}" ]]; then
    error "No run dir provided. Exiting";
fi

tumor_sample_id_during_run=$(load_tumor_sample_from_metadata "${run_dir}")

tumor_sample_barcode=$(load_tumor_sample_barcode_from_metadata "${run_dir}")
if [[ -z "${tumor_sample_barcode}" ]]; then
    info "Could not load tumor sample barcode from metadata. Attempt to resolve from LIMS."
    tumor_sample_barcode=$(find_barcode_for_sample_name "${tumor_sample_id_during_run}")
fi

ref_sample_barcode=$(load_ref_sample_barcode_from_metadata "${run_dir}")
if [[ -z "${ref_sample_barcode}" ]]; then
    info "Could not load ref sample barcode from metadata. Attempting to resolve from LIMS."
    ref_sample_barcode=$(find_ref_barcode_for_sample_name "${tumor_sample_id_during_run}")
fi

tumor_sample=$(load_sample_name_for_barcode "${tumor_sample_barcode}")
ref_sample=$(load_sample_name_for_barcode "${ref_sample_barcode}")

if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${tumor_sample}" || -z "${tumor_sample_barcode}" ]]; then
    warn "Incomplete information for reporter. Exiting"
    warn "  ref sample name: ${ref_sample}"
    warn "  ref sample barcode: ${ref_sample_barcode}"
    warn "  tumor sample name: ${tumor_sample}"
    warn "  tumor sample id during run: ${tumor_sample_id_during_run}"
    warn "  tumor sample barcode: ${tumor_sample_barcode}"
    exit 1;
fi

pipeline_version_file=${run_dir}/pipeline.version
purple_purity_tsv=$(locate_purple_purity "${run_dir}")
purple_qc_file=$(locate_purple_qc "${run_dir}")
purple_somatic_driver_catalog_tsv=$(locate_purple_somatic_driver_catalog "${run_dir}")
purple_germline_driver_catalog_tsv=$(locate_purple_germline_driver_catalog "${run_dir}")
purple_somatic_variant_vcf=$(locate_purple_somatic_variants "${run_dir}")
purple_germline_variant_vcf=$(locate_purple_germline_variants "${run_dir}")
purple_somatic_copynumber_tsv=$(locate_purple_somatic_copynumber_tsv "${run_dir}")
purple_circos_plot=$(locate_purple_circos_plot "${run_dir}")
linx_fusion_tsv=$(locate_linx_fusions "${run_dir}")
linx_breakend_tsv=$(locate_linx_breakends "${run_dir}")
linx_driver_catalog_tsv=$(locate_linx_driver_catalog "${run_dir}")
chord_prediction_txt=$(locate_chord_prediction "${run_dir}")
molecular_tissue_origin_txt=$(locate_cuppa_conclusion_txt "${run_dir}")
molecular_tissue_origin_plot=$(locate_cuppa_conclusion_plot "${run_dir}")
annotated_virus_tsv=$(locate_virus_annotation_tsv "${run_dir}")
peach_genotype_tsv=$(locate_peach_genotype_prod_tsv "${run_dir}")
protect_evidence_tsv=$(locate_protect_evidence "${run_dir}")

germline_reporting_tsv=/data/dbs/germline_reporting/germline_reporting_pilot.tsv
sample_summary_tsv=/data/dbs/summary_patient_report/summary_samples.tsv

expected_pipeline_version="5.22"

mkdir --parents "${output_dir_report}/good/data/"
java -jar "${patient_reporter_jar}" \
    -primary_tumor_tsv "${primary_tumor_tsv}" \
    -lims_dir "${lims_dir}" \
    -rva_logo "${rva_logo}" \
    -company_logo "${company_logo}" \
    -signature "${signature}" \
    -expected_pipeline_version "${expected_pipeline_version}" \
    -override_pipeline_version \
    -comments "This is a pilot patient report and is not meant for production purpose" \
    -ref_sample_id "${ref_sample}" \
    -ref_sample_barcode "${ref_sample_barcode}" \
    -tumor_sample_id "${tumor_sample}" \
    -tumor_sample_barcode "${tumor_sample_barcode}" \
    -pipeline_version_file "${pipeline_version_file}" \
    -purple_purity_tsv "${purple_purity_tsv}" \
    -purple_qc_file "${purple_qc_file}" \
    -purple_somatic_driver_catalog_tsv "${purple_somatic_driver_catalog_tsv}" \
    -purple_germline_driver_catalog_tsv "${purple_germline_driver_catalog_tsv}" \
    -purple_somatic_variant_vcf "${purple_somatic_variant_vcf}" \
    -purple_germline_variant_vcf "${purple_germline_variant_vcf}" \
    -purple_somatic_copynumber_tsv "${purple_somatic_copynumber_tsv}" \
    -purple_circos_plot "${purple_circos_plot}" \
    -linx_fusion_tsv "${linx_fusion_tsv}" \
    -linx_breakend_tsv "${linx_breakend_tsv}" \
    -linx_driver_catalog_tsv "${linx_driver_catalog_tsv}" \
    -chord_prediction_txt "${chord_prediction_txt}" \
    -molecular_tissue_origin_txt "${molecular_tissue_origin_txt}" \
    -molecular_tissue_origin_plot "${molecular_tissue_origin_plot}" \
    -annotated_virus_tsv "${annotated_virus_tsv}" \
    -peach_genotype_tsv "${peach_genotype_tsv}" \
    -protect_evidence_tsv "${protect_evidence_tsv}" \
    -germline_reporting_tsv "${germline_reporting_tsv}" \
    -sample_summary_tsv "${sample_summary_tsv}" \
    -output_dir_data "${output_dir_report}/good/data/" \
    -output_dir_report "${output_dir_report}/good/" \
    -ref_genome_version 37 \
    -log_debug \
    "$@"

mkdir --parents "${output_dir_report}/insufficient_dna/data/"
java -jar "${patient_reporter_jar}" \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -rva_logo ${rva_logo} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -expected_pipeline_version ${expected_pipeline_version} \
    -override_pipeline_version \
    -output_dir_report "${output_dir_report}/insufficient_dna/" \
    -output_dir_data "${output_dir_report}/insufficient_dna/data/" \
    -qc_fail \
    -qc_fail_reason "insufficient_dna" \
    -tumor_sample_id "${tumor_sample}" \
    -tumor_sample_barcode "${tumor_sample_barcode}" \
    -ref_genome_version 37 \
    -log_debug \
    "$@"

mkdir --parents "${output_dir_report}/insufficient_tcp_deep_wgs/data/"
java -jar "${patient_reporter_jar}" \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -rva_logo ${rva_logo} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -expected_pipeline_version ${expected_pipeline_version} \
    -override_pipeline_version \
    -output_dir_report "${output_dir_report}/insufficient_tcp_deep_wgs/" \
    -output_dir_data "${output_dir_report}/insufficient_tcp_deep_wgs/data/" \
    -qc_fail \
    -qc_fail_reason "insufficient_tcp_deep_wgs" \
    -ref_sample_id "${ref_sample}" \
    -ref_sample_barcode "${ref_sample_barcode}" \
    -tumor_sample_id "${tumor_sample}" \
    -tumor_sample_barcode "${tumor_sample_barcode}" \
    -purple_purity_tsv "${purple_purity_tsv}" \
    -purple_qc_file "${purple_qc_file}" \
    -ref_genome_version 37 \
    -log_debug \
    "$@"

mkdir --parents "${output_dir_report}/insufficient_tcp_shallow_wgs/data/"
java -jar "${patient_reporter_jar}" \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -rva_logo ${rva_logo} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -expected_pipeline_version ${expected_pipeline_version} \
    -override_pipeline_version \
    -output_dir_report "${output_dir_report}/insufficient_tcp_shallow_wgs/" \
    -output_dir_data "${output_dir_report}/insufficient_tcp_shallow_wgs/data/" \
    -qc_fail \
    -qc_fail_reason "insufficient_tcp_shallow_wgs" \
    -ref_sample_id "${ref_sample}" \
    -ref_sample_barcode "${ref_sample_barcode}" \
    -tumor_sample_id "${tumor_sample}" \
    -tumor_sample_barcode "${tumor_sample_barcode}" \
    -ref_genome_version 37 \
    -log_debug \
    "$@"

mkdir --parents "${output_dir_report}/sufficient_tcp_qc_failure/data/"
java -jar "${patient_reporter_jar}" \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -rva_logo ${rva_logo} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -expected_pipeline_version ${expected_pipeline_version} \
    -override_pipeline_version \
    -output_dir_report "${output_dir_report}/sufficient_tcp_qc_failure/" \
    -output_dir_data "${output_dir_report}/sufficient_tcp_qc_failure/data/" \
    -qc_fail \
    -qc_fail_reason "sufficient_tcp_qc_failure" \
    -ref_sample_id "${ref_sample}" \
    -ref_sample_barcode "${ref_sample_barcode}" \
    -tumor_sample_id "${tumor_sample}" \
    -tumor_sample_barcode "${tumor_sample_barcode}" \
    -purple_purity_tsv "${purple_purity_tsv}" \
    -purple_qc_file "${purple_qc_file}" \
    -ref_genome_version 37 \
    -log_debug \
    "$@"

mkdir --parents "${output_dir_report}/technical_failure/data/"
java -jar "${patient_reporter_jar}" \
    -primary_tumor_tsv ${primary_tumor_tsv} \
    -lims_dir ${lims_dir} \
    -rva_logo ${rva_logo} \
    -company_logo ${company_logo} \
    -signature ${signature} \
    -expected_pipeline_version ${expected_pipeline_version} \
    -override_pipeline_version \
    -output_dir_report "${output_dir_report}/technical_failure/" \
    -output_dir_data "${output_dir_report}/technical_failure/data/" \
    -qc_fail \
    -qc_fail_reason "technical_failure" \
    -tumor_sample_id "${tumor_sample}" \
    -tumor_sample_barcode "${tumor_sample_barcode}" \
    -ref_genome_version 37 \
    -log_debug \
    "$@"