#!/bin/bash

sullivan=$1
picard=$2

bamfile=$3

tmpfastqdir=/data/tmp/fastq

${picard} SamToFastq I=${bamfile} ODIR=${tmpfastqdir} OPRG=true RGT=ID NON_PF=true RC=true

sequencerrun1=$4
if [ "$#" -eq 4 ]; then
    ${sullivan} -fastqpath1 ${sequencerrun1} -recreated ${tmpfastqdir}
fi

if [ "$#" -eq 5 ]; then
     sequencerrun2=$5
     ${sullivan} -fastqpath1 ${sequencerrun1} -fastqpath2 ${sequencerrun2} -recreated ${tmpfastqdir}
fi