#!/bin/bash

sullivan=$1
picard=$2

bamfile=$3

tmpfastqdir=/data/tmp/fastq

${picard} SamToFastq I=${bamfile} ODIR=${tmpfastqdir} OPRG=true RGT=ID NON_PF=true RC=true

fastqpath1=$4
if [ "$#" -eq 4 ]; then
    ${sullivan} -fastqpath1 ${fastqpath1} -recreated ${tmpfastqdir}
fi

if [ "$#" -eq 5 ]; then
     fastqpath2=$5
     ${sullivan} -fastqpath1 ${fastqpath1} -fastqpath2 ${fastqpath2} -recreated ${tmpfastqdir}
fi

rm ${tmpfastqdir}/*.fastq