#!/bin/bash

sullivan=$1
picard=$2

bamfile=$3
sequencerrun1=$4
sequencerrun2=$5

tmpfastqdir=/data/tmp/fastq

${picard} SamToFastq I=${bamfile} ODIR=${tmpfastqdir} OPRG=true RGT=ID NON_PF=true RC=true
${sullivan} -fastqpath1 ${sequencerrun1} -fastqpath2 ${sequencerrun2} -recreated ${tmpfastqdir}