#!/usr/bin/env bash

source message_functions || exit 1
source actin_config || exit 1
source locate_files || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting."
fi

gcp_project=$(production_actin_nki_project)

do_download_actin_report_to_tmp ${patient} ${gcp_project}

hospital_id="$(lookup_nki_hospital_id_for_actin_id ${patient})"
actin_report_file_name="${patient}.actin.pdf"
preferred_actin_report_file_name="${hospital_id}_${actin_report_file_name}"

mv "$(locate_local_tmp_actin_reports_directory)/${actin_report_file_name}" "$(locate_local_tmp_actin_reports_directory)/${preferred_actin_report_file_name}"