#!/usr/bin/env bash

source message_functions || exit 1
source actin_config || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting."
fi

gcp_project="$(production_actin_emc_project)"
namespace="$(actin_emc_tm_progene_study_namespace)"

do_download_actin_report_to_tmp "${patient}" "${gcp_project}" "${namespace}"