#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting."
fi

local_dir="${HOME}/hmf/tmp/orange_no_germline"
if [[ ! -d "${local_dir}" ]]; then
    mkdir -p "${local_dir}"
fi

orange_report="$(locate_actin_orange_no_germline_pdf_gcp ${patient})"

orange_report_file_name="$(echo $(basename "${orange_report}"))"
preferred_orange_report_file_name="${patient}_${orange_report_file_name}"

gsutil cp ${orange_report} ${local_dir}/${preferred_orange_report_file_name}