#!/usr/bin/env bash

source message_functions || exit 1
source actin_config || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Missing parameters. Exiting."
fi

gcp_project=$(production_actin_nki_project)
do_download_orange_germline_actin_to_tmp ${patient} ${gcp_project}
