#!/bin/bash

BAM_SLICER_SCRIPT=/home/mircea/workspace/scripts/hmftools/bamslicer/bam_slicer

INPUT_FILE=$1

if [ -z "$INPUT_FILE" ];
  then
    echo "Usage: $ ./batch_bam_slicer input_file"
    echo "   input_file	file containing sample, chromosome, start and end of region to be sliced, one per line (tab separated)"
    exit 1
fi

while read sample chromosome start end; do
   tmp_file="${sample}_${chromosome}_${start}_${end}.bed"
   output_file="${sample}_${chromosome}_${start}_${end}.bam"
   echo "${chromosome}	${start}	${end}" > $tmp_file
   $BAM_SLICER_SCRIPT $sample $tmp_file $output_file
   rm $tmp_file
done < $INPUT_FILE

