#!/usr/bin/env bash

source message_functions || exit 1

version="3.11.13"

if [[ ! -d "${HOME}/.pyenv" ]]; then 
    info "PyEnv not yet present, installing"
    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
fi

info "Initialising pyenv..."
${HOME}/.pyenv/bin/pyenv install ${version}
${HOME}/.pyenv/versions/${version}/bin/pip install --upgrade pip

info "Switching to new ${version} version"
export PATH="${HOME}/.pyenv/versions/${version}/bin:$PATH"
