#!/bin/bash
cpct_folder="s3://hmf_owncloud/ecrf/files/ecrf uploads/CPCT02/"
drup_folder="s3://hmf_owncloud/ecrf/files/ecrf uploads/DRUP/"
cpct_symlink="/data/ecrf/cpct_ecrf.xml"
cpct_output=$(sudo su - sbp -c "download_ecrf \"${cpct_folder}\" cpct_ecrf" | tee /dev/tty | awk 'END {print $1 " " $2}')
cpct_file=$(echo $cpct_output | awk '{print $1}')
cpct_status=$(echo $cpct_output | awk '{print $2}')
if [ "$cpct_status" == "OK" ]; then
   echo "Changing owner of $cpct_file to $USER:users"
   sudo chown $USER:users $cpct_file
   if [ -L $cpct_symlink ]; then    
      echo "Deleting old symlink"
      rm $cpct_symlink
   fi
   if [ -e $cpct_symlink ]; then
      echo "$cpct_symlink exists, but is not a symlink; skipping"
   else
      echo "Creating symlink $cpct_symlink -> $cpct_file"
      ln -s $cpct_file $cpct_symlink
   fi
fi
drup_output=$(sudo su - sbp -c "download_ecrf \"${drup_folder}\" drup_ecrf" | tee /dev/tty | awk 'END {print $1 " " $2}')
drup_file=$(echo $drup_output | awk '{print $1}')
drup_status=$(echo $drup_output | awk '{print $2}')
if [ "$drup_status" == "OK" ]; then
   echo "Changing owner of $drup_file to $USER:users"
   sudo chown $USER:users $drup_file
fi

