#!/usr/bin/env bash

source locate_files || exit 1
source metadata_functions || exit 1
source api_functions || exit 1
source message_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting"
fi

sample_dir="/data/experiments/charlotte_emc_actionability/database/${sample}"

primary_tumor_doids=$(get_primary_tumor_doids_for_sample ${sample})
if [[ -z "${primary_tumor_doids}" ]]; then
    primary_tumor_doids="\"\""
fi

patient=${sample:0:12}

output_directory="${sample_dir}/actin"

actin_jar="$(locate_cohort_actin)"

info "Running ACTIN Build Clinical From Doids Only on ${patient}"

java -cp ${actin_jar} com.hartwig.actin.clinical.BuildClinicalFromDoidsOnly \
    -patient ${patient} \
    -primary_tumor_doids ${primary_tumor_doids} \
    -output_directory ${output_directory} \
    "$@"
