#!/usr/bin/env bash

source message_functions || exit 1

SCRIPT_NAME="$(basename "$0")"
MIN_COVERAGE=50

main() {
  info "Started ${SCRIPT_NAME}"

  bam=$1 && shift
  samtools=$1 && shift  # version 1.13 or greater

  # sanity checks
  [[ -n ${samtools} ]] || die "Not enough arguments to script ${SCRIPT_NAME}"
  [[ -f ${bam} ]] || die "Bam argument does not point to file"

  all_depth="${bam}.all.depth"
  min_coverage_depth="${bam}.min${MIN_COVERAGE}.depth"

  if [[ ! -f ${all_depth} ]]; then
    info "Start samtools depth"
    "${samtools}" depth -o "${all_depth}" -s "${bam}" || die "Could not determine depth of bam file"
    info "Finished samtools depth"
  fi

  if [[ ! -f ${min_coverage_depth} ]]; then
    info "Start filtering depth file"
    awk -v min="${MIN_COVERAGE}" '$3>=min' "${all_depth}" > "${min_coverage_depth}" || die "Could not filter depth file"
    info "Finished filtering depth file"
  fi

  total_mapped_count=$(awk '{sum+=$3;} END{printf "%.0f", sum;}' "${all_depth}") \
          || die "Could not determine total mapped count"
  info "Total mapped number of bases (excluding overlaps): ${total_mapped_count}"

  average_coverage_above_minimum=$(awk '{n++;sum+=$3} END {printf "%.0f", n?sum/n:0}' "${min_coverage_depth}") \
          || die "Could not determine average coverage over ${MIN_COVERAGE}"
  info "Average coverage of bases with coverage over ${MIN_COVERAGE}: ${average_coverage_above_minimum}"

  rm "${all_depth}"

  info "Finished ${SCRIPT_NAME}"
}

main "$@"
