#!/usr/bin/env bash

source message_functions || exit 1

tool=$1 && shift

if [[ -z ${tool} ]]; then
    error "Not enough parameters provided. Exiting"
fi

vm="data-vm-prod-2"
tool_jar=$(find -L "${HOME}/hmf/repos/oncoact/${tool}/target" -type f -name "*-jar-with-dependencies.jar")

if [[ ! -f "${tool_jar}" ]]; then
    error "Could not locate ${tool} jar!"
fi

info "Copying ${tool_jar} to ${vm}"
gcloud compute scp ${tool_jar} ${vm}:/data/experiments/pilot_tools/${tool}/${tool}.jar
