#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1
source metadata_functions || exit 1

orig_run_dir=$1 && shift

if [[ -z "${orig_run_dir}" ]]; then
    error "Parameters missing. Exiting.";
fi

if [[ ! -d "${orig_run_dir}" ]]; then
    error "Run dir '${orig_run_dir}' not present. Probably not downloaded yet?"
fi

sample=$(load_tumor_sample_from_actin_metadata ${orig_run_dir})
info "Running ACTIN molecular pipeline on ${sample}"

run_dir="$(locate_actin_platinum_directory_for_sample ${sample})"
if [[ -d "${run_dir}" ]]; then
    info "Cleaning up ${run_dir}"
    rm -r "${run_dir}"
fi

info "Copying ${orig_run_dir} to ${run_dir}"
cp -r "${orig_run_dir}" "${run_dir}"

# Post-process all DNA
run_actin_dna_post_process ${run_dir}

# Post-process all RNA and integrate with DNA.
run_actin_rna_post_process ${run_dir}
