#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

run_dir=$1 && shift

if [[ ! -d "${run_dir}" ]]; then
    error "Run dir '${run_dir}' not present."
fi

sample=$(basename ${run_dir})

info "Running ACTIN DNA interpretation pipeline update on ${sample} in ${run_dir}"

# Rerun protect to bump to v2.2 and use ACTIN + reload to prod database
run_protect_research_on_actin_db ${run_dir}

# Also load to pilot db for proper source names
load_protect_data_prod_to_pilot_db ${run_dir}

# TODO Re-enable once prod is on v3.71 patient-db.
#load_protect_data_prod ${run_dir}

# Run ORANGE in ACTIN mode to produce final molecular output.
run_orange_in_actin_mode ${run_dir}

# Interpret ORANGE results for ACTIN ingestion
actin_orange_interpreter_pilot ${sample}
load_actin_molecular_pilot ${sample}