#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting.";
fi

download_isofox_to_run_dir ${run_dir}
if [[ -d "${run_dir}/isofox" ]]; then
    # Make sure sample is present in the sample metadata file for RNA!
    load_isofox_data_to_prod ${run_dir}

    run_cuppa_dna_rna_prod ${run_dir}
    generate_cup_dna_rna_report ${run_dir}
fi

download_rna_bam_to_run_dir ${run_dir}
rna_bam_dir="$(locate_rna_bam_directory ${run_dir})"
if [[ -d "${rna_bam_dir}" ]]; then
    # Annotation of purple somatic variants will only work on v5.28+ pipelines
    virusbreakend_dir="${run_dir}/virusbreakend"
    if [[ -d "${run_dir}/purple" ]]; then
        cp -r "${run_dir}/purple" "${run_dir}/purple_orig"
    fi

    annotate_somatic_variants_with_rna ${run_dir}
    load_rna_annotated_somatic_variants_to_prod ${run_dir}

    annotated_somatic_vcf="$(locate_rna_annotated_somatic_variants ${run_dir})"
    if [[ -f ${annotated_somatic_vcf} ]]; then
        info "Replace purple somatic VCF with RNA-annotated version"
        original_somatic_vcf="$(locate_purple_somatic_variants ${run_dir})"
        cp "${annotated_somatic_vcf}" "${original_somatic_vcf}"
        cp "${annotated_somatic_vcf}.tbi" "${original_somatic_vcf}.tbi"
    fi

    slice_rna_bam_for_hla ${run_dir}

    # Rerun LILAC to produce data on DNA/RNA combined.
    run_lilac_for_actin_run ${run_dir}

    # TODO Germline VCF can be annotated on pipeline v5.29
    #annotate_germline_variants_with_rna ${run_dir}

    # Rerunning ORANGE to pick up CUPPA DNA-RNA and LILAC RNA
    run_orange_in_actin_mode ${run_dir}

    # Clean up RNA bam
    rm -r ${rna_bam_dir}
fi
