#!/usr/bin/env bash

source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Parameters missing. Exiting.";
fi

# TODO Switch back to research after release of v2.0

# Run standard ORANGE in research
run_orange_pilot ${run_dir}

# Disabled-germline is generated to be able to share externally with people who do not wish to see germline.
run_orange_pilot_no_germline ${run_dir}

