#!/usr/bin/env bash

set -e

script_name=$(basename "$0")

msg() {
    local msg_type=$1 && shift
    local msg_content=$* && shift
    echo "[${msg_type}] $(date +'%y%m%d %T') - ${msg_content}"
}

info() {
    msg "INFO" "$@"
}

error() {
    msg "ERROR" "$@" >&2
    exit 1
}

die() {
    msg "ERROR" "$@" >&2
    exit 1
}

command -v gcloud > /dev/null || die "Dependency gcloud not found"

function usage() {
    echo "-----"
    echo " Usage: $script_name -o <out_file> -u <run_base_url> -t <tumor_sample> -b <billing_project> -s <service_account> [-r <ref_sample>] [-d <duration>]"
    echo ""
    echo " Required arguments:"
    echo "   -o  Output file path for IGV config"
    echo "   -u  Run base URL (gs://bucket/run_name)"
    echo "   -t  Tumor sample name"
    echo "   -b  Billing project for signed URLs"
    echo "   -s  Service account to impersonate for signed URLs"
    echo ""
    echo " Optional arguments:"
    echo "   -r  Reference sample name (if provided, ref BAM will be included)"
    echo "   -d  Duration for signed URLs (default: 1d, max: 7d)"
    echo ""
    echo " Example (tumor only):"
    echo "   $script_name -o ~/igv-config.txt -u gs://bucket/run -t TUMOR01 -b hmf-ops -s hmf-ops@hmf-ops.iam.gserviceaccount.com"
    echo ""
    echo " Example (with reference):"
    echo "   $script_name -o ~/igv-config.txt -u gs://bucket/run -t TUMOR01 -r REF01 -b hmf-ops -s hmf-ops@hmf-ops.iam.gserviceaccount.com"
    echo "-----"
    exit 1
}

out_file=""
run_base_url=""
tum=""
ref=""
duration="1d"
region="europe-west4"
billing_project=""
service_account=""

while getopts "o:u:t:r:d:b:s:h" opt; do
    case "${opt}" in
        o) out_file="${OPTARG}" ;;
        u) run_base_url="${OPTARG}" ;;
        t) tum="${OPTARG}" ;;
        r) ref="${OPTARG}" ;;
        d) duration="${OPTARG}" ;;
        b) billing_project="${OPTARG}" ;;
        s) service_account="${OPTARG}" ;;
        h) usage ;;
        *) usage ;;
    esac
done

if [[ -z "${out_file}" || -z "${run_base_url}" || -z "${tum}" || -z "${billing_project}" || -z "${service_account}" ]]; then
    info "Missing required arguments"
    usage
fi

info "Start of ${script_name}"

function main() {
    info "Details:"
    info "  Duration: ${duration}"
    info "  Region: ${region}"
    info "  RunBaseURL: ${run_base_url}"
    info "  TumSample: ${tum}"
    if [[ -n "${ref}" ]]; then
        info "  RefSample: ${ref}"
    fi
    info "  BillingProject: ${billing_project}"
    info "  ServiceAccount: ${service_account}"
    info "  OutputFile: ${out_file}"

    create_igv_config "${out_file}" "${run_base_url}" "${ref}" "${tum}" || die "Unable to create IGV config. Exiting."

    info "Finished with ${script_name}"
    info "IGV config created at: ${out_file}"
}

create_igv_config () {
    local out_file=$1 && shift
    local run_base_url=$1 && shift
    local ref=$1 && shift
    local tum=$1 && shift

    tum_bam="${run_base_url}/${tum}/aligner/${tum}.bam"
    tum_bai="${run_base_url}/${tum}/aligner/${tum}.bam.bai"

    # Build gcloud command
    local sign_url_cmd="gcloud storage sign-url --duration=${duration} --region=${region} --billing-project=${billing_project} --impersonate-service-account=${service_account}"

    info "Requesting signed URLs for tumor"
    tum_bam_url=$(${sign_url_cmd} "${tum_bam}" | tail -n1)
    tum_bai_url=$(${sign_url_cmd} "${tum_bai}" | tail -n1)

    info "Creating output file [${out_file}]"
    {
        if [[ -n "${ref}" ]]; then
            ref_bam="${run_base_url}/${ref}/aligner/${ref}.bam"
            ref_bai="${run_base_url}/${ref}/aligner/${ref}.bam.bai"

            info "Requesting signed URLs for reference"
            ref_bam_url=$(${sign_url_cmd} "${ref_bam}" | tail -n1)
            ref_bai_url=$(${sign_url_cmd} "${ref_bai}" | tail -n1)

            echo "load ${ref_bam_url} index=${ref_bai_url}"
        fi
        echo "load ${tum_bam_url} index=${tum_bai_url}"
        echo "goto TP53"
        echo "collapse"
        echo "colorBy READ_STRAND"
    } > "${out_file}"
}

main
