#!/usr/bin/env bash

source message_functions || exit 1

set=$1 && shift

[[ -n "${set}" ]] || die "No set name provided. Exiting"

nextcloud_dir="STAGING/New-Reports-Viewing"

bucket="gs://diagnostic-pipeline-output-prod-1"
orange_dir="${bucket}/${set}/orange_no_germline/"

temp_folder_path_file=$( pwd )"/temp_cp_orange_${set}"
mkdir $temp_folder_path_file
gsutil cp -r ${orange_dir}  $temp_folder_path_file/

temp_path_orange=$( pwd )"/temp_cp_orange_${set}/orange"
orange_json=$( ls $temp_path_orange | grep json)
orange_pdf=$( ls $temp_path_orange | grep pdf)


info "Uploading orange data to Nextcloud for viewing."
do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "$temp_path_orange/${orange_json}"
do_upload_files_to_nextcloud_directory "${nextcloud_dir}" "$temp_path_orange/${orange_pdf}"

rm -r $temp_folder_path_file