#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

run_dir=$1 && shift

if [[ -z "${run_dir}" ]]; then
    error "Missing input parameters. Exiting";
fi

crest_jar=$(locate_pilot_crest)
output_dir="${run_dir}/crest_pilot"

info "Running CREST pilot on ${run_dir}"

do_run_crest ${run_dir} ${crest_jar} ${output_dir}