#!/usr/bin/env bash

run_dir=$1

echo "[INFO] Running Purple on ${run_dir}"
do_run_purple_no_db ${run_dir}

echo "[INFO] Running GRIDSS annotations on ${run_dir}"
do_run_gridss_viral_annotate_prod ${run_dir}
do_run_gridss_repeatmasker_insertion_annotate_prod ${run_dir}

echo "[INFO] Run CHORD on ${run_dir}"
run_chord_prod ${run_dir}

echo "[INFO] Create symlinks for metrics files"
create_symlink_metric_file ${run_dir}

echo "[INFO] Running linx for ${run_dir}"
do_run_linx_no_db ${run_dir}

# A little tricky - assume no pathogenic germline variants.
if [ ! -d ${run_dir}/bachelor ]; then
    echo "[INFO] Faking bachelor to be present"
	  mkdir ${run_dir}/bachelor
	  touch ${run_dir}/bachelor/bachelor_found_no_variants
fi
