## Check variant counts
SELECT 
(SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.somaticVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter = "PASS") AS NewSom,
(SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.somaticVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter = "PASS") AS TruthSom,
(SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.structuralVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" and filter <> "PON") AS NewSv,
(SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.structuralVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" and filter <> "PON") AS TruthSv,
(SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.svBreakend WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS NewSvbe,
(SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.svBreakend WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS TruthSvbe;
