#!/usr/bin/env bash

source metadata_functions

run_dir=$1 && shift
output_path=$1 && shift
input_path=$1 && shift

tumor_sample=$(load_tumor_sample_from_metadata ${input_path}/${run_dir})

if [[ -z "${run_dir}" ]]; then
    echo "[ERROR] No run dir provided. Exiting" && exit 1;
fi

if [[ -z "${output_path}" ]]; then
    echo "[ERROR] No output path provided. Exiting" && exit 1;
fi

if [[ -z "${input_path}" ]]; then
    echo "[ERROR] No input path provided. Exiting" && exit 1;
fi

protect_prod_tsv_path=$( find ${input_path}/${run_dir}/protect/${tumor_sample}.protect.tsv)
cat ${protect_prod_tsv_path} > "${output_path}/${tumor_sample}.protect.tsv_prod"
cat ${protect_prod_tsv_path} | awk -F '\t' '{print $2, $3, $4, $5, $6, $7, $8, $9}'  > "${output_path}/${tumor_sample}.protect.tsv_prod_actionability"
cat ${protect_prod_tsv_path} | awk -F '\t' '{print $1}'  > "${output_path}/${tumor_sample}.protect.tsv_prod_events"

protect_pilot_tsv_path=$( find ${input_path}/${run_dir}/protect_pilot/${tumor_sample}.protect.tsv)
cat ${protect_pilot_tsv_path} > "${output_path}/${tumor_sample}.protect.tsv_pilot"
cat ${protect_pilot_tsv_path} | awk -F '\t' '{print $2, $3, $4, $5, $6, $7, $8, $9}'  > "${output_path}/${tumor_sample}.protect.tsv_pilot_actionability"
cat ${protect_pilot_tsv_path} | awk -F '\t' '{print $1}'  > "${output_path}/${tumor_sample}.protect.tsv_pilot_events"
