#!/usr/bin/env bash

run_dir=$1 && shift
ouputPath=$1 && shift

json_file_pilot=$( ls ${run_dir}/patient_report_prod_data/ )
pathFile_pilot=$( ls ${run_dir}/patient_report_prod_data/${json_file_pilot} )
cat ${pathFile_pilot} | jq '.' > ${ouputPath}"/"${json_file_pilot}"_pilot"

json_file_prod=$( ls ${run_dir}/patient_report_pilot_data/ )
pathFile_prod=$( ls ${run_dir}/patient_report_pilot_data/${json_file_prod} )

cat ${pathFile_prod} | jq '.' > ${ouputPath}"/"${json_file_prod}"_prod"