SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "germlineVariant" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.germlineVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter = "PASS") AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.germlineVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter = "PASS") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "germlineVariantPathogenic" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.germlineVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter = "PASS" AND pathogenic != 0) AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.germlineVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter = "PASS" AND pathogenic != 0) AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "germlineVariantReported" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.germlineVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter = "PASS" AND reported != 0) AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.germlineVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter = "PASS" AND reported != 0) AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "somaticVariant" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.somaticVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter = "PASS") AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.somaticVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter = "PASS") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "somaticVariantReported" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.somaticVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter = "PASS" AND reported = 1) AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.somaticVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter = "PASS" AND reported = 1) AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "structuralVariant" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.structuralVariant WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND filter <> "PON") AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.structuralVariant WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND filter <> "PON") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "svBreakendDisruptive" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.svBreakend WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND disruptive = 1) AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.svBreakend WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND disruptive = 1) AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "svBreakendReported" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.svBreakend WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND reportedDisruption = 1) AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.svBreakend WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND reportedDisruption = 1) AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "svFusion" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.svFusion WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.svFusion WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "svFusionReported" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.svFusion WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID" AND reported = 1) AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.svFusion WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID" AND reported = 1) AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "driverCatalog" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.driverCatalog WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.driverCatalog WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "virusBreakend" AS Type,
  (SELECT COUNT(*) FROM VARIABLE_TRUTH_DB_SCHEMA.virusBreakend WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT COUNT(*) FROM VARIABLE_NEW_DB_SCHEMA.virusBreakend WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "hrStatus" AS Type,
  (SELECT hrStatus FROM VARIABLE_TRUTH_DB_SCHEMA.chord WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT hrStatus FROM VARIABLE_NEW_DB_SCHEMA.chord WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT STRCMP(New, Truth)) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "msStatus" AS Type,
  (SELECT msStatus FROM VARIABLE_TRUTH_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT msStatus FROM VARIABLE_NEW_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT STRCMP(New, Truth)) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "tmbStatus" AS Type,
  (SELECT tmbStatus FROM VARIABLE_TRUTH_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT tmbStatus FROM VARIABLE_NEW_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT STRCMP(New, Truth)) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "tmlStatus" AS Type,
  (SELECT tmlStatus FROM VARIABLE_TRUTH_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT tmlStatus FROM VARIABLE_NEW_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT STRCMP(New, Truth)) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "cuppaTumorLocation" AS Type,
  (SELECT cuppaTumorLocation FROM VARIABLE_TRUTH_DB_SCHEMA.cuppa WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT cuppaTumorLocation FROM VARIABLE_NEW_DB_SCHEMA.cuppa WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT STRCMP(New, Truth)) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "sufficientCoverage" AS Type,
  (SELECT sufficientCoverage FROM VARIABLE_TRUTH_DB_SCHEMA.metric WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT sufficientCoverage FROM VARIABLE_NEW_DB_SCHEMA.metric WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "purity" AS Type,
  (SELECT purity FROM VARIABLE_TRUTH_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT purity FROM VARIABLE_NEW_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
UNION SELECT "VARIABLE_NEW_SAMPLE_ID" AS Sample, "ploidy" AS Type,
  (SELECT ploidy FROM VARIABLE_TRUTH_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_TRUTH_SAMPLE_ID") AS Truth,
  (SELECT ploidy FROM VARIABLE_NEW_DB_SCHEMA.purity WHERE sampleId = "VARIABLE_NEW_SAMPLE_ID") AS New,
  (SELECT New - Truth) AS Delta,
  (SELECT CASE WHEN Delta = 0 THEN "PASS" ELSE "FAIL" END) AS Result
;