#!/usr/bin/env bash

source message_functions || exit 1

jobs_dir=$1
logs_dir=$2
db_schema=$3
tag=$4 # eg "before_load" or "after_load"

info "Starting execution of verification SQL jobs"
find "${jobs_dir}" -type f -name "*.sql" | while read -r sql_file ; do
    job_name="$(basename "${sql_file}")"
    log_file="${logs_dir}/${job_name}.log"
    [[ -n "${tag}" ]] && log_file="${logs_dir}/${tag}_${job_name}.log"
    info "Executing ${job_name} (log: ${log_file})"
    execute_sql_on_pipeline_verification_db "${db_schema}" "${sql_file}" > "${log_file}"
done
info "Finished execution of verification SQL jobs"