#!/usr/bin/env bash

pilot_report_json=$1 && shift
prod_report_json=$1 && shift

diff <(jq . ${pilot_report_json}) <(jq . ${prod_report_json})

## add row number in json file
# cat {json_file} | jq '.' > {temp_json_file}
# cat --number {temp_json_file}