#!/usr/bin/env bash

source message_functions || exit 1

print_usage(){
    echo "-----"
    echo " Descr: Verifies a new COLO829T Somatic pipeline run"
    echo " Usage: $(basename $0) -o <out_dir> -t <truth_dir> -n <truth_dir>"
    echo " Options:"
    echo "   -o  out_dir    Path to output directory"
    echo "   -t  truth_run  Path to directory of truth run"
    echo "   -n  truth_run  Path to directory of new run to be verified"
    echo "   -f  force      Continue if output directory already exists"
    echo " Example:"
    echo "   $(basename $0) -o /path/to/p5_verification_v5.25 -t /path/to/211029_COLO829v003_v5.24 /path/to/YYMMDD_COLO829v003_v5.25"
    echo "-----"
    exit 1
}

sanity_checks="TRUE"
while getopts ':fo:t:n:' flag; do
    case "${flag}" in
        f) sanity_checks="FALSE" ;;
        o) out_dir=${OPTARG} ;;
        t) truth_run=${OPTARG} ;;
        n) new_run=${OPTARG} ;;
        *) print_usage
        exit 1 ;;
    esac
done

if [[ -z "${out_dir}" || -z "${truth_run}" || -z "${new_run}" ]]; then
    print_usage
fi

main() {
    info "Starting with script $(basename $0)"

    truth_run=$(realpath "$truth_run")
    new_run=$(realpath "$new_run")
    
    ## some input sanity checks
    [[ -n "${out_dir}" && "${out_dir}" =~ ^\/ ]] || die "Incorrect out_dir format (${out_dir})?"
    [[ -f "${new_run}/pipeline.version" ]] || die "Pipeline version file missing (in new run: ${new_run})"
    [[ -d "${new_run}" ]] || die "New run dir not found (${new_run})"
    [[ -d "${truth_run}" ]] || die "Truth run dir not found (${truth_run})"
    if [[ "${sanity_checks}" == "TRUE" ]]; then
        [[ ! -d "${out_dir}" ]] || die "Output dir exists (${out_dir})"
    fi

    info "Constructing variables"
    truth_run_name=$(basename "${new_run}")
    new_run_name=$(basename "${new_run}")
    jobs_dir="${out_dir}/jobs"
    logs_dir="${out_dir}/logs"

    info "Config:"
    info "  Out path: ${out_dir}"
    info "  Jobs directory: ${jobs_dir}"
    info "  Logs directory: ${logs_dir}"
    info "  Truth run name: ${truth_run_name}"
    info "  New run name: ${new_run_name}"

    info "Creating directory structure"
    mkdir -p "${out_dir}" "${jobs_dir}" "${logs_dir}" || die "Unable to create dirs"
    cd "${out_dir}" || die "Unable to move to output directory"

    info "Gathering script and sql job files"
    jobs_source_path="/data/repos/scripts/validation"
    script_jobs=(
        "${jobs_source_path}/compare_v5_runs"
        "${jobs_source_path}/diff_v5_COLO829v003_runs"
        "/data/repos/scripts/functions/test/locate_files_test"
        "${jobs_source_path}/run_all_sql_verification_jobs"
    )
    sql_jobs=(
        "${jobs_source_path}/check_update_time.sql"
        "${jobs_source_path}/compare_metrics.sql"
        "${jobs_source_path}/compare_purity.sql"
        "${jobs_source_path}/counts_variants.sql"
        "${jobs_source_path}/diff_somatic_variants.sql"
        "${jobs_source_path}/diff_germline_variants.sql"
        "${jobs_source_path}/diff_sv.sql"
        "${jobs_source_path}/diff_sv_test.sql"
    )
    for job_file_path in "${script_jobs[@]}" "${sql_jobs[@]}"; do
        copy_file "${job_file_path}" "${jobs_dir}"
    done

    metadata_file="${new_run}/metadata.json"
    info "Checking format of ${metadata_file}"
    check_metadata_json "${metadata_file}"

    grep_for="err|warn|exit|excep"
    info "Looking for anomalies in run.log files (${grep_for})"
    find "${new_run}" -name "run.log" -exec grep -Pi "${grep_for}" {} + | grep -v germline_caller > "${logs_dir}/runlogs_check.txt"

    info "Executing locate_files test"
    "${jobs_dir}/locate_files_test" "${new_run}" > "${logs_dir}/locate_files_test.log" 2>&1

    info "Executing compare_v5_runs"
    out_log="${logs_dir}/compare_v5_runs.log"
    err_log="${logs_dir}/compare_v5_runs.err"
    "${jobs_dir}/compare_v5_runs" "${truth_run}" "${new_run}" > "${out_log}" 2>"${err_log}"

    info "Executing diff_v5_COLO829v003_runs"
    "${jobs_dir}/diff_v5_COLO829v003_runs" "${truth_run}" "${new_run}" > "${logs_dir}/diff_v5_COLO829v003_runs.log" 2>&1

    db_load_script="load_run_into_pipeline_v5_validation_db"
    sql_query_script="run_all_sql_verification_jobs"
    info "TODO manual steps:"
    info "  1. Inspect all log files in ${logs_dir}"
    info "  2. If not already loaded: Execute sql queries (nohup ${sql_query_script} ${jobs_dir} ${logs_dir} before_load > ${logs_dir}/run_all_sql_verification_jobs_before_load.log &)"
    info "  3. If not already loaded: Load into DB (nohup ${db_load_script} ${new_run} > ${logs_dir}/${db_load_script}.log &)"
    info "  4. Execute sql queries again after load (nohup ${sql_query_script}  ${jobs_dir} ${logs_dir} after_load > ${logs_dir}/run_all_sql_verification_jobs_after_load.log &)"
    info "  5. Inspect all SQL log files in logs dir (ls ${logs_dir})"
    info "Finished with $(basename $0)"
}

copy_file() {
    local file_path=$1 && shift
    local target_dir=$1 && shift

    if [[ ! -f "${file_path}" ]]; then
        die "File not found (${file_path})"
    else
        info "Copying file ($file_path)"
        cp "${file_path}" "${jobs_dir}"
        [[ $? -eq 0 ]] || die "Unable to copy file (${file_path}) to dir (${target_dir})"
    fi
}

check_metadata_json() {
    local metadata_json=$1 && shift
    fields_to_check=(
        '.set'
        '.reference.sampleName'
        '.reference.barcode'
        '.tumor.sampleName'
        '.tumor.barcode'
        '.tumor.primaryTumorDoids'
    )
    for field in ${fields_to_check[*]}; do
        if [[ $(jq "select(${field} == null)" "${metadata_json}") ]]; then
            warn "  Field ${field} absent metadata (${metadata_json})"
        else
            info "  OK field found in metadata (${field})"
        fi
    done

    # specific check on COLO doid
    tumor_name=$(jq '.tumor.sampleName' "${metadata_json}")
    expected_doid="8923"
    if [[ "$tumor_name" =~ COLO829 ]]; then
        doid=$(jq -r '.tumor.primaryTumorDoids | join(",")' "${metadata_json}")
        if [[ "${doid}" == "${expected_doid}" ]]; then
            info "  OK found expected tumor DOIDs '${expected_doid}' in metadata json"
        else
            warn "  Expected tumor DOIDs '${expected_doid}' but found '${doid}' instead"
        fi
    fi
}

main
