#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source database_functions || exit 1

actin_database_jar=$1 && shift
actin_database_name=$1 && shift

if [[ -z ${actin_database_jar} || -z ${actin_database_name} ]]; then
    error "Parameters missing."
fi

clinical_feed_directory=$(locate_actin_clinical_feed_directory)
clinical_curation_directory=$(locate_actin_clinical_curation_directory)

credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}" "${actin_database_name}")

java11 -Xmx8G -Xms2G -jar ${actin_database_jar} \
    -clinical_feed_directory ${clinical_feed_directory} \
    -clinical_curation_directory ${clinical_curation_directory} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"

