#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source database_functions || exit 1

actin_credentials=$1 && shift
actin_jar=$1 && shift
actin_database_name=$1 && shift

if [[ -z "${actin_credentials}" || -z "${actin_jar}" || -z "${actin_database_name}" ]]; then
    error "Parameters missing. Exiting."
fi

clinical_directory="$(locate_actin_curated_clinical_directory)"

db_user=$(extract_database_user "${actin_credentials}")
db_pass=$(extract_database_password "${actin_credentials}")
db_url=$(construct_database_url "${actin_credentials}" "${actin_database_name}")

info "Loading all clinical data into ACTIN database '${actin_database_name}'"
java -cp ${actin_jar} com.hartwig.actin.database.clinical.ClinicalLoaderApplication \
    -clinical_directory ${clinical_directory} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"
