#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

actin_db=$1 && shift

if [[ -z "${actin_db}" ]]; then
    error "No ACTIN db provided. Exiting"
fi

# Resources
actin_database_sql=/data/resources/custom/actin/sql_database/generate_database.sql

# Database details
credentials=$(gcloud secrets versions access "latest" --secret=mysql-patients-sql-prod-1-writer --project=hmf-secrets)

db_user=$(echo ${credentials} | sed 's/ /\n/g' | grep user= | cut -d"=" -f2 | sed 's/"//g')
db_pass=$(echo ${credentials} | sed 's/ /\n/g' | grep password= | cut -d"=" -f2  | sed 's/"//g')
db_host=$(echo ${credentials} | sed 's/ /\n/g' | grep host= | cut -d"=" -f2 | sed 's/"//g')

info "Rebuilding ACTIN db '${actin_db}' on '${db_host} using ${actin_database_sql}"

mysql ${actin_db} --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${actin_database_sql}
