#!/usr/bin/env bash

source locate_files || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting."
fi

actin_jar="$(locate_pilot_actin)"
actin_database_name="actin_pilot"

do_load_actin_molecular ${sample} ${actin_jar} ${actin_database_name}
