#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

patient=$1 && shift

if [[ -z "${patient}" ]]; then
    error "Parameters missing. Exiting."
fi

actin_credentials="$(prod_writer_sql_credentials)"
actin_jar="$(locate_cohort_actin)"
actin_database_name="actin_cohort"

patient_json="$(locate_actin_cohort_molecular_directory ${patient})/${patient}.patient_record.json"

do_load_actin_molecular ${patient_json} "${actin_credentials}" ${actin_jar} ${actin_database_name}
