#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

actin_database_jar=$(locate_pilot_actin_database)

clinical_feed_directory=$(locate_actin_clinical_feed_directory)
clinical_curation_directory=$(locate_actin_clinical_curation_directory)

credentials=$(prod_writer_sql_credentials)

db_host=$(extract_database_host "${credentials}")
db_port=$(extract_database_port "${credentials}")
db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")

database_name="actin_pilot"
db_url="mysql://${db_host}:${db_port}/${database_name}?enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2&serverTimezone=CET&useSSL=false"

java11 -Xmx8G -Xms2G -jar ${actin_database_jar} \
    -clinical_feed_directory ${clinical_feed_directory} \
    -clinical_curation_directory ${clinical_curation_directory} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"

