#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting."
fi

actin_credentials="$(prod_writer_sql_credentials)"
actin_jar="$(locate_actin_jar_on_vm)"
actin_database_name="actin_pilot"

molecular_json="$(locate_actin_molecular_json ${sample})"

do_load_actin_molecular ${molecular_json} "${actin_credentials}" ${actin_jar} ${actin_database_name}
