#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

info "Loading all treatment match results into ACTIN EMC database"
for run_dir in $(locate_actin_treatment_match_directory)/*; do
    json_file=$(basename ${run_dir})
    patient=$(echo ${json_file} | cut -d "." -f 1)

    load_actin_treatment_match_emc ${patient}
done
