#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

actin_credentials="$(emc_actin_writer_sql_credentials)"
actin_jar="$(locate_pilot_actin)"
actin_database_name="actin"

do_load_actin_treatments ${actin_jar} ${actin_database_name}
