#!/usr/bin/env bash

source locate_files || exit 1
source message_functions || exit 1

info "Loading all treatment match results into ACTIN EMC database"

for json_file in $(locate_actin_treatment_match_directory)/*; do
    treatment_match_json=$(basename ${json_file})
    patient=$(echo ${treatment_match_json} | cut -d "." -f 1)

    load_actin_treatment_match_emc ${patient}
done
