#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

actin_credentials="$(prod_actin_writer_sql_credentials)"
actin_jar="$(locate_pilot_actin)"
actin_database_name="actin"

trial_database_directory="$(locate_actin_trial_database_directory)"

do_load_actin_trials ${trial_database_directory} "${actin_credentials}" ${actin_jar} ${actin_database_name}
