#!/usr/bin/env bash

source locate_files || exit 1
source database_functions || exit 1

actin_credentials="$(prod_writer_sql_credentials)"
actin_jar="$(locate_actin_jar_on_vm)"
actin_database_name="actin_pilot"

trial_database_directory="$(locate_actin_trial_database_directory)"

do_load_actin_trials ${trial_database_directory} "${actin_credentials}" ${actin_jar} ${actin_database_name}
