#!/usr/bin/env bash

snpeff_database=$1 && shift
vcf=$1 && shift

java -jar /data/tools/snpEff/4.3s/snpEff.jar \
    -c /data/resources/custom/snpeff/snpEff.config "${snpeff_database}" \
    -v ${vcf} \
    -hgvs \
    -lof \
    -no-downstream \
    -ud 1000 \
    -no-intergenic \
    -noShiftHgvs
