#!/usr/bin/env bash

snpeff_database=$1 && shift
vcf=$1 && shift

java -jar /data/common/tools/snpEff_v4.3s/snpEff.jar \
    -c /data/common/tools/snpEff_v4.3s/snpEff.config "${snpeff_database}" \
    -v ${vcf} \
    -hgvs -lof -no-downstream -ud 1000 -no-intergenic -noShiftHgvs