#!/usr/bin/env bash

password=$1 && shift

input_samples=/data/common/dbs/idgenerator/input/samples.csv
patient_mapping=/data/common/dbs/idgenerator/input/patient_mapping.csv

do_run_hmf_id_generator \
    -anonymize_ids \
    -password ${password} \
    -sample_ids_file ${input_samples} \
    -patient_mapping_file ${patient_mapping}
