#!/usr/bin/env bash

password=$1 && shift
sample_ids_file=$1 && shift

if [ -z "${password}" ]; then
    echo "[ERROR] Please provide an anonimisation password! Exiting"
    exit 1
fi

if [ -z "${sample_ids_file}" ]; then
    echo "[INFO] No sample IDs file provided. Using default"
    sample_ids_file=/data/common/dbs/idgenerator/input/samples.csv
fi

patient_mapping=/data/common/dbs/idgenerator/input/patient_mapping.csv

do_run_hmf_id_generator \
    -anonymize_ids \
    -password ${password} \
    -sample_ids_file ${sample_ids_file} \
    -patient_mapping_file ${patient_mapping} \
    "$@"
