#!/usr/bin/env bash

source database_functions || exit 1

id_generator_jar=$1 && shift
database=$1 && shift
sample_hashes_in=$1 && shift
sample_hashes_out=$1 && shift

password=$(cat /data/common/dbs/idgenerator/credentials/anonimisation_pwd)

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_host=$(extract_database_host "${credentials}")
db_port=$(extract_database_port "${credentials}")
db_dependencies=$(extract_database_dependencies "${credentials}")
db_url=$( echo "mysql://${db_host}:${db_port}/${database}?serverTimezone=CET${db_dependencies}")

java -jar ${id_generator_jar} \
    -password ${password} \
    -in "${sample_hashes_in}" \
    -out "${sample_hashes_out}" \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"