#!/usr/bin/env bash

source database_functions || exit 1

id_generator_jar=$1 && shift
database_name=$1 && shift
sample_hashes_in=$1 && shift
sample_hashes_out=$1 && shift

password=$(cat /data/resources/custom/idgenerator/credentials/anonimisation_pwd)

credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
db_url=$(construct_database_url "${credentials}", ${database_name})

java -jar ${id_generator_jar} \
    -password ${password} \
    -in "${sample_hashes_in}" \
    -out "${sample_hashes_out}" \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    "$@"