#!/bin/bash

id_generator_script=/data/common/repos/scripts/hmftools/idgenerator/run_hmf_id_generator
password=$1
new_password=$2

${id_generator_script} -update_ids -password ${password} -new_password ${new_password}

