#!/usr/bin/env bash

source message_functions || exit 1


if [[ $# -gt 1 ]]; then
    echo "Only one option may be provided"
    exit 1
fi
case "$1" in
    --major|-M) BUMP_TYPE="major" ;;
    --minor|-m) BUMP_TYPE="minor" ;;
    --patch|-p) BUMP_TYPE="patch" ;;
    --beta|-b)  BUMP_TYPE="beta"  ;;
esac

git status &>/dev/null || { echo "Not in a git checkout" >&2; exit 1; }

TAG_REGEX="^v?(([0-9]+)\.([0-9]+)\.([0-9]+)(-((alpha|beta)\.([0-9])+))?(_([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
latest="$(git tag -l | egrep "$TAG_REGEX" | sort -V | tail -n1)"
if [[ ${latest} =~ ${TAG_REGEX} ]]; then
    branch="$(git branch | grep '^*' | cut -d' ' -f2)"
    a=${BASH_REMATCH[2]}
    b=${BASH_REMATCH[3]}
    c=${BASH_REMATCH[4]}
    beta_version=${BASH_REMATCH[8]}
    description=${BASH_REMATCH[9]}
    final_version=${BASH_REMATCH[11]}
    major="$((a+1)).0.0"
    minor="${a}.$((b+1)).0"
    patch="${a}.${b}.$((c+1))"

    if [[ ${branch} == "master" ]]; then
        if [[ ${BUMP_TYPE} == "beta" ]]; then
            echo "Cannot make beta releases on [master]" >&2
            exit 1
        fi
        if [[ -n "${BUMP_TYPE}" ]]; then
            echo "${!BUMP_TYPE}"
            exit 0
        fi
        printf "Next tags:\n\n"
        info "Major/minor/patch: $major / $minor / $patch"
        info "Beta branch names: Cannot make beta releases on [master]"
    else
        local_beta="$(diff <(git tag --merged master) <(git tag --merged "$branch") | grep '^>' | sort -V | tail -n1 | cut -d' ' -f2)"
        if [[ -z ${local_beta} ]]; then
            beta_suffix="beta.1_${branch}"
        else
            beta_suffix="beta.$((beta_version+1))${description}"
        fi


        if [[ ${BUMP_TYPE} == "beta" ]]; then
            if [[ -z ${local_beta} ]]; then
                echo "No existing beta tag on branch [${branch}]. Use --major, --minor, or --patch to create the first beta." >&2
                exit 1
            fi
            [[ ${local_beta} =~ ${TAG_REGEX} ]]
            echo "${BASH_REMATCH[2]}.${BASH_REMATCH[3]}.${BASH_REMATCH[4]}-beta.$((BASH_REMATCH[8]+1))${BASH_REMATCH[9]}"
            exit 0
        fi
        if [[ -n ${BUMP_TYPE} ]]; then
            echo "${!BUMP_TYPE}-${beta_suffix}"
            exit 0
        fi
        printf "Next tags:\n\n"
        info "Major/minor/patch: Cannot make non-beta releases on non-master branch [${branch}]"
        printf "Beta branch names: "
        echo "${major}-${beta_suffix} / ${minor}-${beta_suffix} / ${patch}-${beta_suffix}"
    fi
    echo
fi
