#!/usr/bin/env bash

JSON_PATH=$1

if [ -z ${JSON_PATH+x} ]; then
    echo "[EXIT] No json given"
    exit 1
fi

sbp_curl https://api.hartwigmedicalfoundation.nl/hmf/v1/shares -XPOST -H "Content-Type: application/json" -d @${JSON_PATH}