#!/usr/bin/env bash

json_path=$1

if [[ -z ${json_path+x} ]]; then
    echo "[ERROR] No json given"
    exit 1
fi

sbp_curl https://api.hartwigmedicalfoundation.nl/hmf/v1/shares -XPOST -H "Content-Type: application/json" -d @${json_path}