#!/usr/bin/env bash

share_id=$1 # eg 118

if [[ -z ${share_id+x} ]]; then
    echo "[ERROR] No share id given?"
    exit 1
fi

sbp_curl https://api.hartwigmedicalfoundation.nl/hmf/v1/shares/${share_id} -XDELETE