#!/usr/bin/env bash

api_cred_dir="/data/common/dbs/api_credentials"
api_crt_file="${api_cred_dir}/api.crt"
api_key_file="${api_cred_dir}/api.key"

curl -v --cert-type pem --cert ${api_crt_file} --key ${api_key_file} "$@"