#!/bin/bash
source locate_files
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

data_output_dir=${run_dir}/svAnalysis
credentials=/data/common/dbs/mysql_credentials/prod
sv_jar=/data/common/tools/variantannotator_v2.8/variant-annotator.jar
sample=$(load_tumor_sample_from_metadata ${run_dir})

${prefix}/do_run_va_fus_dis_only ${sample} ${data_output_dir} ${credentials} ${sv_jar} $@
