#!/bin/bash
source locate_files
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

data_output_dir=${run_dir}/sv
credentials=/data/common/dbs/mysql_credentials/prod
patient_db_jar=/data/common/tools/patient-db_v3.20/patient-db.jar
sample=$(load_tumor_sample_from_metadata ${run_dir})
structural_vcf=$(locate_purple_structural_variants ${run_dir})

${prefix}/do_run_load_sv ${sample} ${data_output_dir} ${structural_vcf} ${credentials} ${patient_db_jar} $@
