#!/bin/bash

run_dir=$1 && shift
sample=$1 && shift
credentials=$1 && shift
sv_jar=$1 && shift

db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

fusion_csv=/data/common/dbs/cosmic_census/171127_cosmic_gene_fusions.csv
ensembl_db=$(cat ${prefix}/ensembl_db_url | head -n 1)

structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf)
if [ $? -ne 0 ]
then
    echo "Unable to locate bpi structural variants. Exiting."
    exit 1
fi

java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
    -jar ${sv_jar} \
    -vcf_file ${structural_vcf} \
    -sample ${sample} \
    -ensembl_db ${ensembl_db} \
    -fusion_csv ${fusion_csv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    $@
