#!/bin/bash
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/gridss_test
sv_jar=/data/common/tools/variantannotator_pilot/variant-annotator.jar
ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

sample=$(load_tumor_sample_from_metadata ${run_dir})

structural_vcf=$(find -L ${run_dir}/purple/ -type f -name *.purple.sv.vcf.gz)
if [ -z ${structural_vcf} ]
then
    echo "Unable to locate gridss structural variants. Exiting."
    exit 1
fi

${prefix}/do_run_sv_loader ${sample} ${structural_vcf} ${credentials} ${sv_jar} -ref_genome ${ref_genome} $@
