#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/tools/patient-db_v1.0/credentials
sv_jar=/data/common/tools/variantannotator_v1.0/variant-annotator.jar

${prefix}/do_run_sv_loader ${run_dir} ${credentials} ${sv_jar} $@
