#!/bin/bash
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/prod
sv_jar=/data/common/tools/variantannotator_v1.4/variant-annotator.jar
sample=$(load_tumor_sample_from_metadata ${run_dir})

${prefix}/do_run_sv_loader ${sample} ${run_dir} ${credentials} ${sv_jar} $@
