#!/usr/bin/env bash

########################## ACTIN GCP projects and VMs #########################

pilot_actin_project() {
    echo "hmf-crunch"
}

pilot_actin_vm() {
    echo "data-vm-prod-2"
}

production_actin_emc_project() {
    echo "actin-emc"
}

production_actin_emc_ops_vm() {
    echo "emc-vm-operations"
}

production_actin_nki_project() {
    echo "actin-nki"
}

production_actin_nki_ops_vm() {
    echo "nki-vm-operations"
}

production_actin_mcgi_project() {
    echo "actin-mcgi"
}

production_actin_mcgi_ops_vm() {
    echo "mcgi-vm-operations"
}


production_actin_serve_vm() {
    echo "serve-vm-actin-1"
}

production_actin_serve_project() {
    echo "hmf-crunch"
}

################################ ACTIN Databases ##############################

emc_phase1_sql_database_name() {
    echo "actin_emc_phase1"
}
