#!/usr/bin/env bash

source message_functions || exit 1

actin_submission="HMFregACTN"

info "Querying LIMS regarding ACTIN samples"
query_lims.pl -type samples -filter "submission=${actin_submission}"

info "Querying API regarding ACTIN samples"
hmf_api_get 'samples?submission=${actin_submission}' | jq

info "Querying API regarding ACTIN runs"
hmf_api_get 'runs?submission=${actin_submission}'