#!/bin/bash

sample_id=$1 && shift
output_dir=$1 && shift
knowledgebase=$1 && shift

actionability_analyzer_application_jar=/data/common/tools/actionability_pilot/actionability-analyzer.jar

echo "Extracting actionability for sample ${sample_id}"
echo "Using the knowledgebase from ${knowledgebase}"
echo "output files are writing to ${output_dir}"

db_credentials=/data/common/dbs/mysql_credentials/prod
db_user=$(awk '/^user/ {print $2}' ${db_credentials})
db_pass=$(awk '/^pass/ {print $2}' ${db_credentials})
db_url=$(awk '/^url/ {print $2}' ${db_credentials})

java -Dorg.jooq.no-logo=true -jar ${actionability_analyzer_application_jar} \
    -sample_ID ${sample_id} \
    -output_dir ${output_dir} \
    -knowledgebase ${knowledgebase} \
    -hmfpatients_db ${db_url} \
    -db_user ${db_user} \
    -db_password ${db_pass}
