#!/bin/bash
#
# Performs GRIDSS preprocessing
#
source do_run_gridss_lib

input_vcf=$1 && shift

PICARD_JAR=${base_path}/tools/picard-tools_v1.135/picard.jar
ref_genome=${base_path}/refgenomes/human_virus/human_virus.fa
output_vcf=${input_vcf/.vcf.gz/.ann.vcf.gz}
input_decompressed=${input_vcf/.gz/}
withBEALN=${output_vcf}.withbealn.vcf
missingBEALN=${output_vcf}.missingbealn.vcf
annotatedBEALN=${output_vcf}.withannotation.vcf

if [[ ! -f ${input_vcf} ]] ; then
	echo "[ERROR] Missing input VCF $input_vcf"
	exit 1
fi

if [[ "${input_vcf/.ann.vcf.gz/}" != "$input_vcf" ]] ; then
	echo "[WARN] Already annotated purple VCF $input_vcf. Exiting."
    exit 1
fi

gunzip -c ${input_vcf} > ${input_decompressed}
grep -E "^#" < ${input_decompressed} | tee ${withBEALN} > ${missingBEALN}
grep BEALN < ${input_decompressed}  | grep -vE "^#" >> ${withBEALN}
grep -v BEALN < ${input_decompressed}  | grep -vE "^#" >> ${missingBEALN}

# Work-around for https://github.com/PapenfussLab/gridss/issues/199
CANDIDATES=$(grep -vE "^#" < ${missingBEALN} | grep -E '([].[][ACGTNagctn]{2})|([ACGTNagctn]{2}[].[])' | wc -l)
if [[ ${CANDIDATES} -gt 0 ]] ; then
	java -Xmx1G ${gridss_jvm_args} \
		-Dgridss.output_to_temp_file=true \
		gridss.AnnotateUntemplatedSequence \
		REFERENCE_SEQUENCE=${ref_genome} \
		INPUT=${missingBEALN} \
		OUTPUT=${annotatedBEALN} \
		WORKER_THREADS=${threads}
else
	cp ${missingBEALN} ${annotatedBEALN}
fi

java -jar ${PICARD_JAR} SortVcf \
	I=${withBEALN} \
	I=${annotatedBEALN} \
	O=${output_vcf}

rm ${input_decompressed} ${withBEALN} ${missingBEALN} ${annotatedBEALN} ${annotatedBEALN}.idx