#!/bin/bash
#
# Performs GRIDSS preprocessing
#
source do_run_gridss_lib

if [[ ! -f $gridss_raw_vcf.unannotated.vcf ]] ; then
	echo $(date) IdentifyVariants
	/usr/bin/time -o ${log_prefix}.IdentifyVariants.log \
	java -Xmx8G $gridss_jvm_args \
		-Dgridss.gridss.output_to_temp_file=true \
		gridss.IdentifyVariants \
		$gridss_common_args \
		INPUT=$normal_bam \
		INPUT=$tumor_bam \
		OUTPUT_VCF=$gridss_raw_vcf.unannotated.vcf \
		ASSEMBLY=$assembly_bam \
		WORKER_THREADS=$threads \
		BLACKLIST=$blacklist \
		CONFIGURATION_FILE=$gridss_config_file
fi
