#!/bin/bash
source load_metadata

libgridss=/data/common/repos/scripts/gridss/
gridss_pon=/data/common/dbs/gridss/pon3792v1/

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

# GRIDSS somatic filtering should use the raw GRIDSS VCF.
original_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.vcf.gz)
if [ -z ${original_vcf} ]
then
    echo "[ERROR] Unable to locate raw gridss structural variants. Exiting."
    exit 1
fi

output_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.vcf
full_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.full.vcf
if [ -a ${output_vcf}.gz ]
then
    echo "[INFO] Already processed gridss structural variants. RERUNNING!"
    #echo "[WARN] Already processed gridss structural variants. Exiting."
    #exit 1
fi

unzipped_vcf=$(dirname ${original_vcf})/$(basename -s .gz ${original_vcf})
# workaround for https://github.com/Bioconductor/VariantAnnotation/issues/19
gunzip -c ${original_vcf} | awk ' { if (length($0) >= 4000) { gsub(":0.00:", ":0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000:")} ; print $0  } ' > ${unzipped_vcf}

Rscript ${libgridss}/gridss_somatic_filter.R -p ${gridss_pon} -i ${unzipped_vcf} -o ${output_vcf} -f ${full_vcf} -s ${libgridss} --gc

rm ${unzipped_vcf}
mv ${output_vcf}.bgz ${output_vcf}.gz
mv ${output_vcf}.bgz.tbi ${output_vcf}.gz.tbi
mv ${full_vcf}.bgz ${full_vcf}.gz
mv ${full_vcf}.bgz.tbi ${full_vcf}.gz.tbi
