#!/bin/bash
source load_metadata

libgridss=/data/common/repos/scripts/gridss/
gridss_pon=/data/common/dbs/gridss/pon/

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift
tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})

original_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.vcf.gz)
if [ -z ${original_vcf} ]
then
    echo "Unable to locate raw gridss structural variants. Exiting."
    exit 1
fi

output_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.vcf
full_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.full.vcf
if [ -a ${output_vcf}.gz ]
then
    echo "Already processed gridss structural variants. Exiting."
    exit 1
fi

unzipped_vcf=$(dirname ${original_vcf})/$(basename -s .gz ${original_vcf})
gunzip -c ${original_vcf} > ${unzipped_vcf}

Rscript ${libgridss}/gridss_somatic_filter.R -p ${gridss_pon} -i ${unzipped_vcf} -o ${output_vcf} -f ${full_vcf} -s ${libgridss}

rm ${unzipped_vcf}
mv ${output_vcf}.bgz ${output_vcf}.gz
mv ${output_vcf}.bgz.tbi ${output_vcf}.gz.tbi
mv ${full_vcf}.bgz ${full_vcf}.gz
mv ${full_vcf}.bgz.tbi ${full_vcf}.gz.tbi