#!/usr/bin/env bash

input_vcf=$1 && shift

output_vcf=${input_vcf/.gz/}

if [[ ! -f ${input_vcf} ]] ; then
	echo "[ERROR] Missing input VCF ${input_vcf}"
	exit 1
fi

base_path="/data/common"
if [ -z "$(hostname | grep datastore)" ]; then
	  # Common folder does not exist on crunches...
	  base_path="/data"
fi

repeatmasker=${base_path}/dbs/repeatmasker/hg19.fa.out
libgridss=/data/common/repos/scripts/gridss/

Rscript ${libgridss}/gridss_annotate_insertions_repeatmaster.R \
	  --input ${input_vcf} \
	  --output ${output_vcf} \
	  --repeatmasker ${repeatmasker} \
	  --scriptdir ${libgridss}

mv ${output_vcf}.bgz ${output_vcf}.gz
mv ${output_vcf}.bgz.tbi ${output_vcf}.gz.tbi
