#!/bin/bash
#
# Performs GRIDSS preprocessing
#
source do_run_gridss_lib

PICARD_JAR=$base_path/tools/picard-tools_v1.135/picard.jar

ref_genome=$base_path/refgenomes/human_virus/human_virus.fa

input_vcf=${run_dir}/purple/${tumor_sample}.purple.sv.vcf.gz
output_vcf=${input_vcf/.vcf.gz/.ann.vcf.gz}

input_decompressed=${input_vcf/.gz/}
withBEALN=$output_vcf.withbealn.vcf
missingBEALN=$output_vcf.missingbealn.vcf
annotatedBEALN=$output_vcf.withannotation.vcf

if [[ $(gunzip -c $input_vcf | grep -E "^#" | grep BPI_AF | wc -l) -gt 0 ]] ; then
	# headers not missing - just decompress as normal
	gunzip -c $input_vcf > $input_decompressed
else
	# hack to add missing headers
	gunzip -c $input_vcf | awk 'NR==10 {print; print "##INFO=<ID=BPI_AF,Number=.,Type=Float,Description=\"Allele fraction at for each breakend\">\n##INFO=<ID=LOCAL_LINKED_BY,Number=1,Type=String,Description=\"Breakend linking information\">\n##INFO=<ID=REMOTE_LINKED_BY,Number=1,Type=String,Description=\"Partner breakend linking information\">"} NR!=10' > $input_decompressed
fi

grep -E "^#" < $input_decompressed | tee $withBEALN > $missingBEALN
grep BEALN < $input_decompressed  | grep -vE "^#" >> $withBEALN
grep -v BEALN < $input_decompressed  | grep -vE "^#" >> $missingBEALN

java -Xmx1G $gridss_jvm_args \
	-Dgridss.output_to_temp_file=true \
	gridss.AnnotateUntemplatedSequence \
	REFERENCE_SEQUENCE=$ref_genome \
	INPUT=$missingBEALN \
	OUTPUT=$annotatedBEALN \
	WORKER_THREADS=$threads

java -jar $PICARD_JAR SortVcf \
	I=$withBEALN \
	I=$annotatedBEALN \
	O=$output_vcf

rm $input_decompressed $withBEALN $missingBEALN $annotatedBEALN $annotatedBEALN.idx