#!/usr/bin/env bash

prefix=`dirname $(readlink $0 || echo $0)`

run_dir=$1 && shift
bachelor_output_dir=bachelor_pilot
bachelor_config=/data/common/dbs/bachelor/lynparza_20180503.xml

credentials=/data/common/dbs/mysql_credentials/pilot
bachelor_jar=/data/common/tools/bachelor_pilot/bachelor.jar
bachelor_pp_jar=/data/common/tools/bachelor-pp_pilot/bachelor-pp.jar

${prefix}/do_run_bachelor_pilot ${run_dir} ${bachelor_output_dir} ${bachelor_config} ${credentials} ${bachelor_jar} ${bachelor_pp_jar} $@

