#!/usr/bin/env bash

source locate_files

prefix=$(dirname $(readlink $0 || echo $0))

bachelor_jar=$(locate_pilot_bachelor)
output_dir=/data/common/dbs/bachelor/pilot

${prefix}/do_create_bachelor_external_db_filters ${bachelor_jar} ${output_dir}


