#!/usr/bin/env bash

sample=$1 && shift
bachelor_dir=$1 && shift
credentials=$1 && shift
bachelor_jar=$1 && shift

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Loading germline variants"

java -Xmx8G -Xms4G -cp ${bachelor_jar} com.hartwig.hmftools.bachelor.LoadGermlineVariants \
    -sample ${sample} \
    -sample_data_dir ${bachelor_dir} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} 

