#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/pilot
bachelor_pp_jar=/data/common/tools/bachelor_pp_pilot/bachelor_pp.jar

${prefix}/do_run_bachelor ${run_dir} ${credentials} ${bachelor_pp_jar} $@
