#!/bin/bash
source load_metadata

run_dir=$1 && shift
credentials=$1 && shift
bachelor_jar=$1 && shift
bachelor_pp_jar=$1 && shift

# CHSH: Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

# CHSH: Load meta data
sample=$(load_tumor_sample_from_metadata ${run_dir})

# CHSH: File Locations
lynparza_config=/data/experiments/eligibility/lynparza_20180503.xml
bach_run_dir=${run_dir}
bach_output_dir=${run_dir}/bachelor/
if [ $? -ne 0 ]
then
    echo "[ERROR] Unable to locate germline variants. Exiting."
    exit 1
fi

if [ ! -d "${bach_output_dir}" ]; then
    echo "[INFO] Creating Bachelor output dir"
    mkdir ${bach_output_dir}
fi

echo "[INFO] Running Bachelor"

java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
    -jar ${bachelor_jar} \
    -sample ${sample} \
    -configXml "$lynparza_config" \
    -germline \
    -runDirectory ${bach_run_dir} \
    -output_dir ${bach_output_dir} \
    -log_debug \
    $@

# CHSH: Slice BAM files using the bachelor bed file just created
bed_file=${bach_output_dir}/bachelor_bed.csv

echo "[INFO] Slicing BAM files"

bed_based_bam_slicer ${bed_file} ${bach_output_dir}

if [ ! -f "${bach_output_dir}/*bam" ]; then
    echo "[ERROR] BAM slicing failed"
    exit
fi

echo "[INFO] Creating Pile-ups"

# /data/common/tools/sambamba_v0.6.5/sambamba mpileup -t 1 CPCT02070218T_13_32915121_32915122.bam --samtools "-q 1 -f /data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta" -L bachelor_bed.csv > CPCT02070218T_001.mpu

ref_genome_file=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta

# Run Mini Pileup on these bam files
fileIndex=1
for file in ${bach_output_dir}/*bam; do
    #echo $file

    mpuFile="${bach_output_dir}${sample}_${fileIndex}.mpu"
    echo $mpuFile

    /data/common/tools/sambamba_v0.6.5/sambamba mpileup \
        -t 1 $file \
        --samtools "-q 1 -f ${ref_genome_file}" \
        -L ${bed_file} \
        > ${mpuFile}

    fileIndex=$(( $fileIndex + 1 ))
done

echo "[INFO] Uploading germline variants"

bach_data_file=${bach_output_dir}/bachelor_output.csv
high_conf_bed=/data/common/dbs/GIAB_NIST_v3.2.2/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz
vcf_header=/data/experiments/eligibility/sample_bachelor_header.vcf

java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
    -jar ${bachelor_pp_jar} \
    -sample ${sample} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
    -bach_input_file ${bach_data_file} \
    -mpileup_dir ${bach_output_dir} \
    -high_confidence_bed ${high_conf_bed} \
    -ref_genome ${ref_genome_file} \
    -write_to_db \
    -write_vcf_file \
    -vcf_header_file ${vcf_header} \
    -data_output_path ${bach_output_dir} \
    -log_debug