#!/usr/bin/env bash

bachelor_jar=/data/common/tools/bachelor_pilot/bachelor.jar

run_dir=$1 && shift
run=$(basename ${run_dir})

java -Xmx8G -Xms4G \
    -jar ${bachelor_jar} \
    -configXml /data/experiments/eligibility/lynparza_20180503.xml \
    -germline
    -output /data/experiments/eligibility/${run}.germline_eligibility.csv \
    -runDirectory ${run_dir}