#!/usr/bin/env bash

source metadata_functions
source locate_files

run_dir=$1 && shift

bachelor_jar=$(locate_prod_bachelor)

# Load meta data
sample=$(load_tumor_sample_from_metadata ${run_dir})
sample_ref=$(load_ref_sample_from_metadata ${run_dir})

# file Locations
clinvar_filters=/data/common/dbs/bachelor/bachelor_clinvar_filters.csv
bachelor_xml_config=/data/common/dbs/bachelor/bachelor_hmf.xml
ref_genome_file=$(locate_ref_genome_fasta_file)

germline_vcf=$(locate_germline_variants ${run_dir} ${sample_ref})

tumor_cram_file=${run_dir}/${sample}/cram/${sample}.cram
bachelor_output_dir=${run_dir}/bachelor
purple_dir=${run_dir}/purple

if [[ ! -d "${bachelor_output_dir}" ]]; then
    echo "[INFO] ${bachelor_output_dir} does not exist yet, creating..."
    mkdir ${bachelor_output_dir}
fi

echo "[INFO] Running Bachelor"

java -Xmx8G -Xms4G -jar ${bachelor_jar} \
    -sample ${sample} \
    -include_vcf_filtered \
    -germline_vcf ${germline_vcf} \
    -tumor_bam_file ${tumor_cram_file} \
    -purple_data_dir ${purple_dir} \
    -xml_config ${bachelor_xml_config} \
    -ext_filter_file ${clinvar_filters} \
    -ref_genome ${ref_genome_file} \
    -output_dir ${bachelor_output_dir} \
    -log_debug