#!/usr/bin/env bash

source message_functions || exit 1

SERVERS=(sts1.prod-1 sts2.prod-1)

main () {
    info "Starting server status check"
    for server in "${SERVERS[@]}"; do
        process_server "$server" "$type"
    done
}

function process_server () {
    local server=$1 && shift
    header "$server"
    header "Docker"
    ssh "$server" "docker ps --format '{{.Names}}: {{.Status}}'"
    header "Flowcells"
    ssh "$server" "find /data/flowcells -mindepth 1 -maxdepth 1 -type d -not -name TestRuns -not -name MyRun" 
    echo ""
}

header () {
   local text=$1 && shift
   echo "# $text:"
}

main
