#!/usr/bin/env bash

source message_functions || exit 1

if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Usage: $(basename "$0") {lab run id}"
    echo " Exmpl: $(basename "$0") NO24-0182"
    echo "        $(basename "$0") NO24-0183 NO24-0184"
    echo "---"
    exit 1
fi

SHEET_LOCATION="/data/tmp/registration_test/samplesheet"
LOG_LOCATION="/data/tmp/registration_test/log"
JSON_LOCATION="/data/tmp/registration_test/json"
NAS_LOCATION="/volume1/worksheets"

T_SAMPLE_IS_REPEAT_ATTEMPT_REGEX="(\d{6}T[IVX]+)|(\d{6}T\d+)"
curr_date=$(date +'%y%m%d')
create_log="${LOG_LOCATION}/${curr_date}_create_jsons"

run_ids=("$@") && shift $#

for sheet in "${run_ids[@]}";
do
  copy_file_from_nas "${NAS_LOCATION}/${sheet}/SampleSheet.csv" "${SHEET_LOCATION}/${sheet}_SampleSheet.csv" || warn "Could not get SampleSheet for ${sheet}"
done

info "JsonCreation started for testing"
for sheet in "${SHEET_LOCATION}"/*SampleSheet*;
do
    echo "${sheet}";
    print_register_json.pl -outdir "${JSON_LOCATION}" -samplesheet "${sheet}" "$@";
done > "${create_log}"

info "JsonCreation done and log written to: ${create_log}"
if [[ $( grep -Pc "${T_SAMPLE_IS_REPEAT_ATTEMPT_REGEX}" "${create_log}" ) -gt 0 ]]; then
    ## multiple biopsies usually need R from bam2fastq
    warn " ATTENTION: Found T[IVX]+ or T\d+ samples so might need to adjust R barcode"
    grep -P "${T_SAMPLE_IS_REPEAT_ATTEMPT_REGEX}" "${create_log}" | grep Somatic_T
fi

## Samples/barcodes that already exist in HMF API already have the use_existing_sample flag
## but in case a barcode is re-used at the same register batch then manual adjustment is needed
for dup_bc in $( cat "${JSON_LOCATION}"/*json | jq -r '.samples[].barcode' | sort | uniq -d ); do
   warn "Found duplicate barcode (${dup_bc}): make sure the use_existing_sample flag is set correctly on second one:";
   find "${JSON_LOCATION}" -maxdepth 1 -name "*json" | while read -r ready_json; do
       if [[ $(grep -c "${dup_bc}" "${ready_json}") -gt 0 ]]; then
           warn "  ${ready_json}"
       fi
   done
done

rm /data/tmp/registration_test/*/*
