#!/usr/bin/env bash

source message_functions || exit 1

json=$1

api_cred_dir="/data/common/dbs/api_credentials/acc"
api_crt_file="${api_cred_dir}/api.crt"
api_key_file="${api_cred_dir}/api.key"
api_url='https://api.acc.hartwigmedicalfoundation.nl/hmf/v1/action/register'

if [[ -z "${json+x}" ]]; then error " No json given"; fi
if [[ ! -f "${api_crt_file}" ]]; then error "File does not exist (${api_crt_file})"; fi
if [[ ! -f "${api_key_file}" ]]; then error "File does not exist (${api_key_file})"; fi
if [[ ! -f "${json}" ]]; then error "File does not exist (${json})"; fi

curl -s -v --cert-type pem --cert ${api_crt_file} --key ${api_key_file} ${api_url} -XPOST -H "Content-Type: application/json" -d @${json}
