#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

bpi_jar=${base_path}/tools/break-point-inspector_pilot/break-point-inspector.jar
# KODU: BPI generally assumes it runs on top of an already run BPI
bpi_output=${run_dir}/structuralVariants/bpi
bpi_version=1.5

${prefix}/do_run_new_bpi ${run_dir} ${bpi_jar} ${bpi_output} ${bpi_version}