#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

path_addition="common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	path_addition=""
fi

bpi_jar=/data/${path_addition}/tools/break-point-inspector_v1.5/break-point-inspector.jar
bpi_output=${run_dir}/structuralVariants/bpi

${prefix}/do_run_bpi ${run_dir} ${bpi_jar} ${bpi_output}
