#!/bin/bash

run_dir=$1 && shift
bpi_jar=$1 && shift
bpi_output=$1 && shift
samtools=/data/common/tools/samtools_v1.2/samtools

mkdir -p ${bpi_output}

structural_vcf=$(ls ${run_dir}/structuralVariants/manta/*/results/variants/somaticSV.vcf.gz)
if [ $? -ne 0 ]
then
	echo "Unable to locate Manta structural variants. Exiting."
	exit 1
fi

tumor_bam=$(ls ${run_dir}/structuralVariants/bpi/*/*T_sliced.bam)
if [ $? -ne 0 ]
then
    echo "Unable to locate tumor bam. Exiting."
    exit 1
fi
${samtools} index ${tumor_bam}

ref_bam=$(ls ${run_dir}/structuralVariants/bpi/*/*R_sliced.bam)
if [ $? -ne 0 ]
then
    echo "Unable to locate ref bam. Exiting."
    exit 1
fi
${samtools} index ${ref_bam}

output_tsv=$(ls ${bpi_output}/*/*.tsv)
if [ $? -ne 0 ]
then
    echo "Unable to locate original bpi tsv. Exiting."
    exit 1
fi

java -Xmx8G -Xms4G \
    -jar ${bpi_jar} \
    -vcf ${structural_vcf} \
    -ref ${ref_bam} \
    -tumor ${tumor_bam} \
    -output_vcf ${bpi_output}/*/*.vcf \
    > ${output_tsv}
