#!/bin/bash
run_dir=$1 && shift
bpi_jar=$1 && shift
bpi_output=$1 && shift
metadata=$run_dir/metadata

if [[ ! -f ${metadata} ]] ; then
    echo "Missing metadata file in run directory. Aborting" 1>&2
    exit 1
fi

source load_metadata
ref_sample=$(load_ref_sample_from_metadata $run_dir)
tumor_sample=$(load_tumor_sample_from_metadata $run_dir)
joint_name=$(load_joint_name_from_metadata $run_dir)

base_path="/data/common"
if [ -z "`hostname | grep datastore`" ]; then
    # KODU: common folder does not exist on crunches...
	base_path="/data"
fi

samtools=${base_path}/tools/samtools_v1.2/samtools

mkdir -p ${bpi_output}

structural_vcf=$(ls ${run_dir}/structuralVariants/manta/*/results/variants/somaticSV.vcf.gz)
if [ $? -ne 0 ]
then
	echo "Unable to locate Manta structural variants. Exiting."
	exit 1
fi

tumor_bam=${run_dir}/structuralVariants/bpi/${joint_name}/${tumor_sample}_sliced.bam
if [ ! -f ${tumor_bam} ]
then
    echo "Unable to locate tumor bam (${tumor_bam}). Exiting."
    exit 1
fi
${samtools} index ${tumor_bam}

ref_bam=${run_dir}/structuralVariants/bpi/${joint_name}/${ref_sample}_sliced.bam
if [ ! -f ${ref_bam} ]
then
    echo "Unable to locate ref bam (${ref_bam}). Exiting."
    exit 1
fi
${samtools} index ${ref_bam}

output_tsv=$(ls ${bpi_output}/*/*.tsv)
if [ $? -ne 0 ]
then
    echo "Unable to locate original bpi tsv. Exiting."
    exit 1
fi

#joint_name=$(basename $(dirname ${output_tsv} ) )
output_vcf=$(dirname ${output_tsv})/${joint_name}_somaticSV_bpi.vcf

if grep -q bpiVersion=1.5 ${output_vcf}; then
    echo "BPI version 1.5 already run. Exiting."
    exit 1
fi

echo "Running BPI on ${run_dir}"

java -Xmx8G -Xms4G \
    -jar ${bpi_jar} \
    -contamination_fraction 0.03 \
    -vcf ${structural_vcf} \
    -ref ${ref_bam} \
    -tumor ${tumor_bam} \
    -output_vcf ${output_vcf} \
    > ${output_tsv}
