#!/usr/bin/env bash

work_dir=$1 && shift

if [[ -z "${work_dir}" ]]; then
    echo "[ERROR] No work dir passed. Exiting!" && exit 1
fi

if [[ ! -d "${work_dir}/somatics" ]]; then
    echo "[ERROR] No somatics dir found in ${work_dir}. Exiting!" && exit 1
fi

if [[ ! -f "${work_dir}/mutationalLoad.tsv" ]]; then
    echo "[ERROR] No mutational load input file found in ${work_dir}. Exiting!" && exit 1
fi

Rscript /data/common/tools/paddle_pilot/dnds.R ${work_dir}