#!/usr/bin/env bash

source locate_files

output_dir=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
    echo "[ERROR] Output dir not a directory. Exiting" && exit 1;
fi

cohort_tsv=${output_dir}/cohort.tsv
cohort_select_samples_sql=/data/common/repos/scripts/hmftools/paddle/select_dnds_example_samples.sql

echo "[INFO] Writing cohort file to ${cohort_tsv} using ${cohort_select_samples_sql}"
execute_sql_on_gcp_prod ${cohort_select_samples_sql} > ${cohort_tsv}

paddle_jar=/data/common/tools/paddle_v1.0/paddle.jar
credentials=$(locate_prod_database_credentials)

# Database details
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})
db_url=$(awk '/^url/ {print $2}' ${credentials})

echo "[INFO] Running paddle exonic variant application with output dir '${output_dir}'"

java -cp ${paddle_jar} com.hartwig.hmftools.paddle.PaddleExonicVariantsApplicationKt  \
    -output_dir ${output_dir} \
    -cohort_tsv ${cohort_tsv} \
    -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} \
