#!/usr/bin/env bash

source locate_files || exit 1

feed_directory="$(locate_actin_clinical_input_feed_directory)"
curation_directory="$(locate_actin_clinical_curation_directory)"
output_directory="$(locate_actin_curated_clinical_directory)"

actin_jar="$(locate_pilot_actin)"

info "Running ACTIN Clinical on ${feed_directory}"
java -cp ${actin_jar} com.hartwig.actin.clinical.ClinicalIngestionApplication \
    -feed_directory ${feed_directory} \
    -curation_directory ${curation_directory} \
    -output_directory ${output_directory} \
    "$@"

