#!/usr/bin/env bash

source message_functions || exit 1

query_1="SELECT patientId, otherMolecularPatientId, birthYear, registrationDate FROM patient WHERE otherMolecularPatientId IS NOT NULL AND otherMolecularPatientId <> '' AND DATEDIFF(current_date,registrationDate)<60;"
query_2="SELECT patientId, otherMolecularPatientId, birthYear, registrationDate FROM patient WHERE otherMolecularPatientId IS NULL AND (YEAR(registrationDate)-birthYear)<40 AND DATEDIFF(current_date,registrationDate)<60;"

echo ""
info "Checking for recent ACTIN patients if other molecular patient IDs exist:"

execute_sql_on_actin_pilot "${query_1}"

echo ""
info "Done!"

echo ""
info "Checking for recent ACTIN patients without other molecular patient IDs, which may be unexpected:"

execute_sql_on_actin_pilot "${query_2}"

echo ""
info "Done!"