#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source actin_config || exit 1

gcp_project="$(production_actin_nki_project)"
transformed_feed_directory="$(locate_actin_transformed_feed_directory)"

mkdir -p "${transformed_feed_directory}"
transformed_contents=$(ls "${transformed_feed_directory}")
if [[ ${transformed_contents} ]]; then
	echo -ne "Some previous transformed feed records exist in ${transformed_feed_directory}:\n${transformed_contents}\nDelete them? (y/N) "
	read -r response
        if [[ "${response}" == "y" || "${response}" == "Y" ]]; then
		rm -rf "${transformed_feed_directory}"
		mkdir -p "${transformed_feed_directory}"
		info "Emptied ${transformed_feed_directory}."
	fi
else
	info "No previous transformed feed found in ${transformed_feed_directory}"
fi

echo -e "\nTransformed feed records in cloud:"
gs_path="${gcp_project}-clinical-feed-transformed"
runs=$(gcloud storage ls gs://${gs_path} | grep "${gs_path}/2")

echo "${runs}" | nl
read -rp "Which run would you like to pull (fill in the ID)? " choice
selected_gs_path=$(echo "${runs}" | sed -n "${choice}p")

if [[ ${selected_gs_path} ]]; then
	all_files=$(gcloud storage ls "${selected_gs_path}")
	shared_data_bucket=$(locate_actin_shared_data_external_bucket "${gcp_project}")
	exclusions=$(gcloud storage ls "${shared_data_bucket}/record" | xargs -Ixxx -n1 basename xxx ".patient_record.json")
	filtered_files=$(echo "${all_files}" | grep -vf <(echo -e "${exclusions}"))

	if [[ -n "${filtered_files[*]}" ]]; then
		path_without_trailing_slash="${selected_gs_path::-1}"
		child_path="${path_without_trailing_slash##*/}"
		mkdir -p "${transformed_feed_directory}/${child_path}"

		gcloud storage cp ${filtered_files} "${transformed_feed_directory}/${child_path}/"
		info "Copied ${selected_gs_path} to ${transformed_feed_directory}/. Previously-shared patients were omitted."
	else
		info "No files to copy after previously-shared patients were omitted."
	fi
fi
