#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source actin_functions || exit 1

dir=$(locate_actin_curated_clinical_directory)

clinical_ingestion_results="${dir}/clinical_ingestion_results.json"
if [[ -f ${clinical_ingestion_results} ]]; then
    info "Removing ${clinical_ingestion_results}"
    rm "${clinical_ingestion_results}"
fi

info "Renaming NKI clinical records in ${dir}"

for json_file in $(ls ${dir}/*.json); do
    json_name=$(basename ${json_file})
    hashed_id=$(echo ${json_name} | cut -d "." -f 1)

    info "Looking up NKI ACTIN ID for ${hashed_id}"
    actin_id=$(find_nki_actin_id_from_hash ${hashed_id})

    if [[ -z "${actin_id}" ]]; then
        error "Could not resolve ACTIN ID for NKI hash ${hashed_id}"
    fi

    info " Resolved ACTIN ID to be ${actin_id} for ${hashed_id}. Renaming clinical json"
    mv "${json_file}" "${dir}/${actin_id}.clinical.json"
done

info "Done!"