#!/usr/bin/env bash

source actin_config || exit 1

curr_host=$(hostname)
if [[ "$(hostname)" == $(production_actin_nki_ops_vm) ]]; then
    actin_clinical_ingestion_nki
elif [[ "$(hostname)" == $(production_actin_emc_ops_vm) ]]; then
    actin_clinical_ingestion_emc
    reload_all_actin_clinical_pilot
else
    error "Can only run actin clinical pipeline on either NKI or EMC ops vm"
fi
