#!/usr/bin/env bash

source locate_files || exit 1

gsutil cp $(locate_actin_clinical_input_feed_directory)/*.tsv $(locate_actin_clinical_feed_input_bucket)
touch $(locate_actin_clinical_input_feed_directory)/upload.complete
gsutil cp $(locate_actin_clinical_input_feed_directory)/upload.complete $(locate_actin_clinical_feed_input_bucket)