#!/usr/bin/env bash

# Note: The 3rd param is the minimal local entries required for the sync to start.

# We assume this script as a cronjob rather than from a terminal, so we need to source .bashrc to get all paths
source ${HOME}/.bashrc

echo "[INFO] Archiving Sequencer Archive"
do_archive_directory_to_gcp /data/sequencer_archive sequencer_archive 2982

echo "[INFO] Archiving Patient Reports"
do_archive_directory_to_gcp /data/cpct/final_reports patient_reports/final 6014
do_archive_directory_to_gcp /data/cpct/old_cpct_reports patient_reports/old 544
do_archive_directory_to_gcp /data/core/final_reports patient_reports/core 59

echo "[INFO] Archiving Data Requests"
do_archive_directory_to_gcp /data/data_archive/datarequests data_requests 111

echo "[INFO] Archiving Submissions"
do_archive_directory_to_gcp /data/submissions submissions 722

echo "[INFO] Archiving Shallow Seq Pipelines"
do_archive_directory_to_gcp /data/data_archive/shallow_seq_pipelines shallow_seq_pipelines 1087

echo "[INFO] Archiving SnpCheck Data"
do_archive_directory_to_gcp /data/common/snpcheck snpcheck 6

echo "[INFO] Archiving Samplesheets"
do_archive_directory_to_gcp /data/samplesheets samplesheets 2828
