#!/usr/bin/env bash

source api_functions || exit 1
source gcp_functions || exit 1
source message_functions || exit 1

set=$1 && shift

if [[ -z "${set}" ]]; then
    error "No set provided to $(basename $0). Exiting"
fi

run_bucket=$(load_intial_run_bucket_for_set ${set})
if [[ -z "${run_bucket}" ]]; then
    error "No initial run bucket found for set '${set}'. Exiting"
fi

info "Copying set ${set} from ${run_bucket} to hmf-crunch"

switch_to_hmf_ops_service_account
gsutil -u hmf-database -m cp gs://${run_bucket}/${set}/sage_somatic/* gs://hmf-sage/${set}/
gsutil -u hmf-database -m cp gs://${run_bucket}/${set}/amber/* gs://hmf-amber/${set}/
gsutil -u hmf-database -m cp gs://${run_bucket}/${set}/cobalt/* gs://hmf-cobalt/${set}/
gsutil -u hmf-database -m cp gs://${run_bucket}/${set}/gridss/*unfiltered.vcf.gz* gs://hmf-gridss/unfiltered/${set}/
gsutil -u hmf-database -m cp gs://${run_bucket}/${set}/gripss/*somatic*.vcf.gz* gs://hmf-gripss/${set}/