#!/usr/bin/env bash

source gcp_functions || exit 1
source message_functions || exit 1

biopsy=$1 && shift
set=$1 && shift
sample=$1 && shift

if [[ -z "${biopsy}" ]] || [[ -z "${sample}" ]]; then
    error "Not all input parameters provided to $(basename $0). Exiting"
fi

ds_path="/data/gcp/cram_downloads/${sample}_cram"

api_request="datasets/${biopsy}"
api_request+="?set=${set}"
api_request+="&output=condensed"
api_request+="&datatype=aligned_reads"

cram_url=$(hmf_api_get "${api_request}" | jq -r ".${sample}.path")

if [[ -z "${cram_url}" ]]; then
    error "$(basename $0) unable to construct gs URL to cram. Exiting"
fi

info "API provided CRAM URL: ${cram_url}"
info "Downloading cram to ${ds_path}"
mkdir -p "${ds_path}"
switch_to_hmf_ops_service_account
gsutil -u hmf-database cp "${cram_url}" "${ds_path}/"