#!/usr/bin/env bash

source api_functions || exit 1
source message_functions || exit 1

set=$1 && shift

if [[ -z "${set}" ]]; then
    error "No set provided. Exiting."
fi

biopsy=$(load_tumor_sample_id_for_set "${set}")
sample=$(load_ref_sample_id_for_set "${set}")

do_download_cram_for_sample "${biopsy}" "${set}" "${sample}"