#!/usr/bin/env bash

KEY="projects/hmf-database/locations/europe-west4/keyRings/hmf-database/cryptoKeys/hmf-database-20191001"

set -e

[[ $# -ne 2 ]] && echo "USAGE: $0 [source_bucket] [project]" && exit 1
source_bucket="gs://${1#gs://}"
gsutil kms encryption -w -k $KEY ${source_bucket}
gsutil -m rewrite -O -k ${source_bucket}/**
