#!/usr/bin/env bash

source api_functions
source locate_files

set_name=$1 && shift
type=$1 && shift

if [[ -z "${set_name}" ]] || [[ -z "${type}" ]]; then
    echo "[ERROR] Not all input parameters provided to $(basename $0)." && exit 1
fi

bam_slicer_jar=/data/common/tools/bam-slicer_v1.5/bam-slicer.jar
gcp_sign_url_script="generate_signed_gcp_url.py"
gcp_key_file="/data/common/dbs/gcp_credentials/hmf-download"
ref_genome=$(locate_ref_genome_fasta_file)

## query run info
run_info=$(load_run_info_for_set ${set_name})

## setup all variables
pipeline=$(extract_pipeline_version_from_run_info "${run_info}")

if [[ ${type} = "REF" ]]; then
    sample=$(load_ref_sample_id_for_set ${set_name})
else
    sample=$(load_tumor_sample_id_for_set ${set_name})
fi

bucket=$(echo ${set_name} | tr A-Z a-z | tr _ -)
bam_prefix="hmf-cram-${bucket}"

if [[ ${pipeline} = v5* ]]; then
    bam="${bam_prefix}/${sample}.cram"
else
    bam="${bam_prefix}/${sample}_dedup.realigned.cram"
fi

internal_bam_url="gs://${bam}"
external_bam_url=$(${gcp_sign_url_script} "${gcp_key_file}" "${bam}" 172800)
echo "$(date +"%H:%M:%S") - [INFO ] - GCP BAM URL: ${internal_bam_url}"
echo "$(date +"%H:%M:%S") - [INFO ] - GCP BAM URL: ${external_bam_url}"

crai=${bam}.crai
internal_crai_url="gs://${crai}"
external_crai_url=$(${gcp_sign_url_script} "${gcp_key_file}" "${crai}" 172800)
echo "$(date +"%H:%M:%S") - [INFO ] - GCP INDEX URL: ${internal_crai_url}"
echo "$(date +"%H:%M:%S") - [INFO ] - GCP INDEX URL: ${external_crai_url}"

