#!/usr/bin/env bash

source api_functions || exit 1
source message_functions || exit 1

biopsy=$1 && shift
# Type can be REF or TUM
type=$1 && shift

if [[ -z "${biopsy}" ]] || [[ -z "${type}" ]]; then
    error "No biopsy name and type provided to $(basename $0)."
fi

if [[ ${type} = "REF" ]]; then
    sample=$(echo $biopsy | cut -c1-12)R
    cram=$(locate_reference_cram ${biopsy})
elif [[ ${type} = "TUM" ]]; then
    sample=$biopsy
    cram=$(locate_tumor_cram ${biopsy})
else
    error "Did not recognize sample type ${type}. Should be REF or TUM"
fi

echo "${sample} ${cram}"


