#!/usr/bin/env bash

source message_functions || exit 1

set=$1 && shift

[[ -n "${set}" ]] || die "No set provided to $(basename $0). Exiting"

bucket="diagnostic-pipeline-output-prod-1"
healthchecker_url="gs://${bucket}/${set}/health_checker/"

healthchecker_success=$( gsutil  -u hmf-database ls ${healthchecker_url} | grep ".HealthCheckSucceeded" | wc -l );
healthchecker_fail=$( gsutil  -u hmf-database ls ${healthchecker_url} | grep ".HealthCheckFailed" | wc -l )

if [[ ${healthchecker_success} == 0 && ${healthchecker_fail} == 0 ]]; then
   warn "HealthChecker has not been run for ${set}"
elif [[ ${healthchecker_success} == 0 ]]; then
   warn "HealthChecker has failed for ${set}!!"
else
   info "HealthChecker has succeeded for ${set}"
fi


# Printing pipeline version just for double-checking!
pipeline_version_url="gs://${bucket}/${set}/pipeline.version"
pipeline_version=$(gsutil -u hmf-database cat "${pipeline_version_url}" )
info "This run has been done with pipeline ${pipeline_version}"

