#!/usr/bin/env bash

source message_functions || exit 1

set=$1 && shift
relative_file_path="health_checker/run.log"

[[ -n "${set}" ]] || die "No set provided to $(basename $0). Exiting"

info "Searching for run to find bucket"
runs_json=$(hmf_api_get "runs?set_name=${set}" | jq '[.[] | select(.ini | test("Somatic.ini|PipelineV5.ini|CPCT.ini")) | select(.bucket | test("diagnostic-pipeline-output-prod-1"))]')
run_count=$(jq 'length' <<< "${runs_json}")

run_json=$(jq '.[-1]' <<< "${runs_json}")
bucket=$(jq -r '.bucket' <<< "${run_json}")
file_url="gs://${bucket}/${set}/${relative_file_path}"

[[ -n "${bucket}" ]] || die "No initial run bucket found for set '${set}'. Exiting"

info "Performing cat on file url (${file_url})"
gsutil -u hmf-database cat "${file_url}"

[[ "${run_count}" -eq 1 ]] || warn "Multiple runs were encountered for set (${run_count}). Results are from most recent run!"