#!/usr/bin/env bash

source message_functions || exit 1

vm_name=""
image_name=""
image_project="hmf-build"
zone="europe-west4-a"
machine_type="n1-standard-2"
disk_type="pd-ssd"
disk_size="200G"
service_account="hmf-crunch@hmf-crunch.iam.gserviceaccount.com"
network="projects/hmf-vpc-network/global/networks/vpc-network-prod-1"
subnet="projects/hmf-vpc-network/regions/europe-west4/subnetworks/vpc-network-subnet-research-prod-1"
family="base"
preemptible="FALSE"
vm_project="hmf-crunch"
startup_script="NONE"
cost_center="experiments"

print_usage() {
    script=$(basename "$0")
    echo ""
    echo "Descr: Creates a VM (using account ${service_account})"
    echo "Usage: ${script} -n <NAME> [options]"
    echo "Examp: ${script} -n ${USER}-test-vm"
    echo ""
    echo "Options:"
    echo "  -i image_name          Image name [default is most recent ${family} image]"
    echo "  -p image_project       Image project [${image_project}]"
    echo "  -m machine_type        VM machine type [${machine_type}]"
    echo "  -s disk_size           VM boot disk size [${disk_size}]"
    echo "  -t disk_type           VM boot disk type [${disk_type}]"
    echo "  -e                     Make VM pre-emptible"
    echo "  -d startup_script      Startup script (as a file) [${startup_script}]"
    echo ""
    echo "See also:"
    echo "  https://cloud.google.com/compute/docs/disks"
    echo "  https://cloud.google.com/compute/docs/machine-types"
    echo "  https://cloud.google.com/sdk/gcloud/reference/compute/instances/create"
    echo "  gcloud --project ${image_project} compute images list | grep ${family}"
    echo "  gcloud --project ${vm_project} compute compute instances list"
    echo "  gcloud compute instances delete --zone ${zone} --quiet \$vm"
    echo "  gcloud compute instances ssh \$vm"
    echo ""
    exit 1
}

while getopts ':n:p:i:m:s:t:ed:c:' flag; do
    case "${flag}" in
        n) vm_name=${OPTARG} ;;
        i) image_name=${OPTARG} ;;
        p) image_project=${OPTARG} ;;
        m) machine_type=${OPTARG} ;;
        s) disk_size=${OPTARG} ;;
        t) disk_type=${OPTARG} ;;
        e) preemptible="TRUE" ;;
        d) startup_script=${OPTARG} ;;
        c) cost_center=${OPTARG} ;;
        *) print_usage
        exit 1 ;;
    esac
done

if [[ -z "${vm_name}" || "$1" == "-h" || "$1" == "--help" ]]; then
    print_usage
fi

# if VM will be created with crunch service account then make sure that project is set
current_project=$(gcloud config get-value project) || die "Unable to get-value project"
if [[ ! "${current_project}" == "${vm_project}" ]]; then
    info "Current config wants to create VM in ${vm_project} but current project is ${current_project}"
    info "Switch to ${vm_project} (gcloud config set project ${vm_project}) and try again"
    exit 1
fi

if [[ -z "${image_name}" ]]; then
    info "Searching for latest ${family} image"
    image_name=$(gcloud --project="${image_project}" compute images describe-from-family "${family}" | grep name | cut -d" " -f2) \
    || die "Unable to describe-from-family from project ${image_project}"
fi

info "Details of VM to be created:"
info "          Name: ${vm_name}"
info "       Project: ${current_project}"
info "         Image: ${image_name} in ${image_project}"
info "        Config: ${machine_type}|${disk_size}|${disk_type}|${zone}|preemptible=${preemptible}"
info "       Account: ${service_account}"
info "Startup script: ${startup_script}"

info "Press [ENTER] to create VM..."
read -r -s

if [[ "${preemptible}" == "TRUE" ]]; then
    preemptible_arg=" --preemptible"
else
    preemptible_arg=""
fi

if [[ "${startup_script}" != "NONE" ]]; then
    startup_script_arg=" --metadata-from-file=startup-script=${startup_script}"
else
    startup_script_arg=""
fi

info "Start creating VM instance ${vm_name}"
gcloud compute instances create "${vm_name}" \
--image "${image_name}" \
--image-project "${image_project}" \
--machine-type "${machine_type}" \
--boot-disk-type "${disk_type}" \
--boot-disk-size "${disk_size}" \
--scopes cloud-platform \
--no-restart-on-failure \
--zone "${zone}" \
--service-account "${service_account}" \
--network "${network}" \
--subnet "${subnet}" \
--no-address \
--metadata enable-oslogin=TRUE \
${preemptible_arg} \
${startup_script_arg} || die "Something wrong with VM creation. Check the gcloud response."

labels="user=$USER,cost_center=${cost_center}"
gcloud compute instances add-labels ${vm_name} --zone=${zone} --labels=${labels}
gcloud compute disks add-labels ${vm_name} --zone=${zone} --labels=${labels}

info "VM usage:"
info "  Access: gcloud compute ssh ${vm_name}"
info "  Delete: gcloud compute instances delete --zone ${zone} -q ${vm_name}"

info "Finished creating VM instance ${vm_name}"
