#!/usr/bin/env bash

source metadata_functions

set=$1

if [ -z "$set" ]; then
    echo "[ERROR] No set provided to process_finished_run. Exiting"
    exit 1
fi

echo "[INFO] Processing finished GCP run ${set}"

download_path=/data/gcp/downloaded_runs
download_set_gcp ${set} ${download_path}
downloaded_set_path=${download_path}/${set}

if [ ! -f ${downloaded_set_path}/metadata.json ]; then
    echo "[ERROR] No metadata file found. Probably something wrong with the downloading of the run. Exiting"
    exit 1;
fi

processed_path=/data/gcp/processed_runs
echo "[INFO] Copying set ${set} to processed path ${processed_path}"
processed_set_path=${processed_path}/${set}

if [ -d ${processed_set_path} ]; then
    echo "[INFO] Removing processed set prior to recopy"
    rm -r ${processed_set_path}
fi

cp -r ${downloaded_set_path} ${processed_set_path}

tumor_sample=$(load_tumor_sample_from_metadata ${processed_set_path})

if [[ ${tumor_sample} =~ ^CORE ]]; then
    echo "[INFO] Skipped loading into database for ${set} because ${tumor_sample} is a CORE sample!"
else
    echo "[INFO] Loading data into production database for ${tumor_sample}"
    load_run_into_prod_db ${processed_set_path}
fi