#!/usr/bin/env bash

source message_functions || exit 1

gcp_project="hmf-database"
gcp_account="hmf-ops"
exclude_rgx='hmf-output-\d+|hmf-cram-'

info "Setting GCP project to ${gcp_project} (ignore access WARNING)"
gcloud config set project "${gcp_project}"

info "Switching to service account ${gcp_account}"
gcloud config set account ${gcp_account}@${gcp_project}.iam.gserviceaccount.com

info "Searching for non-weekly buckets (exclude regex ${exclude_rgx}):"
gsutil -u "${gcp_project}" ls gs:// | \
    grep -vP "${exclude_rgx}" | \
    xargs printf " gsutil -u ${gcp_project} ls %s\n"
