#!/usr/bin/env bash

set -e
source message_functions || exit 1

BUCKET="gs://data-vm-resources-prod-1"
FASTCP="gsutil -m -o GSUtil:parallel_process_count=7 -o GSUtil:parallel_thread_count=1 cp"

info "Syncing data-vm resources to GCP"
gsutil cp /data/dbs/clinical_data/curated_primary_tumor.tsv ${BUCKET}/dbs/clinical_data/curated_primary_tumor.tsv
$FASTCP /data/ops/lims/prod/*.tsv ${BUCKET}/ops/lims/prod/
gsutil cp /data/ops/lims/prod/lims.json ${BUCKET}/ops/lims/prod/
$FASTCP /data/ecrf/* ${BUCKET}/ecrf/

info "Done syncing data-vm resources"
