#!/usr/bin/env bash

echo "[INFO] Syncing registration resources to GCP!"

gcloud auth activate-service-account --key-file /data/common/dbs/gcp_credentials/hmf-ops
gsutil -m rsync -d /data/samplesheets gs://hmf-registration-resources/samplesheets
gsutil -m rsync -d /data/ops/lims/prod gs://hmf-registration-resources/lims/prod

gsutil -m cp -n gs://hmf-registration-resources/jsons_and_logs/jsons/registered/* /data/ops/api/prod/jsons/registered/
gsutil -m cp -n gs://hmf-registration-resources/jsons_and_logs/logs/* /data/ops/api/prod/logs/
