#!/usr/bin/env bash

DIR="/data/tools"

source message_functions || exit 1
source locate_files || exit 1
source locate_gcp_files || exit 1

set -e

info "Syncing tools from GCP"
gsutil -m rsync -r gs://common-tools ${DIR}
chmod +x ${DIR}/kraken2/2.1.0/kraken2
chmod +x ${DIR}/kraken2/2.1.0/classify
chmod +x ${DIR}/bcftools/1.3.1/bcftools
chmod +x ${DIR}/bcftools/1.9/bcftools
chmod +x ${DIR}/snpEff/4.3s/snpEff.sh
chmod +x ${DIR}/bwa/0.7.17/bwa
chmod +x ${DIR}/sambamba/0.6.5/sambamba
chmod +x ${DIR}/sambamba/0.6.8/sambamba
chmod +x ${DIR}/chord/60.02_1.03/extractSigPredictHRD.R
chmod +x ${DIR}/chord/2.00_1.14/extractSigPredictHRD.R
chmod +x ${DIR}/samtools/1.10/samtools
chmod +x ${DIR}/samtools/1.18/samtools
chmod +x ${DIR}/bcl2fastq/2.20.0.422/bcl2fastq
chmod +x ${DIR}/star/2.7.3a/STAR
chmod +x ${DIR}/rmblast/2.10.0/rmblastn
chmod +x ${DIR}/trf/4.0.9/trf

find /data/tools/cuppa -maxdepth 1 -type d | egrep '[0-9]' | while read v; do
    if [[ ! -d ${v}/cuppa-chart ]]; then
        info "Extracting cuppa-chart for ${v}"
        unzip ${v}/cuppa.jar "cuppa-chart/*" -d ${v}
    fi
done

if [[ $(whoami) == "root" ]]; then
    chgrp -R users ${DIR}
    chmod -R g+w ${DIR}
fi

info "Tools synced from GCP"

