#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source locate_gcp_files || exit 1

set -e

info "Syncing resources from GCP"
gsutil -m rsync -Pr gs://common-resources /data/resources/bucket
cd /data/resources/public && git pull
cd /data/resources/private && git pull
info "Resources synced from GCP"

