#!/usr/bin/env bash

DIR="/data/tools"

source message_functions || exit 1
source locate_files || exit 1
source locate_gcp_files || exit 1

set -e

info "Syncing tools from GCP"
gsutil -m rsync -r gs://common-tools ${DIR}
for b in kraken2/2.1.0/kraken2 kraken2/2.1.0/classify repeatmasker/4.1.1/RepeatMasker bcftools/1.3.1/bcftools \
    bcftools/1.9/bcftools snpEff/4.3s/snpEff.sh bwa/0.7.17/bwa sambamba/0.6.5/sambamba sambamba/0.6.8/sambamba \
    chord/60.02_1.03/extractSigPredictHRD.R chord/2.00_1.14/extractSigPredictHRD.R gridss/2.7.2/gridss.sh \
    gridss/2.8.3/gridss.sh gridss/2.9.3/gridss.sh gridss/2.9.4/gridss.sh gridss/2.11.1/gridss.sh gridss/2.11.1/gridsstools \
    gridss/2.11.1/virusbreakend.sh gridss/2.11.1/gridss_annotate_vcf_kraken2.sh \
    gridss/2.11.1/gridss_annotate_vcf_repeatmasker.sh samtools/1.9/samtools samtools/1.10/samtools \
    bcl2fastq/2.20.0.422/bcl2fastq star/2.7.3a/STAR rmblast/2.10.0/rmblastn trf/4.0.9/trf; do
    chmod +x ${DIR}/${b}
done

if [[ $(whoami) == "root" ]]; then
    chgrp -R users ${DIR}
    chmod -R g+w ${DIR}
fi

info "Tools synced from GCP"

