#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source locate_gcp_files || exit 1

set -e

api_url=http://api.prod-1
local_path=/data/datasets
credentials=$(locate_prod_database_credentials)
dsync_jar=$(locate_dsync)
db_url=$(awk '/^url/ {print $2}' ${credentials})

gcloud secrets versions access "latest" --secret=mysql-diagnostic-patients-sql-prod-1-reader  --project=hmf-secrets | sed s/\"//g  > /tmp/credentials.properties

java11 -jar ${dsync_jar} \
    --api_url ${api_url} \
    --patient_db_url ${db_url} \
    --patient_db_credentials /tmp/credentials.properties \
    --local_path ${local_path} \
    --threads 100

rm /tmp/credentials.properties
