#!/usr/bin/env bash

source message_functions || exit 1

target_directory=""

print_usage() {
    script=$(basename "$0")
    echo ""
    echo "Description: Unmounts a bucket mounted with gcsfuse. (WARNING: Can unmount non-bucket mounts as well.)"
    echo "Usage: ${script} -t <target-directory>"
    echo "Examples:"
    echo "    ${script} -t /mnt/bucket"
    echo ""
    echo "Options:"
    echo "  -t target_directory    Directory to unmount."
    echo ""
    exit 1
}

while getopts ':t:' flag; do
    case "${flag}" in
        t) target_directory=${OPTARG} ;;
        *) warn "Incorrect options provided" && print_usage
        exit 1 ;;
    esac
done

if [[ -z "${target_directory}" || $1 == "" || "$1" == "-h" || "$1" == "--help" ]]; then
    print_usage
fi

info "Unmounting ${target_directory}"
sudo umount "${target_directory}" || die "Could not unmount directory: ${target_directory}"
