#!/usr/bin/env bash

file_to_upload=$1 && shift
bucket='hmf-share'

if [[ -z "${file_to_upload}" ]]; then echo "[EXIT] No file provided to upload" && exit 1; fi
if [[ ! -f "${file_to_upload}" ]]; then echo "[EXIT] Not a file ($file_to_upload)" && exit 1; fi

echo "[INFO] Uploading file to GCP bucket ${bucket}"

gcloud auth activate-service-account --key-file /data/common/dbs/gcp_credentials/hmf-share
gsutil cp -n ${file_to_upload} gs://${bucket}/
