#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1
source io_functions || exit 1

compar_jar="/data/experiments/pilot_tools/compar/compar.jar"

base_dir="/data/experiments/verification_pipeline_v5_35_0"

output_dir="${base_dir}/compar_pilot_COLO829"
create_or_cleanup_dir ${output_dir}

driver_gene_panel=$(locate_driver_gene_panel_37_tsv)

base_dir_534="${base_dir}/COLO829_v5_34_1"
base_dir_535="${base_dir}/COLO829_v5_35_0"

info "Running compar on COLO829 v5.34 versus v5.35"

# TODO (KD): Include CUPPA or change to ALL once CUPPA v2 is supported in compar
categories="PURITY,DRIVER,SOMATIC_VARIANT,GERMLINE_VARIANT,GERMLINE_DELETION,GERMLINE_SV,FUSION,DISRUPTION,CHORD,LILAC"

java -jar ${compar_jar} \
    -sample "COLO829v003T" \
    -categories "${categories}" \
    -match_level "DETAILED" \
    -sample_dir_ref "${base_dir_534}"\
    -sample_dir_new "${base_dir_535}"\
    -output_dir "${output_dir}" \
    -output_id "v534_vs_v535" \
    -driver_gene_panel "${driver_gene_panel}" \
    -log_debug
