#!/bin/bash

file_with_sql_to_execute=$1

credentials=/data/common/dbs/mysql_credentials/prod
db_name="hmfpatients"
db_user=$(awk '/^user/ {print $2}' ${credentials})
db_pass=$(awk '/^pass/ {print $2}' ${credentials})

mysql ${db_name} --user="${db_user}" --password="${db_pass}" < ${file_with_sql_to_execute}
