#!/usr/bin/env bash

source io_functions || exit 1
source actin_config || exit 1

version="local-SNAPSHOT"

source_path="$HOME/hmf/repos/serve/algo/target"
target_path="$HOME/hmf/repos/serve/serve"

create_or_cleanup_dir ${target_path}
cp -r "${source_path}" "${target_path}"

mv "${target_path}/target/algo-${version}-jar-with-dependencies.jar" "${target_path}/target/serve-${version}-jar-with-dependencies.jar"

vm="$(production_actin_serve_vm)"
project="$(production_actin_project)"

do_deploy_pilot_serve_tool ${vm} ${project} "serve"