#!/bin/bash
source load_metadata

prefix=`dirname $(readlink $0 || echo $0)`
run_dir=$1 && shift

credentials=/data/common/dbs/mysql_credentials/pilot
sv_jar=/data/common/tools/linx_pilot/sv-analyser.jar

${prefix}/do_run_linx ${run_dir} ${credentials} ${sv_jar} $@
