#!/usr/bin/env bash

source locate_files || exit 1

run_dir=$1 && shift
output_dir=${run_dir}/linx_pilot/

database="hmfpatients_pilot"
linx_jar=$(locate_pilot_linx)

do_run_linx_pilot ${run_dir} ${database} ${linx_jar} ${output_dir} "$@"
