#!/usr/bin/env bash

source locate_files || exit 1

output_dir=$1 && shift

linx_jar=$(locate_prod_linx)

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_database_user "${credentials}")
db_pass=$(extract_database_password "${credentials}")
ensembl_db="mysql://localhost/homo_sapiens_core_89_37?serverTimezone=UTC&useSSL=false"

java -Xmx8G -Xms4G -cp ${linx_jar} com.hartwig.hmftools.linx.gene.GenerateEnsemblDataCache \
    -output_dir ${output_dir} \
    -ensembl_user ${db_user} -ensembl_pass ${db_pass} \
    -ensembl_db ${ensembl_db} \
    "$@"

