#!/bin/bash
prefix=`dirname $(readlink $0 || echo $0)`

PATH=/data/common/tools/samtools_v1.2:$PATH
export PATH

hotspot_bed=/data/experiments/181108_hotspot_caller/HotspotCaller.bed
hotspot_tsv=/data/common/dbs/somatic_hotspot_v2/Hotspot.tsv
ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
sambamba=/data/common/tools/sambamba_v0.6.5/sambamba
GERMLINE_PON=/data/common/dbs/PON_v2.0/GERMLINE_PON.vcf.gz
SOMATIC_PON=/data/common/dbs/PON_v2.0/SOMATIC_PON.vcf.gz
bcftools=/data/common/tools/bcftools_v1.9/bcftools

sample=$1
normal=${sample:0:12}R
out_dir=/data/experiments/181108_hotspot_caller/${sample}
mkdir -p ${out_dir}

sample_bam=${out_dir}/${sample}.bam
normal_bam=${out_dir}/${normal}.bam

sample_pileup=${out_dir}/${sample}.hotspot.pileup
normal_pileup=${out_dir}/${normal}.hotspot.pileup

if [ ! -f ${sample_pileup} ]; then
    ${prefix}/../bamslicer/bam_slicer ${sample} ${hotspot_bed} ${sample_bam}
    ${sambamba} mpileup -t 8 -L ${hotspot_bed} ${sample_bam} -o ${sample_pileup} --samtools "-q 1 -f ${ref_genome}"
    rm ${sample_bam}
    rm ${out_dir}/${sample}.bai
fi

if [ ! -f ${normal_pileup} ]; then
    ${prefix}/../bamslicer/bam_slicer_normal ${sample} ${hotspot_bed} ${normal_bam}
    ${sambamba} mpileup -t 8 -L ${hotspot_bed} ${normal_bam} -o ${normal_pileup} --samtools "-q 1 -f ${ref_genome}"
    rm ${normal_bam}
    rm ${out_dir}/${normal}.bai
fi

hotspot_vcf=${out_dir}/${sample}.hotspot.vcf.gz
if [ ! -f ${hotspot_vcf} ]; then
    java -Xmx8G -Xms4G \
        -jar /data/common/tools/hotspotcaller_pilot/hotspot-caller.jar \
        -tumor ${sample} -tumor_pileup ${sample_pileup} \
        -reference ${normal} -reference_pileup ${normal_pileup} \
        -hotspot ${hotspot_tsv} \
        -out ${hotspot_vcf}

    tabix -p vcf ${hotspot_vcf}

    germline_vcf=${out_dir}/${sample}.germline.vcf.gz
    ${bcftools} annotate -a ${GERMLINE_PON} -c GERMLINE_PON_COUNT ${hotspot_vcf} -O z -o ${germline_vcf}
    tabix -p vcf ${germline_vcf}

    pon_vcf=${out_dir}/${sample}.pon.vcf.gz
    ${bcftools} annotate -a ${SOMATIC_PON} -c SOMATIC_PON_COUNT ${germline_vcf} -O z -o ${pon_vcf}
    tabix -p vcf ${pon_vcf}

    filtered_vcf=${out_dir}/${sample}.filtered.vcf.gz
    ${bcftools} filter -e 'GERMLINE_PON_COUNT!="." && MIN(GERMLINE_PON_COUNT) > 5' -s GERMLINE_PON -m+ ${pon_vcf} z -O u | \
    ${bcftools} filter -e 'SOMATIC_PON_COUNT!="." && MIN(SOMATIC_PON_COUNT) > 3' -s SOMATIC_PON -m+ -O u | \
    ${bcftools} filter -i 'FORMAT/AD[1:0] >= 2 && FORMAT/AD[0:0] = 0' -s LOW_CONFIDENCE  -m+ -O z -o ${filtered_vcf}

    snpEff_vcf=${out_dir}/${sample}.snpEff.vcf
    java -jar /data/common/tools/snpEff_v4.3s/snpEff.jar \
        -c "/data/common/tools/snpEff_v4.3s/snpEff.config" "GRCh37.75" \
        -v ${filtered_vcf} \
        -hgvs -lof -no-downstream -ud 1000 -no-intergenic -noShiftHgvs \
        > ${snpEff_vcf}

    rm ${hotspot_vcf}*
    rm ${germline_vcf}*
    rm ${pon_vcf}*
    rm ${filtered_vcf}*
    mv ${snpEff_vcf} ${out_dir}/${sample}.hotspot.vcf
    bgzip ${out_dir}/${sample}.hotspot.vcf
    tabix -p vcf ${hotspot_vcf}
fi

