#!/bin/bash

api_url() {
  environment=$1 && shift
  echo "api_url"
  echo "$environment"

  if [[ "${environment}" == "prod" ]]; then
      echo "http://api.prod-1/hmf/v1"
  elif [[ "${environment}" == "pilot" ]]; then
      echo "http://api.pilot-1/hmf/v1"
  else
      error "Environment should be either prod or pilot"
      exit 1
  fi
}

api_curl_get () {
    url=$1 && shift
    curl --fail --silent --show-error \
          -H "Content-Type: application/json" \
          -X GET "${url}"
}

api_curl_post () {
    request=$1 && shift
    data=$1 && shift
    environment=$1 && shift

    echo "api_curl_post"
    echo $request
    echo ${data}
    echo ${environment}

    api_url=$(api_url "${environment}")
    url="${api_url}/${request}"
#    curl --silent --show-error \
#          -H "Content-Type: application/json" \
#          -H "Accept: application/json" \
#          -X POST "${url}" \
#          --data "${data}"
}

extract_wrapper_api_endpoint() {
    query=$1 && shift
    environment=$1 && shift

    api_url=$(api_url "${environment}")
    request="${api_url}/${query}"
    echo api_curl_get "${request}"
}

extract_wrapper_api() {
    url=$1 && shift
    environment=$1 && shift

    sample_object=$(extract_wrapper_api_endpoint "${url}" "${environment}")
    size_object=$(echo ${sample_object} | jq '. | length')
    if [[ ${size_object} -eq 0 ]]; then
      error "No reporting created entry is present. Add entry first in created endpoint"
      exit 1
    elif [[ ${size_object} -eq 1 ]]; then
      echo ${sample_object} | jq .[]
    else
      ## if more entries and all are equals we assume last one is the one which is shared
      echo ${sample_object} | jq .[-1]
    fi
}

extract_reporting_id() {
    sample_barcode=$1 && shift
    report_type=$1 && shift
    environment=$1 && shift

    sample_object=$(extract_wrapper_api "reports/created?barcode=${sample_barcode}&report_type=${report_type}" "${environment}")
    echo ${sample_object} | jq .id
}

extract_reporting_id_on_barcode() {
    sample_barcode=$1 && shift
    environment=$1 && shift

    sample_object=$(echo extract_wrapper_api "reports/created?barcode=${sample_barcode}" "${environment}")
    echo ${sample_object} | jq .id
}

extract_object_created_on_reporting_id() {
    id=$1 && shift
    environment=$1 && shift

    echo extract_wrapper_api "reports/created?id=${id}" "${environment}"
}

extract_object_created() {
    sample_barcode=$1 && shift
    report_type=$1 && shift
    environment=$1 && shift

    sample_object=$(extract_wrapper_api "reports/created?barcode=${sample_barcode}&report_type=${report_type}" "${environment}")
    echo ${sample_object}
}

extract_object_shared() {
    reporting_id=$1 && shift
    environment=$1 && shift

    sample_object=$(extract_wrapper_api "shared?report_created_id=${reporting_id}" "${environment}")
    echo ${sample_object}
}