#!/bin/bash

source message_functions

sample_barcode=$1
new_status="Ready"

if [[ $# -ne 1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo "Descr: Patches sample status to ${new_status}"
    echo "Usage: $(basename $0) \$sample_barcode"
    echo "   Eg: $(basename $0) FR123456"
    echo "-----"
    exit 1
fi

info "Querying api to find sample by barcode (${sample_barcode})"
sample_json=$(hmf_api_get "samples?barcode=${sample_barcode}")

## Make sure only one object is selected
[[ $(echo "${sample_json}" | jq length) -eq 1 ]] || die "Amount of samples found for ${sample_barcode} is not 1"

## Patch
sample_oid=$(echo "${sample_json}" | jq -r .[0].id)
hmf_api_patch samples "${sample_oid}" "status=${new_status}"
