#!/bin/bash

source message_functions || exit 1
source locate_reporting_api || exit 1

sample_barcode=$1 && shift

## extract correct report created id
report_created_id=$(extract_reporting_id ${sample_barcode})

current_date=$(date '+%d-%b-%YT%H:%M:%S')
data=$(printf '{"%s": "%s", "%s": %s}' "share_date" "${current_date}" "report_created_id" "${report_created_id}")

info "Adding entry to shared API"
curl --silent --show-error \
      -H "Content-Type: application/json" \
      -H "Accept: application/json" \
      -X POST http://api.pilot-1/hmf/v1/reports/shared --data "${data}"
