#!/usr/bin/env bash

source message_functions || exit 1

run_id=$1

key='status'
val="Invalidated"

if [[ $# -ne 1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo "Descr: Patches run ${key} to ${val}"
    echo "Usage: $(basename $0) \$run_id"
    echo "   Eg: $(basename $0) 1234"
    echo "-----"
    exit 1
fi

info "Querying api to find run by id (${run_id})"
runs_json=$(hmf_api_get "runs/${run_id}")
count=$(echo "${runs_json}" | jq length)
[[ "${count}" -eq 1 ]] || die "Amount of runs found for ${run_id} is not 1 (${count})"

run=$(echo "${runs_json}" | jq -r .[0])
oid=$(echo "${run}" | jq -r .id)
sts=$(echo "${run}" | jq -r .status)

info "About to patch run object ${oid} with ${key}=${val}"
[[ "${sts}" != "${val}" ]] || die "Field ${key} is already set to ${val} for ${run_id}"

hmf_api_patch -c "runs" -o "${oid}" -f "${key}" -v "${val}"

