#!/bin/bash

source message_functions

run_name=$1
new_status="Validated"

if [[ $# -ne 1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "-----"
    echo "Descr: Patches run status to ${new_status}"
    echo "Usage: $(basename $0) \$run_name"
    echo "   Eg: $(basename $0) 200101_HMFregXXXX_FR123_FR456_SAMPLE"
    echo "-----"
    exit 1
fi

info "Querying api to find run by name (${run_name})"
set_json=$(hmf_api_get "sets?name=${run_name}")

## Make sure only one set is selected
[[ $(echo "${set_json}" | jq length) -eq 1 ]] || die "Amount of sets found for ${run_name} is not 1"

set_oid=$(echo "${set_json}" | jq -r .[0].id)
run_json=$(hmf_api_get "runs?set_id=${set_oid}")

## Make sure only one run is selected
[[ $(echo "${run_json}" | jq length) -eq 1 ]] || die "Amount of runs found for ${run_name} is not 1"

## Patch
run_oid=$(echo "${run_json}" | jq -r .[0].id)
hmf_api_patch -c "runs" -o "${run_oid}" -f "status" -v "${new_status}"
