#!/bin/bash

source message_functions || exit 1
source locate_reporting_api || exit 1

set -e

sample_barcode=$1 && shift
report_type=$1 && shift

## extract correct report created id
report_created_id=$(extract_reporting_id ${sample_barcode} ${report_type})

data=$(printf '{"%s": %s}' "report_created_id" "${report_created_id}")

info "Adding entry to shared API"
api_curl_post "reports/shared" ${data} "pilot"