#!/usr/bin/env bash

JSON_DIR="/data/ops/api/prod/database"
CRED_DIR="/data/common/dbs/api_credentials"
CRT_FILE="${CRED_DIR}/api.crt"
KEY_FILE="${CRED_DIR}/api.key"
BASE_URL="https://api.hartwigmedicalfoundation.nl/hmf/v1"
LOG_FILE="${JSON_DIR}/update_api_db.log"
DATETIME=$(date)

DB_TYPES=( fastq entities runs samples sets flowcells inis shares stacks )

if [[ ! -f "${CRT_FILE}" ]]; then echo "[ERROR] CRT file not found (${CRT_FILE})" && exit 1; fi
if [[ ! -f "${KEY_FILE}" ]]; then echo "[ERROR] KEY file not found (${KEY_FILE})" && exit 1; fi

for TYPE in "${DB_TYPES[@]}"; do
    API_URL="${BASE_URL}/${TYPE}"
    if [[ "${TYPE}" == "fastq" ]]; then
        ## adding bucket filter reduces output significantly
        API_URL+="?bucket=hmf-fastq-storage"
    fi
    OUTPUT_FILE="${JSON_DIR}/${TYPE}.json"
    OUTPUT_FILE_TMP="${JSON_DIR}/tmp_${TYPE}.json.tmp"

    curl \
        --cert-type pem \
        --cert "${CRT_FILE}" \
        --key "${KEY_FILE}" \
        -X GET \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        "${API_URL}" \
        > ${OUTPUT_FILE_TMP}

    if [[ 0 -eq $? ]]; then
        cp ${OUTPUT_FILE_TMP} ${OUTPUT_FILE}
        echo "[INFO] Written to ${OUTPUT_FILE}"
    else
        echo "${DATETIME} WARN retrieval of $TYPE failed so stopping" && exit 1
    fi
done

rm ${JSON_DIR}/tmp_*.tmp

echo "${DATETIME} Script $(basename $0) has finished" | tee -a ${LOG_FILE}
