#!/usr/bin/env bash

sample_sheets=("$@")

## only proceed if input
if [[ -z "${sample_sheets}" ]]; then
    echo "[WARN] No samplesheet paths given?" && exit 1
fi

## Flowcell done at GCP so get info per sample
for sample_sheet in "${sample_sheets[@]}"; do
    api_check_samples_of_one_flowcell "${sample_sheet}"
done
