#!/usr/bin/env bash

source message_functions || exit 1

dates=("$@") # YYMMDD
dates_count=${#dates[@]}
logs_dir="/data/ops/recurrent/flowcell_sample_checks/"

## only proceed if input
if [[ "${dates_count}" -lt 1 ]]; then
    echo "Usage: $(basename $0) <date1> [<date2> <dateN>]"
    echo "   Eg: $(basename $0) 210101 210102 210104"
    exit 1
fi

for date in "${dates[@]}"; do
    info "----- ${date} -----"
    find /data/samplesheets/ -name "${date}_*_SampleSheet.csv" | while read -r sheet; do
        api_check_samples_of_one_flowcell "${sheet}"
    done
done

## Print all samples that are not ok
YYMMDD=$(date "+%y%m%d")
info "Grepping all log files from today (${YYMMDD}) for samples that are not OK:"
cat "${logs_dir}/${YYMMDD}_flowcell_sample_check_"* | grep -v ^# | grep -v ^OK | tr "\t" " " | sort | uniq
