#!/usr/bin/env bash
#
submission=$1

echo ""
echo "--- GENERAL INFO ---"
echo "[INFO] Checking $submission"

  totalLimsSamples=$( query_lims -type samples -filter "submission=${submission}" | grep -v "^#" | wc -l )
   totalLimsFailed=$( query_lims -type samples -filter "submission=${submission}" | grep -v "^#" | grep Failed | wc -l )
      totalSamples=$( query_sbp_api -type samples -filter "submission=${submission}" | grep -v "^#" | wc -l )
 totalSamplesReady=$( query_sbp_api -type samples -filter "submission=${submission}" -filter "status=Ready" | grep -v "^#" | wc -l )
         totalRuns=$( query_sbp_api -type runs -filter "name=${submission}" | grep -v "^#" | wc -l )
totalRunsValidated=$( query_sbp_api -type runs -filter "name=${submission}" -filter "status=Validated" | grep -v "^#" | wc -l )
     totalRunsDone=$( query_sbp_api -type runs -filter "name=${submission}" -filter "status=Validated|Failed|SnpCheck" | grep -v "^#" | wc -l )

echo "[INFO] $totalLimsSamples samples in LIMS (${totalLimsFailed} failed)"
echo "[INFO] $totalSamplesReady samples Ready of total $totalSamples at SBP"
echo "[INFO] $totalRuns runs present at SBP of which $totalRunsDone finished ($totalRunsValidated Validated)"
echo ""

echo "--- FOR ALL SUBMISSIONS ---"
echo "[INFO] Inspect further:"
echo "  query_lims -type samples -filter submission=${submission}"
echo "  query_sbp_api -type samples -filter submission=${submission}"
echo "  query_sbp_api -type runs -filter name=${submission}"
echo "[INFO] Or gather submission if all is ready and ok:"
echo "  gather_submission ${submission}"
echo ""

## We should provide nextseq data also via portal from now on
## but will keep next block for some time in case we still need
if [ "" ]; then
  ## when we share fastq from datastore
  submDir="/data/submissions/${submission}"
  submTar="${submDir}/${submission}.tar"
  echo "--- ONLY IN CASE OF MANUAL NEXTSEQ PROCESSING ---"
  echo "[INFO] In case of nextseq run you can get yield/q30 info with:"
  echo "  seqRun=\"ENTER RUN NAME\" # eg seqRun=180101_NB500901_0000_AHXXXXXXX"
  echo "  pathToSeqRun=/data/data_archive/next_seq/\${seqRun}"
  echo "  check_bcl2fastq_conversion -run \${pathToSeqRun} | grep SAMPLE | awk '{ print \$11\"\t\"\$9\"\t\"\$4\"\t\t\"\$3\"\t\"\$10 }' | sort -k2"
  echo "[INFO] And create tar with:"
  echo "  cd \${pathToSeqRun}/Data/Intensities/BaseCalls"
  echo "  tar -cvf ${submTar} $submission"
  echo "[INFO] And create tar listing later with:"
  echo "  cd ${submDir}; tar -tf ${submTar} > ${submTar}.list; ls -l"
  echo ""
fi
