#!/usr/bin/env bash

subm_json=$(query_lims.pl -type submissions -json \
    -filter "has_lab_finished=TRUE" \
    -filter "project_type!=Cohort" \
    -filter "project_type!=CORE")

echo "${subm_json}"| jq -r '.[].submission' | while read subm; do 
    subm_dir="/data/submissions/${subm}"
    if [[ ! -d "${subm_dir}" ]]; then
        query_lims.pl -type submissions -filter "submission=${subm}" | grep -v ^#
    fi
done
