#!/bin/bash

SUBMISSIONS_DIR="/data/submissions"
HMF_QUERY_SCRIPT="query_lims"
SBP_QUERY_SCRIPT="query_sbp_api"
HMF_LIMS_JSON='/data/lims/lims.json'
submission=$1

## sanity checks
if [[ $# -eq 0 ]] ; then echo "run with eg: $0 HMFreg0000"; exit 1; fi
if [[ -z ${submission+x} ]]; then echo "Missing submission id as input"; exit 1; fi
if [[ ! ${submission} =~ ^HMFreg ]]; then echo "Submission should start with \"HMFreg\""; exit 1; fi

## setting up variables
outPath=${SUBMISSIONS_DIR}'/'${submission}
lmsFile=${outPath}'/lims.txt'
samFile=${outPath}'/samples.txt'
runFile=${outPath}'/runs.txt'
logFile=${outPath}'/log.txt'
bcsFile=${outPath}'/barcodes.txt'
dateString=$( date )
project=$( cat ${HMF_LIMS_JSON} | jq -r ".submissions.${submission}.project_name" )
if [[ -z ${project+x} ]]; then echo "[EXIT] Unable to find project for submission"; exit 1; fi

## create dirs
if [[ -e ${outPath} ]] ; then echo "[EXIT] Dir exists already (${outPath})"; exit 1; fi
mkdir -p ${outPath} || exit 1

## get all samples involved from LAB LIMS
echo "[INFO] Querying HMF LIMS to get sample list"
${HMF_QUERY_SCRIPT} -submission ${submission} > ${lmsFile}

## get q30/yield data from SBP API
echo "[INFO] Querying SBP API to get sample status"
${SBP_QUERY_SCRIPT} -type samples -filter "submission=${submission}" > ${samFile}
${SBP_QUERY_SCRIPT} -type samples -filter "submission=${submission}" -json > $( echo ${samFile} | sed 's/txt$/json/' )

## get entity/run-status from SBP API
echo "[INFO] Querying SBP API to get run status"
${SBP_QUERY_SCRIPT} -type runs -filter "name=${submission}" > ${runFile}
${SBP_QUERY_SCRIPT} -type runs -filter "name=${submission}" -json > $( echo ${runFile} | sed 's/txt$/json/' )

## get counts to check completeness
hmfCount=$( cat ${lmsFile} | grep -v "^#" | wc -l )
sbpCount=$( cat ${samFile} | grep -v "^#" | awk '$6 ==  "Ready"' | wc -l )

## setup barcodes file (needed later for fastq file cleanup)
cat ${samFile} | grep -v "^#" | cut -f2 > ${bcsFile}

## logging
echo "#        Date = ${dateString}" >> ${logFile}
echo "#  Submission = ${submission}" >> ${logFile}
echo "#     Project = ${project}"    >> ${logFile}
echo "# SampleCount = ${hmfCount}"   >> ${logFile}
echo "#   DataCount = ${sbpCount}"   >> ${logFile}

## stdout msg
echo "[INFO] Log:"
cat ${logFile}
echo "[INFO] Inspect output files:"
echo " cd ${outPath}"
echo " cat ${lmsFile}"
echo " cat ${samFile}"
echo " cat ${runFile}"

## warn if not complete
if [[ ${hmfCount} -ne ${sbpCount} ]]; then 
  echo "[WARNING] There might be missing samples!" 
  exit 1
fi

exit 0
