#!/usr/bin/env bash

query_script=$1 && shift
obj_type=$1 && shift
obj_key=$1 && shift
obj_val=$1 && shift

filter="${obj_key}=${obj_val}"
objects=$("${query_script}" -type "${obj_type}" -json -filter "$filter" -exact)
count=$(echo ${objects} | jq 'length')

echo "# Found ${count} object(s) with: ${query_script} -type ${obj_type} -json -filter $filter -exact"
echo "${objects}" | jq -Sr 'sort'
