#!/usr/bin/env bash

LIMS_JSON_FILE="/data/lims/lims.json"
SUBMISSIONS_JSON="$(cat "$LIMS_JSON_FILE" | jq -c '.submissions')"
CORE_BUCKET="hmf-output-core"

submissions_to_visit=("$@") # optional

if [[ "$#" -eq 0 ]]; then
    submissions_to_visit=( $(echo "$SUBMISSIONS_JSON" | jq -r 'keys[]' | sort -r | head -100) )
fi

for submission in "${submissions_to_visit[@]}"; do
    obj_json=$(echo "${SUBMISSIONS_JSON}" | jq ".${submission}")
    project_name=$(echo "${obj_json}" | jq -r ".project_name")
    project_type=$(echo "${obj_json}" | jq -r ".project_type")
    sample_count=$(echo "${obj_json}" | jq -r ".sample_count")
    analysis_type=$(echo "${obj_json}" | jq -r ".analysis_type")
    entity=""
    bucket=""

    ## reset some fields according to project type
    if [[ "$project_type" == "Human research" ]]; then
        project_type="HUM-RES"
    elif [[ "$project_type" == "non human research" || "$project_type" == "Non human research" ]]; then
        project_type="NONHUM-RES"
    elif [[ "$project_type" == "KG production" ]]; then
        project_type="KG"
    elif [[ "$project_type" == "CORE" ]]; then
        analysis_type="SomaticAnalysis"
    else
        project_type="CheckProjectType(${project_type})"
    fi
    
    ## retrieve missing info
    samples_json=$(query_lims.pl -type samples -filter "submission=${submission}" -json)
    if [[ "$project_type" == "Cohort" ]]; then
        entity="NA"
        bucket="NA"
        analysis_type="NA"
    elif [[ $(echo "$samples_json" | jq 'length') -gt 0 ]]; then
        entity=$(echo "$samples_json" | jq -r '.[-1].entity')
        bucket=$(query_api.pl -type entities -json | jq -r ".[] | select( .name == \"${entity}\" ) | .bucket")
    fi

    ## perform some sanity checks
    #echo "[DEBUG] $submission $entity $bucket"
    if [[ -z "$entity" || "$entity" == "null" ]]; then echo "[WARNING] No entity found for $submission!"; fi
    if [[ -z "$bucket" || "$bucket" == "null" ]]; then echo "[WARNING] No bucket found for $submission!"; fi
    if [[ "$project_type" == "CORE" && "$bucket" != "$CORE_BUCKET" ]]; then
        echo -e "\n[WARNING] Found CORE submission with wrong bucket (submission=$submission entity=$entity bucket=$bucket)!!\n"
    fi

    ## output
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
        "$submission" \
        "$project_name" \
        "$project_type" \
        "$analysis_type" \
        "$sample_count"
done
