#!/usr/bin/env bash

SUBMISSIONS=("$@") # optional
JSON=/data/lims/submissions.json

if [ "$#" -eq 0 ]; then
    SUBMISSIONS=( $(cat $JSON | jq -r 'keys[]' | sort -r | head -100) )
fi

for submission in "${SUBMISSIONS[@]}"; do
    MAINKEY=".${submission}"

    ## retrieve info
    project_name=$(cat ${JSON} | jq -r "${MAINKEY}.project_name" )
    project_type=$(cat ${JSON} | jq -r "${MAINKEY}.project_type" )
    sample_count=$(cat ${JSON} | jq -r "${MAINKEY}.sample_count" )
    submission=$(cat ${JSON} | jq -r "${MAINKEY}.submission" )
    product=$(cat ${JSON} | jq -r "${MAINKEY}.analysis_type" )
    center=$(echo $projectName | cut -d"-" -f1 )

    ## reset some fields according to project type
    if [[ $project_type == "Human research" ]]; then
        project_type="HUM-RES"
    elif [[ $project_type == "non human research" || $project_type == "Non human research" ]]; then
        project_type="NONHUM-RES"
    elif [[ $project_type == "KG production" ]]; then
        project_type="KG"
    elif [[ $project_type == "CORE" ]]; then
        product="SomaticAnalysis"
    else
        projectType="UnknownProjectType"
    fi

    ## check entitity existance and bucket
    entity=$(query_lims -type samples -filter submission=${submission} -json | jq -r '.[-1].entity')
    bucket=$(query_sbp_api -type entities -json | jq -r ".[] | select( .name == \"${entity}\" ) | .bucket")
    if [[ $project_type == "KG" ]]; then
        bucket=$bucket_by_submission
    elif [[ $project_type == "CORE" ]]; then
        if [[ "${bucket}" != "hmf-output-core" ]]; then
            echo "[WARNING] Potentialy wrong bucket for $submission ($bucket)!!"
        fi
    fi

    ## output
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
        "$submission" \
        "$project_name" \
        "$project_type" \
        "$product" \
        "$sample_count"
done
