#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

unregistered_jsons_dir=$(locate_sample_registration_unregistered_jsons_dir) || die "Could not find the unregistered-jsons dir"

if [ -f "${unregistered_jsons_dir}"/null.json ]
then
    rm "${unregistered_jsons_dir}"/null.json
fi

for json in "${unregistered_jsons_dir}"/*.json; do
    echo ""
    info "About to register: ${json}"
    request_body=$(cat $json)
    curl -X 'POST' 'http://lama.prod-1/api/registration/hartwig-api' -H 'accept: */*' -H 'Content-Type: application/json' -d "${request_body}"
done