#!/usr/bin/env bash

source sbp_api_functions

set=$1

if [ -z "${set}" ]; then
    echo "[ERROR] Provide a set. Exiting"
    exit 1
fi

run_info=$(load_run_info_for_set ${set})
run_bucket=$(extract_bucket_from_run_info "${run_info}")

echo "[INFO] Testing SBP API functions on ${set}"
echo "[INFO] Run Info = ${run_info}"
echo "[INFO] Run Bucket = ${run_bucket}"
echo "[INFO] Rerun V3 Info = $(load_rerun_v3_info_for_set ${set})"
echo "[INFO] Rerun V4 Info = $(load_rerun_v4_info_for_set ${set})"
echo "[INFO] Tumor Sample ID = $(load_tumor_sample_id_for_set ${set})"
echo "[INFO] Ref Sample ID = $(load_ref_sample_id_for_set ${set})"
echo "[INFO] Tumor BAM Location in ${run_bucket} = $(locate_tumor_bam_for_set_in_bucket ${run_bucket} ${set})"
echo "[INFO] Ref BAM Location in ${run_bucket} = $(locate_ref_bam_for_set_in_bucket ${run_bucket} ${set})"
