#!/usr/bin/env bash

source message_functions || exit 1
command -v query_lims.pl > /dev/null || die "Unable to locate cmd (query_lims.pl)"

sample_name=$1

info "Searching LIMS for samples with name ${sample_name}"
samples=$(query_lims.pl -type samples -filter "sample_name=${sample_name}" -exact -json)
sample_count=$(jq 'length' <<< "${samples}")
if [[ "$sample_count" == 0 ]]; then
    die "No samples found"
elif [[ "$sample_count" -gt 1 ]]; then
    warn "More than 1 sample found. Using last one."
fi
sample=$(jq '.[-1]' <<< "${samples}")
submission_id=$(jq -r '.submission' <<< "${sample}")

info "Searching LIMS for submission with id ${submission_id}"
submission=$(query_lims.pl -type submissions -filter "submission=${submission_id}" -exact -json | jq '.[-1]')
group_id=$(jq -r '.group_id' <<< "${submission}")

info "Searching LIMS for groups with id ${group_id}"
groups=$(query_lims.pl -type contact_groups -filter "group_id=${group_id}" -exact -json)

if [[ $(jq 'length' <<< "${groups}") -lt 1 ]]; then
    die "No groups found for submission '${submission_id}'"
fi
group=$(jq '.[-1]' <<< "${groups}")

info "Sample $sample_name with submission $submission_id is linked to contact group $group_id"rt
jq -r 'to_entries[] | .key + ": " + .value' <<< "${group}" | grep -v ^group_id | sort