#!/usr/bin/env bash

## setup main variables
DATESTR="$(date '+%y%m%d')"
NAS_DIR="/volume1/machines/LIMS"
OUT_DIR="/data/lims"
LAB_DIR="${OUT_DIR}/labfiles"
DAY_DIR="${LAB_DIR}/${DATESTR}"
SYM_DIR="${OUT_DIR}/latest"
ACC2CSV="/data/common/tools/access2csv_v190415/target/appassembler/bin/access2csv"

CPCT_FILE='LIMS_v4.1_be.accdb'
SAMP_FILE='HMF-FOR-001 Received Samples 2019 v5.5.xlsx'
PROC_FILE='HMF-FOR-002 Sample in process 2019 v4.1.xlsx'

CPCT_NAS_PATH="${NAS_DIR}/${CPCT_FILE}"
SAMP_NAS_PATH="${NAS_DIR}/${SAMP_FILE}"
PROC_NAS_PATH="${NAS_DIR}/${PROC_FILE}"

## File and dir sanity checks
if ssh nas "[[ ! -d ${NAS_DIR} ]]"; then echo "[EXIT] Error: dir does not exist (nas:${NAS_DIR})" && exit 1; fi
for nasFilePath in "$CPCT_NAS_PATH" "$SAMP_NAS_PATH" "$PROC_NAS_PATH"; do
    if ssh nas "[[ ! -f '${nasFilePath}' ]]"; then echo "[EXIT] Error: file does not exist (nas:${nasFilePath})" && exit 1; fi
done
for outdir in $OUT_DIR $LAB_DIR $SYM_DIR; do
    if [[ ! -d ${outdir} ]]; then echo "[EXIT] Error: dir does not exist (${outdir})" && exit 1; fi
    if [[ ! -w ${outdir} ]]; then echo "[EXIT] Error: no write permission (${outdir})" && exit 1; fi
done
mkdir -p ${DAY_DIR}

## Setup file variables
cpctSource="${DAY_DIR}/${CPCT_FILE}"
cpctTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrack.accdb"
cpctTxt="${cpctTarget}.csv"
cpctLatest="${SYM_DIR}/lims_cpct"

sampSource="${DAY_DIR}/${SAMP_FILE}"
sampTarget="${DAY_DIR}/${DATESTR}_LimsReceived.xlsx"
sampTxt="${sampTarget}_samp.tsv"
sampLatest="${SYM_DIR}/lims_samp"
submTxt="${sampTarget}_subm.tsv"
submLatest="${SYM_DIR}/lims_subm"
contTxt="${sampTarget}_cont.tsv"
contLatest="${SYM_DIR}/lims_cont"

procSource="${DAY_DIR}/${PROC_FILE}"
procTarget="${DAY_DIR}/${DATESTR}_LimsInProcess.xlsx"
procTxt="${procTarget}.tsv"
procLatest="${SYM_DIR}/lims_proc"

## Retrieve files from NAS
echo "[INFO] Syncing LIMS files from NAS to DATASTORE"
echo "[INFO]   SourceDir: nas:${NAS_DIR}"
echo "[INFO]   TargetDir: ${DAY_DIR}"
rsync -s "nas:${CPCT_NAS_PATH}" ${DAY_DIR}
rsync -s "nas:${SAMP_NAS_PATH}" ${DAY_DIR}
rsync -s "nas:${PROC_NAS_PATH}" ${DAY_DIR}

## Make sure all required files are present
if [ ! $? -eq 0 ]; then echo "[EXIT] Error with RSYNC from NAS, please check " && exit 1; fi
for inputFile in "${cpctSource}" "${sampSource}" "${procSource}"; do
    if [[ ! -f "${inputFile}" ]]; then
        echo "[EXIT] Error: input file from NAS not present (${inputFile})" && exit 1;
    fi
done

## Symlink LIMS files to create stable naming for downstream work
ln -sfn "${cpctSource}" "${cpctTarget}"
ln -sfn "${sampSource}" "${sampTarget}"
ln -sfn "${procSource}" "${procTarget}"

## Convert to text format
echo "[INFO] Converting input files to CSV/TSV"
echo "[INFO]   Converting $( basename ${cpctTarget} )"
${ACC2CSV} --with-header --input "${cpctTarget}" --output ${DAY_DIR} --table tblSamples --quote-all false
if [ ! $? -eq 0 ]; then echo "[EXIT] CPCT export to csv FAILED" && exit 1; fi
mv ${DAY_DIR}/tblSamples.csv ${cpctTxt}
echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "submissions")"
xlsx2csv -d "\t" "${sampTarget}" -s 1 | tail -n +5 > ${submTxt}
if [ ! $? -eq 0 ]; then echo "[EXIT] SUBM export to csv FAILED" && exit 1; fi
echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "samples")"
xlsx2csv -d "\t" "${sampTarget}" -s 2 | tail -n +2 > ${sampTxt}
if [ ! $? -eq 0 ]; then echo "[EXIT] SAMP export to csv FAILED" && exit 1; fi
echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "Group_ID")"
xlsx2csv -d "\t" "${sampTarget}" -s 3 | tail -n +2 > ${contTxt}
if [ ! $? -eq 0 ]; then echo "[EXIT] CONT export to csv FAILED" && exit 1; fi
echo "[INFO]   Converting $( basename ${procTarget} )"
xlsx2csv -d "\t" "${procTarget}" -s 1 | tail -n +5 > ${procTxt}
if [ ! $? -eq 0 ]; then echo "[EXIT] PROC export to csv FAILED" && exit 1; fi

## Create latest symlinks
echo "[INFO] Symlinking to latest files"
echo "[INFO]   $cpctLatest"
ln -sfn $cpctTxt $cpctLatest
echo "[INFO]   $submLatest"
ln -sfn $submTxt $submLatest
echo "[INFO]   $sampLatest"
ln -sfn $sampTxt $sampLatest
echo "[INFO]   $contLatest"
ln -sfn $contTxt $contLatest
echo "[INFO]   $procLatest"
ln -sfn $procTxt $procLatest

## Gather some metrics
echo "[INFO] Stats:"
for latestFile in $cpctLatest $submLatest $sampLatest $contLatest $procLatest; do
    totalLines=$(cat $latestFile | wc -l)
    echo "[INFO]   LineCount of ${latestFile} = ${totalLines}"
done
