#!/bin/bash

DATESTR=$( date "+%y%m%d" )
OUT_DIR="/data/lims/labfiles"
NAS_DIR="/volume1/machines/BFX/LIMS"

## setup links
limsCpctFrom=$NAS_DIR/HMF-FOR-006*xlsx
limsCpctTo=$OUT_DIR/backup/$DATESTR"_LimsCPCTtracking.xlsx"
limsRestFrom=$NAS_DIR/HMF-FOR-001*xlsx
limsRestTo=$OUT_DIR/backup/$DATESTR"_LimsReceivedSamp.xlsx"
limsProcFrom=$NAS_DIR/HMF-FOR-002*xlsx
limsProcTo=$OUT_DIR/backup/$DATESTR"_LimsInProcess.xlsx"

## retrieve file
echo "[INFO] About to sync files from nas to datastore"
scp nas:$limsCpctFrom $limsCpctTo
scp nas:$limsRestFrom $limsRestTo
scp nas:$limsProcFrom $limsProcTo

## symlink the lims excel files
ln -sfn $limsCpctTo $OUT_DIR/latest_lims_cpct
ln -sfn $limsRestTo $OUT_DIR/latest_lims_rest
ln -sfn $limsProcTo $OUT_DIR/latest_lims_proc

## done
echo "[INFO] Output files are in $OUT_DIR"
echo "[INFO] You can now run \"convert_lims_data\" to update the lims json"
