#!/usr/bin/env bash

lims_dir="/data/ops/lims/pilot"
code_dir="/data/common/repos/scripts/lims"

out_json="${lims_dir}/lims.json"
log_file="${lims_dir}/update.log"

echo "===== Running $(basename $0) at $(date) =====" 2>&1 | tee -a ${log_file}
${code_dir}/convert_lims_data_pilot.pl \
    -out_json "${out_json}" \
    -execute 2>&1 | tee -a ${log_file}

## TODO: remove following lines once everything uses the new /data/ops location
old_file_path="/data/lims/lims_pilot.json"
echo "[INFO] Copying output file to old location for backwards compatibility (${old_file_path})"
cp "$out_json" "${old_file_path}"
