#!/usr/bin/env bash

source message_functions || exit 1

lims_dir="/data/ops/lims/prod"
code_dir="/data/repos/scripts/lims"

back_dir="${lims_dir}/backup"
out_json="${lims_dir}/lims.json"
log_file="${lims_dir}/update.log"
tmp_file="${lims_dir}/update_in_progress.tmp"

mod_date=$(date -r "${out_json}" "+%Y-%m-%d %H:%M:%S")
run_date=$(date "+%Y-%m-%d %H:%M:%S")

echo "===== Running $(basename $0) =====" 2>&1 | tee -a ${log_file}
[[ ! -f "${tmp_file}" ]] || die "Update already in progress (${tmp_file}). Exiting."
info "Creating tmp file to avoid concurrent updates (${tmp_file})"
touch "${tmp_file}" || die "Unable to create tmp file (${tmp_file})"

info "LastMod date: ${mod_date}" 2>&1 | tee -a ${log_file}
info "Current date: ${run_date}" 2>&1 | tee -a ${log_file}

if [[ -f "${out_json}" ]]; then
    info "Backing up ${out_json}"
    cp "${out_json}" "${back_dir}"
fi

info "Retrieving LIMS files from NAS"
${code_dir}/sync_lab_lims_from_nas "${lims_dir}" 2>&1 | tee -a ${log_file}
info "Converting LIMS files to ${out_json}"
${code_dir}/convert_lims_data.pl \
    -lims_dir "${lims_dir}" \
    -out_json "${out_json}" \
    2>&1 | tee -a ${log_file}

info "Removing tmp file (${tmp_file})"
rm "${tmp_file}" || die "Unable to remove tmp file (${tmp_file})"