#!/usr/bin/env bash

lims_dir="/data/ops/lims/pilot"
code_dir="/data/common/repos/scripts/lims"

out_json="${lims_dir}/lims.json"
log_file="${lims_dir}/update.log"

echo "===== Running $(basename $0) at $(date) =====" 2>&1 | tee -a ${log_file}
${code_dir}/convert_lims_data_pilot.pl \
    -lims_dir "${lims_dir}" \
    -out_json "${out_json}" \
    2>&1 | tee -a ${log_file}
