#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

ckb_db=$1 && shift

# Resources
ckb_database_sql=/data/common/dbs/ckb/sql_database/generate_ckb_db.sql

# Database details
credentials=$(prod_writer_sql_credentials)

db_user=$(extract_credentials_value "${credentials}" user)
db_pass=$(extract_credentials_value "${credentials}" password)
db_host=$(extract_credentials_value "${credentials}" host)

info "Rebuilding CKB db '${ckb_db}' on '${db_host} using ${ckb_database_sql}"

mysql ${ckb_db} --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${ckb_database_sql}
