#!/usr/bin/env bash

source message_functions || exit 1

zip_file=$1 && shift

# first add file to gs://hmf-crunch-resources/serve/ckb/ bucket
if [[ -z "${zip_file}" ]]; then
    error "No zip file provided. Exiting"
fi

# copying data from bucket
info "Copy zip file from gs://hmf-crunch-resources/serve/ckb/${zip_file}"
gsutil cp gs://hmf-crunch-resources/serve/ckb/${zip_file} /data/resources/crunch/ckb/production/

# unzip file
info "Unziping file ${zip_file}"
unzip /data/resources/crunch/ckb/production/${zip_file}

#rename dir
info "Renaming dir"
date=$(echo ${zip_file} | awk -F '-' '{print $NF}' | awk -F '.' '{print $1}' | cut -c 3-)
mv /data/resources/crunch/ckb/production/api-export /data/resources/crunch/ckb/production/${date}_ckb_flex_dump
rm ${zip_file}

# create new symlink
info "Creating new symlink"
unlink /data/resources/crunch/ckb/production/ckb_flex_dump
ln -s /data/resources/crunch/ckb/production/${date}_ckb_flex_dump /data/resources/crunch/ckb/production/ckb_flex_dump

info "CKB dump is updated!"