#!/usr/bin/env bash

source message_functions || exit 1
source locate_files || exit 1

sample=$1 && shift

if [[ -z "${sample}" ]]; then
    error "Parameters missing. Exiting.";
fi

orig_run_dir=/data/datasets/${sample}

if [[ ! -d ${orig_run_dir} ]]; then
    error "Run dir ${orig_run_dir} not present. Probably not downloaded yet?"
fi

run_dir=$(locate_actin_molecular_directory)/${sample}
if [[ -d ${run_dir} ]]; then
    info "Cleaning up ${run_dir}"
    rm -r ${run_dir}
fi

info "Copying ${orig_run_dir} to ${run_dir}"
cp -r ${orig_run_dir} ${run_dir}

if [[ ! -d ${run_dir}/linx/plot ]]; then
    # LINX plot dir does not get propagated through GS in case of no drivers - see also DEV-2201
    warn "No linx plot dir found. Assume no drivers were found."
    mkdir -p ${run_dir}/linx/plot
fi

# Set the pipeline manually to v5.24 in case file does not exist
pipeline_version_file=${run_dir}/pipeline.version
if [[ ! -f ${pipeline_version_file} ]]; then
    version="5.24"
    info "Setting pipeline version to ${version} in ${run_dir}"
    echo ${version} >> ${pipeline_version_file}
fi

# Retain original cuppa for cuppa_conclusion. TODO Should be fixed in ORANGE
cp -r ${run_dir}/cuppa ${run_dir}/cuppa_orig

# To correct for the missing SIG data - see also DEV-2196
run_cuppa_dna_prod ${run_dir}
# To generate the CUPPA report as a picture (png) - see also DEV-2195
generate_cup_report_pipeline ${run_dir}

info "Copying original Cuppa conclusion back into new cuppa dir"
cp ${run_dir}/cuppa_orig/${sample}.cuppa.conclusion.txt ${run_dir}/cuppa/

# Check if RNA data is present and if yes -> post-process all RNA and integrate with DNA.
run_actin_rna_post_process ${run_dir}

# Run standard ORANGE in production - see also DEV-2027
run_orange_prod ${run_dir} -max_evidence_level C

# Disabled-germline is generated to be able to share externally with people who do not wish to see germline.
do_run_orange_prod ${run_dir} ${run_dir}/orange_no_germline -max_evidence_level C -disable_germline