#!/usr/bin/env bash

source message_functions || exit 1

providedId=$1

if [[ -z ${providedId} ]]; then
    error "Please provide reporting-id or pathology number."
fi


echo "--Isolation barcode for for sample ${providedId}--"

isolation_barcode_reporting-id=$( lama_api_get queries/isolation-barcodes/reporting-id/${providedId} 2> /dev/null | jq -r )
isolation_barcode_pa-nr=$( lama_api_get queries/isolation-barcodes/pathology-number/${providedId} 2> /dev/null | jq -r )

if [ $(echo $isolation_barcode_reporting-id | wc -w) != 0 ]; then
    echo "${isolation_barcode_reporting-id}"
    exit
elif [ $(echo $isolation_barcode_pa-nr | wc -w) != 0 ]; then
    echo "${isolation_barcode_pa-nr}"
  	exit
else
    echo "No isolation barcode found."
    exit
fi

